from .blocks import check, code, lecture, math, p, steps, svg, table, tip

CHAPTER = {
    "id": "ch1",
    "num": "01",
    "title": "Computer Systems",
    "blurb": "Discrete data, Boolean algebra, logic gates, K-maps, SDLC, aur OSI model.",
    "lectures": [
        lecture(
            "discrete-digital",
            "1.1.1 – 1.1.2",
            "Discrete, continuous, aur digital systems",
            8,
            [
                p("Aaj ki pehli lecture do qisam ki quantities se shuru hoti hai: discrete aur continuous. Discrete woh cheez hai jo alag alag ginne layak ho. Aap classroom ke students ek ek karke gin sakte hain. Parking ki cars bhi discrete hain. Inki value jump karti hai, beech ki adhi value nahi hoti."),
                p("Continuous quantity ek range ke andar koi bhi value le sakti hai. Pani ka temperature 30 bhi ho sakta hai, 30.2 bhi, aur us ke beech ki koi bhi reading. Chalti hui car ki speed bhi continuous hai, kyunke woh smoothly badalti hai."),
                svg("stairs", "Stairs discrete hain, har step ek fixed value. Ramp continuous hai, aap us pe kahin bhi ruk sakte hain.", "Stairs discrete, ramp continuous."),
                p("Digital system ek electronic system hai jo sirf do values use karta hai: zero aur one. In dono ko binary digits, ya bits, kehte hain. Zero ka matlab OFF, LOW, ya FALSE hai. One ka matlab ON, HIGH, ya TRUE hai."),
                table(
                    ["Faida", "Urdish matlab"],
                    [
                        ["Reliable", "Noise aur interference se kam bigadta hai."],
                        ["Accurate", "Copy karne pe quality kharab nahi hoti."],
                        ["Easy design", "Sirf do states handle karni hoti hain."],
                        ["Programmable", "Software se control karna asaan hai."],
                    ],
                    "Digital systems reliable, accurate, easy to design, aur programmable hoti hain.",
                ),
                p("Misal: computer data ko zero aur one mein process karta hai. Smartphone photos aur music ko binary mein store karta hai. Digital camera image ko binary code mein capture karti hai."),
                tip("Exam mein stairs versus ramp wali analogy likh dena. Examiner ko foran pata chal jata hai ke discrete aur continuous clear hain."),
                check(
                    "Temperature of water discrete hai ya continuous?",
                    "Continuous, kyunke woh range ke andar koi bhi value le sakti hai.",
                ),
            ],
        ),
        lecture(
            "analog-digital",
            "1.1.3",
            "Analog aur digital signals",
            8,
            [
                p("Yeh golden topic hai. Analog signal continuous hoti hai. Waqt ke sath smoothly badalti hai, bilkul sine wave ki tarah. Insan ki awaaz aur purana thermometer analog misaal hain."),
                p("Digital signal ke sirf do level hote hain: HIGH, yaani one, aur LOW, yaani zero. Yeh ek value se doosri value pe foran jump karti hai, is liye square wave banti hai. Computer ka data digital signal hai."),
                svg("waves", "Analog sine wave smooth hai. Digital square wave sirf high aur low pe rehti hai.", "Sine wave aur square wave."),
                table(
                    ["Feature", "Analog data", "Digital data"],
                    [
                        ["Nature", "Continuous flow", "Discrete bits"],
                        ["Reliability", "Noise se bigad jati hai", "Noise ke khilaf mazboot"],
                        ["Copy", "Quality gir sakti hai", "Copy same rehti hai"],
                    ],
                    "Analog continuous aur noise se kamzor hai. Digital discrete hai aur noise resist karti hai.",
                ),
                check(
                    "Square wave analog hai ya digital?",
                    "Digital. Sirf HIGH one aur LOW zero.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "boolean",
            "1.1.4 – 1.1.6",
            "Boolean algebra, operations, aur truth tables",
            12,
            [
                p("Boolean algebra George Boole ne banai. Is mein sirf do values hain: TRUE jo one hai, aur FALSE jo zero hai. Digital electronics aur programming ki bunyad yahi hai."),
                table(
                    ["Concept", "Matlab", "Example"],
                    [
                        ["Variable", "Letter jo zero ya one rakhe", "A, B, C, X, Y"],
                        ["Operation", "Variable pe action", "AND, OR, NOT"],
                        ["Expression", "Variables aur operations ka mel", "Y = A + B"],
                    ],
                    "Variable letter hai, operation action hai, expression unka combination hai.",
                ),
                p("AND operation ka output one sirf tab hota hai jab tamam inputs one hon. Darwaze pe do taale hon, darwaza tab khulega jab dono taale khul jayen."),
                math(r"Y = A \cdot B", "Y barabar A dot B. Dot ka matlab AND hai."),
                p("OR operation ka output one ho jata hai jab koi bhi ek input one ho. Kamre ke do darwaze hon, aap kisi ek se andar aa sakte hain."),
                math(r"Y = A + B", "Y barabar A plus B. Boolean plus ka matlab OR hai, normal jama nahi."),
                p("NOT operation input ko ulta kar deta hai. Yeh unary hai, sirf ek operand pe chalti hai. Input one ho to output zero. Switch ON ho to kamra roshan, switch OFF ho to kamra andhera. Yahan switch ki misaal inversion samjhane ke liye hai."),
                math(r"Y = A'", "Y barabar A prime, yaani NOT A."),
                steps(
                    "Truth table kaise banain",
                    [
                        "Inputs ginain. Unki tadad n hai.",
                        "Rows nikalain: 2 ki power n.",
                        "Tamam combinations binary order mein likhein.",
                        "Har row ka output calculate karein.",
                    ],
                    "Pehle inputs ginain, phir do ki power n rows, phir binary combinations, phir output.",
                ),
                math(r"\text{rows} = 2^{n}", "Rows barabar two to the power n. Do inputs hon to char rows. Teen inputs hon to aath rows."),
                tip("Plus yahan jama nahi hai. Boolean mein plus OR hai, aur dot AND hai."),
                check(
                    "Do inputs ki truth table mein kitni rows hoti hain?",
                    "Char rows, kyunke 2 ki power 2 barabar 4.",
                ),
            ],
        ),
        lecture(
            "basic-gates",
            "1.1.7",
            "Basic logic gates: AND, OR, NOT",
            9,
            [
                p("Logic gates electronic circuits hain jo Boolean operations karti hain. Yeh tamam digital systems ki eentein hain. Golden topic hai, symbol aur truth table dono yaad rakhne hain."),
                svg("gate", "AND gate ka output tab one hota hai jab A bhi one ho aur B bhi one ho.", "AND gate.", gate="and"),
                table(
                    ["A", "B", "AND", "OR"],
                    [
                        ["0", "0", "0", "0"],
                        ["0", "1", "0", "1"],
                        ["1", "0", "0", "1"],
                        ["1", "1", "1", "1"],
                    ],
                    "AND sirf last row mein one deta hai. OR pehli row ke ilawa har jagah one deta hai.",
                ),
                svg("gate", "NOT gate ka ek hi input hota hai, aur output hamesha ulta hota hai.", "NOT gate.", gate="not"),
                table(
                    ["A", "NOT Y"],
                    [["0", "1"], ["1", "0"]],
                    "NOT zero ko one banata hai aur one ko zero.",
                ),
                check(
                    "A one hai aur B zero hai. AND ka output kya hoga?",
                    "Zero. AND ko dono inputs one chahiye.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "universal-gates",
            "1.1.7",
            "Universal aur advanced gates",
            10,
            [
                p("NAND aur NOR ko universal gates kehte hain, kyunke dunya ka koi bhi logic circuit sirf in gates se bana sakte hain. NAND ka matlab NOT AND hai. NOR ka matlab NOT OR hai."),
                svg("gate", "NAND, AND ke output pe bubble laga kar inversion kar deta hai.", "NAND gate.", gate="nand"),
                math(r"Y = (A \cdot B)'", "NAND: Y barabar A dot B, poori cheez prime."),
                svg("gate", "NOR, OR ke output ko ulta kar deta hai.", "NOR gate.", gate="nor"),
                math(r"Y = (A + B)'", "NOR: Y barabar A plus B, poori cheez prime."),
                table(
                    ["A", "B", "NAND", "NOR", "XOR", "XNOR"],
                    [
                        ["0", "0", "1", "1", "0", "1"],
                        ["0", "1", "1", "0", "1", "0"],
                        ["1", "0", "1", "0", "1", "0"],
                        ["1", "1", "0", "0", "0", "1"],
                    ],
                    "XOR tab one hai jab inputs alag hon. XNOR tab one hai jab inputs same hon.",
                ),
                svg("gate", "XOR exclusive OR hai. Inputs alag hon to output one.", "XOR gate.", gate="xor"),
                math(r"Y = A \oplus B", "Y barabar A xor B."),
                tip("Yaad rakhein: XOR one deta hai jab inputs exclusively different hon. XNOR one deta hai jab inputs same hon."),
                check(
                    "NAND aur NOR ko universal kyun kehte hain?",
                    "Kyunke koi bhi logic circuit sirf NAND se, ya sirf NOR se, bana sakte hain.",
                ),
            ],
        ),
        lecture(
            "minterms",
            "1.1.8 – 1.1.11",
            "Expressions, minterms, aur logic diagrams",
            11,
            [
                p("Boolean expression solve karte waqt order zaroori hai. Pehle parentheses, phir NOT, phir AND, phir OR. Jaise normal math mein multiply pehle hota hai, yahan AND, OR se pehle hota hai."),
                steps(
                    "Order of precedence",
                    ["Parentheses", "NOT, yaani prime", "AND, yaani dot", "OR, yaani plus"],
                    "Pehle brackets, phir NOT, phir AND, phir OR.",
                ),
                p("Minterm SOP hai, sum of products. Yeh un tamam variables ka AND product hai jahan output one aata hai. Jis variable ki value zero ho us pe prime lagta hai. Jis ki value one ho woh seedha rehta hai."),
                p("Maxterm POS hai, product of sums. Yeh un rows ka OR sum hai jahan output zero aata hai. Yahan rule ulta hai: value one ho to prime, value zero ho to seedha."),
                table(
                    ["A", "B", "Y", "Minterm", "Maxterm"],
                    [
                        ["0", "0", "0", "—", "A + B"],
                        ["0", "1", "1", "A'B", "—"],
                        ["1", "0", "0", "—", "A' + B"],
                        ["1", "1", "1", "AB", "—"],
                    ],
                    "Jahan Y one hai wahan minterm likhein. Jahan Y zero hai wahan maxterm.",
                ),
                math(r"Y = A'B + AB", "Final SOP: Y barabar A prime B, plus A B."),
                p("Logic diagram dikhata hai ke gates kaise judi hain. Sab se pehle woh operation draw karein jiski precedence zyada ho."),
                svg("circuit", "Y barabar A dot B plus C. Pehle AND gate A aur B ko jodti hai, phir OR gate us result ko C ke sath jodti hai.", "Logic diagram of Y = A·B + C."),
                check(
                    "Expression Y = A dot B + C mein pehle kaun si gate draw hogi?",
                    "AND gate, kyunke AND ki precedence OR se zyada hai.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "kmaps",
            "1.1.13",
            "Karnaugh maps se simplification",
            10,
            [
                p("K-map Boolean expression ko simplify karne ka graphical tareeqa hai. Grid Gray code mein hoti hai, is liye bagal wale cells sirf ek bit se farq rakhte hain. Hum ones ko groups mein jodte hain. Group ka size one, two, four, ya eight hota hai, yaani two ki power."),
                svg("kmap2", "Do variables A aur B ke liye char cells chahiye, kyunke two squared barabar four.", "Two-variable K-map."),
                math(r"\text{cells} = 2^{n}", "Cells barabar two to the power n. Do variables, char cells. Teen variables, aath cells."),
                p("Grouping rule: groups jitne bare ho saken utne bare banayein, lekin size sirf two ki power ho. Overlap allowed hai. Group ke andar jo variable zero se one pe badal jaye, woh hat jata hai."),
                svg("kmap3", "Teen variables mein columns Gray code hain: zero zero, zero one, one one, one zero. Kinare wrap ho sakte hain. Left cell right cell ke sath group ho sakti hai.", "Three-variable K-map."),
                tip("Gray code yaad rakhein: 00, 01, 11, 10. 01 ke baad 10 nahi, 11 aata hai, taake sirf ek bit badle."),
                check(
                    "K-map mein group ka size kya ho sakta hai?",
                    "1, 2, 4, ya 8. Yaani two ki powers. Overlap allowed hai.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "logisim",
            "LogiSim",
            "LogiSim Evolution mein circuit banana",
            8,
            [
                p("LogiSim Evolution ek graphical tool hai. Is mein aap wohi truth tables aur Boolean expressions simulate karte hain jo theory mein seekhte hain."),
                svg("logisim", "Left side library hai, right side canvas. Simulation mein bright green logic one hai, dark green logic zero, blue unknown, aur red error ya short circuit.", "LogiSim areas and wire colors."),
                steps(
                    "Y = A dot B kaise banayein",
                    [
                        "Toolbar se AND gate canvas pe rakhein.",
                        "Do input pins left side pe rakhein aur unhein A aur B likhein.",
                        "Output pin right side pe rakhein aur usay Y likhein.",
                        "Wiring tool se sirf seedhi horizontal ya vertical wires khainchein.",
                        "Poke tool, yaani ungli wala icon, se A aur B ko zero one kar ke test karein.",
                    ],
                    "AND gate rakhein, do inputs A aur B, output Y, wires jodein, phir poke tool se test karein.",
                ),
                check(
                    "LogiSim mein bright green wire ka kya matlab hai?",
                    "Logic one, yaani HIGH.",
                ),
            ],
        ),
        lecture(
            "sdlc",
            "1.2.1 – 1.2.3",
            "Software Development Life Cycle",
            10,
            [
                p("SDLC ek structured process hai jo software ko shuru se akhir tak guide karti hai. Is se goals clear rehte hain, planning behtar hoti hai, risk kam hota hai, aur quality barhti hai. Yeh golden topic hai."),
                steps(
                    "SDLC ke 6 phases",
                    [
                        "Requirement analysis: client se zarooratain, features ki list, SRS document.",
                        "System design: architecture, database, screens, flowcharts. Design document.",
                        "Implementation: Python ya Java mein asal code.",
                        "Testing: bugs dhoondhna. Test reports.",
                        "Deployment: users tak pohanchana. Direct, phased, ya pilot.",
                        "Maintenance: support, updates, patches.",
                    ],
                    "Chhe phases: requirements, design, implementation, testing, deployment, maintenance.",
                ),
                tip("Ghar banane ki analogy yaad rakhein. Phase one family se poochna ke kitne kamre chahiye. Phase two architect ka naqsha. Phase three mazdooron ka kaam."),
                table(
                    ["Testing", "Tester code dekhta hai?", "Kya check hota hai"],
                    [
                        ["Black box", "Nahi", "Inputs aur outputs, functionality"],
                        ["White box", "Haan", "Andar ki logic aur structure"],
                    ],
                    "Black box sirf bahar se test karta hai. White box code ke andar dekhta hai.",
                ),
                check(
                    "Sab se important SDLC phase kaun si hai, notes ke mutabiq?",
                    "Requirement analysis, kyunke yahin se SRS banta hai.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "waterfall-agile",
            "1.2.4 – 1.2.7",
            "Waterfall aur Agile",
            10,
            [
                p("Waterfall linear hai. Ek phase poora hue baghair agla shuru nahi hota. Wapas jana mushkil hai. Istemal tab karein jab requirements clear, fixed, aur samajh aa chuki hon, project chhota ya medium ho, aur technology stable ho."),
                svg("waterfall", "Waterfall seedhi line mein neeche girta hai. Testing bohot der se hoti hai.", "Waterfall phases."),
                p("Al-Noor Library Management System waterfall ki case study hai, kyunke coding se pehle requirements sau feesad fixed thin."),
                p("Agile iterative hai. Software chhote cycles mein banta hai jinhein sprints kehte hain, aam tor pe do se char hafte. Customer ki feedback lagatar aati hai. Tab use karein jab requirements badal sakti hon, ya jaldi working software chahiye."),
                svg("agile", "Har sprint ke baad feedback milti hai aur agla sprint us hisaab se mud jata hai.", "Agile sprint loop."),
                p("Al-Noor Student Mobile Application agile ki case study hai, kyunke teachers, parents, aur students development ke dauran naye features mangte rahe."),
                table(
                    ["Dimension", "Waterfall", "Agile"],
                    [
                        ["Flexibility", "Sakht, baad mein change mushkil", "Agle sprint mein change asaan"],
                        ["Customer", "Sirf shuru aur akhir", "Har sprint ke baad"],
                        ["Delivery", "Ek dafa bilkul akhir mein", "Har sprint ke baad thora software"],
                        ["Testing", "Der se, alag phase", "Har sprint ke andar"],
                        ["Documents", "Bhari documentation", "Halki, kaam karta software zaroori"],
                    ],
                    "Waterfall sakht aur akhir mein deliver karta hai. Agile flexible hai aur baar baar deliver karta hai.",
                ),
                check(
                    "Requirements agar beech mein badal rahi hon to kaun sa model behtar hai?",
                    "Agile, kyunke agla sprint nayi requirement le sakta hai.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "osi",
            "1.3.1 – 1.3.4",
            "OSI ke saat layers",
            10,
            [
                p("Communication model batata hai ke data ek device se doosre device tak kaise jata hai. OSI model ISO ne 1984 mein banaya. Yeh communication ko saat layers mein baantta hai. Golden topic hai."),
                svg("osi", "Upar application hai, neeche physical. Mnemonic neeche se upar: Please Do Not Throw Sausage Pizza Away.", "OSI seven layers."),
                tip("Mnemonic: Please Do Not Throw Sausage Pizza Away. Physical, Data link, Network, Transport, Session, Presentation, Application."),
                table(
                    ["Layer", "Kaam", "Misal"],
                    [
                        ["7 Application", "User apps ko network service", "HTTP, HTTPS, FTP, SMTP, DNS"],
                        ["6 Presentation", "Translation, encryption, compression", "SSL/TLS, JPEG, MP3, ASCII"],
                        ["5 Session", "Session kholna, rakhna, band karna", "NetBIOS, RPC"],
                        ["4 Transport", "End to end delivery, ports, errors", "TCP reliable, UDP fast"],
                    ],
                    "Upar ki char layers: application, presentation, session, transport.",
                ),
                p("Transport layer pe yaad rakhein: TCP tab jab accuracy chahiye, jaise web aur email. UDP tab jab speed zyada zaroori ho, jaise video streaming aur online game. UDP thodi packets kho bhi de to chal jata hai."),
                table(
                    ["Layer", "Kaam", "Misal"],
                    [
                        ["3 Network", "IP address aur routing", "IP, ICMP ping, routers"],
                        ["2 Data link", "MAC address aur frames", "Ethernet, switches"],
                        ["1 Physical", "Raw bits zero one", "Cables, hubs, Wi-Fi radio"],
                    ],
                    "Neeche teen layers hardware ke qareeb hain: network, data link, physical.",
                ),
                check(
                    "Online game ke liye TCP behtar hai ya UDP?",
                    "UDP, kyunke speed accuracy se zyada zaroori hai.",
                ),
            ],
            golden=True,
        ),
        lecture(
            "tcpip",
            "1.3.5 – 1.3.6",
            "TCP/IP model aur OSI se farq",
            7,
            [
                p("TCP/IP woh practical model hai jo asal internet pe chalta hai. Yeh OSI ki saat layers ko char layers mein sama leta hai."),
                svg("tcpip", "Application OSI ke 7, 6, 5 ko cover karti hai. Transport sirf 4. Internet sirf 3. Network access 2 aur 1.", "TCP/IP mapped onto OSI."),
                table(
                    ["TCP/IP layer", "OSI layers"],
                    [
                        ["1 Application", "Application, Presentation, Session"],
                        ["2 Transport", "Transport"],
                        ["3 Internet", "Network"],
                        ["4 Network Access", "Data Link aur Physical"],
                    ],
                    "Char TCP/IP layers saat OSI layers ko cover karti hain.",
                ),
                check(
                    "OSI ka network layer TCP/IP mein kis naam se hai?",
                    "Internet layer.",
                ),
            ],
        ),
    ],
}
