"""Class XII preface and units 1, 2 and 4. Unit 3 is in content_xii_oop.py."""

from reportlab.lib.units import mm

PREFACE = {
    "grade": "XII",
    "unit": "",
    "kicker": "Class XII  |  before the units",
    "title": "How to use the Class XII lectures",
    "weight": "",
    "periods": "Same 75-mark paper shape as Computer Science Paper II",
    "intro": (
        "Class XII moves from the computer itself to building software, then to pointers, classes, files, databases, multimedia and wireless communication. "
        "The paper shape is the same three-hour, 75-mark pattern described in the Class XI preface: 29 multiple-choice questions, 10 short answers out of 15, and 2 detailed answers out of 3. "
        "Confirm the model paper for your year at biek.edu.pk."
    ),
    "slos": [
        "Plan revision by the unit weights in the 2019 curriculum.",
        "Give extra practice to object-oriented programming, which carries the highest weight.",
    ],
    "path": [
        "Read Unit 1 as the story of a project. The later programming units are the building and testing phases of that story.",
        "Type the pointer, class and file programs. They are short and they are examined.",
        "Work the library database on paper up to third normal form before you write SQL.",
    ],
    "sections": [
        ("h", "Unit weight in Class XII"),
        ("table", "", ["Unit", "Title", "Weight", "Theory periods", "Lab periods"], [
            ["1", "System development life cycle", "10%", "15", "-"],
            ["2", "Pointers", "15%", "5", "5"],
            ["3", "Object-oriented programming in C++", "25%", "30", "30"],
            ["4", "File handling", "15%", "5", "5"],
            ["5", "Database fundamentals", "15%", "20", "10"],
            ["6", "Introduction to multimedia", "15%", "20", "20"],
            ["7", "Wireless and mobile communication", "10%", "15", "-"],
        ]),
        ("p", "Object-oriented programming is a quarter of the course. Pointers and files are short units with a high weight, so the programs in those units repay careful practice."),
    ],
    "terms": [],
    "summary": [
        "Spend the most programming time on classes, constructors, inheritance and polymorphism.",
        "Be able to draw an ER diagram and write a SELECT with a WHERE clause.",
    ],
    "mcqs": [],
    "shorts": [],
    "longs": [],
    "labs": [],
}

LECTURES = []

LECTURES.append({
    "grade": "XII",
    "unit": "1",
    "kicker": "Class XII  |  Unit 1  |  weight 10%",
    "title": "System development life cycle",
    "weight": "10%",
    "periods": "15 theory periods",
    "intro": "A system is a set of parts working toward a purpose. Building a software system properly means moving through agreed phases, with a named person responsible for each kind of work.",
    "slos": [
        "Define a system and the system development life cycle, and say why the cycle matters.",
        "Describe the roles of the project manager, analyst, architect, developers, testers, operations and support.",
        "Explain planning, requirements, design, implementation, testing, deployment and maintenance.",
        "Distinguish functional and non-functional requirements, and describe an SRS, bugs, errors and an SLA.",
    ],
    "path": [
        "Use one system the class knows, such as a college library, and walk it through every phase.",
        "Put the seven roles on the board beside the phase each role leads.",
        "Write three functional and three non-functional requirements for that library before defining the SRS.",
    ],
    "sections": [
        ("h", "1.1 Systems and the people who build them"),
        ("def", "System", "A set of interrelated components that work together to achieve a purpose."),
        ("def", "System development life cycle", "The ordered set of phases through which a software system is planned, built, tested, delivered and kept in service."),
        ("p", "The cycle matters because a college that starts coding on the first day often builds the wrong system. Requirements that are written down can be checked. A design can be reviewed before money is spent on programming. Testing finds faults before students meet them. Maintenance keeps the system useful after delivery. The cycle also tells a team who is responsible for each kind of decision."),
        ("table", "Stakeholders in the cycle", ["Role", "Leads this work"], [
            ["Project manager", "Plan, schedule, cost and coordination of the team"],
            ["Business analyst", "Finding and writing what the organisation needs"],
            ["System architect", "The overall design and structure of the solution"],
            ["Software developer", "Writing the programs"],
            ["Tester", "Checking that the system meets the requirements and reporting faults"],
            ["Operational team", "Putting the system into real use and running it"],
            ["Production support", "Looking after the system after it is live, including repairs and small changes"],
        ]),
        ("h", "1.2 The phases"),
        ("diagram", "sdlc", "Figure 1.1  The phases used in this course. Maintenance sends new needs back into planning.", 48 * mm),
        ("h3", "Planning and requirements"),
        ("p", "**Problem identification** names what is wrong or missing. A library may be losing track of which student has which book. **Planning** sets the scope, the time and the people. **Feasibility** asks whether the system should be built at all."),
        ("table", "Feasibility questions", ["Kind", "The question"], [
            ["Technical", "Can it be built with the hardware, software and skills available?"],
            ["Economic", "Do the benefits justify the cost?"],
            ["Operational", "Will the librarians and students actually be able to use it?"],
            ["Schedule", "Can it be ready for the term in which it is needed?"],
        ]),
        ("p", "**Requirement gathering** collects what the system must do, from interviews, existing forms and observation. A **functional requirement** is a behaviour: the librarian can issue a book to a member, search by title, and record a return. A **non-functional requirement** is a quality: the search should answer within a few seconds, only a librarian can delete a member, and the screens should be readable on the lab monitors."),
        ("def", "Software requirements specification", "The document that records what the system must do and the constraints on how well it must do it. Designers and testers work from this document."),
        ("p", "An SRS usually contains an introduction, a description of the users, the functional requirements, the non-functional requirements, the data that must be stored, and the interfaces with other systems. It is the agreement between the college and the builders."),
        ("h3", "Design, build, test, deliver, maintain"),
        ("p", "**Design** decides the structure of the software, the data and the screens. An **algorithm** is a finite, ordered, unambiguous set of steps that solves a problem. A **flowchart** is a diagram of those steps. Use an oval for start and stop, a parallelogram for input or output, a rectangle for a process, a diamond for a decision, and arrows for the order."),
        ("p", "**Implementation** is the coding of the design in a language such as C++. **Testing** runs the system to see whether it meets the SRS. A **bug** is a defect in the software. An **error** is a mistake or a wrong result: a person may write a wrong formula (a human error), the program may contain a defect (a bug), and the user may then see a wrong total (a failure or an incorrect result). In answers, define a bug as a fault in the program and an error as a wrong step or a wrong result, and give one example of each."),
        ("p", "**Deployment** puts the finished system into the place where it will be used: the library computers, the real data and the trained staff. **Maintenance** repairs faults, adapts the system when rules change, and improves it. A **service level agreement** is a written commitment between the provider and the customer about the service, for example the hours the system will be available and how quickly a serious fault will be attended to."),
        ("tip", "An 8-mark SDLC answer that only lists five headings will look thin. For each phase write one sentence of work and name the role that leads it. Use the library as the running example."),
    ],
    "terms": [
        ["System", "Interrelated parts working for a purpose."],
        ["SDLC", "The phases of planning, building, testing, delivering and maintaining software."],
        ["Feasibility", "A study of whether the proposed system can and should be built."],
        ["Functional requirement", "A behaviour the system must perform."],
        ["Non-functional requirement", "A quality or constraint, such as speed or security."],
        ["SRS", "The specification of requirements that guides design and testing."],
        ["Algorithm", "A finite sequence of clear steps that solves a problem."],
        ["SLA", "An agreement on the level of service to be provided."],
    ],
    "summary": [
        "The life cycle reduces the chance of building the wrong system.",
        "Analysts gather requirements, architects design, developers code, testers test, operations deploy, and support maintains.",
        "Functional requirements say what the system does. Non-functional requirements say how well.",
        "A bug is a defect in the software. An SLA states the service the live system must provide.",
    ],
    "labs": [
        "Write six requirements for a college library system: three functional and three non-functional. Draw a flowchart to issue a book.",
    ],
    "mcqs": [
        {"q": "A functional requirement describes:", "options": ["What the system does", "Only the colour of the case", "The brand of keyboard", "A topology"], "a": "A", "why": "Functional requirements are behaviours, such as issuing a book."},
        {"q": "The SRS is mainly used so that:", "options": ["Design and test have a written set of requirements", "RAM is refreshed", "A cable is crimped", "A pointer is dereferenced"], "a": "A", "why": "The specification is the agreed description of the system to be built."},
        {"q": "Which role leads the writing of program code?", "options": ["Software developer", "Only the projector", "The CMOS battery", "The barcode"], "a": "A", "why": "Developers implement the design by coding."},
        {"q": "Economic feasibility asks whether:", "options": ["The benefits justify the cost", "The screen is an LCD", "The language is C++", "The bus is unidirectional"], "a": "A", "why": "Economic feasibility compares cost and benefit."},
        {"q": "A diamond in a flowchart means:", "options": ["A decision", "A start symbol only", "A database table", "A wireless cell"], "a": "A", "why": "A diamond is the decision symbol. An oval is start or stop."},
        {"q": "An SLA belongs most naturally to:", "options": ["Support of a live system", "Erasing an EPROM", "Declaring an int", "A simplex link only"], "a": "A", "why": "A service level agreement sets the service expected after deployment."},
        {"q": "Maintenance happens:", "options": ["After the system is in use, and can lead to new requirements", "Only before the problem is identified", "Only inside the ALU", "Only on paper flowcharts"], "a": "A", "why": "Maintenance looks after the live system and often starts another cycle."},
        {"q": "A bug is:", "options": ["A defect in the software", "A network topology", "A file attribute", "A normal form"], "a": "A", "why": "A bug is a fault in the program that can cause wrong behaviour."},
    ],
    "shorts": [
        {"q": "Define the system development life cycle.", "a": "The system development life cycle is the set of phases through which a system is planned, designed, built, tested, deployed and maintained. It matters because each phase checks the work of the one before it, so the team is less likely to code a system that does not meet the need."},
        {"q": "Differentiate functional and non-functional requirements.", "a": "A functional requirement states a behaviour, for example that a librarian can record the return of a book. A non-functional requirement states a quality or constraint, for example that the record is saved securely and the screen responds promptly. Both belong in the SRS."},
        {"q": "What is feasibility? Name two kinds.", "a": "Feasibility is the study of whether a proposed system should be built. Technical feasibility asks whether the tools and skills exist. Economic feasibility asks whether the benefit justifies the cost. Operational and schedule feasibility are the other two kinds used in class."},
        {"q": "Differentiate an algorithm and a flowchart.", "a": "An algorithm is a written sequence of finite, clear steps that solves a problem. A flowchart is a diagram of those steps, using standard symbols such as a rectangle for a process and a diamond for a decision. The flowchart shows the same logic in a form that is easy to follow on paper."},
        {"q": "What is a service level agreement?", "a": "A service level agreement is a commitment between a service provider and a customer about the level of service. It can state the hours a system will be available and the time allowed to respond to a serious fault."},
    ],
    "longs": [
        {"q": "Explain the phases of the software development life cycle with the role responsible for each.", "points": [
            "Define system and SDLC, and give one reason the cycle is used.",
            "Describe problem identification, planning, feasibility and requirements, and name the analyst and the project manager.",
            "Describe the SRS, then design and the architect, including algorithm and flowchart.",
            "Describe coding by developers, testing by testers, deployment by operations, and maintenance by production support.",
            "Define bug and SLA in the last two phases, using a library example throughout.",
        ]},
        {"q": "Explain how requirements are gathered and written for a college library system.", "points": [
            "Name the users: librarian, member, administrator.",
            "Give three functional requirements in complete sentences.",
            "Give three non-functional requirements: speed, security, usability.",
            "Say what an SRS contains and who uses it afterwards.",
            "Mention feasibility briefly so the college does not specify a system it cannot run.",
        ]},
    ],
})

LECTURES.append({
    "grade": "XII",
    "unit": "2",
    "kicker": "Class XII  |  Unit 2  |  weight 15%",
    "title": "Pointers",
    "weight": "15%",
    "periods": "5 theory periods and 5 lab periods",
    "intro": "A pointer holds the address of a variable. With that address the program can read or change the variable itself. Pointers are short to write and easy to lose marks on, so the operators and the types have to be exact.",
    "slos": [
        "Explain why pointers are used and what a memory address is.",
        "Use the address-of operator and the dereference operator.",
        "Declare and initialise a pointer.",
        "Write a program that displays an address and a value, and a function that changes variables through pointers.",
    ],
    "path": [
        "Draw a variable as a box and a pointer as a box that contains the address of the first box.",
        "Type the single-variable program and read both the address and the value.",
        "Pass two addresses into a function and show that the originals change.",
    ],
    "sections": [
        ("h", "2.1 Addresses and pointer variables"),
        ("def", "Pointer", "A variable whose value is the address of another variable."),
        ("p", "Every variable occupies memory, and that place has an address. The **address-of operator** `&` produces the address of a variable. The **dereference operator** `*` uses an address to reach the variable that lives there. Declaring `int *p;` means p is a pointer to an int. It does not mean that p is an int."),
        ("p", "Initialising the pointer matters. `int *p = &marks;` stores the address of marks in p. After that, `*p` and `marks` name the same value. Changing `*p` changes marks. A pointer that has never been set must not be dereferenced. It does not yet point at a variable you own."),
        ("diagram", "pointer", "Figure 2.1  p stores the address of marks. *p is the value 25.", 46 * mm),
        ("p", "Pointers matter because a function can receive an address and change the caller's variable, because dynamic structures such as linked data are built from addresses, and because a large value can be shared by passing its address rather than copying it. In this unit the required skill is the simple use: take an address, store it, and reach the value."),
        ("code", "Program 2.1  Address and value through a pointer", "pointer_basic"),
        ("p", "The address printed for p changes from run to run. That is expected. The value 25, and the new value 40 after `*p = 40`, stay the same. The program shows both operators: `&marks` goes into p, and `*p` comes back to the value."),
        ("h", "2.2 Pointers as function arguments"),
        ("p", "A function parameter of type `int *` receives an address. Inside the function, `*a` reaches the original variable. At the call, pass `&first`, not first. Passing first would pass the number, and the types would not match."),
        ("code", "Program 2.2  Double two integers through pointers", "pointer_double"),
        ("p", "Input 4 and 7 prints 8 and 14. This is the pointer form of pass by reference. The `&` form you used in Class XI (`int &n`) and the pointer form (`int *n` plus `*n`) both let a function change the original. The pointer form makes the address visible, which is the point of this unit."),
        ("tip", "In an exam, the declaration `int *p;` the assignment `p = &x;` and the use `*p` are three separate marks. Write all three. State the type the pointer points to."),
    ],
    "terms": [
        ["Address", "The location of a variable in memory."],
        ["Pointer", "A variable that stores an address."],
        ["&", "The address-of operator. &x is the address of x."],
        ["*", "The dereference operator. *p is the object p points to."],
        ["NULL", "A pointer value that points nowhere. Do not dereference it."],
    ],
    "summary": [
        "A pointer stores an address. & takes an address. * follows an address.",
        "The declaration int *p says that *p is an int, so p points to an int.",
        "A function changes a caller's variable when it receives the variable's address and assigns through *.",
    ],
    "labs": [
        "Display the address and the value of a variable using a pointer.",
        "Pass the addresses of two variables to a function and double both values.",
    ],
    "mcqs": [
        {"q": "The operator & produces:", "options": ["The address of its operand", "The square of a number", "A new class", "A file mode"], "a": "A", "why": "& is the address-of operator."},
        {"q": "If p points to marks, then *p is:", "options": ["The value of marks", "The name of the file", "Always zero", "The layer number"], "a": "A", "why": "Dereferencing p reaches the variable it points to."},
        {"q": "int *p; declares:", "options": ["A pointer to int", "An int that cannot change", "A string", "A table"], "a": "A", "why": "The * in the declaration belongs with p and makes p a pointer."},
        {"q": "Which call matches the parameter int *a?", "options": ["doubleBoth(&first, &second)", "doubleBoth(first, second)", "doubleBoth(*first, *second)", "doubleBoth(a, b, c)"], "a": "A", "why": "The function expects addresses, and &first is an address."},
        {"q": "Assigning *p = 40; when p points to marks:", "options": ["Changes marks to 40", "Deletes the program", "Changes the topology", "Closes a file"], "a": "A", "why": "*p names the same memory as marks."},
        {"q": "A pointer should be initialised so that:", "options": ["It holds the address of a real variable before it is dereferenced", "It holds a class name", "It replaces main", "It stores a flowchart"], "a": "A", "why": "Dereferencing an unset pointer does not refer to a known variable."},
        {"q": "Passing a pointer into a function is useful because:", "options": ["The function can change the original variable", "The keyboard becomes wireless", "ROM becomes volatile", "Arrays become illegal"], "a": "A", "why": "The function receives the address and writes through it."},
        {"q": "The value printed as the address of a local variable:", "options": ["Can differ from one run to the next", "Is always 25", "Is the source code", "Is the SRS"], "a": "A", "why": "The system chooses where to place the variable each run."},
    ],
    "shorts": [
        {"q": "Define a pointer and state the purpose of & and *.", "a": "A pointer is a variable that stores the address of another variable. The operator & gives the address of a variable. The operator * uses a pointer to reach the variable at that address. After int *p = &marks, *p and marks refer to the same value."},
        {"q": "Write the declaration and initialisation of a pointer to an int variable named marks.", "a": "int marks = 25; int *p = &marks; The declaration int *p says p points to an int. The initialiser stores the address of marks. *p then reads or changes marks."},
        {"q": "Why is a pointer parameter able to change the caller's variable?", "a": "The caller passes the address, for example &first. The parameter holds that address. An assignment to *a writes into the caller's variable, not into a copy of the number."},
        {"q": "Give two uses of pointers.", "a": "A function can modify the variables of its caller by receiving their addresses. Programs also use addresses to build data structures whose size can grow, and to share a large object without copying it."},
        {"q": "What is wrong with dereferencing a pointer that has not been initialised?", "a": "The pointer does not yet hold the address of a variable the program owns. Using * on it reaches an unknown location. Initialise the pointer with &variable, or set it only from a known object, before you dereference it."},
    ],
    "longs": [
        {"q": "Explain pointers with a program that shows the address and the value of a variable.", "points": [
            "Define pointer, address, & and *.",
            "Declare an int and a pointer, and initialise the pointer with the address of the int.",
            "Print the variable, the pointer, and the dereferenced pointer.",
            "Change the variable through *p and print the variable again to show it changed.",
            "State one reason this is useful in a function call.",
        ]},
        {"q": "Write a function that receives the addresses of two integers and doubles both. Explain each operator at the call and inside the function.", "points": [
            "Write the function heading with two int* parameters.",
            "Inside, assign *a = *a * 2 and the same for b.",
            "In main, read two integers and call the function with &first and &second.",
            "Explain why the arguments need & and why the body needs *.",
            "Give the sample 4 and 7 becoming 8 and 14.",
        ]},
    ],
})

LECTURES.append({
    "grade": "XII",
    "unit": "4",
    "kicker": "Class XII  |  Unit 4  |  weight 15%",
    "title": "File handling",
    "weight": "15%",
    "periods": "5 theory periods and 5 lab periods",
    "intro": "Variables disappear when the program ends. A file keeps data on secondary storage. This lecture opens files, chooses a mode, and reads and writes both text and binary data.",
    "slos": [
        "Define file handling and distinguish text and binary files.",
        "Open a file for reading, writing or appending.",
        "Explain BOF and EOF, and single-character, string and binary streams.",
        "Write programs that create and read a text file and a binary file of student records.",
    ],
    "path": [
        "Show a text file in an editor, then show that a binary file is not meant to be read that way.",
        "Teach open, check, use, close as a fixed four-step habit.",
        "Write the student text program, then the same student as a binary record.",
    ],
    "sections": [
        ("h", "4.1 Files, modes and ends"),
        ("def", "File handling", "The part of a program that creates, writes, reads and updates data stored in a file on secondary storage."),
        ("p", "A **text file** stores characters. You can open it in an editor and read the numbers and words. A **binary file** stores the bytes of the data as the program holds them in memory. It is compact and it preserves the exact bits of an int or a float. It is not a document for a person to edit."),
        ("table", "Modes used with ifstream, ofstream and fstream", ["Mode", "Effect"], [
            ["ios::in", "Open for reading. The file should already exist."],
            ["ios::out", "Open for writing. A new file is created. An existing file is emptied first."],
            ["ios::app", "Open for appending. New output is added at the end. Existing contents stay."],
            ["ios::binary", "Treat the file as binary. Combine it with in or out, for example ios::in | ios::binary."],
        ]),
        ("p", "`ofstream` is for output, `ifstream` is for input, and `fstream` can do both. After `open`, test the stream before you use it. Close the file when the work is finished so the buffer is written and the file is released."),
        ("def", "BOF", "Beginning of file. The position before the first byte, where a newly opened input file starts."),
        ("def", "EOF", "End of file. The condition that becomes true when a read goes past the last data. The loop `while (inFile >> word)` stops when no more input can be read."),
        ("p", "A stream is a flow of data. **Single-character I/O** uses `get` and `put`. **String I/O** uses `>>`, `getline` and `<<`. **Binary I/O** uses `read` and `write` with a memory address and a size. `write(reinterpret_cast<char*>(&s), sizeof(s))` copies the bytes of the object s into the file. `read` copies them back into an object of the same type."),
        ("h", "4.2 Text and binary programs"),
        ("code", "Program 4.1  Write and read a text file", "text_file"),
        ("p", "Program 4.1 creates student.txt, writes a name and a mark, closes it, then opens it again and reads both values. The file remains on the disk after the program ends. That is the whole point of file handling."),
        ("code", "Program 4.2  Write and read a binary student record", "binary_file"),
        ("p", "The student is a structure with a char array, an int and a float, so the object can be copied as a block of bytes. The name is placed with `strcpy` so the array contains a proper C string. Reading uses the same struct and the same size. If the reading program used a different layout, the bytes would be interpreted wrongly."),
        ("tip", "State text versus binary before you write code in a long question. Then show open, the transfer, close, and a second open to read the data back. Mention EOF if the question asks how a loop knows when to stop."),
    ],
    "terms": [
        ["Text file", "A file stored as characters."],
        ["Binary file", "A file stored as the raw bytes of the data."],
        ["ofstream", "A stream used to write a file."],
        ["ifstream", "A stream used to read a file."],
        ["Append", "Adding new data at the end of an existing file."],
        ["EOF", "The end-of-file condition, true when no more data can be read."],
    ],
    "summary": [
        "Files keep data after the program ends.",
        "Text files store characters. Binary files store memory images of objects.",
        "Choose in, out or app, and add binary when the bytes must be preserved.",
        "Open, check, read or write, and close. EOF tells an input loop to stop.",
    ],
    "labs": [
        "Write a name and a mark to a text file and read them back.",
        "Write a student structure to a binary file and read it into a second variable.",
    ],
    "mcqs": [
        {"q": "A text file stores:", "options": ["Characters", "Only electrical addresses", "Flowchart symbols", "OSI layers"], "a": "A", "why": "Text files hold character data that an editor can show."},
        {"q": "ios::app means:", "options": ["Append at the end of the file", "Erase ROM", "Sort an array", "Close the monitor"], "a": "A", "why": "Append keeps existing data and adds at the end."},
        {"q": "ios::out on an existing file:", "options": ["Opens it for writing and discards the old contents", "Always appends", "Converts it to a pointer", "Marks it read-only in Windows"], "a": "A", "why": "Output mode creates or empties the file. Append mode keeps it."},
        {"q": "EOF becomes true when:", "options": ["A read passes the last data", "The computer boots", "A class is declared", "Wi-Fi connects"], "a": "A", "why": "End of file means there is nothing left to read."},
        {"q": "Binary read and write transfer:", "options": ["A block of bytes of a given size", "Only one flowchart", "Only comments", "A topology name"], "a": "A", "why": "read and write copy a stated number of bytes."},
        {"q": "Which header declares file streams?", "options": ["fstream", "iostream only, with no file support at all", "cmath", "cstring only"], "a": "A", "why": "File stream classes are declared in fstream. iostream covers cin and cout."},
        {"q": "Closing a file:", "options": ["Flushes the buffer and releases the file", "Deletes the compiler", "Changes the address bus", "Is illegal in C++"], "a": "A", "why": "close completes pending output and frees the file."},
        {"q": "A binary student record should be read into:", "options": ["An object with the same member layout", "A different unrelated type on purpose", "An OSI layer", "A service level agreement"], "a": "A", "why": "The bytes match the struct that was written."},
    ],
    "shorts": [
        {"q": "Differentiate a text file and a binary file.", "a": "A text file stores data as characters and can be opened in an editor. A binary file stores the bytes of values as they are held in memory, using read and write. Binary storage preserves exact numeric bits and is not meant to be edited as a document."},
        {"q": "Differentiate write mode and append mode.", "a": "ios::out opens a file for writing and empties it if it already exists. ios::app opens a file so that new output is added after the existing contents. Use out when the file should be created fresh. Use app when older records must remain."},
        {"q": "What are BOF and EOF?", "a": "BOF is the beginning of the file, the position where reading normally starts. EOF is the end-of-file condition, which becomes true when a read can obtain no more data. An input loop stops when EOF is reached."},
        {"q": "Write the statements that open a text file for output and write a name.", "a": "ofstream outFile(\"student.txt\"); outFile << name << endl; outFile.close(); The first statement creates or empties the file. The second writes the name. The third closes it."},
        {"q": "Why must the struct used to read a binary record match the struct that wrote it?", "a": "write copies the bytes of the object in memory order. read copies those same bytes back. A different member order or a different size would place the bytes into the wrong members, so the name, age or percentage would be wrong."},
    ],
    "longs": [
        {"q": "Explain file modes and the difference between text and binary handling. Include BOF and EOF.", "points": [
            "Define file handling and why files outlive variables.",
            "Contrast text and binary with one example of each transfer: << and >>, then read and write.",
            "Explain in, out, app and binary.",
            "Define BOF and EOF and show them in a read loop.",
            "Mention open, test, use and close as the safe order.",
        ]},
        {"q": "Describe a program that stores a student in a binary file and reads the student back.", "points": [
            "Define a struct with a char name, an int age and a float percentage.",
            "Fill the fields, using strcpy for the name.",
            "Open an ofstream with ios::binary and write sizeof bytes.",
            "Close, open an ifstream with ios::binary, and read into a second struct.",
            "Print the fields to show the data survived.",
        ]},
    ],
})
