"""Class XII Unit 3, object-oriented programming."""

OOP = {
    "grade": "XII",
    "unit": "3",
    "kicker": "Class XII  |  Unit 3  |  weight 25%",
    "title": "Object-oriented programming in C++",
    "weight": "25%",
    "periods": "30 theory periods and 30 lab periods",
    "intro": "This unit carries a quarter of Class XII. A class describes a kind of object. An object is one real instance. Encapsulation, inheritance and polymorphism are the three ideas the paper expects you to define, to distinguish, and to show in code.",
    "slos": [
        "Explain encapsulation, inheritance and polymorphism, and the relationship of class and object.",
        "Use private and public members, and protected when a derived class must see them.",
        "Write constructors, including overloading, and a destructor.",
        "Write a derived class that uses members of its base class.",
        "Overload member functions and override a base function in a derived class.",
    ],
    "path": [
        "Build the Student class on the first day: private data, public functions, one object.",
        "Add a default constructor and a parameterised constructor with the Time class.",
        "Inherit DriveClass from Base and show protected data being used.",
        "Finish with one class that overloads area, and a derived class that overrides show.",
    ],
    "sections": [
        ("h", "3.1 Classes, objects and the three principles"),
        ("def", "Object-oriented programming", "A way of organising a program as objects. An object combines data and the functions that work on that data. Classes describe those objects."),
        ("def", "Class", "A user-defined type that specifies the data members and member functions common to a kind of object."),
        ("def", "Object", "One instance of a class. It has its own copies of the data members and it can call the member functions."),
        ("p", "**Encapsulation** places data and the functions that use it inside a class, and controls who may touch the data. **Inheritance** lets a new class receive members from an existing class, so common code is written once. **Polymorphism** lets one name mean more than one function, chosen from the arguments or from the kind of object."),
        ("p", "A class has **data members**, the values stored in each object, and **member functions**, the operations. Data members are usually private. Member functions that the rest of the program may call are public. The public functions are the interface. The private data is the detail that can change without rewriting every caller."),
        ("h", "3.2 Encapsulation and access"),
        ("table", "Access specifiers", ["Specifier", "Who can use the member"], [
            ["private", "Member functions of the same class. This is the default if you write nothing."],
            ["public", "Any code that has the object."],
            ["protected", "The class itself and classes derived from it. Not the general caller."],
        ]),
        ("def", "Data hiding", "Keeping data members private so that outside code cannot change them directly. Outside code calls a public function, and that function can check the value."),
        ("p", "A **constructor** is a member function with the same name as the class and no return type. It runs automatically when an object is created, so the object starts in a known state. A **default constructor** takes no arguments. A **parameterised constructor** takes values and copies them into the data members. **Constructor overloading** means providing more than one constructor, with different parameter lists. A **destructor** has the class name with a tilde in front, such as `~Time()`, takes no arguments, and runs when the object is destroyed. Use it to release anything the object acquired. In the simple classes in this unit the destructor is often empty, but you should be able to write one."),
        ("code", "Program 3.1  Class Student with private data and public functions", "student_class"),
        ("p", "Main cannot write `s.age = 17` if age is private. It calls `setData`, and `showData` prints the values. That is encapsulation. Input 17 and 88 prints those values through the object, not through the variables in main."),
        ("code", "Program 3.2  Default and parameterised constructors", "constructor_student"),
        ("code", "Program 3.3  Class Time with two constructors", "time_class"),
        ("p", "`Time t(h, m, s)` calls the constructor with three arguments. `Time empty;` calls the default constructor and prints 0:0:0. The two constructors are an overload. There is no return type in front of Time."),
        ("h", "3.3 Inheritance"),
        ("def", "Inheritance", "A mechanism by which a derived class receives members from a base class and can add its own members."),
        ("p", "**Reusability** is the practical gain. The base class holds the common members. Each derived class adds what is special to it, instead of copying the common code. The **base class** is the existing class. The **derived class** is the new class, written `class DriveClass : public Base`. Public inheritance means the public members of the base stay public for users of the derived class."),
        ("p", "Protected members are the ones a derived class may use while the rest of the program still cannot. In the program below, name and age are protected in Base, so DriveClass can rely on the base functions that set them. Roll belongs only to the derived class."),
        ("code", "Program 3.4  A derived class using a base class", "inheritance"),
        ("p", "The object in main is a DriveClass, not a Base. `setDrive` calls `setBase`, so the derived class reuses the base behaviour. The printed name, age and roll show both parts of the object."),
        ("h", "3.4 Polymorphism"),
        ("def", "Polymorphism", "One interface, more than one function. In this course that means overloading and overriding."),
        ("p", "**Overloading** a member function means several functions in the same class share a name and differ in their parameter lists. `area(int)` and `area(int, int)` can both exist. The call decides which one runs. This is the same rule as function overloading in Class XI."),
        ("p", "**Overriding** means a derived class provides its own version of a function that the base class already has. The derived version replaces the base version for a derived object. If the base function is marked `virtual` and the call is made through a base pointer that actually points to a derived object, the derived function runs. That is the form of overriding that behaves according to the real object. A function that is not virtual and is called through a base pointer would run the base version, so the examples in this lecture mark `show` as virtual."),
        ("code", "Program 3.5  Overloading area and overriding show", "poly"),
        ("p", "`shape.area(4)` prints 16. `shape.area(4, 5)` prints 20. The pointer `p` has type Base* and points at a Drive object. Because `show` is virtual, the call prints `Drive show`. If you remove virtual, the same call prints `Base show`. That single experiment is the best way to remember why the keyword is there."),
        ("table", "Overloading and overriding", ["Basis", "Overloading", "Overriding"], [
            ["Where", "Same class", "Derived class and its base"],
            ["Names", "Same name", "Same name"],
            ["Parameter list", "Must differ", "Stays the same"],
            ["What chooses the function", "The arguments at the call", "The kind of object, when the function is virtual"],
        ]),
        ("tip", "A full-mark class program has: the class heading, private data, a public constructor or setter, a public display function, an object in main, a call, and matching braces. Inheritance adds the colon, public Base, and at least one use of a base member."),
    ],
    "terms": [
        ["Class", "The description of data members and member functions."],
        ["Object", "One instance of a class."],
        ["Encapsulation", "Data and functions bound together, with access controlled."],
        ["Data hiding", "Private data changed only through member functions."],
        ["Constructor", "A special function that initialises an object when it is created."],
        ["Destructor", "A special function that runs when an object is destroyed."],
        ["Base class", "The class that is inherited from."],
        ["Derived class", "The class that inherits."],
        ["Overriding", "A derived class replacing a base function of the same signature."],
    ],
    "summary": [
        "A class is a type. An object is one value of that type.",
        "Private data and public functions are encapsulation. Protected data is visible to derived classes.",
        "Constructors initialise. You may overload them. A destructor tidies up.",
        "Inheritance reuses a base class. Polymorphism in this unit is overloading plus overriding.",
    ],
    "labs": [
        "Define Student with age and percentage. Input the values and show them through an object.",
        "Initialise a Student and a Time object with constructors.",
        "Inherit a derived class from a base class and show data through the derived object.",
        "Demonstrate overloading of area and overriding of show.",
    ],
    "mcqs": [
        {"q": "An object is:", "options": ["An instance of a class", "A transmission medium", "A file mode", "A normal form"], "a": "A", "why": "The class describes the kind. The object is one instance."},
        {"q": "Private members can be used directly by:", "options": ["Member functions of the same class", "Every function in the program", "Only the operating system", "Only SQL"], "a": "A", "why": "Private means the rest of the program must go through the class's own functions."},
        {"q": "A constructor:", "options": ["Has the class name and no return type", "Is named main", "Must return int", "Is a topology"], "a": "A", "why": "Constructors are named after the class and do not have a return type."},
        {"q": "Public inheritance is written:", "options": ["class Drive : public Base", "class Drive inherits Base", "Drive extends public", "public(Drive, Base)"], "a": "A", "why": "The colon and public Base are the C++ syntax."},
        {"q": "Protected members are available to:", "options": ["The class and its derived classes", "Every file on the disk", "Only the linker, never a derived class", "Only constructors of unrelated classes"], "a": "A", "why": "Protected sits between private and public for inheritance."},
        {"q": "Overloading is distinguished by:", "options": ["The parameter list", "The return type alone", "The file name", "The colour of the IDE"], "a": "A", "why": "Overloaded functions share a name and differ in their parameters."},
        {"q": "A virtual function lets a base pointer call:", "options": ["The derived override when the object is derived", "Only ROM", "A flowchart", "The power supply"], "a": "A", "why": "virtual selects the function from the actual object."},
        {"q": "The destructor name for class Time is:", "options": ["~Time", "delete Time", "Time()", "end Time"], "a": "A", "why": "The destructor is a tilde followed by the class name."},
    ],
    "shorts": [
        {"q": "Differentiate a class and an object.", "a": "A class is a user-defined type that describes data members and member functions. An object is one instance of that class and holds its own data. Student is the class. One pupil, s, is an object. Many objects can be created from one class."},
        {"q": "Define encapsulation and data hiding.", "a": "Encapsulation binds data and the functions that operate on it into a class, and uses access specifiers to control access. Data hiding keeps the data private so outside code cannot assign to it directly. A public function can check a value before storing it."},
        {"q": "Differentiate a constructor and a destructor.", "a": "A constructor runs when an object is created and initialises it. It has the class name and no return type. A destructor runs when the object is destroyed and releases what the object acquired. Its name is ~ followed by the class name. A class may overload constructors. There is one destructor."},
        {"q": "What does public inheritance give the derived class?", "a": "The derived class receives the members of the base and can add its own. Public members of the base remain available to users of the derived object. Protected members of the base can be used inside the derived class. Private members of the base stay accessible only through the base class's own functions."},
        {"q": "Differentiate overloading and overriding.", "a": "Overloading defines several functions of the same name in one class with different parameter lists. The arguments select the function. Overriding defines, in a derived class, a function with the same signature as a base function. For a derived object the derived function replaces the base one. Mark the base function virtual when the call is made through a base pointer."},
    ],
    "longs": [
        {"q": "Explain encapsulation, inheritance and polymorphism, and illustrate each with C++.", "points": [
            "Define OOP, class and object.",
            "Explain encapsulation with private data and a public set and show function. Mention the access specifiers.",
            "Explain inheritance with base, derived, public inheritance and reusability. Mention protected.",
            "Explain polymorphism as overloading and overriding, with the virtual keyword for a real override through a pointer.",
            "Use one small sketch of code for each idea rather than one unrelated program.",
        ]},
        {"q": "Explain constructors, constructor overloading and the creation of objects. Use the class Time.", "points": [
            "Define a constructor and state that it has no return type.",
            "Write a default constructor that stores zeroes and a constructor that copies hours, minutes and seconds.",
            "Show Time empty; and Time t(h, m, s); and say which constructor each one calls.",
            "Show a display function.",
            "Add one sentence on the destructor and when it runs.",
        ]},
    ],
}
