"""Practical journal for the Class XI and Class XII labs."""

LABS = [
    {
        "grade": "XI",
        "code": "XI-1",
        "title": "Parts of the system unit and the motherboard",
        "aim": "Identify the processor, motherboard, memory, storage, power supply and ports, and say which block of the computer diagram each one belongs to.",
        "need": ["A desktop system unit the teacher has opened, or a labelled photograph of a motherboard", "The block diagram from Unit 1"],
        "steps": [
            "Unplug the computer before the case is opened. Do this only with the teacher.",
            "Point to the power supply, the motherboard, the hard drive, the RAM and the processor fan.",
            "On the motherboard, find the processor socket, the RAM slots, the CMOS battery, a port cluster and an expansion slot.",
            "Write one sentence for each part saying whether it is processing, storage, memory or connection.",
        ],
        "output": "A labelled list of at least eight parts, each attached to its function.",
        "viva": ["Which part keeps the clock when the mains lead is pulled out?", "Why is the processor fitted with a heat sink?"],
    },
    {
        "grade": "XI",
        "code": "XI-2",
        "title": "Seating memory and connecting drives",
        "aim": "Remove and reseat a RAM module and trace the data and power cables of a drive.",
        "need": ["An unplugged system unit", "A RAM module compatible with the board"],
        "steps": [
            "Shut down, unplug the mains, and press the power button once.",
            "Release the RAM clips, remove the module, and note the notch.",
            "Press the module back into the same slot until both clips close.",
            "Trace the drive's data cable to the board and its power cable to the power supply. Do not force a connector.",
        ],
        "output": "The machine still starts, and you can say which notch direction you used.",
        "viva": ["Why must the mains lead be out?", "What does the notch prevent?"],
    },
    {
        "grade": "XI",
        "code": "XI-3",
        "title": "Boot options in firmware setup",
        "aim": "Open the BIOS or UEFI setup and find the boot order without leaving a changed setting.",
        "need": ["A lab computer", "The key the teacher gives for setup, often Del, F2 or F10"],
        "steps": [
            "Restart and press the setup key before the operating system loads.",
            "Find the screen that lists boot devices.",
            "Read the first device in the list and write it down.",
            "Exit without saving.",
        ],
        "output": "The name of the first boot device, and confirmation that you discarded changes.",
        "viva": ["What is the BIOS for?", "What is the difference between a cold boot and a warm boot?"],
    },
    {
        "grade": "XI",
        "code": "XI-4",
        "title": "Files, folders, paths and search",
        "aim": "Create, copy, move, rename and delete files, and find a file by name.",
        "need": ["Windows with File Explorer"],
        "steps": [
            "Create a folder CS-XI on the desktop.",
            "Create a text file inside it, then copy the file, rename the copy, and move the copy to a second folder.",
            "Write the absolute path of the renamed file, including the drive letter.",
            "Delete nothing until you have searched for the file by part of its name and opened it from the search result.",
        ],
        "output": "Two folders, a renamed copy, and the path written in your journal.",
        "viva": ["How does a copy differ from a move?", "What is an absolute path?"],
    },
    {
        "grade": "XI",
        "code": "XI-5",
        "title": "Attributes and the control panel",
        "aim": "Set file attributes and locate hardware and software settings, dxdiag and msconfig.",
        "need": ["The file created in XI-4"],
        "steps": [
            "Open the file properties and set Read-only. Try to save a change and record what happens. Clear Read-only.",
            "Set Hidden, refresh the folder, then show hidden files and clear the attribute.",
            "From the control panel, find the display or sound settings and the list of installed programs. Change nothing you cannot reverse.",
            "Run dxdiag and record the operating system name and the memory size. Run msconfig, look at Services, and close without saving.",
        ],
        "output": "The four attribute names, plus the operating system and RAM reported by dxdiag.",
        "viva": ["What does the archive attribute mean?", "Why should msconfig be closed without a change unless you intend one?"],
    },
    {
        "grade": "XI",
        "code": "XI-6",
        "title": "Calculator",
        "aim": "Use arithmetic operators and guard against division by zero.",
        "need": ["A C++ compiler"],
        "steps": ["Type the program, compile it, and run it twice.", "First use 12 and 3. Then use 12 and 0."],
        "program": "calculator",
        "output": "The first run prints 15, 9, 36 and 4. The second run refuses the division.",
        "viva": ["What is the difference between / and %?", "Why is the divisor tested?"],
    },
    {
        "grade": "XI",
        "code": "XI-7",
        "title": "Mark sheet with selection",
        "aim": "Choose a grade with if and else-if, and reject an impossible mark.",
        "need": ["A C++ compiler"],
        "steps": ["Run the program with 76, with 40 and with 110."],
        "program": "marksheet",
        "output": "Grades B, Fail and Invalid.",
        "viva": ["Why does the order of the else-if tests matter?", "Which structure would you use for a menu of exact day numbers?"],
    },
    {
        "grade": "XI",
        "code": "XI-8",
        "title": "Prime or composite",
        "aim": "Use a loop and a decision to classify a number.",
        "need": ["A C++ compiler"],
        "steps": ["Test 17, 18 and 1."],
        "program": "prime",
        "output": "17 is prime, 18 is composite, and 1 is neither.",
        "viva": ["Why does the loop start at 2?", "What does break do here?"],
    },
    {
        "grade": "XI",
        "code": "XI-9",
        "title": "Digits and factors",
        "aim": "Isolate digits with integer division and list factors with a loop.",
        "need": ["A C++ compiler"],
        "steps": [
            "Run the digit program below with 2024.",
            "Run Program 5.7, Factors of a number, from the Class XI lecture, with 12.",
        ],
        "program": "digits",
        "output": "The digits of 2024 print as 2, 0, 2 and 4 on separate lines. The factor program prints 1 2 3 4 6 12.",
        "viva": ["What does n % 10 give?", "Why does the factor loop run from 1 to n?"],
    },
    {
        "grade": "XI",
        "code": "XI-10",
        "title": "Functions: stars and the larger number",
        "aim": "Write a function, call it, and return a value.",
        "need": ["A C++ compiler"],
        "steps": [
            "Build the star function below and call it with size 4.",
            "Build Program 5.11, the larger function, from the Class XI lecture and call it with 14 and 22.",
        ],
        "program": "stars",
        "output": "Four rows of stars, growing from one star to four. larger(14, 22) returns 22.",
        "viva": ["Which names are formal parameters?", "Where is the value of larger sent back?"],
    },
    {
        "grade": "XI",
        "code": "XI-11",
        "title": "Sort, search and average",
        "aim": "Traverse an array to sort it, to find a value, and to average a list.",
        "need": ["A C++ compiler"],
        "steps": ["Run the sort and search program and look up 4.", "Run the average program with four numbers: 10 20 30 40."],
        "program": "sort_search",
        "output": "The numbers print as 1 2 4 5. The names print as Ali Hina Sara. 4 is found at index 2. The average is 25.",
        "viva": ["Why is the first index 0?", "What does the function report if the value is absent?"],
    },
    {
        "grade": "XI",
        "code": "XI-12",
        "title": "Matrices, strings and an employee record",
        "aim": "Add and multiply 3 by 3 matrices, reverse a name, and store an employee in a structure.",
        "need": ["A C++ compiler"],
        "steps": [
            "Run the matrix program below and check the first row of the sum and of the product.",
            "Run Program 6.6 from the Class XI lecture with the name Ayesha.",
            "Run Program 6.7, the employee structure, with Ali, Teacher and 55000.",
        ],
        "program": "matrix",
        "output": "Sum row 2 2 3. Product equals the first matrix because the second is an identity. Ayesha reverses to ahseyA. The employee fields print back unchanged.",
        "viva": ["What does the null character do in a C string?", "How do you reach a structure member?"],
    },
    {
        "grade": "XI",
        "code": "XI-13",
        "title": "Straight and crossover cables",
        "aim": "Tell a straight-through cable from a crossover cable and know where each is used.",
        "need": ["Two short lengths of twisted-pair cable", "RJ-45 plugs and a crimp tool, used by the teacher", "A cable tester if the lab has one"],
        "steps": [
            "A straight-through cable uses the same colour order at both ends. The T568B order is white-orange, orange, white-green, blue, white-blue, green, white-brown, brown.",
            "A crossover cable uses T568B at one end and T568A at the other. T568A swaps the orange and green pairs: white-green, green, white-orange, blue, white-blue, orange, white-brown, brown.",
            "Use straight-through from a computer to a switch. The older direct computer-to-computer link used a crossover. Many modern ports detect the cable and adapt.",
            "If you crimp, the teacher checks the order before the plug is pressed. Test continuity afterwards.",
        ],
        "output": "A note of both colour orders and which cable joins a PC to a switch.",
        "viva": ["Which cable joins a PC to a switch?", "Name one guided medium other than twisted pair."],
    },
    {
        "grade": "XI",
        "code": "XI-14",
        "title": "Network devices, IP settings and a small LAN",
        "aim": "Identify the devices, read an IP configuration, and describe a central server against a peer arrangement.",
        "need": ["The lab network", "A computer on that network"],
        "steps": [
            "Point to the NIC, the switch, the router or modem, and any wireless access point.",
            "Open the IP settings. Record the IPv4 address, the subnet mask and the default gateway.",
            "A typical lab host might be 192.168.1.10 with mask 255.255.255.0 and gateway 192.168.1.1. Use the numbers your screen shows, not this example, if they differ.",
            "Decide whether shared files come from one server (centralised) or from several student computers (decentralised, peer sharing). Write which one the lab uses and one consequence.",
        ],
        "output": "A sketch of the lab links and the three IP numbers from the computer you used.",
        "viva": ["What does the default gateway do?", "Give one advantage of keeping shared files on one server."],
    },
    {
        "grade": "XII",
        "code": "XII-1",
        "title": "Class Student",
        "aim": "Hide age and percentage in a class and reach them through an object.",
        "need": ["A C++ compiler"],
        "steps": ["Compile the class, enter 17 and 88, and confirm that main does not assign to the private members directly."],
        "program": "student_class",
        "output": "Age 17 and percentage 88 printed by showData.",
        "viva": ["Why is the data private?", "What is the object in this program?"],
    },
    {
        "grade": "XII",
        "code": "XII-2",
        "title": "Constructors for Student and Time",
        "aim": "Initialise objects with a default constructor and a parameterised constructor.",
        "need": ["A C++ compiler"],
        "steps": ["Run the Student constructor program.", "Run the Time program with 2 15 40 and notice the second object created with no arguments."],
        "program": "time_class",
        "output": "Time prints 2:15:40 and the default object prints 0:0:0. The Student constructor program prints age 17 and percentage 91.",
        "viva": ["How can you tell a constructor from an ordinary function?", "What is constructor overloading?"],
    },
    {
        "grade": "XII",
        "code": "XII-3",
        "title": "Inheritance, overloading and overriding",
        "aim": "Reuse a base class, overload a member function, and override a virtual function.",
        "need": ["A C++ compiler"],
        "steps": ["Run the inheritance program with Ayesha 17 4521.", "Run the polymorphism program and read both area lines and the show line."],
        "program": "inheritance",
        "output": "Name, age and roll come from the derived object. The other program prints square 16, rectangle 20 and Drive show.",
        "viva": ["What does protected allow?", "Why is show marked virtual?"],
    },
    {
        "grade": "XII",
        "code": "XII-4",
        "title": "Pointers",
        "aim": "Show an address and a value, then change two variables through pointer parameters.",
        "need": ["A C++ compiler"],
        "steps": ["Run the basic pointer program and record the value before and after the write through the pointer.", "Run the doubling program with 4 and 7."],
        "program": "pointer_basic",
        "output": "The value changes from 25 to 40. The doubling program prints 8 and 14. The numeric address may differ each run.",
        "viva": ["What does & return?", "What does the star do in *p and in the declaration int *p?"],
    },
    {
        "grade": "XII",
        "code": "XII-5",
        "title": "Text and binary files",
        "aim": "Store a student in a text file and in a binary file, then read both back.",
        "need": ["A C++ compiler", "A folder you are allowed to write in"],
        "steps": ["Run the text program and open student.txt in an editor.", "Run the binary program and compare the editor view of student.bin with the printed fields."],
        "program": "text_file",
        "output": "The text file shows Ayesha and 88 as characters. The binary program prints Ayesha, 17 and 88.5. The binary file is not a document to edit.",
        "viva": ["What does ios::app do differently from ios::out?", "What is EOF for?"],
    },
    {
        "grade": "XII",
        "code": "XII-6",
        "title": "SQL for a student result",
        "aim": "Create a table, change its rows, and write a query that selects and projects.",
        "need": ["Microsoft Access or any SQL environment the lab provides"],
        "steps": [
            "Create STUDENT with StudentID as the primary key, StudentName as NOT NULL, and Dept.",
            "Insert Ayesha of Science and Bilal of Science.",
            "Update one department, then delete a row you created for practice.",
            "Add RESULT with StudentID, SubjectID and Marks, and a foreign key to STUDENT if the software makes that easy.",
            "Write a query that shows only the names of Science students, and a join that shows a name with a mark.",
        ],
        "program": """CREATE TABLE STUDENT (
    StudentID VARCHAR(6) PRIMARY KEY,
    StudentName VARCHAR(40) NOT NULL,
    Dept VARCHAR(20)
);

INSERT INTO STUDENT (StudentID, StudentName, Dept)
VALUES ('S1', 'Ayesha', 'Science');

SELECT StudentName
FROM STUDENT
WHERE Dept = 'Science';
""",
        "output": "The Science query returns Ayesha. The table refuses a second row with StudentID S1.",
        "viva": ["Which clause selects rows?", "Which part of SELECT projects columns?"],
    },
    {
        "grade": "XII",
        "code": "XII-7",
        "title": "A short multimedia sequence",
        "aim": "Combine text, an image and sound on layers, use two keyframes, export the result, and be ready to extend it to two minutes.",
        "need": ["A video editor such as OpenShot, Shotcut or the package installed in the lab", "One diagram from these lectures and a short recording of your voice"],
        "steps": [
            "Plan four scenes on paper. For this practical, build the first 20 to 30 seconds.",
            "Set the canvas, put the diagram on a lower layer and a title on a higher layer.",
            "Set a keyframe at the start and another two seconds later that moves the title slightly.",
            "Add the voice recording. Export an MP4. If the software allows, export a second format as well.",
            "Show the file to the teacher. Extend the same project to about two minutes for the full curriculum piece, then share it by the method the teacher sets.",
        ],
        "output": "An MP4 that shows a title over a diagram and plays your voice.",
        "viva": ["What is a layer for?", "What is a keyframe for?"],
    },
]
