"""Class XI lectures aligned to the Sindh Computer Science Curriculum 2019."""

from reportlab.lib.units import mm

PREFACE = {
    "grade": "XI",
    "unit": "",
    "kicker": "Class XI  |  before the units",
    "title": "How to use these lectures",
    "weight": "",
    "periods": "Paper pattern used with the published BIEK scheme for Computer Science",
    "intro": (
        "These lectures follow the Sindh Curriculum for Computer Science, Grades XI-XII, 2019, "
        "which is the curriculum taught for the Board of Intermediate Education, Karachi. "
        "Each unit states the outcomes, teaches the ideas in classroom language, and ends with "
        "the kind of questions the board paper asks. They are original teaching notes, not a copy of any textbook."
    ),
    "slos": [
        "Know the shape of the Computer Science paper and the weight of each Class XI unit.",
        "Write a definition, a difference, and a program in the form examiners can mark.",
    ],
    "path": [
        "Read the lecture once without stopping on the questions.",
        "Close the notes and answer the checkpoint. Then mark it with the key.",
        "Type every complete program and run it. The practical journal has the lab steps.",
        "Before the exam, confirm the model paper and any reduced syllabus for your year on the board site biek.edu.pk.",
    ],
    "sections": [
        ("h", "The paper"),
        ("p", "The scheme published by the Board for Computer Science Paper I and Computer Science Paper II sets a three-hour paper of 75 marks. Use that shape for practice. If the board issues a new model paper for your examination year, follow the new paper."),
        ("table", "", ["Section", "Time guide", "What you do", "Marks"], [
            ["A", "30 minutes", "29 multiple-choice questions. Attempt all of them.", "29"],
            ["B", "90 minutes", "15 short questions are set. Attempt any 10. Each is 3 marks.", "30"],
            ["C", "60 minutes", "3 detailed questions are set. Attempt any 2. Each is 8 marks. The scheme does not split these into parts.", "16"],
        ]),
        ("p", "Section A is about 40 percent of the paper, Section B about 40 percent, and Section C about 20 percent. A paper of this shape rewards a student who can define a term, give an example, and still write a working program."),
        ("h", "Unit weight in Class XI"),
        ("p", "The curriculum gives these weights. A higher weight means more classroom time and a greater chance of a longer question."),
        ("table", "", ["Unit", "Title", "Weight", "Theory periods", "Lab periods"], [
            ["1", "Overview of the computer system", "15%", "15", "-"],
            ["2", "Computer memory", "10%", "10", "-"],
            ["3", "Inside the system unit", "15%", "10", "10"],
            ["4", "Operating system", "10%", "10", "10"],
            ["5", "Programming in C++", "20%", "20", "20"],
            ["6", "Arrays, strings and structures", "15%", "25", "25"],
            ["7", "Communication and networks", "15%", "25", "-"],
        ]),
        ("h", "How answers earn marks"),
        ("ul", [
            "**Define** means one precise sentence, then stop. Add an example only if the question asks for it.",
            "**Differentiate** means a table. Three rows are enough for 3 marks. Name the basis of comparison in the first column.",
            "**Explain** or **describe** means a short paragraph with a reason, not a list of headings only.",
            "**Write a program** means a complete program: include line, the code, and a return from main. Use the variable names the question gives.",
            "Draw a diagram when the question says show, draw, or illustrate. Label every box.",
        ]),
        ("tip", "Many colleges still use an old compiler that wants `#include <iostream.h>` and `void main()`. These lectures use standard C++, which current compilers accept: `#include <iostream>`, `using namespace std;`, and `int main()`. The logic the examiner marks is the same. Match the house style of your practical journal, and keep the program correct."),
    ],
    "terms": [],
    "summary": [
        "Practice all three sections. Programming units carry the most weight in Class XI.",
        "Check the current model paper on biek.edu.pk before the annual examination.",
    ],
    "mcqs": [],
    "shorts": [],
    "longs": [],
    "labs": [],
}

LECTURES = []

LECTURES.append({
    "grade": "XI",
    "unit": "1",
    "kicker": "Class XI  |  Unit 1  |  weight 15%",
    "title": "Overview of the computer system",
    "weight": "15%",
    "periods": "15 theory periods",
    "intro": "A computer is a system, not a single box. This lecture names the parts, sorts the devices by the job they do, and separates the programs that run the machine from the programs that do your work.",
    "slos": [
        "Describe a computer and the four basic operations.",
        "Draw the block diagram and place hardware, software and memory on it.",
        "Classify input, output, storage, processing and communication devices.",
        "Explain system software, application software and utility software.",
        "Compare primary and secondary memory.",
        "Describe how computing is used now, including artificial intelligence and cloud computing.",
    ],
    "path": [
        "Start with the definition and the block diagram. Students copy the diagram before any list of devices.",
        "Sort devices by function. A device can be named only after its class is clear.",
        "Teach the three software families with one example each.",
        "Close with artificial intelligence and the cloud, each tied to a local example.",
    ],
    "sections": [
        ("h", "1.1 A computer system"),
        ("def", "Computer", "An electronic system that takes data as input, processes it according to instructions, stores data and results, and gives information as output."),
        ("p", "Data is the raw fact you enter, such as a set of marks. Information is the processed result, such as a grade or a class average. The machine follows a program, which is a stored sequence of instructions. The four operations you should be able to name in order are input, processing, storage and output."),
        ("diagram", "computer", "Figure 1.1  Block diagram of a computer system.", 58 * mm),
        ("p", "The arrows in Figure 1.1 are the basic operations. Input devices send data in. The CPU processes it. Memory holds the instructions and the data while the work is going on. Output devices present the result. Secondary storage keeps a copy after the power is switched off. Software is the set of programs that tell this hardware what to do. Hardware is the physical equipment."),
        ("h", "1.2 Hardware by function"),
        ("p", "Classify a device by the job it does. A keyboard is input because data travels from the user into the computer. A printer is output because information travels out. A hard disk is storage. The processor is the processing device. A router is a communication device."),
        ("h3", "Input devices"),
        ("ul", [
            "**Keyboard** enters characters. A mouse points and clicks.",
            "**Joystick or joypad** is used for direction and actions, often in games and simulators.",
            "**Scanning devices** turn a printed page or a photograph into digital data.",
            "**Data tablet and stylus** let a person draw or write by hand. The stylus is the pen.",
            "**Voice recognition** turns speech into text or commands. A **microphone** captures the sound.",
            "**Touch screen** receives input by touch and often displays output as well. Name the role the question asks about.",
            "**Webcam** captures live video. A **barcode scanner** reads a printed code on a product.",
        ]),
        ("h3", "Output devices"),
        ("ul", [
            "**Monitors** display results. LED and LCD panels are flat and use less power. Plasma is an older flat panel. CRT is the deep glass monitor of earlier computers.",
            "**Printers** put results on paper. A dot-matrix printer is an impact printer: pins strike a ribbon. Inkjet and laser printers are non-impact. Thermal printers heat special paper.",
            "A **plotter** draws precise lines, used for maps and engineering drawings.",
            "A **multimedia projector** throws the screen onto a wall. **Speakers and headphones** produce sound.",
            "A **speech generating device (SGD)** speaks text aloud for a user who cannot use ordinary speech.",
        ]),
        ("h3", "Storage, processing and communication"),
        ("ul", [
            "**Hard disk** stores large amounts of data magnetically. **Flash, USB and pen drives** store data in electronic memory and travel in a pocket.",
            "**CD, DVD, CD-R and CD-RW** are optical discs. CD-R records once. CD-RW can be rewritten. **Blu-ray** holds high-definition video. **SD and microSD cards** are small flash cards used in phones and cameras.",
            "The **processor** is the processing hardware. It is taught properly in Unit 3.",
            "**Network interface card** connects the computer to a network cable or a wireless network.",
            "A **modem** turns the computer's digital signal into a form a telephone or cable line can carry, and turns the incoming signal back.",
            "**Data terminal equipment** is the device at the end of a link, such as a computer or a terminal. A **fax machine** sends a copy of a page over a telephone line.",
            "A **hub** repeats data to every connected device. A **switch** sends a frame only toward its destination inside a local network. A **router** forwards packets between networks. A **gateway** connects networks that do not speak the same protocol and translates between them.",
        ]),
        ("tip", "If a question asks you to classify webcam, plotter, SD card, router and keyboard, write the class first and the name second: input, output, storage, communication, input."),
        ("h", "1.3 Software"),
        ("def", "Software", "The programs and related data that tell the hardware what to do."),
        ("p", "**System software** runs and controls the computer. It includes the operating system, device drivers, language translators and antimalware programs. A device driver teaches the operating system how to talk to one piece of hardware, such as a printer. A language translator turns a program written by a person into a form the processor can run."),
        ("table", "Language translators", ["Translator", "What it does"], [
            ["Assembler", "Converts assembly language into machine code."],
            ["Compiler", "Translates a whole high-level program into an object program, then the program can be run."],
            ["Interpreter", "Translates and runs one statement at a time. It stops at the first error it meets."],
        ]),
        ("p", "**Antimalware** protects the computer from harmful programs. Antivirus software finds and removes viruses. A Trojan horse is a harmful program disguised as something useful, so protection has to recognise that disguise as well."),
        ("p", "**Application software** does a job for the user. General-purpose software is sold for many people and many tasks: a word processor, a spreadsheet, a browser. Special-purpose software is built for one kind of organisation: a college admission system, a hospital record system, a shop billing system."),
        ("p", "**Utility software** maintains the computer. Compression software makes files smaller for storage or sending. Data-recovery software tries to bring back deleted or damaged files. A disk manager partitions a disk, cleans up files and can defragment a hard disk."),
        ("h", "1.4 Primary and secondary memory"),
        ("p", "Primary memory is the memory the CPU works with directly. RAM holds the running program and its data. It is fast, and it is volatile: the contents go when the power goes. ROM holds permanent start-up instructions and is non-volatile."),
        ("p", "Secondary memory keeps data and programs for the long term. Hard disks, USB drives, optical discs and memory cards are secondary. The CPU does not execute a program from a USB drive directly. The program is first loaded into RAM. Secondary memory has more capacity, costs less per byte, and keeps its contents without power. It is slower than RAM."),
        ("table", "Primary memory and secondary memory", ["Basis", "Primary", "Secondary"], [
            ["Contact with the CPU", "Direct", "Indirect, through primary memory"],
            ["Speed", "Faster", "Slower"],
            ["Typical contents", "Running program and data", "Stored files and software"],
            ["Power removed", "RAM loses its contents", "Contents remain"],
            ["Capacity and cost", "Smaller, costlier per byte", "Larger, cheaper per byte"],
        ]),
        ("h", "1.5 Computing now"),
        ("p", "Computers now sit inside phones, vehicles, hospitals, banks and classrooms. They speed up calculation, store huge records, and connect people. The same tools raise questions of privacy, honest use of information, and dependence on a working network."),
        ("def", "Artificial intelligence", "The building of computer systems that perform tasks which ordinarily need human intelligence, such as recognising speech, learning from examples, and supporting a decision."),
        ("p", "In a hospital, an AI system can flag an X-ray for a doctor to review. In a school it can practise language with a student. In traffic it can change signal timing. On a farm it can watch crop images for disease. The system is a tool for a person who remains responsible for the decision."),
        ("def", "Cloud computing", "The delivery of storage, software and processing over a network, from servers run by a provider, paid for and used as they are needed."),
        ("ul", [
            "A college can start with a small service and increase storage or processing when admissions begin.",
            "Students reach the same files from a lab computer or a phone.",
            "The provider maintains the servers and keeps backup copies as part of the service.",
            "Several people can work on one document.",
            "The college spends less on its own server room at the start.",
        ]),
        ("p", "Cloud work needs a network connection. The data lives on the provider's machines, so the college needs a clear agreement about who may see it."),
        ("tip", "A strong 8-mark answer on this unit is the block diagram with labels, plus one paragraph that places software and both kinds of memory on the diagram."),
    ],
    "terms": [
        ["Data", "Raw facts entered into the computer."],
        ["Information", "Data after processing, useful for a decision."],
        ["Hardware", "Physical parts of the computer system."],
        ["Software", "Programs that instruct the hardware."],
        ["System software", "Programs that operate and control the computer."],
        ["Application software", "Programs that perform a user task."],
        ["Utility software", "Programs that maintain the computer."],
        ["Volatile memory", "Loses its contents when power is removed."],
        ["Cloud computing", "On-demand computing services delivered over a network."],
    ],
    "summary": [
        "A computer inputs, processes, stores and outputs. Hardware does the physical work. Software gives the instructions.",
        "Name every device by its function: input, output, storage, processing or communication.",
        "System software runs the machine. Application software does the user's job. Utilities maintain the machine.",
        "Primary memory serves the CPU now. Secondary memory keeps files for later.",
        "AI systems support intelligent tasks. Cloud services provide computing over a network.",
    ],
    "labs": [
        "On a real system unit, point to the processor area, the memory modules, the hard drive and one port. Say which block of Figure 1.1 each part belongs to.",
    ],
    "mcqs": [
        {"q": "Which operation turns data into information?", "options": ["Input", "Processing", "Storage only", "Printing only"], "a": "B", "why": "Processing applies instructions to data and produces information."},
        {"q": "A plotter is classified as:", "options": ["Input", "Output", "Processing", "Communication"], "a": "B", "why": "A plotter presents results, usually as a precise drawing."},
        {"q": "Which program translates a high-level program one statement at a time?", "options": ["Compiler", "Assembler", "Interpreter", "Device driver"], "a": "C", "why": "An interpreter translates and executes statement by statement."},
        {"q": "A college fee system written for that college only is:", "options": ["Special-purpose application software", "An operating system", "A device driver", "ROM"], "a": "A", "why": "It performs one organisation's task, so it is special-purpose application software."},
        {"q": "RAM is described as volatile because:", "options": ["It is very large", "Its contents are lost when power is removed", "It stores files permanently", "It cannot be read"], "a": "B", "why": "Volatile memory needs power to hold its contents."},
        {"q": "Which device forwards packets from one network to another?", "options": ["Plotter", "Router", "Stylus", "Compiler"], "a": "B", "why": "A router connects networks and forwards packets."},
        {"q": "Cloud computing provides resources:", "options": ["Only by replacing the keyboard", "Over a network, as they are needed", "Only on a CD-ROM", "Only inside ROM"], "a": "B", "why": "The provider delivers storage, software or processing over a network."},
        {"q": "Compression software is a:", "options": ["Utility", "Language translator", "Input device", "Protocol"], "a": "A", "why": "Compression maintains files by making them smaller. That is a utility."},
    ],
    "shorts": [
        {"q": "Define a computer.", "a": "A computer is an electronic system that accepts data, processes it according to stored instructions, stores data and results, and produces information as output."},
        {"q": "Differentiate compiler and interpreter.", "a": "A compiler translates the whole source program and produces an object program which is then executed. An interpreter translates and executes one statement at a time and reports an error as soon as it reaches it. A compiled program is generally ready to run again without translating the source each time."},
        {"q": "Give two differences between primary and secondary memory.", "a": "Primary memory is directly accessible by the CPU and is faster. RAM, which is primary memory, loses its contents when power is removed. Secondary memory keeps files after power is removed, has larger capacity, and is slower. Programs are loaded from secondary memory into primary memory before execution."},
        {"q": "What is a device driver?", "a": "A device driver is system software that lets the operating system control a particular hardware device, such as a printer or a network card."},
        {"q": "Write two advantages of cloud computing.", "a": "The user can increase storage or processing when the work grows, and can reach the same files from different places. The provider maintains the servers, so the user spends less on a private machine room at the start."},
    ],
    "longs": [
        {"q": "Draw the block diagram of a computer system and explain its parts.", "points": [
            "Define a computer in one sentence.",
            "Draw input, CPU, memory and output. Inside the CPU show ALU, control unit and registers. Show a double arrow between CPU and memory.",
            "Explain input as data entering, processing as the CPU following instructions, memory as the working store, and output as information leaving.",
            "Add secondary storage under memory and say that it keeps files when power is off.",
            "Close with one line: hardware is the equipment in the diagram, software is the instructions that make it work.",
        ]},
        {"q": "Explain system software, application software and utility software with examples.", "points": [
            "Define software.",
            "System software operates the computer: operating system, device drivers, translators (assembler, compiler, interpreter) and antimalware.",
            "Application software does user work. General-purpose examples include a word processor and a browser. A special-purpose example is a hospital system.",
            "Utility software maintains the machine: compression, data recovery and disk management.",
            "Give one situation in which a student uses one program from each family on the same day.",
        ]},
    ],
})

LECTURES.append({
    "grade": "XI",
    "unit": "2",
    "kicker": "Class XI  |  Unit 2  |  weight 10%",
    "title": "Computer memory",
    "weight": "10%",
    "periods": "10 theory periods",
    "intro": "Memory is where the computer holds bits. This lecture teaches the units used to measure that holding, then the chips the CPU uses, then the devices that keep work after the computer is switched off.",
    "slos": [
        "Use bit, nibble, byte, kilobyte, megabyte, gigabyte and terabyte correctly.",
        "Distinguish volatile and non-volatile memory.",
        "Explain SRAM, DRAM, ROM, PROM, EPROM and EEPROM.",
        "Describe hard drives, USB flash drives, external hard drives, memory cards and combo drives.",
    ],
    "path": [
        "Practise the unit ladder with two numerical conversions before naming chips.",
        "Teach volatile and non-volatile with the power cable as the test.",
        "Compare SRAM with DRAM, then the ROM family, in tables students can reproduce.",
        "Finish with secondary devices they can point to in the lab.",
    ],
    "sections": [
        ("h", "2.1 Units of memory"),
        ("p", "A **bit** is one binary digit, 0 or 1. It is the smallest unit of storage. A **nibble** is 4 bits. A **byte** is 8 bits and is the usual unit for one character in the older character codes."),
        ("table", "The ladder used in this course", ["Unit", "Equals"], [
            ["1 nibble", "4 bits"],
            ["1 byte", "8 bits"],
            ["1 kilobyte (KB)", "1024 bytes"],
            ["1 megabyte (MB)", "1024 KB"],
            ["1 gigabyte (GB)", "1024 MB"],
            ["1 terabyte (TB)", "1024 GB"],
        ]),
        ("p", "In this course the multiplier is 1024, which is 2 to the power 10. Worked example: a file of 2 KB contains 2 x 1024 = 2048 bytes, and 2048 x 8 = 16384 bits. Worked example the other way: 4096 MB is 4096 / 1024 = 4 GB."),
        ("tip", "Write the unit in the answer. A bare 2048 is not a complete conversion if the question asked for bytes."),
        ("h", "2.2 Primary memory"),
        ("def", "Volatile memory", "Memory that loses its stored contents when the power supply is removed."),
        ("def", "Non-volatile memory", "Memory that keeps its stored contents when the power supply is removed."),
        ("p", "RAM is volatile working memory. ROM and secondary storage are non-volatile. The test is simple: switch the power off and ask whether the contents are still there."),
        ("h3", "RAM"),
        ("def", "RAM", "Random access memory. The processor can reach any location directly, without reading all the earlier locations. It holds the program and data that are in use, and it is volatile."),
        ("p", "**Static RAM (SRAM)** stores each bit in a small circuit of transistors arranged as a flip-flop. It does not need a refresh. It is fast and costly, so it is used in small amounts as cache inside or beside the processor."),
        ("p", "**Dynamic RAM (DRAM)** stores each bit as a charge in a tiny capacitor. The charge leaks, so the memory must be refreshed many times a second. DRAM is slower than SRAM and much cheaper per bit, so the large main memory of a PC is DRAM."),
        ("table", "SRAM and DRAM", ["Basis", "SRAM", "DRAM"], [
            ["Cell", "Flip-flop made of transistors", "Capacitor and transistor"],
            ["Refresh", "Not required", "Required"],
            ["Speed", "Faster", "Slower"],
            ["Cost and density", "Costlier, fewer bits on a chip", "Cheaper, more bits on a chip"],
            ["Typical use", "Cache", "Main memory"],
        ]),
        ("h3", "ROM and its family"),
        ("def", "ROM", "Read-only memory. In ordinary work the processor reads it and does not rewrite it. It is non-volatile and often holds the start-up program."),
        ("ul", [
            "**PROM**, programmable ROM, is written once by the user with a special device. After that the contents stay fixed.",
            "**EPROM**, erasable programmable ROM, can be erased by ultraviolet light through a window on the chip and then programmed again.",
            "**EEPROM**, electrically erasable programmable ROM, is erased and rewritten by electrical signals. A location can be updated without removing the chip. Flash memory, used in pen drives and SSDs, is a form of EEPROM erased in blocks.",
        ]),
        ("table", "The ROM family", ["Type", "Written", "Erased"], [
            ["ROM", "At manufacture", "Not erasable in ordinary use"],
            ["PROM", "Once, by the user", "Not erasable"],
            ["EPROM", "By a programmer", "By ultraviolet light"],
            ["EEPROM", "Electrically", "Electrically"],
        ]),
        ("diagram", "memory", "Figure 2.1  Memory ladder. The top is the fastest and the smallest. The bottom is the slowest and the largest.", 48 * mm),
        ("h", "2.3 Secondary memory"),
        ("def", "Secondary memory", "Non-volatile storage that keeps programs and data for later use. It is larger and slower than main memory. The CPU uses its contents after they are loaded into RAM."),
        ("ul", [
            "A **hard disk drive** stores data on magnetic platters. A head reads and writes while the platter spins. Capacity is large. It is the traditional store inside a desktop system unit.",
            "A **USB flash drive**, also called a pen drive or data traveller, uses flash memory. It is portable, has no spinning part, and plugs into a USB port.",
            "An **external hard drive** is a hard disk in its own case, usually attached by USB, used for backup and for moving large folders.",
            "An **SD card** or **microSD card** is a flash card used in phones, cameras and some laptops.",
            "A **combo drive** is an optical drive that works with more than one disc type, commonly CD and DVD. Discs are removable. CD-R records once. CD-RW can be rewritten.",
        ]),
        ("p", "Choose the device from the job. A running program needs RAM. A file you will open next month needs secondary storage. A copy you will carry to college needs a USB drive or a memory card. A full backup of a lab machine needs an external hard drive or a large internal disk."),
        ("tip", "Do not call a hard disk ROM. Both keep data without power. ROM is primary semiconductor memory for permanent instructions. A hard disk is secondary magnetic storage for files."),
    ],
    "terms": [
        ["Bit", "A single binary digit, 0 or 1."],
        ["Nibble", "Four bits."],
        ["Byte", "Eight bits."],
        ["RAM", "Volatile working memory with direct access to any location."],
        ["SRAM", "Fast RAM that stores bits in flip-flops and needs no refresh."],
        ["DRAM", "RAM that stores bits as charge and needs refresh."],
        ["ROM", "Non-volatile memory read in ordinary operation."],
        ["EEPROM", "ROM that can be erased and rewritten electrically."],
        ["Cache", "Small, fast SRAM used to feed the processor."],
    ],
    "summary": [
        "Measure memory from the bit up. In this course 1 KB is 1024 bytes.",
        "RAM is volatile working memory. SRAM is cache. DRAM is main memory.",
        "ROM, PROM, EPROM and EEPROM are non-volatile. They differ in how they are programmed and erased.",
        "Hard disks, flash drives, memory cards and optical combo drives are secondary storage.",
    ],
    "labs": [
        "Convert 3 KB to bytes and to bits on paper. Then read the size of a real file in the operating system and say whether it is closer to a KB, an MB or a GB.",
    ],
    "mcqs": [
        {"q": "A nibble contains:", "options": ["2 bits", "4 bits", "8 bits", "1024 bits"], "a": "B", "why": "A nibble is half a byte, so 4 bits."},
        {"q": "How many bytes are there in 1 KB in this course?", "options": ["1000", "1024", "8", "512"], "a": "B", "why": "The course uses 1024, which is 2 to the power 10."},
        {"q": "Which memory needs to be refreshed?", "options": ["SRAM", "DRAM", "DVD", "PROM"], "a": "B", "why": "DRAM stores charge in capacitors, and that charge must be refreshed."},
        {"q": "EPROM is erased by:", "options": ["Ultraviolet light", "A magnet", "A paper jam", "A plotter"], "a": "A", "why": "EPROM is erased by ultraviolet light shone through its window."},
        {"q": "Which memory is typically used as cache?", "options": ["DRAM", "SRAM", "CD-R", "Blu-ray"], "a": "B", "why": "SRAM is fast enough and costly enough that it is used in small cache."},
        {"q": "A pen drive is:", "options": ["Volatile primary memory", "Secondary flash storage", "A language translator", "An input-only device"], "a": "B", "why": "A pen drive keeps files without power and uses flash memory."},
        {"q": "PROM can be programmed:", "options": ["Every time the PC boots", "Once by the user", "Only by ultraviolet light", "Only by a router"], "a": "B", "why": "PROM is programmable once. After programming it stays fixed."},
        {"q": "Which statement about ROM is correct?", "options": ["It is volatile", "It commonly holds start-up instructions", "It is a magnetic platter", "It is erased by deleting a folder"], "a": "B", "why": "ROM is non-volatile and is used for permanent start-up code."},
    ],
    "shorts": [
        {"q": "Convert 4 MB into KB.", "a": "1 MB = 1024 KB, so 4 MB = 4 x 1024 = 4096 KB."},
        {"q": "Differentiate SRAM and DRAM.", "a": "SRAM stores each bit in a transistor flip-flop, does not need refresh, and is faster and costlier. It is used as cache. DRAM stores each bit as a charge, needs refresh, and is cheaper per bit. It is used as main memory."},
        {"q": "Differentiate EPROM and EEPROM.", "a": "EPROM is erased by ultraviolet light and is then reprogrammed. EEPROM is erased and rewritten by electrical signals, so it can be updated in the circuit. Both are non-volatile programmable ROM."},
        {"q": "Why is RAM called volatile?", "a": "RAM needs electrical power to hold its contents. When power is removed, the stored program and data disappear."},
        {"q": "What is a combo drive?", "a": "A combo drive is an optical drive that reads or writes more than one disc type, commonly both CD and DVD."},
    ],
    "longs": [
        {"q": "Explain the units of memory from bit to terabyte, with one numerical example.", "points": [
            "Define bit, nibble and byte with the numbers 1, 4 and 8.",
            "Give the ladder KB, MB, GB and TB, each 1024 of the unit below.",
            "Work one conversion in full, for example 2 KB = 2048 bytes = 16384 bits. Show the multiplication.",
            "Say why a standard matters: file sizes and memory chips are compared with these units.",
        ]},
        {"q": "Describe RAM and ROM, including SRAM, DRAM, PROM, EPROM and EEPROM.", "points": [
            "Define RAM as volatile direct-access working memory, and ROM as non-volatile memory read during ordinary work.",
            "Contrast SRAM and DRAM with cell, refresh, speed, cost and use.",
            "Describe PROM once, EPROM with ultraviolet erase, and EEPROM with electrical erase.",
            "Give the job of each: DRAM as main memory, SRAM as cache, ROM family as permanent or semi-permanent instructions and firmware.",
        ]},
    ],
})
