"""Class XI units 3 to 7."""

from reportlab.lib.units import mm

MORE = []

MORE.append({
    "grade": "XI",
    "unit": "3",
    "kicker": "Class XI  |  Unit 3  |  weight 15%",
    "title": "Inside the system unit",
    "weight": "15%",
    "periods": "10 theory periods and 10 lab periods",
    "intro": "The system unit is the case that holds the working parts of a desktop computer. This lecture opens the case in words: the board, the processor, the buses, the ports and the slots.",
    "slos": [
        "Describe CPU casings and the main parts inside the system unit.",
        "Name the components on the motherboard and the job of each.",
        "Explain the internal architecture and the external pins of a microprocessor.",
        "Read a processor specification.",
        "Define address, data and control buses and say which way data flows.",
        "Describe serial, parallel, USB and HDMI ports, and PCI, EISA and VESA slots.",
    ],
    "path": [
        "Point at a real case before drawing the motherboard.",
        "Teach the processor as one chip with a clear inside and a clear outside.",
        "Use one numerical example of an address bus.",
        "Finish in the lab by seating RAM and identifying one port.",
    ],
    "sections": [
        ("h", "3.1 The system unit"),
        ("def", "System unit", "The case that houses the motherboard, processor, memory, storage, power supply, ports and cooling of a desktop computer."),
        ("p", "Cases differ by size and by how easily they can be expanded. A **tower** stands on the floor, has room for drives and cards, and the fans can move air through a tall space. A **desktop** case lies flat and can hold a monitor, with less room to expand. A **small-form** case saves desk space and accepts fewer cards. An **all-in-one** builds the computer into the monitor housing, which is tidy and harder to upgrade."),
        ("ul", [
            "The **power supply** converts mains AC into the low-voltage DC the parts use, and it feeds them through labelled connectors.",
            "The **motherboard** is the main circuit board. The processor, memory and cards are mounted on it or plugged into it.",
            "The **hard drive** stores files. A **combo drive** reads optical discs.",
            "**Ports** are the sockets on the edge of the case. The **cooling system** is the heat sink and fan on the processor, plus the fans that move air through the case.",
        ]),
        ("h", "3.2 The motherboard"),
        ("p", "Every important signal of the computer meets on the motherboard. Learn the part and the job together."),
        ("table", "Parts on the motherboard", ["Part", "Function"], [
            ["Microprocessor", "Executes instructions. It sits in a socket on the board."],
            ["BIOS in ROM", "Permanent start-up firmware. It runs the power-on self-test and starts loading the operating system."],
            ["RAM slots", "Hold the memory modules that form main memory."],
            ["CMOS battery", "Keeps the clock and the saved setup when the computer is unplugged."],
            ["Jumpers", "Small pins and clips that select a setting, used more on older boards."],
            ["Ports", "Connect external devices such as a keyboard, a display or a USB drive."],
            ["Expansion slots", "Accept cards that add a function, such as a better display or a network."],
            ["System bus", "The shared paths that carry addresses, data and control signals among the parts."],
        ]),
        ("h", "3.3 The microprocessor"),
        ("def", "Microprocessor", "A processor built on a single integrated circuit. In a PC it is the CPU."),
        ("p", "Inside the chip, five ideas explain how it works. The **clock** sends a regular pulse that times every step. A 3 GHz clock ticks three thousand million times a second. **Registers** are tiny storage locations inside the processor, faster than RAM, used for the instruction being executed, the address being used, and the current result. The **ALU** performs arithmetic and logical operations. The **control unit** fetches an instruction from memory, decodes it, and tells the other parts when to act. **Cache** is a small SRAM store of recently used instructions and data, so the processor waits less often for DRAM."),
        ("p", "Outside, the chip is known by its pins. **Address pins** carry the address of the memory location the processor wants. They carry that address outward, so the address bus is unidirectional. **Data pins** carry the value being read or written, so they are bidirectional. **Control pins** carry signals such as read, write, and whether the address refers to memory or to an input-output device. **Interrupt pins** let a device ask the processor to pause and attend to it. **Power pins** supply voltage and ground."),
        ("p", "A specification names the manufacturing technology, often in nanometres, the generation or family, the clock speed, the word size in bits (32 or 64), the width of the data bus, and the cache sizes at each level. A wider data bus moves more bits in one transfer. A wider address bus can name more locations: a 16-bit address bus can name 2 to the power 16, which is 65536 locations."),
        ("h", "3.4 Buses"),
        ("def", "Bus", "A shared set of electrical lines that carries signals from one component to another."),
        ("table", "The system bus", ["Bus", "Carries", "Direction"], [
            ["Address bus", "The address of a memory location or a port", "Unidirectional, from the processor"],
            ["Data bus", "The data being read or written", "Bidirectional"],
            ["Control bus", "Timing and command signals such as read, write and interrupt", "The separate lines run in the direction each signal needs"],
        ]),
        ("p", "Unidirectional means the signal travels one way. Bidirectional means it can travel either way, not both ways on the same wire at the same instant. The address leaves the processor. Data may leave or enter."),
        ("h", "3.5 Ports"),
        ("ul", [
            "A **serial port** sends bits one after another on a single data line. The older COM port is the classroom example. The cable can be longer. The transfer is slower than a wide parallel cable of the same era.",
            "A **parallel port** sends a group of bits at the same time, one bit on each wire. The older printer port is the example. It is fast over a short cable.",
            "**USB**, Universal Serial Bus, is the general port on a modern PC. Devices can be plugged in while the computer is on. One port can feed a hub of several devices, and the bus can supply power to small devices. Later versions of USB move data faster.",
            "**HDMI**, High-Definition Multimedia Interface, carries digital video and audio together to a monitor, a television or a projector.",
        ]),
        ("h", "3.6 Expansion slots"),
        ("p", "**PCI**, Peripheral Component Interconnect, is the common slot used to add a card such as a network card or a sound card. **EISA**, Extended Industry Standard Architecture, is an older 32-bit slot that also accepted older ISA cards. The curriculum's third name, written VISA in the acronym list, refers in this topic to the **VESA local bus** slot. That slot was tied closely to the processor bus so a video card could move data quickly. It belongs to the generation of PCs before PCI became the usual choice."),
        ("tip", "If the question lists PCI, EISA and VISA, describe three expansion slots. In the answer you may write VESA local bus and add that the curriculum acronym is VISA. Describe the slot, not Virtual Instrument Software Architecture, which is a different use of those letters."),
        ("note", "Lab safety: shut the computer down, unplug the mains, and press the power button once to discharge the supply. Seat RAM only in the matching slot, with the notch lined up, until the clips close. Do this with your teacher present."),
    ],
    "terms": [
        ["Motherboard", "The main circuit board that connects the processor, memory, storage and cards."],
        ["ALU", "The part of the CPU that performs arithmetic and logic."],
        ["Control unit", "The part of the CPU that fetches, decodes and directs instructions."],
        ["Register", "A small, fast storage location inside the CPU."],
        ["Cache", "Fast SRAM that holds recently used instructions and data."],
        ["Bus", "A shared path of wires carrying address, data or control signals."],
        ["Port", "A socket used to connect an external device."],
        ["BIOS", "Firmware in ROM that starts the computer."],
    ],
    "summary": [
        "The case, power supply, motherboard, drives, ports and cooling make the system unit.",
        "The processor clock, registers, ALU, control unit and cache explain the inside. Address, data, control, interrupt and power pins explain the outside.",
        "Address lines leave the processor. Data lines carry values in or out.",
        "Serial, parallel, USB and HDMI are ports. PCI, EISA and the VESA local bus are expansion slots.",
    ],
    "labs": [
        "Identify the processor socket, RAM slots, CMOS battery, expansion slots and one USB port on a motherboard.",
        "With the power unplugged and a teacher present, remove and reseat a RAM module. Note the notch and the clips.",
        "Enter the BIOS or UEFI setup and find the boot-order screen. Leave the setting as you found it unless the teacher asks for a change.",
    ],
    "mcqs": [
        {"q": "The ALU is responsible for:", "options": ["Arithmetic and logic", "Long-term file storage", "Converting AC to DC", "Printing"], "a": "A", "why": "The arithmetic and logic unit calculates and compares."},
        {"q": "Which bus carries the location the processor wants to read?", "options": ["Data bus", "Address bus", "HDMI", "Power supply"], "a": "B", "why": "The address bus carries the address of the location."},
        {"q": "The address bus is:", "options": ["Bidirectional", "Unidirectional from the processor", "A printer only", "A type of ROM"], "a": "B", "why": "Addresses are issued by the processor toward memory."},
        {"q": "Cache memory is usually built from:", "options": ["DRAM", "SRAM", "CD-R", "Magnetic tape"], "a": "B", "why": "Cache needs the speed of SRAM."},
        {"q": "The CMOS battery:", "options": ["Prints documents", "Keeps setup and the clock when mains power is off", "Is the main hard disk", "Translates C++"], "a": "B", "why": "The battery maintains saved setup information and the time."},
        {"q": "HDMI carries:", "options": ["Digital video and audio", "Only mains electricity", "Only a paper signal", "Ultraviolet light"], "a": "A", "why": "HDMI is a digital multimedia port for picture and sound."},
        {"q": "A 10-bit address bus can name:", "options": ["10 locations", "100 locations", "1024 locations", "8 locations"], "a": "C", "why": "Ten address lines name 2 to the power 10, which is 1024 locations."},
        {"q": "PCI is a:", "options": ["Type of RAM", "Expansion slot", "Keyboard layout", "File attribute"], "a": "B", "why": "PCI is an expansion slot for add-in cards."},
    ],
    "shorts": [
        {"q": "Write the functions of the ALU and the control unit.", "a": "The ALU performs arithmetic operations such as addition and logical operations such as comparison. The control unit fetches each instruction from memory, decodes it, and directs the other parts of the computer to carry it out."},
        {"q": "Differentiate address bus and data bus.", "a": "The address bus carries the address of a memory location and is unidirectional, from the processor. The data bus carries the data being read or written and is bidirectional. The width of the address bus limits how many locations can be named. The width of the data bus limits how many bits move in one transfer."},
        {"q": "What is the BIOS?", "a": "The BIOS is firmware stored in ROM on the motherboard. When the computer is switched on it runs a self-test and starts the process of loading the operating system."},
        {"q": "Why is a heat sink fitted on the processor?", "a": "The processor produces heat while it works. The heat sink, with its fan, conducts that heat away so the chip stays within a safe temperature."},
        {"q": "Give one use of USB and one use of HDMI.", "a": "USB connects general devices such as a pen drive, a printer or a keyboard, and it can supply power to small devices. HDMI connects a display and carries digital video and audio together."},
    ],
    "longs": [
        {"q": "Describe the main components of the system unit and the main parts found on a motherboard.", "points": [
            "Define the system unit and name tower, desktop and all-in-one as case styles.",
            "Explain power supply, motherboard, hard drive, combo drive, ports and cooling.",
            "On the motherboard, give the job of the processor, BIOS, RAM slots, CMOS battery, ports, expansion slots and the system bus.",
            "Close with the path of a program: it is stored on the drive, loaded into RAM, and executed by the processor.",
        ]},
        {"q": "Explain the internal parts and the external pins of a microprocessor.", "points": [
            "Define a microprocessor.",
            "Explain clock, registers, ALU, control unit and cache.",
            "Explain address, data, control, interrupt and power pins.",
            "Add one specification sentence: clock speed, bit size, bus width and cache are how two processors are compared.",
            "Give the 16-bit address example: 65536 locations.",
        ]},
    ],
})

MORE.append({
    "grade": "XI",
    "unit": "4",
    "kicker": "Class XI  |  Unit 4  |  weight 10%",
    "title": "Operating systems",
    "weight": "10%",
    "periods": "10 theory periods and 10 lab periods",
    "intro": "The operating system is the program that makes the hardware usable. It starts the computer, shares the processor, keeps files, and gives you a way to command the machine.",
    "slos": [
        "Define an operating system and its objectives.",
        "Describe batch, multitasking, time sharing, multiprocessing, parallel, distributed and embedded systems.",
        "Explain the main functions, including booting and process management.",
        "Describe process states, and distinguish a thread from a process.",
        "Manage files, folders, paths, search, attributes and the control panel in a GUI.",
        "Use the ideas behind dxdiag and msconfig, and describe open-source and mobile systems.",
    ],
    "path": [
        "Define the operating system from the user's problem: hardware is difficult to command directly.",
        "Teach features as ways of sharing a computer, using the tables.",
        "Walk the process-state diagram with one running program and one that is waiting for a file.",
        "Spend the lab on real files, attributes, control panel, dxdiag and msconfig.",
    ],
    "sections": [
        ("h", "4.1 What an operating system is"),
        ("def", "Operating system", "System software that manages hardware and software resources and provides services so that the user and the application programs can use the computer."),
        ("p", "Its objectives are convenience, efficiency and the ability to evolve. Convenience means a user can start a program, save a file and use a printer without knowing the wiring. Efficiency means the processor, memory and disks stay busy and are shared fairly. Evolution means new hardware can be added through drivers and updates."),
        ("table", "Systems you should recognise", ["System", "Character"], [
            ["DOS", "Single-user, command-line operating system used on early PCs."],
            ["Windows", "A widely used graphical operating system for personal computers, with multitasking."],
            ["Mac OS", "The graphical operating system used on Apple personal computers."],
            ["UNIX", "A multi-user, multitasking system strong on servers and on shared machines. Many later systems took ideas from it."],
        ]),
        ("h3", "Ways of working"),
        ("ul", [
            "**Batch processing** collects jobs and runs them one after another without the user sitting at the machine for each step. A payroll run is the classic example.",
            "**Multitasking** keeps more than one program loaded and switches the processor among them so the user seems to have several programs at once.",
            "**Time sharing** gives each user a short slice of processor time. The users of a shared computer each feel they have the machine.",
            "**Multiprocessing** uses two or more processors in one computer system.",
            "**Parallel processing** splits a job across multiple processors so parts of the work proceed at the same time.",
            "A **distributed** system spreads the work across computers that communicate over a network.",
            "An **embedded** operating system runs inside a device such as a washing machine, a car controller or a POS terminal. It is built for that device.",
        ]),
        ("h", "4.2 Functions"),
        ("table", "What the operating system manages", ["Function", "What it does"], [
            ["Booting", "Starts the computer and loads the operating system into RAM."],
            ["Process management", "Creates, schedules and removes processes."],
            ["Memory management", "Allocates RAM and keeps one process out of another's memory."],
            ["File management", "Names, stores, opens and protects files and folders."],
            ["I/O management", "Controls input and output devices through drivers."],
            ["Secondary storage management", "Tracks free space and the location of files on disks."],
            ["Network management", "Provides access to network resources."],
            ["Protection", "Checks users and permissions so one person cannot freely change another's work."],
            ["Command interpreter", "Reads the user's command, from a typed line or from a click, and asks the system to carry it out."],
        ]),
        ("p", "**Cold booting** starts from a computer that was switched off. Power reaches the board, the firmware in ROM runs a power-on self-test, finds a bootable drive, and loads the operating system. **Warm booting** restarts a computer that is already on. Modern PCs use UEFI firmware for this start-up role. The curriculum name for the start-up firmware is BIOS."),
        ("h", "4.3 Processes"),
        ("def", "Process", "A program in execution. It has its own identity, its own state, and its own address space."),
        ("diagram", "states", "Figure 4.1  States of a process.", 62 * mm),
        ("ul", [
            "**New**: the process is being created.",
            "**Ready**: the process has everything it needs except the processor.",
            "**Running**: the processor is executing its instructions.",
            "**Waiting or blocked**: the process cannot continue until an event finishes, often an input or output operation.",
            "**Terminated**: execution is finished and the operating system reclaims the resources.",
        ]),
        ("p", "A **thread** is a path of execution inside a process. Threads of one process share that process's memory. A **process** has its own memory space. **Multithreading** means one process has several threads, for example one thread drawing a page while another loads an image. **Multitasking** means the system switches among several processes. Multiprocessing means more than one processor is present."),
        ("h", "4.4 Working in a graphical operating system"),
        ("p", "Windows presents a desktop, icons, a taskbar and windows. **Windows Explorer**, now called File Explorer, is the program that shows drives, folders and files. You create a folder, delete it, copy it, rename it, and move it by cut and paste or by dragging. A copy leaves the original in place. A move takes it to the new place."),
        ("p", "A **drive** is a storage device with a letter, such as C. A **path** is the address of a file. An absolute path starts from the drive, for example `C:\\College\\CS\\notes.txt`. A relative path starts from the folder you are already in. The backslash separates folder names in Windows."),
        ("p", "Search finds a file by name, by part of a name, or by date. **Attributes** are flags stored with the file. **Read-only** refuses an ordinary save. **Hidden** keeps the file out of the ordinary listing. **System** marks a file the operating system depends on. **Archive** marks a file that should be included in the next backup. You can inspect and change attributes from the file's properties."),
        ("p", "The **control panel** is the place where hardware and software are adjusted: display, sound, user accounts, date and time, devices, and programs. `dxdiag` opens the DirectX diagnostic tool, which reports the computer's system, display and sound resources. `msconfig` opens System Configuration, which shows start-up choices and services. Change msconfig only when you understand the item, because a wrong boot setting can stop the machine starting normally."),
        ("h", "4.5 Other operating systems"),
        ("p", "Linux is the usual classroom example of an operating system other than Windows. **Open-source** software is distributed with its source code. People may study it, share it, and modify it under the licence. The advantages are a low licence cost, the right to inspect the code, a community that repairs faults in public, and the freedom to adapt the system."),
        ("p", "**Android** is an open-source operating system for mobile devices, built on a Linux kernel. Phones show a version number in the settings. Older classroom charts also use dessert codenames such as KitKat and Lollipop. What you need to write is that Android is a mobile operating system, it is versioned, and each version adds features and repairs."),
        ("note", "In the lab, create a folder `CS-XI` on the desktop, copy a file into it, rename the copy, make it read-only, hide it, then search for it by name. Open dxdiag and read the operating system name and the memory size. Open msconfig, look at the Services tab, and close it without saving a change."),
    ],
    "terms": [
        ["Operating system", "Software that manages resources and provides a way to use the computer."],
        ["Booting", "The start-up sequence that loads the operating system."],
        ["Process", "A program that is being executed."],
        ["Thread", "A single path of execution inside a process."],
        ["Multitasking", "Sharing one processor among several tasks by switching."],
        ["Time sharing", "Giving each user a slice of processor time."],
        ["Path", "The location of a file, written as drive and folders."],
        ["Open source", "Software whose source code may be studied and modified under its licence."],
    ],
    "summary": [
        "The operating system makes hardware usable and shares it safely.",
        "Batch, interactive multitasking, time sharing, multiprocessing, parallel, distributed and embedded are different ways of organising that work.",
        "A process moves through new, ready, running, waiting and terminated.",
        "Files live at paths and carry attributes. The control panel, dxdiag and msconfig are the Windows tools named in this unit.",
    ],
    "labs": [
        "Show the desktop, File Explorer, a drive and a path.",
        "Create, rename, copy, move and delete a folder. Search for the file afterwards.",
        "Set and clear the read-only and hidden attributes.",
        "Open control panel, dxdiag and msconfig. Record the operating system name and the installed RAM. Do not save a change in msconfig.",
    ],
    "mcqs": [
        {"q": "A program in execution is a:", "options": ["File attribute", "Process", "Port", "Nibble"], "a": "B", "why": "A process is a program that is running."},
        {"q": "Which state means the process is waiting for the processor?", "options": ["Terminated", "Ready", "New only", "ROM"], "a": "B", "why": "A ready process can run as soon as the scheduler dispatches it."},
        {"q": "Time sharing is used so that:", "options": ["Each user gets a slice of CPU time", "Files are compressed", "ROM is erased", "A plotter draws faster"], "a": "A", "why": "Time sharing switches the CPU among users quickly."},
        {"q": "An embedded OS is found in:", "options": ["A device built for a specific product", "A compiler only", "A nibble", "A barcode definition"], "a": "A", "why": "Embedded systems run inside dedicated devices."},
        {"q": "The hidden attribute:", "options": ["Speeds up the ALU", "Keeps a file out of the ordinary listing", "Converts AC to DC", "Is a network topology"], "a": "B", "why": "Hidden is a file attribute that suppresses the normal display."},
        {"q": "dxdiag is used to:", "options": ["Diagnose DirectX system, display and sound information", "Erase EPROM with ultraviolet light", "Design a bus topology", "Compile C++"], "a": "A", "why": "dxdiag reports the multimedia and system resources Windows can see."},
        {"q": "Threads of the same process:", "options": ["Must each have a separate hard disk", "Share that process's memory", "Are always stored in ROM", "Replace the power supply"], "a": "B", "why": "Threads are lightweight paths of execution inside one process address space."},
        {"q": "Open-source software allows the user to:", "options": ["Study and modify the source under the licence", "Remove the need for a processor", "Disable every attribute", "Turn DRAM into a printer"], "a": "A", "why": "The source is available for study and modification under its licence."},
    ],
    "shorts": [
        {"q": "Define an operating system.", "a": "An operating system is system software that manages hardware and software resources and provides services through which the user and application programs use the computer."},
        {"q": "Differentiate multitasking and multiprocessing.", "a": "Multitasking switches one processor among several tasks so they appear to run together. Multiprocessing uses two or more processors in the computer. A machine can do both: several processors, each shared among tasks."},
        {"q": "Differentiate a process and a thread.", "a": "A process is a running program with its own address space. A thread is one path of execution inside a process. Threads of a process share its memory. Creating a thread costs less than creating another process."},
        {"q": "List the five states of a process.", "a": "New, ready, running, waiting (blocked), and terminated. A new process is admitted to ready. The scheduler dispatches a ready process to running. It may wait for input or output, return to ready when that finishes, or terminate."},
        {"q": "What is a file path? Give one example.", "a": "A path is the location of a file in the folder tree. An absolute Windows path includes the drive, for example C:\\College\\CS\\notes.txt."},
    ],
    "longs": [
        {"q": "Explain the main functions of an operating system.", "points": [
            "Define the operating system and its objectives: convenience, efficiency, evolution.",
            "Explain booting, process management, memory management and file management.",
            "Explain I/O, secondary storage, network, protection and the command interpreter.",
            "Give one example for protection, such as a user account and a read-only file.",
        ]},
        {"q": "Describe process states and distinguish multithreading from multitasking.", "points": [
            "Define a process.",
            "Draw or describe new, ready, running, waiting and terminated, with the reason for each move.",
            "Define a thread and say that threads share a process's memory.",
            "Multithreading is many threads in one process. Multitasking is many processes sharing the processor. Multiprocessing is many processors.",
        ]},
    ],
})

MORE.append({
    "grade": "XI",
    "unit": "5",
    "kicker": "Class XI  |  Unit 5  |  weight 20%",
    "title": "Programming in C++",
    "weight": "20%",
    "periods": "20 theory periods and 20 lab periods",
    "intro": "This is the heaviest unit in Class XI. You will write complete C++ programs that calculate, decide, repeat, and call functions. Every program in this lecture was written to compile and run.",
    "slos": [
        "Use C++ data types, operators, and cin and cout, including cascading.",
        "Write selection with if, if-else, else-if, switch and nested if.",
        "Write for, while, do-while and nested loops, and use break, continue and goto correctly.",
        "Declare, define and call functions. Explain scope, parameters, inline functions and exit.",
        "Pass constants, pass by value and pass by reference. Use default arguments and return values.",
        "Overload functions by the number and types of arguments.",
    ],
    "path": [
        "Type the calculator on the first lab day. Do not stay on the board for the whole period.",
        "Add decisions, then loops, then functions. Each lab program below is one of those steps.",
        "Teach pass by reference with the before-and-after output on the screen.",
        "End with overloading, and say clearly that return type alone does not overload a function.",
    ],
    "sections": [
        ("h", "5.1 Data, operators and streams"),
        ("p", "A C++ program for this course starts with the iostream header and a main function. `cin` reads from the keyboard. `cout` writes to the screen. The insertion operator `<<` sends a value out. The extraction operator `>>` brings a value in. Cascading means chaining those operators in one statement."),
        ("table", "Types you will use", ["Type", "Holds", "Example"], [
            ["int", "Whole numbers", "int marks = 76;"],
            ["float", "Numbers with a fractional part", "float average = 72.5;"],
            ["double", "A fractional number kept more precisely", "double tax = 0.05;"],
            ["char", "One character", "char grade = 'A';"],
            ["bool", "true or false", "bool pass = true;"],
            ["void", "No value, used for a function that only does work", "void drawStars(int n);"],
        ]),
        ("table", "Operators", ["Family", "Operators", "Meaning"], [
            ["Arithmetic", "+  -  *  /  %", "Add, subtract, multiply, divide, remainder"],
            ["Assignment", "=  +=  -=", "Store a value, or change the stored value"],
            ["Relational", "==  !=  >  <  >=  <=", "Compare two values. The result is true or false"],
            ["Logical", "&&  ||  !", "And, or, not"],
            ["Increment", "++  --", "Add 1 or subtract 1"],
            ["Conditional", "? :", "Choose one of two values"],
        ]),
        ("p", "Integer division drops the fraction: `7 / 2` is 3. The remainder operator gives what is left: `7 % 2` is 1. Use `==` to compare and `=` to assign. Confusing those two is the most common logic error in a condition."),
        ("code", "Program 5.1  Calculator, with cascading output", "calculator"),
        ("p", "The division line is guarded. Division by zero is undefined, so the program tests the divisor first. Sample run: input `12 3` prints sum 15, difference 9, product 36 and quotient 4."),
        ("h", "5.2 Decisions"),
        ("p", "`if` runs a block only when the condition is true. `if-else` chooses one of two blocks. `else if` chains several conditions and the first true condition wins. A nested if is an if inside another if. `switch` compares one integer or character with several constant cases. End each case with `break`, otherwise execution falls into the next case. `default` runs when no case matches."),
        ("code", "Program 5.2  A mark sheet using else-if", "marksheet"),
        ("p", "These grade bands are a classroom exercise so the selection is easy to test. They are not the board's own grading rules. Input 76 prints grade B. Input 110 prints Invalid because the mark is outside 0 to 100."),
        ("code", "Program 5.3  Largest of three, using nested decisions", "largest3"),
        ("code", "Program 5.4  switch for the day of the week", "weekday"),
        ("h", "5.3 Loops and jumps"),
        ("p", "A `for` loop is the natural choice when you know how many times to repeat. A `while` loop tests the condition before the body, so the body may never run. A `do-while` runs the body once and then tests, so it is the right loop for a menu. A nested loop has a loop inside a loop. The inner loop finishes its repetitions for each step of the outer loop."),
        ("code", "Program 5.5  Prime or composite", "prime"),
        ("p", "The number 1 is neither prime nor composite. A prime number is greater than 1 and has no factor other than 1 and itself. The loop tests divisors from 2 up to n/2. If any divisor divides exactly, the number is composite and `break` leaves the loop."),
        ("code", "Program 5.6  Four digits on four lines", "digits"),
        ("p", "Integer division by 1000 isolates the thousands digit. The remainder after division by 10 isolates the last digit. Input must be from 1000 to 9999."),
        ("code", "Program 5.7  Factors of a number", "factors"),
        ("code", "Program 5.8  A menu with do-while", "menu_do_while"),
        ("p", "`break` leaves the nearest loop or switch immediately. `continue` skips the rest of this repetition and goes to the next test. `goto` jumps to a label. It is in the curriculum so you can recognise it. Do not use it in ordinary programs: a loop or a function states the intention more clearly, and a goto makes a long program hard to follow."),
        ("code", "Program 5.9  break, continue and a labelled goto", "jumps"),
        ("h", "5.4 Functions"),
        ("p", "A function is a named block of work. **Predefined** functions come with the language or its library, such as `sqrt` in `cmath`. **User-defined** functions are the ones you write. Functions let you name a task, test it once, and call it from several places. A large program becomes a set of small ones."),
        ("p", "The **signature** is the function's name, its parameter list, and its return type. A **prototype** declares the function before main. The **definition** contains the body. A **call** uses the function. Formal parameters are the names in the definition. Actual parameters are the values sent at the call."),
        ("p", "A **local variable** exists only inside the block where it is declared. A **global variable** is declared outside functions and can be used by all of them; use it rarely, because any function can change it. A **static local variable** keeps its value between calls to that function."),
        ("p", "An **inline** function is a short function that the compiler may place at the point of the call, avoiding a call for a one-line calculation. `exit`, from `cstdlib`, ends the whole program at once. A `return` statement leaves only the current function and can carry a value back to the caller."),
        ("code", "Program 5.10  A function that draws a triangle of stars", "stars"),
        ("code", "Program 5.11  Return the larger of two arguments", "larger"),
        ("h", "5.5 Passing arguments"),
        ("ul", [
            "**By value**: the function receives a copy. Changing the parameter does not change the caller's variable.",
            "**By reference**: the parameter is an alias for the caller's variable, written with `&`. Changing it changes the original.",
            "A **const parameter** is a promise not to modify that parameter inside the function.",
            "A **default argument** is a value used when the caller omits that argument. Defaulted parameters go at the end of the list.",
        ]),
        ("code", "Program 5.12  Value, reference, const, inline and a default argument", "pass_modes"),
        ("p", "Read the output of Program 5.12 carefully. After the call by value the variable is still 10. After the call by reference it is 99. `add(5)` uses the default second argument and returns 15. `add(5, 3)` returns 8. `square(6)` returns 36."),
        ("code", "Program 5.13  exit ends the program", "scope_exit"),
        ("h", "5.6 Overloading"),
        ("def", "Function overloading", "Two or more functions with the same name and different parameter lists, in the same scope. The compiler chooses the function from the arguments at the call."),
        ("p", "You may overload on the number of arguments or on the types of the arguments. You may not overload on the return type alone. Two functions called `sum` that both take two ints and differ only because one returns int and one returns double are rejected. The call would not tell the compiler which one you meant."),
        ("code", "Program 5.14  Overloading on number and type of arguments", "overload"),
        ("tip", "In a board program, write the include line, `using namespace std;`, a complete `main`, and matching braces. Initialise variables before you read them in an expression. Test the program with the sample in the question and with one awkward value, such as 0 or 1."),
    ],
    "terms": [
        ["Operator", "A symbol that asks for an operation on one or more values."],
        ["Cascading", "Chaining << or >> in a single input or output statement."],
        ["Loop", "A statement that repeats a block while a condition holds."],
        ["Prototype", "A declaration of a function's name, return type and parameters."],
        ["Formal parameter", "The parameter name written in the function definition."],
        ["Actual parameter", "The value or variable supplied at the call."],
        ["Pass by reference", "Passing a variable so the function can change the original."],
        ["Overloading", "Same function name, different parameter lists."],
    ],
    "summary": [
        "cin and cout, with << and >>, are the streams for this course.",
        "if, else-if and switch make decisions. for, while and do-while repeat. break and continue alter one loop.",
        "A function has a prototype, a definition and a call. It can return a value.",
        "Pass by value protects the original. Pass by reference changes it. Defaults fill in missing arguments.",
        "Overload by arguments, never by return type alone.",
    ],
    "labs": [
        "Build the calculator, the mark sheet, the prime test, the four-digit split and the factor list.",
        "Write drawStars and larger as separate functions and call them from main.",
        "Show, with printed output, that pass by value does not change the original and pass by reference does.",
    ],
    "mcqs": [
        {"q": "Which operator finds the remainder?", "options": ["/", "%", "==", "&&"], "a": "B", "why": "The % operator yields the remainder of integer division."},
        {"q": "A do-while loop:", "options": ["Never runs the body", "Tests after the body, so the body runs at least once", "Can only count down", "Replaces a function"], "a": "B", "why": "The test is at the bottom, so one execution happens before the test."},
        {"q": "break inside a loop:", "options": ["Skips to the next repetition", "Leaves the loop", "Deletes the file", "Overloads the function"], "a": "B", "why": "break terminates the nearest loop or switch."},
        {"q": "A default argument must:", "options": ["Be the first parameter", "Appear at the end of the parameter list", "Be a pointer", "Be global"], "a": "B", "why": "Defaults are trailing parameters so the call stays unambiguous."},
        {"q": "Which pair can be overloaded together?", "options": ["int f(int) and double f(int)", "int f(int) and int f(int, int)", "Two identical functions", "int f(int) and int f(int)"], "a": "B", "why": "The parameter lists differ in the number of arguments. Return type alone is not enough."},
        {"q": "Pass by value:", "options": ["Sends a copy", "Always changes the caller's variable", "Needs the & symbol on the parameter", "Ends the program"], "a": "A", "why": "The function works on a copy, so the original is unchanged."},
        {"q": "The correct way to compare two ints for equality is:", "options": ["a = b", "a == b", "a := b", "a eq b"], "a": "B", "why": "== compares. A single = assigns."},
        {"q": "exit(0) :", "options": ["Leaves only the current loop", "Terminates the program", "Draws a star", "Opens a file"], "a": "B", "why": "exit ends the entire program. return leaves only the current function."},
    ],
    "shorts": [
        {"q": "What is cascading of the output stream? Write one statement.", "a": "Cascading means using << more than once in a single statement. Example: cout << \"Sum = \" << a + b << endl; The text and the number are sent out by the same statement."},
        {"q": "Differentiate while and do-while.", "a": "while tests the condition before the body, so the body may not run at all. do-while runs the body and then tests, so the body runs at least once. do-while suits a menu that must appear before the user chooses."},
        {"q": "Differentiate formal and actual parameters.", "a": "Formal parameters are the names in the function heading, such as int a and int b in int larger(int a, int b). Actual parameters are the values at the call, such as larger(x, y). The actual values are passed into the formal parameters."},
        {"q": "Why can two functions not be overloaded by return type alone?", "a": "The compiler selects the overloaded function from the arguments at the call. If both functions take the same arguments, the call does not show which function is wanted, even if the return types differ. The program is rejected."},
        {"q": "What does a static local variable do?", "a": "A static local variable is created once and keeps its value after the function returns. The next call sees the value left by the previous call. An ordinary local variable is created again on each call."},
    ],
    "longs": [
        {"q": "Explain selection and iteration structures in C++, with the job of each.", "points": [
            "Define selection as choosing a path, and name if, if-else, else-if, nested if and switch. Mention break and default.",
            "Give a one-line situation for else-if, such as a grade, and for switch, such as a menu number.",
            "Define iteration and compare for, while and do-while, including how many times the body can run.",
            "Explain nested loops with the star triangle: the outer loop is the row, the inner loop prints the stars.",
            "Name break and continue and give the effect of each.",
        ]},
        {"q": "Explain user-defined functions, parameter passing and overloading.", "points": [
            "Give the advantages: a named task, reuse, and a smaller main.",
            "Show prototype, definition and call, and define the signature.",
            "Contrast pass by value and pass by reference with the & sign and the effect on the original variable.",
            "Explain default arguments and the return statement.",
            "Define overloading and state the rule about argument lists and return types. Give sum of two ints and sum of three ints as the example.",
        ]},
    ],
})
