"""Class XI units 6 and 7."""

from reportlab.lib.units import mm

END = []

END.append({
    "grade": "XI",
    "unit": "6",
    "kicker": "Class XI  |  Unit 6  |  weight 15%",
    "title": "Arrays, strings and structures",
    "weight": "15%",
    "periods": "25 theory periods and 25 lab periods",
    "intro": "An array stores many values of one type under one name. A string stores text. A structure stores related values of different types as one record. Most of the Class XI practical journal lives in this unit.",
    "slos": [
        "Define an array, its name, size and index, and initialise arrays of different types.",
        "Access an element, traverse an array, and use sizeof.",
        "Declare, initialise and process a two-dimensional array.",
        "Use C strings with the terminator, and use strlen, strcat, strcpy, strcmp and substr.",
        "Declare a structure, create a variable, and read and display its members.",
    ],
    "path": [
        "Draw five boxes with indexes 0 to 4 before any syntax.",
        "Traverse, search, sort and average on the same small list so the loops look familiar.",
        "Treat a string as an array of char with a hidden zero at the end.",
        "Close with one employee record. That is the bridge to classes in Class XII.",
    ],
    "sections": [
        ("h", "6.1 Arrays"),
        ("def", "Array", "A collection of elements of the same data type, stored in consecutive memory locations and referred to by one name and an index."),
        ("p", "The **name** is the identifier, such as `marks`. The **size** is how many elements were reserved. The **index** is the position of one element. In C++ the first index is 0. An array of 5 elements uses indexes 0, 1, 2, 3 and 4. There is no element at index 5. Using one is a serious error."),
        ("p", "You can initialise an array where you declare it. `int marks[5] = {10, 20, 30, 40, 50};` sets every element. `char grades[3] = {'A', 'B', 'C'};` is an array of characters, which is not yet a C string because there is no terminator. Access one element with the index in brackets: `marks[2]` is 30."),
        ("p", "`sizeof(marks)` gives the storage of the whole array in bytes. `sizeof(marks[0])` gives the storage of one element. Their quotient is the number of elements. On a typical PC an int is 4 bytes, so five ints occupy 20 bytes."),
        ("code", "Program 6.1  Initialise, access, traverse and measure an array", "array_basics"),
        ("p", "Traversal means visiting every element once. The for-loop from 0 to size-1 is the pattern you will reuse for search, total and display."),
        ("h", "6.2 Two-dimensional arrays"),
        ("def", "Two-dimensional array", "An array whose elements are arranged in rows and columns. An element needs a row index and a column index."),
        ("p", "`int table[2][3]` has 2 rows and 3 columns, so 6 ints. In memory the rows are stored one after another. The initialiser lists the rows in order. `table[1][2]` is row 1, column 2, counting from zero, which is the last element of the second row."),
        ("code", "Program 6.2  A 2 by 3 array", "array_2d"),
        ("p", "Addition of two matrices is element by element: each sum element is `a[i][j] + b[i][j]`. The matrices must have the same number of rows and the same number of columns. Multiplication of a 3 by 3 matrix needs three nested loops. The element in row i and column j of the product is the sum of `a[i][k] * b[k][j]` as k runs across the row and down the column."),
        ("code", "Program 6.3  Add and multiply 3 by 3 matrices", "matrix"),
        ("p", "In Program 6.3 the second matrix is an identity matrix, so the product equals the first matrix. The first row of the sum is 2, 2, 3 because the identity adds 1 only to the diagonal."),
        ("h", "6.3 Searching, sorting and the average"),
        ("p", "A linear search looks at each element until it finds the key or reaches the end. Its place in the answer is the index, or a clear 'not found'. Bubble sort repeatedly walks the list and swaps a pair that is out of order. After each outer pass, one more value has settled at the end. For names stored as C strings, the comparison is `strcmp`, and the swap copies whole strings with `strcpy`."),
        ("code", "Program 6.4  Bubble sort, name sort and linear search", "sort_search"),
        ("code", "Program 6.5  Average of a list", "average"),
        ("p", "Program 6.5 uses integer division because the total and the count are ints. The average of 10, 20, 30 and 40 is 25 exactly. If you need a fractional average, store the total in a double."),
        ("h", "6.4 Strings"),
        ("def", "C string", "An array of char that ends with the null character `\\0`. The null character is the terminator. It marks the end and is not part of the text."),
        ("p", "`char name[20] = \"Ali\";` stores A, l, i, and then `\\0`. The size 20 is the room available, not the length of the text. `strlen(name)` counts characters before the terminator, so the length is 3, not 20 and not 4."),
        ("table", "String operations in this unit", ["Operation", "What it does", "Care"], [
            ["strlen(s)", "Counts characters before the terminator", "The terminator is not counted"],
            ["strcpy(dest, src)", "Copies src into dest, including the terminator", "dest must be large enough"],
            ["strcat(dest, src)", "Joins src onto the end of dest", "dest must have room for both strings"],
            ["strcmp(a, b)", "Compares a and b. The result is 0 when they are equal", "A negative result means a comes first"],
            ["s.substr(pos, n)", "From a std::string, takes n characters starting at pos", "This is a member of the string class, not a C-string function"],
        ]),
        ("p", "The curriculum name `substr` belongs to the C++ string class. The C functions `strlen`, `strcpy`, `strcat` and `strcmp` belong to `cstring` and work on char arrays. Keep the two styles apart. Do not pass a `std::string` to `strcpy`."),
        ("code", "Program 6.6  Length, reverse, join, compare and substr", "strings"),
        ("p", "Reversing a name is a loop from the last character down to index 0. For Ayesha the length is 6 and the reverse is ahseyA. `strcpy` followed by two `strcat` calls builds `BIEK Karachi`. `substr(0, 3)` on Computer gives Com."),
        ("h", "6.5 Structures"),
        ("def", "Structure", "A user-defined type that groups members of different types under one name. Each member has its own name."),
        ("p", "The `struct` block declares the type. It does not by itself create a variable. `Employee emp;` creates a variable. Members are reached with a dot: `emp.salary`. A structure can be initialised with a brace list in the same order as the members. An array of structures is a table of records, which is the idea you will meet again in files and in databases."),
        ("code", "Program 6.7  An employee record", "employee"),
        ("p", "This version reads a single-word name with `cin >>`. A name with a space needs `getline`, and mixing `getline` with `>>` needs care about the leftover newline. For the board, a single-word name is the expected program unless the question asks for full names."),
        ("tip", "When a 3-mark question says 'declare a structure for a book', write the struct with the members they name, then declare one variable, then show one member being assigned. Three short pieces of code answer the question."),
    ],
    "terms": [
        ["Index", "The position of an element. The first index in C++ is 0."],
        ["Traversal", "Visiting every element of an array once."],
        ["Null character", "The '\\0' terminator that ends a C string."],
        ["strlen", "Returns the number of characters before the terminator."],
        ["strcmp", "Compares two C strings. Zero means they are equal."],
        ["Structure", "A group of related members that may have different types."],
        ["Member", "One named field inside a structure."],
    ],
    "summary": [
        "An array is one name, one type, many elements, indexes from 0.",
        "sizeof gives bytes. Divide by the size of one element to get the count.",
        "Two indexes select a row and a column. Matrix addition matches positions. Multiplication combines a row with a column.",
        "A C string ends with \\0. strlen, strcpy, strcat and strcmp are the C functions. substr belongs to std::string.",
        "A structure groups different types. The dot operator reaches a member.",
    ],
    "labs": [
        "Sort a numeric list and a short list of names. Search for a value and print its index.",
        "Average a list. Add and multiply two 3 by 3 matrices.",
        "Display a name in reverse using strlen.",
        "Create an Employee structure with name, designation and salary, then display one employee.",
    ],
    "mcqs": [
        {"q": "The index of the first element of a C++ array is:", "options": ["1", "0", "-1", "The size of the array"], "a": "B", "why": "C++ arrays are numbered from zero."},
        {"q": "int a[4] reserves indexes:", "options": ["1 to 4", "0 to 3", "0 to 4", "4 to 8"], "a": "B", "why": "Four elements use indexes 0, 1, 2 and 3."},
        {"q": "strlen on a C string counts:", "options": ["The array capacity, including unused room", "Characters before the terminator", "Only vowels", "The number of arrays in the program"], "a": "B", "why": "The terminator marks the end and is not included in the length."},
        {"q": "strcmp returns 0 when:", "options": ["The strings differ", "The strings are equal", "The first string is empty always", "A file is closed"], "a": "B", "why": "A zero result means the two C strings match."},
        {"q": "strcpy(dest, src) copies:", "options": ["src into dest", "dest into src", "Only the first character, and stops", "A structure member into ROM"], "a": "A", "why": "The destination is the first argument."},
        {"q": "A structure is used when:", "options": ["All values must be the same type and nothing else is allowed", "Related members of different types form one record", "Only one int is needed", "A bus topology is drawn"], "a": "B", "why": "Structures group different types. Arrays group one type."},
        {"q": "table[1][2] in an array declared [2][3] is:", "options": ["Always out of range", "The last column of the second row", "The first element", "A string function"], "a": "B", "why": "Row index 1 is the second row. Column index 2 is the third column."},
        {"q": "The member operator for a structure variable is:", "options": ["->", ".", "::", "&"], "a": "B", "why": "A structure variable uses the dot. The arrow is used with a pointer to a structure."},
    ],
    "shorts": [
        {"q": "Define an array. What are its name, size and index?", "a": "An array is a collection of elements of the same type in consecutive memory, addressed by one name and an index. The name identifies the collection. The size is the number of elements reserved. The index selects one element. In C++ the first index is 0."},
        {"q": "What does sizeof tell you about an array?", "a": "sizeof(array) is the number of bytes occupied by the whole array. Dividing by sizeof(array[0]) gives the number of elements. It does not return the length of a C string; strlen does that."},
        {"q": "Why does a C string need '\\0'?", "a": "The terminator marks where the text ends inside a char array that may be larger than the text. strlen, strcpy and the output of cout stop at that character. Without it, a string function reads on into neighbouring memory."},
        {"q": "Differentiate an array and a structure.", "a": "An array holds many elements of one type, selected by an index. A structure holds named members that may have different types, selected by the member name. A class register of marks can be an array. One student's name, class and fee can be a structure."},
        {"q": "Write the statement that joins two C strings.", "a": "Place the first string in a char array large enough for both, then call strcat(first, second). strcat appends the second string and its terminator onto the first. strcpy is the copy, not the join."},
    ],
    "longs": [
        {"q": "Explain one-dimensional and two-dimensional arrays, with initialisation and access.", "points": [
            "Define an array and the terms name, size and index. State that the first index is 0.",
            "Show a declaration with an initialiser and one access, such as marks[2].",
            "Show a traversal loop and the sizeof quotient.",
            "Define a two-dimensional array as rows and columns. Show int t[2][3] and the element t[1][2].",
            "State the rule for matrix addition and the three-loop pattern for multiplication.",
        ]},
        {"q": "Explain C strings and write the purpose of strlen, strcpy, strcat, strcmp and substr.", "points": [
            "Define a C string as a char array ending in \\0. Distinguish capacity from length.",
            "Give strlen, strcpy, strcat and strcmp with one sentence and one caution each.",
            "Show substr on a std::string and say it is not a cstring function.",
            "Describe the reverse-name loop from length-1 down to 0.",
        ]},
    ],
})

END.append({
    "grade": "XI",
    "unit": "7",
    "kicker": "Class XI  |  Unit 7  |  weight 15%",
    "title": "Computer communication and networks",
    "weight": "15%",
    "periods": "25 theory periods",
    "intro": "A network is computers and other devices joined so they can exchange data. This lecture names the parts of a communication, the directions data can travel, the media, the shapes of a network, and the layered models used to describe it.",
    "slos": [
        "Describe a network, its advantages, and the five communication components.",
        "Define simplex, half duplex and full duplex.",
        "Compare guided and unguided media.",
        "Describe LAN and WAN, and the bus, star, ring, mesh, tree and hybrid topologies.",
        "Name ISO, IEEE, ITU and ASCII, and describe the OSI, TCP/IP and Internet models.",
    ],
    "path": [
        "Start from a message the class actually sends, and name sender, receiver, medium, message and protocol on that example.",
        "Teach direction with a television, a walkie-talkie and a telephone.",
        "Draw bus, star and ring. Describe mesh, tree and hybrid from the drawings.",
        "Build the OSI stack from the physical wire up to the program the user touches. Place TCP/IP beside it.",
    ],
    "sections": [
        ("h", "7.1 A network and its parts"),
        ("def", "Computer network", "A collection of computers and other devices connected so that they can communicate and share resources."),
        ("p", "A college network shares printers, shares files, lets staff send messages, keeps a backup in one place, and gives many computers a path to the internet. The sharing has to be organised, and the cable or wireless link has to be protected and maintained."),
        ("table", "Five components of communication", ["Component", "In a college email"], [
            ["Sender", "The computer of the person who writes the message"],
            ["Receiver", "The computer of the person who reads it"],
            ["Medium", "The cable or the wireless link that carries the signal"],
            ["Message", "The mail itself"],
            ["Protocol", "The agreed rules, such as the rules that format and deliver mail"],
        ]),
        ("def", "Protocol", "A set of rules that communicating devices follow so that a message sent by one can be understood by the other."),
        ("h", "7.2 Direction of data"),
        ("table", "Communication modes", ["Mode", "Direction", "Example"], [
            ["Simplex", "One direction only", "A keyboard sending to the computer, or a television broadcast"],
            ["Half duplex", "Both directions, one at a time", "A walkie-talkie"],
            ["Full duplex", "Both directions at the same time", "A telephone conversation, and ordinary Ethernet"],
        ]),
        ("h", "7.3 Transmission media"),
        ("def", "Guided medium", "A physical path that contains the signal: a wire or a fibre."),
        ("def", "Unguided medium", "A wireless path. The signal travels through the air or space."),
        ("ul", [
            "**Twisted pair** is the ordinary copper LAN cable. Wires are twisted to reduce interference. Shielded twisted pair adds a foil or braid. Unshielded twisted pair is the common Ethernet cable.",
            "**Coaxial cable** has a central copper core, insulation, a shield and a jacket. It resists interference and was widely used for cable television and older networks.",
            "**Fibre optic** cable carries pulses of light in a glass or plastic core. It carries data over long distances with little electrical interference and with high capacity.",
            "**Radio waves** travel in many directions and pass through ordinary walls. They carry Wi-Fi and many mobile signals.",
            "**Microwaves** travel in a straight line between antennas and are used for long point-to-point links. The antennas need a clear path.",
            "**Infrared** is a short-range light signal, used by some remote controls. It does not pass through walls.",
        ]),
        ("h", "7.4 Types and topologies"),
        ("p", "A **LAN**, local area network, covers a room, a lab or a building and is owned by one organisation. A **MAN**, metropolitan area network, covers a town or a city. A **WAN**, wide area network, covers a large region or the world. The internet is the WAN students use every day. The unit list concentrates on LAN and WAN. MAN is the standard type between them and is in the curriculum's own acronyms."),
        ("def", "Topology", "The arrangement of devices and links in a network."),
        ("diagram", "topologies", "Figure 7.1  Bus, star and ring.", 62 * mm),
        ("table", "Topologies", ["Shape", "How it is joined", "What to say in an answer"], [
            ["Bus", "Every device taps one backbone cable", "Easy to add a device. A break in the backbone stops the network."],
            ["Star", "Every device has its own cable to a central switch", "A broken spoke affects one device. The centre is essential."],
            ["Ring", "Each device connects to the next in a circle", "A token or a turn controls who may send. A break can stop the ring."],
            ["Mesh", "Devices have several paths to each other", "The network survives a broken link. It uses more cable."],
            ["Tree", "Stars joined in a hierarchy", "It matches a campus: rooms, floors, then a core switch."],
            ["Hybrid", "A mixture of the shapes above", "A real college network is often a hybrid, not a pure shape."],
        ]),
        ("h", "7.5 Standards and architectures"),
        ("ul", [
            "**ISO**, the International Organization for Standardization, publishes international standards, including the OSI model.",
            "**IEEE**, the Institute of Electrical and Electronics Engineers, publishes the 802 standards for local networks. IEEE 802.3 is Ethernet. IEEE 802.11 is wireless LAN.",
            "**ITU**, the International Telecommunication Union, publishes standards for telecommunications.",
            "**ASCII** is a character-encoding standard, not an organisation. It assigns numbers to letters, digits and controls. The basic set uses 7 bits and contains 128 characters. It is in this unit because communicating computers must agree on how characters are coded.",
        ]),
        ("diagram", "osi", "Figure 7.2  OSI beside TCP/IP. Three OSI layers sit inside the TCP/IP application layer.", 88 * mm),
        ("table", "The OSI layers, from the wire upward", ["Layer", "Job in one sentence"], [
            ["1 Physical", "Sends bits over the medium as electrical, light or radio signals."],
            ["2 Data link", "Organises bits into frames, uses a hardware address, and detects errors on one link."],
            ["3 Network", "Addresses and routes packets across networks. IP works here."],
            ["4 Transport", "Carries data end to end between programs. TCP and UDP work here."],
            ["5 Session", "Opens, manages and closes a dialogue between applications."],
            ["6 Presentation", "Translates formats, and can compress or encrypt."],
            ["7 Application", "Provides the service the user sees, such as the web, mail or file transfer."],
        ]),
        ("p", "The **TCP/IP model**, which is the **Internet model** used on the real internet, has four layers. The application layer covers the work of OSI application, presentation and session. The transport layer carries TCP and UDP. The internet layer carries IP and routing. The network-access layer covers the data link and the physical connection. Learn both models. The board may ask for seven OSI names in order, or for the four TCP/IP names."),
        ("note", "Practical work for this unit is in the journal: straight and crossover cables, the devices in a lab network, an IP address with mask and gateway, and the difference between a network with a central server and a network of equal peers."),
        ("tip", "Memorise the OSI layers with a fixed sentence you can write under pressure, from layer 7 down to layer 1: All People Seem To Need Data Processing. Then still be able to start from the physical layer if the question says 'from the bottom'."),
    ],
    "terms": [
        ["Protocol", "Rules two devices follow in order to communicate."],
        ["Simplex", "Communication in one direction only."],
        ["Full duplex", "Communication in both directions at the same time."],
        ["LAN", "A network covering a small area, owned by one organisation."],
        ["WAN", "A network covering a large geographical area."],
        ["Topology", "The layout of nodes and links."],
        ["OSI model", "A seven-layer reference model for network functions."],
        ["TCP/IP", "The four-layer model used by the internet."],
    ],
    "summary": [
        "Communication needs a sender, a receiver, a medium, a message and a protocol.",
        "Simplex, half duplex and full duplex describe direction.",
        "Twisted pair, coax and fibre are guided. Radio, microwave and infrared are unguided.",
        "LAN and WAN describe the area. Bus, star, ring, mesh, tree and hybrid describe the shape.",
        "OSI has seven layers. TCP/IP, the Internet model, has four.",
    ],
    "labs": [
        "Identify straight-through and crossover cables and the devices in the lab: NIC, switch, router, modem.",
        "Read an IP address, subnet mask and gateway from a working computer.",
        "Say whether the lab is organised around a central server or as peers.",
    ],
    "mcqs": [
        {"q": "A walkie-talkie is an example of:", "options": ["Simplex", "Half duplex", "Full duplex", "A topology"], "a": "B", "why": "Either person can talk, and only one talks at a time."},
        {"q": "Fibre optic cable carries the signal as:", "options": ["Pulses of light", "Ink", "A paper tape", "A process state"], "a": "A", "why": "Fibre carries light pulses in a glass or plastic core."},
        {"q": "In a star topology, the central device is important because:", "options": ["A failure there affects the whole star", "It stores ROM programs", "It replaces the protocol", "It is a simplex printer"], "a": "A", "why": "Every spoke depends on the centre."},
        {"q": "IEEE 802.11 describes:", "options": ["Wireless LAN", "A C++ data type", "EPROM erasing", "File attributes"], "a": "A", "why": "IEEE 802.11 is the wireless LAN family of standards."},
        {"q": "Which OSI layer routes packets between networks?", "options": ["Physical", "Network", "Session", "Application"], "a": "B", "why": "The network layer handles logical addressing and routing."},
        {"q": "TCP and UDP belong to the OSI:", "options": ["Transport layer", "Physical layer", "A cable colour", "CMOS battery"], "a": "A", "why": "Transport provides end-to-end communication. TCP and UDP are its well-known protocols."},
        {"q": "ASCII is:", "options": ["A character-encoding standard", "A topology", "A type of RAM", "An operating system"], "a": "A", "why": "ASCII assigns numeric codes to characters."},
        {"q": "A LAN is best described as:", "options": ["A network over a small area under one organisation", "A single keyboard", "A layer of OSI", "A C++ loop"], "a": "A", "why": "LAN means local area network."},
    ],
    "shorts": [
        {"q": "Name the five components of data communication.", "a": "Sender, receiver, medium, message and protocol. The sender creates the message, the medium carries it, the receiver takes it, and the protocol is the set of rules that makes the exchange understandable."},
        {"q": "Differentiate half duplex and full duplex.", "a": "Half duplex allows both directions, but only one direction at a time, as in a walkie-talkie. Full duplex allows both directions at the same time, as in a telephone call. Both are two-way. They differ in whether the two directions overlap."},
        {"q": "Differentiate guided and unguided media with one example each.", "a": "A guided medium contains the signal in a physical path, for example fibre optic cable. An unguided medium carries the signal through the air, for example radio waves used by Wi-Fi. Guided media follow a cable. Unguided media need no cable between the devices."},
        {"q": "Give one advantage and one risk of bus topology.", "a": "Cable use is simple: devices share one backbone, and a new device can be tapped onto it. A break in that backbone interrupts the network for every device on it."},
        {"q": "Write the four layers of the TCP/IP model.", "a": "Application, transport, internet and network access. The application layer covers the OSI application, presentation and session work. Transport carries TCP and UDP. The internet layer routes IP packets. Network access puts frames and bits onto the local link."},
    ],
    "longs": [
        {"q": "Explain types of networks and network topologies with a labelled description of each topology.", "points": [
            "Define a network and distinguish LAN, MAN and WAN by area.",
            "Define topology.",
            "Describe bus, star and ring, each with how devices are joined and one strength and one weakness.",
            "Describe mesh, tree and hybrid in the same way.",
            "Say which shape matches a school lab and why. A star, or a tree of stars, is the usual answer.",
        ]},
        {"q": "Explain the OSI model and compare it with TCP/IP.", "points": [
            "Say that OSI is a reference model of seven layers and name them in order.",
            "Give one job for each layer, especially physical, data link, network, transport and application.",
            "Name the four TCP/IP layers and show which OSI layers they cover.",
            "State that TCP/IP is the model the internet uses. OSI is the teaching and design reference.",
        ]},
    ],
})
