/** Syllabus SLOs plus one supporting source for the deeper whiteboard. */

const CURRICULUM = {
  xi: {
    short: "Sindh CS XI",
    year: "2026",
    work: "Computer Science, Class XI. School Education & Literacy Department, Government of Sindh.",
  },
  xii: {
    short: "Sindh CS XII",
    year: "2024 / 2025–27",
    work: "Computer Science, Class XII. School Education & Literacy Department, Government of Sindh.",
  },
};

const SLO = {
  xi: {
    "1.1.1": "Discrete quantities",
    "1.1.2": "Digital systems and bits",
    "1.1.3": "Analog and digital signals",
    "1.1.4": "Boolean algebra",
    "1.1.5": "Logic operations",
    "1.1.6": "Truth tables",
    "1.1.7": "Logic gates",
    "1.1.8": "Boolean expressions",
    "1.1.10": "Logic diagrams",
    "1.1.11": "Karnaugh maps",
    "1.1.13": "Simplifying groups",
    "1.2.1": "Software life cycle",
    "1.2.2": "Requirements",
    "1.2.3": "Design",
    "1.2.4": "Implementation",
    "1.2.5": "Testing",
    "1.2.6": "Waterfall",
    "1.2.7": "Agile sprints",
    "1.3.1": "Networked systems",
    "1.3.2": "OSI model",
    "1.3.3": "OSI layers",
    "1.3.4": "Encapsulation",
    "1.3.5": "TCP/IP",
    "1.3.6": "Comparing stacks",
    "2.1": "Computational thinking",
    "2.2": "Algorithms",
    "2.2.2": "Abstraction",
    "2.3.1": "Decomposition",
    "2.3.2": "Pattern recognition",
    "2.3.3": "Writing steps",
    "2.4": "Sorting",
    "2.4.1": "Bubble and selection sort",
    "2.4.2": "Searching",
    "2.5": "Evaluating algorithms",
    "2.5.1": "Time and space",
    "2.6": "Choosing an algorithm",
    "3.1": "Programs",
    "3.2": "High-level languages",
    "3.3": "IDEs",
    "3.4": "Python basics",
    "3.4.1": "Variables",
    "3.4.2": "Operators",
    "3.4.3": "Input and output",
    "3.5": "Control flow",
    "3.5.2": "Loops",
    "3.5.3": "Nested control",
    "3.6": "Debugging",
    "3.6.1": "Error kinds",
    "3.6.2": "Tracebacks",
    "4.1.1": "Data and databases",
    "4.1.2": "DBMS",
    "4.2": "Tables and records",
    "4.3.1": "Keys",
    "4.4": "Entities",
    "4.5": "Relationships",
    "4.6": "Cardinality",
    "4.7": "Referential integrity",
    "4.8": "Queries",
    "4.9": "Filtering",
    "4.10": "Aggregation",
    "4.11": "Charts",
    "4.11.6": "Choosing a chart",
    "5.1.1": "Artificial intelligence",
    "5.1.2": "Internet of Things",
    "5.1.3": "Data analytics",
    "5.2": "Information sources",
    "5.3": "Access and assistive tech",
    "5.4": "Social impacts",
    "5.5": "Responsible use",
    "6.1": "Digital literacy",
    "6.3": "Searching",
    "6.4": "Judging sources",
    "6.5": "Collecting data",
    "6.7": "Presenting an artefact",
    "6.8": "Limits of evidence",
  },
  xii: {
    "1.1": "Human-computer interaction",
    "1.1.1": "Interaction channels",
    "1.1.2": "Traditional and natural input",
    "1.2": "HCI domains",
    "1.3": "User benefit",
    "1.4": "Need analysis",
    "1.5": "Accessibility",
    "1.6": "Common HCI problems",
    "1.7": "User interface",
    "1.8": "User experience",
    "1.9": "Wireframes and prototypes",
    "1.11": "Usability testing",
    "2.1": "Correctness",
    "2.1.1": "Trace tables",
    "2.1.2": "Stepwise reasoning",
    "2.2": "Clarity and modularity",
    "2.3": "Algorithm analysis",
    "2.4": "Big O",
    "2.5": "Linear structures",
    "2.5.1": "Arrays, stacks, and queues",
    "2.5.2": "Trees",
    "2.6": "Graphs and structure choice",
    "2.7": "Retrieval",
    "3.1": "Python collections",
    "3.1.1": "Lists",
    "3.1.2": "Tuples",
    "3.1.3": "Sets",
    "3.1.4": "Dictionaries",
    "3.1.5": "Choosing a collection",
    "3.2": "Functions",
    "3.2.2": "Parameters and return",
    "3.2.4": "Scope",
    "3.3": "Files",
    "3.6": "Exceptions",
    "3.8": "Closing files",
    "3.9": "A small tracker",
    "4.1": "Connecting to data",
    "4.1.1": "SQLite",
    "4.2": "DataFrames",
    "4.3": "Cleaning data",
    "4.3.1": "Missing values",
    "4.3.2": "Label and position",
    "4.3.3": "Filtering rows",
    "4.4": "Descriptive statistics",
    "4.5": "Charts",
    "4.5.2": "Bar charts",
    "4.5.3": "Line charts",
    "4.5.4": "Pie charts",
    "4.5.5": "Box plots",
    "4.5.6": "Scatter plots",
    "4.6": "Histograms",
    "4.6.2": "Choosing a chart",
    "5.1": "Machine learning",
    "5.1.1": "Supervised learning",
    "5.1.2": "Features and labels",
    "5.1.3": "Training",
    "5.1.4": "Neural networks",
    "5.1.5": "Applications",
    "5.2": "Human accountability",
    "5.3": "Security",
    "5.4": "CIA triad",
    "5.4.2": "Encryption and hashing",
    "5.4.3": "Backups",
    "5.5": "Equity",
    "5.5.2": "Access",
    "6.1": "Entrepreneurship",
    "6.2": "Opportunity",
    "6.3": "Users and customers",
    "6.4": "Lean ideas",
    "6.5": "MVP",
    "6.6": "Riskiest assumption",
    "6.8": "Business model",
    "6.9": "Testing a belief",
    "6.10": "Pivot",
    "6.13": "Ethics",
    "6.14": "Shipping small",
  },
};

function src(author, year, title, venue, why) {
  return { author, year, title, venue, why };
}

const SUPPORT = {
  "xi-digital": src("Shannon, C. E.", "1948", "A Mathematical Theory of Communication", "Bell System Technical Journal", "The board’s snap-to-level is quantization: a continuous reading becomes a discrete symbol."),
  "xi-signals": src("Shannon, C. E.", "1949", "Communication in the Presence of Noise", "Proceedings of the IRE", "A receiver keeps the bit when noise stays on one side of a decision threshold."),
  "xi-boolean": src("De Morgan, A.", "1847", "Formal Logic", "Taylor and Walton", "The last board is De Morgan’s rewrite: NOT of AND becomes OR of NOTs."),
  "xi-gates": src("Sheffer, H. M.", "1913", "A Set of Five Independent Postulates for Boolean Algebras", "Transactions of the American Mathematical Society", "One NAND (the Sheffer stroke) is enough to express every Boolean function."),
  "xi-kmap": src("Karnaugh, M.", "1953", "The Map Method for Synthesis of Combinational Logic Circuits", "Transactions of the AIEE", "Don’t-care cells may join a legal group; a forced 0 may not."),
  "xi-sdlc": src("Beck, K., Beedle, M., van Bennekum, A., et al.", "2001", "Manifesto for Agile Software Development", "agilemanifesto.org", "A sprint still ships working software; Agile is not a skipped test."),
  "xi-osi": src("Zimmermann, H.", "1980", "OSI Reference Model — The ISO Model of Architecture for Open Systems Interconnection", "IEEE Transactions on Communications", "Each layer wraps the message; the receiver peels the outer header first."),
  "xi-ct": src("Wing, J. M.", "2006", "Computational Thinking", "Communications of the ACM", "Abstraction names a trusted piece and hides the how."),
  "xi-sort": src("Knuth, D. E.", "1998", "The Art of Computer Programming, Vol. 3: Sorting and Searching", "Addison-Wesley", "Stability asks whether equal keys keep the order they arrived in."),
  "xi-search": src("Cormen, T. H., Leiserson, C. E., Rivest, R. L., & Stein, C.", "2009", "Introduction to Algorithms", "MIT Press", "A correct binary-search step keeps the target, if present, between low and high."),
  "xi-eval": src("Knuth, D. E.", "1974", "Computer Programming as an Art", "Communications of the ACM", "You spend one resource to save another: time, memory, or clarity."),
  "xi-python": src("Python Software Foundation", "2024", "The Python Language Reference", "Objects, values and types", "Assignment binds a name; b = a aliases the same list object."),
  "xi-control": src("Python Software Foundation", "2024", "The Python Standard Library", "Built-in Types · range", "range(start, stop) excludes stop, so range(1, 4) is 1, 2, 3."),
  "xi-debug": src("Python Software Foundation", "2024", "The Python Tutorial", "Errors and Exceptions", "A traceback is a location. Read it from the last line upward."),
  "xi-db": src("Codd, E. F.", "1970", "A Relational Model of Data for Large Shared Data Banks", "Communications of the ACM", "A foreign key stores the identifier, not a copy of the name."),
  "xi-er": src("Chen, P. P.", "1976", "The Entity-Relationship Model: Toward a Unified View of Data", "ACM Transactions on Database Systems", "A many-to-many pair lives in a bridge entity such as Loan."),
  "xi-queries": src("Chamberlin, D. D., & Boyce, R. F.", "1974", "SEQUEL: A Structured English Query Language", "ACM SIGFIDET Workshop", "Filter then group answers a different question than group then filter."),
  "xi-impacts": src("Huff, D.", "1954", "How to Lie with Statistics", "W. W. Norton", "A pattern in a chart is not, by itself, a cause."),
  "xi-literacy": src("Neyman, J.", "1934", "On the Two Different Aspects of the Representative Method", "Journal of the Royal Statistical Society", "Friends-only answers describe the sample, not the population you never asked."),
  "xii-hci": src("Norman, D. A.", "2013", "The Design of Everyday Things", "Basic Books", "A silent success fails the gulf of evaluation: the person cannot see that it worked."),
  "xii-design": src("Fitts, P. M.", "1954", "The Information Capacity of the Human Motor System in Controlling the Amplitude of Movement", "Journal of Experimental Psychology", "A large, nearby target is faster to hit than a small, far one."),
  "xii-correct": src("Knuth, D. E.", "1976", "Big Omicron and Big Omega and Big Theta", "ACM SIGACT News", "Big O drops constants, so 3n and n are the same linear class."),
  "xii-linear": src("Tarjan, R. E.", "1985", "Amortized Computational Complexity", "SIAM Journal on Algebraic Discrete Methods", "A rare array doubling is paid for across many cheap pushes."),
  "xii-nonlinear": src("Cormen, T. H., Leiserson, C. E., Rivest, R. L., & Stein, C.", "2009", "Introduction to Algorithms", "MIT Press", "Sorted inserts can collapse a binary search tree into a list of height n."),
  "xii-structs": src("Python Software Foundation", "2024", "The Python Language Reference", "Mappings", "A second write to the same key replaces the earlier value."),
  "xii-files": src("Shafranovich, Y.", "2005", "Common Format and MIME Type for Comma-Separated Values (CSV) Files", "RFC 4180", "A comma inside a field must be quoted, as in \"Khan, Jr\"."),
  "xii-pandas": src("McKinney, W.", "2010", "Data Structures for Statistical Computing in Python", "Proceedings of the 9th Python in Science Conference", "After a filter, iloc uses position; loc looks up a label."),
  "xii-stats": src("Tukey, J. W.", "1977", "Exploratory Data Analysis", "Addison-Wesley", "One outlier can pull the mean while the median stays the middle value."),
  "xii-ml": src("Mitchell, T. M.", "1997", "Machine Learning", "McGraw-Hill", "Memorizing the practice set is overfitting; a held-out test checks generalization."),
  "xii-security": src("ISO/IEC", "2018", "ISO/IEC 27000: Information security management systems — Overview and vocabulary", "International Organization for Standardization", "Encrypt, hash, and backup do three different CIA jobs."),
  "xii-venture": src("Osterwalder, A., & Pigneur, Y.", "2010", "Business Model Generation", "Wiley", "The user of a product may not be the customer who pays."),
  "xii-mvp": src("Ries, E.", "2011", "The Lean Startup", "Crown Business", "An MVP is small enough to kill one belief quickly."),
};

export function formatSupport(item) {
  if (!item) return "";
  const venue = item.venue ? `. ${item.venue}` : "";
  return `${item.author} (${item.year}). ${item.title}${venue}.`;
}

export function citationHaystack(lecture) {
  const cites = lecture.citations;
  if (!cites) return "";
  const sloText = (cites.slos || []).map((item) => `${item.code} ${item.title}`).join(" ");
  const extra = cites.support ? formatSupport(cites.support) : "";
  return [cites.curriculum?.short, cites.curriculum?.work, sloText, extra, cites.support?.why].filter(Boolean).join(" ");
}

export function applyCitations(lectures) {
  for (const lecture of lectures) {
    const book = CURRICULUM[lecture.track];
    const titles = SLO[lecture.track] || {};
    const slos = (lecture.covers || []).map((code) => ({ code, title: titles[code] || "" }));
    lecture.citations = {
      curriculum: book,
      slos,
      support: SUPPORT[lecture.id] || null,
    };
  }
}

export const supportIds = Object.keys(SUPPORT);
export { CURRICULUM, SLO };
