/** One deeper beat per lecture, drawn on the whiteboard and checked in the quiz. */

const B = (x, y, w, h, label, pen) => ({ t: "box", x, y, w, h, label, pen });
const A = (x1, y1, x2, y2, pen) => ({ t: "arrow", x1, y1, x2, y2, pen });
const T = (x, y, label, pen, anchor) => ({ t: "text", x, y, label, pen, anchor });
const L = (x1, y1, x2, y2, pen) => ({ t: "line", x1, y1, x2, y2, pen });
const C = (x, y, r, label, pen) => ({ t: "circ", x, y, r, label, pen });
const D = (x, y, pen) => ({ t: "dot", x, y, r: 5, pen });
const P = (d, pen) => ({ t: "path", d, pen });

function lesson(title, say, sayUr, ink, note, outcome, quiz) {
  return {
    outcome,
    beat: { title, say, sayUr, scene: { type: "whiteboard", title, ink, note } },
    quiz,
  };
}

function ask(q, choices, answer, why) {
  return { q, choices, answer, why };
}

const DEPTH = {
  "xi-digital": lesson(
    "Quantization",
    "Quantization is the cut. A continuous reading is forced onto the nearest allowed level. The gap between levels is the resolution. More bits make that gap smaller. They do not turn the file back into a ramp.",
    "مسلسل پیمائش قریب ترین سطح پر آتی ہے۔ زیادہ بٹس فاصلہ کم کرتے ہیں، ریمپ واپس نہیں لاتے۔",
    [
      L(36, 130, 480, 130),
      D(70, 130), D(430, 130, "gold"),
      T(58, 158, "0"), T(418, 158, "1"),
      D(190, 78, "gold"),
      A(190, 90, 86, 118, "gold"),
      T(150, 48, "reading snaps to the nearer level", "gold"),
    ],
    "The gold dot is a measurement. The arrow is the rounding.",
    "Explain quantization and what extra bits change.",
    ask("Extra bits in a digital sample…", ["Turn the file back into a continuous ramp", "Make the gap between allowed levels smaller", "Remove the need to round", "Store the exact analog height"], 1, "More bits mean finer discrete levels. The sample is still rounded."),
  ),
  "xi-signals": lesson(
    "The decision threshold",
    "A digital receiver draws a threshold between HIGH and LOW. Noise can wiggle the voltage, and the bit stays put as long as the wiggle does not cross that line. The price is real: the exact analog height is thrown away at the threshold.",
    "وصول کنندہ ایک حد رکھتا ہے۔ شور جب تک حد نہ پار کرے، بٹ نہیں بدلتا۔ اصل اینالاگ اونچائی ضائع ہو جاتی ہے۔",
    [
      P("M 30 100 C 70 70 90 140 130 100 S 190 60 230 110 S 300 150 340 90 S 400 70 470 105", "teal"),
      L(30, 124, 480, 124, "gold"),
      T(300, 48, "above the line = 1"),
      T(300, 168, "below the line = 0", "gold"),
    ],
    "The gold line is the only question the receiver asks.",
    "Describe the threshold a digital receiver uses.",
    ask("A digital receiver ignores small noise when…", ["The voltage never changes", "The wiggle stays on the same side of the threshold", "The signal is analog", "The wire is shorter"], 1, "The bit flips only when the voltage crosses the threshold."),
  ),
  "xi-boolean": lesson(
    "De Morgan",
    "De Morgan's law lets you push a NOT through an AND or an OR. NOT of A AND B equals NOT A OR NOT B. NOT of A OR B equals NOT A AND NOT B. The law is why a NAND gate, which is a NOT around an AND, can be rewired to act as an OR.",
    "ڈی مارگن: اے این ڈی کے باہر ناٹ، دونوں پر ناٹ کے بعد او آر بن جاتا ہے۔ اسی لیے نینڈ سے او آر بن سکتا ہے۔",
    [
      B(24, 70, 150, 52, "A AND B"),
      A(180, 96, 250, 96, "gold"),
      B(258, 70, 210, 52, "NOT A OR NOT B", "gold"),
      T(24, 48, "one NOT outside"),
      T(258, 48, "NOT on each letter", "gold"),
    ],
    "$\\overline{A \\cdot B} = \\overline{A} + \\overline{B}$",
    "Apply De Morgan's law to a NOT around AND or OR.",
    ask("NOT (A AND B) is the same as…", ["NOT A AND NOT B", "NOT A OR NOT B", "A OR B", "A AND NOT B"], 1, "The NOT outside AND becomes OR, and each input is inverted."),
  ),
  "xi-gates": lesson(
    "NOT from one NAND",
    "Tie both inputs of a NAND gate to the same wire. NAND of A and A is NOT of A AND A, which is simply NOT A. That one wiring trick is what universal means. You do not fetch a new chip. You copy NAND and connect the pins.",
    "نینڈ کے دونوں ان پٹ ایک ہی تار سے جوڑ دو۔ نتیجہ ناٹ اے ہے۔ یونیورسل کا مطلب نئی چپ نہیں، جوڑنا ہے۔",
    [
      L(40, 70, 150, 96),
      L(40, 130, 150, 96),
      T(36, 48, "same A"),
      B(156, 68, 130, 56, "NAND", "gold"),
      A(292, 96, 390, 96, "gold"),
      T(400, 102, "NOT A", "gold"),
    ],
    "Both pins see A, so the gate can only invert.",
    "Build a NOT gate from a single NAND.",
    ask("A NAND gate with both inputs tied together acts as…", ["OR", "XOR", "NOT", "a wire that does nothing"], 2, "NAND of A with A is NOT A."),
  ),
  "xi-kmap": lesson(
    "Don't-care cells",
    "A don't-care cell is an input combination the circuit will never see, drawn as X. You may pull an X into a group when that makes a legal power-of-two group larger. You may also leave it out. You may never pull in a cell that is a required 0.",
    "ڈونٹ کیئر یعنی ایکس وہ حالت ہے جو کبھی نہیں آتی۔ اسے گروپ میں لا سکتے ہو اگر گروپ بڑا اور جائز بنے۔ صفر کو شامل نہیں کرتے۔",
    [
      B(70, 50, 70, 50, "1"),
      B(148, 50, 70, 50, "X", "gold"),
      B(70, 108, 70, 50, "0"),
      B(148, 108, 70, 50, "1"),
      C(183, 75, 42, "", "gold"),
      T(280, 78, "X may join"),
      T(280, 118, "0 may not", "gold"),
    ],
    "The circle is a legal pair: one 1 and one X.",
    "Decide when a don't-care cell may enter a group.",
    ask("A don't-care cell marked X…", ["Must always be grouped", "May be grouped only if it enlarges a legal group", "Is the same as a required 1", "Cancels the whole map"], 1, "X is optional. A required 0 is never optional."),
  ),
  "xi-sdlc": lesson(
    "A sprint is not a skipped test",
    "Agile still does every phase. It slices them thin and repeats them. A sprint that codes and ships without a test is not Agile. It is a short waterfall with the testing phase missing. The review at the end of a sprint is a test with a user in the room.",
    "ایجائل مرحلے چھوڑتا نہیں، انہیں پتلا کر کے دہراتا ہے۔ بغیر جانچ کا اسپرت چھوٹا واٹر فال ہے۔",
    [
      B(24, 40, 100, 44, "Need"),
      A(128, 62, 156, 62),
      B(160, 40, 90, 44, "Build"),
      A(254, 62, 282, 62),
      B(286, 40, 90, 44, "Test", "gold"),
      A(380, 62, 400, 150, "gold"),
      B(160, 140, 150, 44, "next slice", "gold"),
    ],
    "The loop returns only after the test, not instead of it.",
    "Explain how Agile keeps testing inside each slice.",
    ask("A sprint that ships with no test is…", ["The definition of Agile", "A short waterfall missing a phase", "Maintenance", "A requirements document"], 1, "Agile repeats the phases. It does not delete testing."),
  ),
  "xi-osi": lesson(
    "Headers wrap the message",
    "Encapsulation means each layer adds its own header and does not rewrite the message inside. The sender wraps from the inside out. The receiver peels headers in reverse, one layer at a time. If a header is wrong, that layer drops the packet before the inner message is even read.",
    "ہر تہہ اپنا ہیڈر لپیٹتی ہے۔ وصول کنندہ الٹی ترتیب میں ہیڈر اتارتا ہے۔ غلط ہیڈر پر پیکٹ وہیں رک جاتا ہے۔",
    [
      B(70, 36, 360, 150, ""),
      B(110, 64, 280, 100, ""),
      B(150, 92, 200, 48, "message", "gold"),
      T(78, 56, "outer header"),
      T(118, 84, "inner header"),
    ],
    "The message sits in the middle. Headers are the frames around it.",
    "Describe encapsulation as headers added and removed in order.",
    ask("The receiver handles OSI headers…", ["In the same order the sender added them", "By peeling the outer header first", "By skipping the network layer", "Only if the message is analog"], 1, "The last header added is the first one removed."),
  ),
  "xi-ct": lesson(
    "Abstraction hides the how",
    "Decomposition splits a problem. Pattern recognition says a piece is a sort, a search, or a queue you already trust. Abstraction is the next cut: you name the piece and stop describing its insides. A function name is an abstraction. Callers depend on the name and the result, not on which loop is inside.",
    "تجزیہ مسئلہ بانٹتا ہے۔ تجرید اندر کا طریقہ چھپا کر صرف نام اور نتیجہ رکھتی ہے۔",
    [
      B(24, 78, 130, 48, "whole task"),
      A(160, 102, 210, 102),
      B(216, 36, 120, 40, "sort", "gold"),
      B(216, 86, 120, 40, "search", "gold"),
      B(216, 136, 120, 40, "queue", "gold"),
      T(360, 102, "name it, hide the loop"),
    ],
    "Once the box has a true name, the arrows inside can stay off the page.",
    "Distinguish abstraction from merely splitting a problem.",
    ask("Abstraction means you…", ["Describe every loop in the write-up", "Name a trusted piece and hide its insides", "Skip testing", "Store data without a key"], 1, "The caller needs the result, not the loop that produced it."),
  ),
  "xi-sort": lesson(
    "Stability",
    "A sort is stable when equal keys keep the order they arrived in. If Ali and Hina both scored 70, and Ali was listed first, a stable sort still lists Ali first. Selection sort reaches across the list and can swap equals apart. A careful bubble sort that does not swap equal neighbors stays stable.",
    "مستحکم ترتیب برابر قدروں کی پرانی ترتیب رکھتی ہے۔ سلیکشن سارٹ برابر قدروں کو ادل بدل سکتا ہے۔",
    [
      B(30, 70, 120, 48, "Ali 70"),
      B(160, 70, 130, 48, "Hina 70"),
      T(24, 48, "arrival order"),
      A(310, 94, 360, 94, "gold"),
      B(368, 70, 130, 48, "Ali, then Hina", "gold"),
    ],
    "The gold box is what a stable sort owes you.",
    "Say what a stable sort preserves when keys are equal.",
    ask("A stable sort of equal keys…", ["Reverses them on purpose", "Keeps the order they had before sorting", "Deletes the duplicates", "Requires a binary tree"], 1, "Equal items stay in their original relative order."),
  ),
  "xi-search": lesson(
    "The search invariant",
    "Binary search has a promise: if the target is in the list, it is still between low and high. Each step must keep that promise. Moving low up when the target is smaller, or moving high down when it is larger, throws the target out. A later step cannot find what an earlier step discarded.",
    "بائنری سرچ کا وعدہ: ہدف اگر فہرست میں ہے تو لو اور ہائی کے درمیان ہے۔ غلط حد ہدف کو باہر پھینک دیتی ہے۔",
    [
      L(40, 120, 470, 120),
      D(70, 120, "teal"), D(250, 120, "gold"), D(430, 120),
      T(52, 150, "low"), T(228, 150, "target", "gold"), T(410, 150, "high"),
      L(70, 96, 430, 96, "teal"),
    ],
    "The teal bracket is the only region you are still allowed to trust.",
    "State the invariant binary search must keep.",
    ask("After a correct binary-search step, the target…", ["Might have been in the half you discarded", "Is still between low and high if it was present", "Is always at index 0", "Has been deleted"], 1, "A correct step only discards values that cannot be the target."),
  ),
  "xi-eval": lesson(
    "You spend one to save another",
    "Correctness comes first. After that, time, memory, and clarity compete. A dictionary answers in constant time and spends memory on the table. A linear scan spends no extra memory and spends time. The in-depth move is to name which cost you are paying, not to pretend an algorithm is free on every axis.",
    "وقت، میموری، اور وضاحت اکٹھے بہترین نہیں ہوتیں۔ جو بچاؤ، وہ کہو کہ کس قیمت پر۔",
    [
      C(260, 52, 28, ""),
      C(120, 150, 28, ""),
      C(400, 150, 28, ""),
      L(150, 140, 240, 72),
      L(280, 72, 370, 140),
      L(148, 150, 372, 150),
      T(230, 46, "time"),
      T(40, 186, "memory"),
      T(360, 186, "clarity"),
    ],
    "Moving toward one corner pulls you away from another.",
    "Name the tradeoff among time, memory, and clarity.",
    ask("A constant-time lookup usually pays with…", ["No memory at all", "Extra memory for the table", "A nested loop", "A loss of correctness"], 1, "The table is the memory you spend to avoid scanning."),
  ),
  "xi-python": lesson(
    "Two names, one list",
    "A name in Python is a label on an object, not a box that holds a private copy. If b equals a, and a is a list, both names point at that one list. Appending through b changes what a sees. Numbers hide this because a new number creates a new object. Lists do not.",
    "پائتھن میں نام ڈبے نہیں، لیبل ہیں۔ اگر بی برابر اے اور اے لسٹ ہے تو دونوں ایک ہی لسٹ دیکھتے ہیں۔",
    [
      T(40, 70, "a"),
      T(40, 140, "b"),
      A(70, 64, 250, 100, "gold"),
      A(70, 134, 250, 112, "gold"),
      B(250, 78, 160, 52, "one list", "gold"),
    ],
    "Both arrows land on the same box. There is no second list.",
    "Explain what happens when two names refer to one list.",
    ask("After b = a, where a is a list, appending through b…", ["Leaves a unchanged", "Changes the list that a also names", "Copies every item first", "Is a syntax error"], 1, "Assignment of a list copies the label, not the items."),
  ),
  "xi-control": lesson(
    "The stop that is not included",
    "range of start and stop counts from start and halts before stop. range of 1 and 4 yields 1, 2, and 3, not 4. The same rule is why a slice marks up to but not including the stop index. Most off-by-one bugs are this open end, drawn as a hollow dot.",
    "رینج سٹارٹ سے چلتی ہے اور سٹاپ سے پہلے رک جاتی ہے۔ آخری نمبر شامل نہیں۔ یہی عام آف بائی ون ہے۔",
    [
      L(40, 110, 460, 110),
      D(80, 110, "teal"), D(190, 110, "teal"), D(300, 110, "teal"),
      C(410, 110, 8, "", "gold"),
      T(70, 146, "1"), T(180, 146, "2"), T(290, 146, "3"), T(390, 146, "4", "gold"),
      T(40, 48, "range(1, 4) includes the filled dots only"),
    ],
    "The hollow dot is the stop. The loop does not land on it.",
    "Predict where range and a slice stop.",
    ask("range(1, 4) produces…", ["1, 2, 3, 4", "1, 2, 3", "0, 1, 2, 3", "4 only"], 1, "The stop value is excluded."),
  ),
  "xi-debug": lesson(
    "The error is a location",
    "Read a traceback from the bottom. The last line is the exception. The line above it is the file and the line number in your code. Fix that line, or the value that arrived there. Printing the variables just above the failing line is a measurement. Guessing a random edit is not.",
    "ٹریس بیک نیچے سے پڑھو۔ آخری سطر غلطی ہے، اس کے اوپر فائل اور لائن نمبر۔ اندازہ نہیں، وہیں دیکھو۔",
    [
      B(40, 36, 280, 40, "your_file.py, line 12"),
      A(180, 80, 180, 108),
      B(40, 112, 280, 40, "ZeroDivisionError", "gold"),
      T(350, 130, "start here", "gold"),
    ],
    "The gold box is the bottom of the traceback, which is where you begin.",
    "Use a traceback to find the failing line.",
    ask("In a Python traceback you start from…", ["The first import in the file", "The last line, the exception and its location", "A random function", "The operating system"], 1, "The bottom names the error and the line that raised it."),
  ),
  "xi-db": lesson(
    "A foreign key is a promise",
    "A foreign key is not just a column with a similar name. It promises that each value is either empty, if your rule allows, or equal to a primary key that exists right now. Storing a student's name in the loan table breaks the promise, because names repeat and names change. Store the id.",
    "فارن کی وعدہ ہے کہ قیمت موجود پرائمری کی کے برابر ہو۔ نام نہیں، آئی ڈی رکھو، کیونکہ نام بدل اور دہرایا جاتا ہے۔",
    [
      B(30, 60, 160, 80, "Student"),
      T(48, 108, "id 14"),
      B(300, 60, 170, 80, "Loan", "gold"),
      T(318, 108, "student_id 14", "gold"),
      A(196, 100, 290, 100),
    ],
    "The arrow is valid only while student 14 still exists.",
    "Explain what a foreign key promises.",
    ask("A loan row should point at a student using…", ["The student's name", "The student's primary key", "A random integer", "The loan's own due date"], 1, "The reference must match a real primary key, and names are not unique."),
  ),
  "xi-er": lesson(
    "Where the pair lives",
    "In a many-to-many relationship the pair cannot sit inside either entity without repeating rows. Student would repeat for every book, or Book would repeat for every student. The bridge entity Loan stores one pair per row: one student id, one book id, and facts about that pairing, such as the due date.",
    "مینی ٹو مینی میں جوڑا کسی ایک اینٹیٹی میں نہیں بیٹھتا۔ لون ہر جوڑا ایک قطار میں رکھتی ہے۔",
    [
      B(20, 78, 120, 48, "Student"),
      A(146, 102, 190, 102),
      B(196, 70, 120, 64, "Loan", "gold"),
      A(322, 102, 366, 102),
      B(372, 78, 120, 48, "Book"),
      T(210, 48, "one pair per row", "gold"),
    ],
    "Loan is the relationship turned into a table.",
    "Say why a many-to-many relationship needs a bridge.",
    ask("Without a Loan table, a many-to-many borrow…", ["Fits cleanly in Student", "Forces repeated rows in Student or Book", "Is one-to-one", "Needs no key"], 1, "Each side has many, so the pair needs its own rows."),
  ),
  "xi-queries": lesson(
    "Filter, then group",
    "The order of operations changes the question. Filter section B first, then average, and you get the average of section B. Average every section first, then throw away the other rows, and the number can look the same only by luck. In a written query, say which rows entered the group.",
    "پہلے فلٹر پھر اوسط، اور پہلے اوسط پھر فلٹر، دو مختلف سوال ہیں۔ لکھو کون سی قطاریں گروپ میں آئیں۔",
    [
      B(24, 40, 140, 44, "section B"),
      A(100, 88, 100, 116),
      B(24, 120, 140, 44, "average", "gold"),
      B(280, 40, 180, 44, "average all"),
      A(360, 88, 360, 116),
      B(280, 120, 180, 44, "then drop rows"),
    ],
    "The gold box is the average you can defend.",
    "Explain why filter-then-group differs from group-then-filter.",
    ask("To average only section B you should…", ["Average every section, then delete rows", "Keep section B, then average", "Sort by name", "Drop the primary key"], 1, "The filter decides which rows enter the average."),
  ),
  "xi-impacts": lesson(
    "A pattern is not a cause",
    "A chart can show that two things rise together. That is a correlation. It does not show that one made the other happen. Screen time and lower marks can share a third cause, such as a long commute. Before you write because, name the evidence that would show a cause, not just a pair of lines.",
    "دو لائنیں اکٹھی چڑھیں تو یہ تعلق ہے، سبب نہیں۔ جب تک وجہ کا ثبوت نہ ہو، because نہ لکھो۔",
    [
      P("M 40 150 L 120 120 L 200 130 L 280 70", "teal"),
      P("M 40 160 L 120 140 L 200 110 L 280 80", "gold"),
      T(300, 90, "together"),
      B(300, 120, 180, 48, "not yet because", "gold"),
    ],
    "Two curves can share a cause you have not drawn.",
    "Separate correlation from a claim of cause.",
    ask("Two rising lines on one chart show…", ["That one variable caused the other", "A correlation, which may have another cause", "A primary key", "A syntax error"], 1, "Correlation is a pattern. Cause needs more evidence."),
  ),
  "xi-literacy": lesson(
    "Who never got asked",
    "A careful artefact names the people missing from the data. A questionnaire handed only to friends measures your friends. Say the population you care about, the sample you actually reached, and one way the sample could lean. That sentence is more honest than a precise-looking average.",
    "صرف دوستوں سے سوال دوستوں کو ناپتا ہے۔ آبادی، نمونہ، اور جھکاؤ لکھو۔",
    [
      C(150, 100, 70, ""),
      D(120, 80, "teal"), D(160, 90, "teal"), D(140, 120, "teal"),
      C(360, 100, 28, "", "gold"),
      T(40, 40, "who you asked"),
      T(310, 48, "who you needed", "gold"),
    ],
    "The small gold circle is the population your average does not cover.",
    "Name the gap between a sample and the population.",
    ask("Surveying only your friends limits the claim because…", ["Friends answer more honestly by definition", "The sample is not the whole population you may care about", "Averages cannot be computed", "Primary data is illegal"], 1, "The people you did not ask can lean the other way."),
  ),
  "xii-hci": lesson(
    "Two gulfs",
    "Norman names two gaps. The gulf of execution is whether a person can tell what action is possible. The gulf of evaluation is whether they can tell if the action worked. A clear button narrows the first. A visible change narrows the second. A silent success fails evaluation even when the data was saved.",
    "عمل کا خلیج: کیا کرنا ممکن ہے؟ جانچ کا خلیج: کیا کام ہو گیا؟ خاموش کامیابی دوسرا خلیج کھلا چھوڑتی ہے۔",
    [
      B(24, 78, 110, 48, "person"),
      A(140, 90, 230, 70, "gold"),
      A(230, 130, 140, 114),
      B(236, 70, 140, 64, "system"),
      T(150, 48, "can I act?", "gold"),
      T(150, 168, "did it work?"),
    ],
    "Feedback is the return arrow. Without it, the lower gulf stays open.",
    "Name the gulfs of execution and evaluation.",
    ask("A saved form that shows no change fails…", ["The gulf of evaluation", "A primary key", "Binary search", "Encapsulation"], 0, "The person cannot tell whether the action worked."),
  ),
  "xii-design": lesson(
    "Fitts, in one sketch",
    "Fitts's law says a target is faster to hit when it is larger and closer to where the pointer already is. The primary action should be a wide control near the thumb or the cursor, not a tiny icon in the far corner. Speed here is human movement, not the processor.",
    "بڑا اور قریب نشان جلد چھوتا ہے۔ اہم بٹن چھوٹا کونے والا آئیکن نہیں ہونا چاہیے۔",
    [
      C(120, 110, 42, "", "gold"),
      C(420, 60, 12, ""),
      T(70, 176, "fast", "gold"),
      T(380, 96, "slow"),
      D(70, 170, "teal"),
    ],
    "The teal dot is where the hand already is. Distance and size both count.",
    "Apply Fitts's law to the size and place of a control.",
    ask("According to Fitts's law, the faster target is…", ["Small and far", "Large and close", "Hidden until hover", "The same speed either way"], 1, "Time grows with distance and shrinks as the target grows."),
  ),
  "xii-correct": lesson(
    "The constant you dropped",
    "Big O keeps the shape and drops the constant. Three n and n are both linear, so they share a class. For a small list the constant can matter more than the class. An algorithm that does one hundred n steps can lose to a simple two n squared until n grows. Say the class, then ask whether n is large yet.",
    "بگ او مستقل ہٹا دیتا ہے۔ تین این اور این دونوں لکیری ہیں۔ چھوٹی فہرست پر مستقل جیت سکتا ہے۔",
    [
      P("M 60 160 L 240 70", "teal"),
      P("M 60 120 L 240 30", "gold"),
      T(260, 80, "n", "teal"),
      T(260, 40, "3n", "gold"),
      T(40, 40, "same O(n)"),
    ],
    "Same slope family. The gold line pays a larger constant.",
    "Explain what Big O hides when two algorithms share a class.",
    ask("3n and n are…", ["Different Big O classes", "Both linear, with different constants", "Both constant time", "Both quadratic"], 1, "The constant 3 is dropped. The class is still linear."),
  ),
  "xii-linear": lesson(
    "The rare expensive push",
    "A dynamic array sometimes has no empty slot, so it allocates a larger block and copies every item. That one push is expensive. If the block doubles each time, most pushes find a free slot. The average cost of a push stays nearly constant. That average is the amortized cost. The spike is real, and it is rare.",
    "کبھی ارے بھر جاتا ہے اور نقل مہنگی ہوتی ہے۔ جگہ دگنی ہو تو زیادہ تر پش سستے رہتے ہیں۔ اوسط لاگت ایمورٹائزڈ ہے۔",
    [
      L(50, 160, 50, 120), L(90, 160, 90, 120), L(130, 160, 130, 40, "gold"),
      L(180, 160, 180, 120), L(220, 160, 220, 120), L(260, 160, 260, 120), L(300, 160, 300, 120),
      L(340, 160, 340, 30, "gold"),
      T(120, 28, "copies", "gold"),
      T(40, 190, "most pushes are the short lines"),
    ],
    "The tall lines are the copies. They do not happen every push.",
    "Describe amortized cost for a growing array.",
    ask("Amortized constant time means…", ["Every single push costs the same", "A rare expensive push is averaged with many cheap ones", "The array never copies", "The cost is quadratic"], 1, "The spikes are real. The average across many pushes stays flat."),
  ),
  "xii-nonlinear": lesson(
    "A tree can collapse into a list",
    "A binary search tree promises a short path only while it stays balanced. Insert sorted keys and every new node can fall to the same side. The height becomes n. Search then walks a linked list and loses the logarithm. Balance is part of the promise, not a decoration.",
    "ترتیب سے داخلہ درخت کو ایک طرف گرا دیتا ہے۔ اونچائی این ہو جائے تو تلاش لسٹ جیسی ہو جاتی ہے۔",
    [
      D(80, 40, "gold"),
      L(80, 48, 160, 80),
      D(160, 88, "gold"),
      L(160, 96, 250, 128),
      D(250, 136, "gold"),
      L(250, 144, 340, 176),
      D(340, 184, "gold"),
      T(360, 100, "height = n", "gold"),
    ],
    "Every link goes the same way. There is no halving left.",
    "Explain when a binary search tree loses logarithmic search.",
    ask("Inserting already sorted keys into an unbalanced tree…", ["Keeps search logarithmic", "Can make the height linear", "Deletes the root", "Turns the tree into a hash table"], 1, "A one-sided tree is a list, and search walks every node."),
  ),
  "xii-structs": lesson(
    "A second write replaces",
    "A set stores each value once. Adding a value that is already there changes nothing. A dictionary stores one value per key. Writing the same key again replaces the old value. It does not grow a list, unless the value you stored was already a list and you append to that list on purpose.",
    "سیٹ دہرائی ہوئی قیمت نہیں رکھتا۔ ڈکشنری میں وہی کلید دوبارہ لکھو تو پرانی قیمت بدل جاتی ہے، فہرست نہیں بنتی۔",
    [
      B(24, 70, 140, 48, "k : 1"),
      A(172, 94, 230, 94, "gold"),
      B(238, 70, 150, 48, "k : 2", "gold"),
      T(24, 48, "second write"),
      T(24, 160, "the key still appears once"),
    ],
    "The gold box is the whole entry after the second assignment.",
    "Predict what a set and a dictionary do with a duplicate.",
    ask("Assigning scores['Ali'] = 9 when Ali already has 7…", ["Keeps both 7 and 9", "Replaces 7 with 9", "Raises an error by definition", "Sorts the dictionary"], 1, "One key holds one value. The new assignment overwrites it."),
  ),
  "xii-files": lesson(
    "A comma inside a field",
    "A CSV row splits on commas. The name Khan, Jr becomes two fields unless the comma is inside quotes. Those quotes are part of the file format, not part of the name. When you read the row back, the quotes should be gone and the comma should still be inside the name. A shifted column is usually this bug.",
    "سی ایس وی کوما پر کٹتا ہے۔ نام کے اندر کوما ہو تو نام کو کوٹس میں رکھو، ورنہ کالم سرک جاتے ہیں۔",
    [
      T(24, 56, "Khan, Jr, 12"),
      A(40, 70, 40, 100),
      B(24, 108, 90, 40, "Khan"),
      B(122, 108, 70, 40, "Jr"),
      B(200, 108, 60, 40, "12"),
      B(300, 70, 190, 48, "\"Khan, Jr\", 12", "gold"),
    ],
    "The top row splits wrong. The gold row is one name and one number.",
    "Explain why a comma inside a CSV field needs quotes.",
    ask("The field Khan, Jr in a CSV file must be…", ["Split into two columns", "Quoted so the comma stays inside the name", "Stored as a primary key", "Removed"], 1, "Quotes tell the reader that this comma is not a separator."),
  ),
  "xii-pandas": lesson(
    "Label versus position",
    "loc selects by label. iloc selects by position, counting from zero. If you have filtered the frame, the labels may be 4, 9, and 12 while the positions are still 0, 1, and 2. loc of 0 then looks for the label 0 and can miss. iloc of 0 returns the first remaining row. Say which one you mean.",
    "لوک لیبل سے چنتا ہے، آئی لوک پوزیشن سے۔ فلٹر کے بعد لیبل صفر پوزیشن صفر نہیں رہتا۔",
    [
      B(30, 50, 70, 36, "4"),
      B(30, 92, 70, 36, "9"),
      B(30, 134, 70, 36, "12"),
      A(110, 68, 200, 68, "gold"),
      T(210, 74, "iloc 0 → row 4", "gold"),
      A(110, 152, 200, 152),
      T(210, 158, "loc 0 → missing"),
    ],
    "After a filter, position and label part company.",
    "Choose loc or iloc when the index is not a simple count.",
    ask("After filtering, iloc[0] returns…", ["The row whose label is 0", "The first remaining row, whatever its label", "Every column named 0", "An error always"], 1, "iloc counts positions. loc looks up labels."),
  ),
  "xii-stats": lesson(
    "One point moves the mean",
    "The median stays at the middle position when you add one extreme mark. The mean walks toward that mark because every value is in the sum. Report both when the class has a single perfect score or a single zero. The standard deviation also grows, because it measures distance from the mean that just moved.",
    "ایک انتہائی نمبر اوسط کو اپنی طرف کھینچتا ہے۔ میڈین درمیان میں رہتی ہے۔ دونوں بتاؤ۔",
    [
      D(80, 120, "teal"), D(120, 120, "teal"), D(160, 120, "teal"), D(200, 120, "teal"),
      D(430, 120, "gold"),
      L(160, 70, 160, 150, "teal"),
      L(250, 70, 250, 150, "gold"),
      T(120, 48, "median", "teal"),
      T(230, 48, "mean", "gold"),
    ],
    "The gold dot is one outlier. The mean has stepped toward it.",
    "Contrast how an outlier moves the mean and the median.",
    ask("Adding one very high mark…", ["Moves the median as far as the mean", "Pulls the mean and leaves the median at the middle position", "Changes neither", "Deletes the mode"], 1, "The mean uses the value. The median uses the middle seat."),
  ),
  "xii-ml": lesson(
    "Memorizing the practice set",
    "Overfitting means the model has learned the training rows, including their noise. It looks perfect on those rows and misses a new row. A held-out test set is rows the model did not train on. If training accuracy is high and test accuracy falls, the model memorized. More practice rows, or a simpler model, are the usual repairs.",
    "اوورفٹنگ مشق کی قطاریں یاد کر لیتی ہے، نئی قطار پر ناکام ہوتی ہے۔ ٹیسٹ سیٹ وہ قطاریں ہیں جو مشق میں نہیں تھیں۔",
    [
      D(70, 140, "teal"), D(120, 100, "teal"), D(170, 130, "teal"), D(220, 80, "teal"),
      P("M 50 150 C 90 90 140 150 190 90 S 230 70 250 100", "teal"),
      D(400, 60, "gold"),
      T(330, 100, "new row", "gold"),
      T(40, 40, "training wiggle"),
    ],
    "The curve hugs the practice dots and misses the gold one.",
    "Define overfitting and what a held-out test set reveals.",
    ask("High accuracy on training rows and low accuracy on new rows means…", ["The model is ready to ship", "The model likely memorized the training set", "The test set is the training set", "The data has no labels"], 1, "A held-out set is how you notice the memorizing."),
  ),
  "xii-security": lesson(
    "Three different jobs",
    "Confidentiality keeps a message from the wrong reader. Encryption serves that job. Integrity means you can tell the message was not changed. A hash of the file serves that job, because a changed file produces a different hash. Availability means the people who should reach it still can. A backup serves that job. One tool does not do all three.",
    "راز داری کے لیے خفیہ کاری، سالمیت کے لیے ہیش، دستیابی کے لیے بیک اپ۔ ایک آلہ تینوں کام نہیں کرتا۔",
    [
      B(24, 70, 140, 64, "secret"),
      B(186, 70, 140, 64, "unchanged", "gold"),
      B(348, 70, 140, 64, "reachable", "teal"),
      T(36, 160, "encrypt"),
      T(200, 160, "hash", "gold"),
      T(360, 160, "backup", "teal"),
    ],
    "Name the job before you name the tool.",
    "Match encryption, hashing, and backup to confidentiality, integrity, and availability.",
    ask("A hash of a file mainly helps you check…", ["That strangers cannot read it", "That the file was not changed", "That the server is fast", "That the password is long"], 1, "A changed file will not produce the same hash. Encryption is the secrecy tool."),
  ),
  "xii-venture": lesson(
    "The user may not be the buyer",
    "A user is the person who touches the product. A customer is the person who pays. In a school canteen app the student is the user and the school, or the canteen owner, may be the customer. If you only interview users, you can build something the buyer will not fund. Talk to both, and write down which person you mean.",
    "صارف چھوتا ہے، گاہک ادا کرتا ہے۔ کینٹین ایپ میں طالب علم صارف ہے اور مالک گاہک ہو سکتا ہے۔ دونوں سے بات کرو۔",
    [
      C(140, 90, 36, ""),
      C(360, 90, 36, "", "gold"),
      T(110, 150, "uses it"),
      T(320, 150, "pays", "gold"),
      D(360, 48, "gold"),
    ],
    "The gold dot is the payment. It does not have to sit on the same person.",
    "Distinguish the user of a product from the customer who pays.",
    ask("In a school app the student is often…", ["Automatically the paying customer", "The user, while someone else may pay", "Neither", "The database"], 1, "Use and payment can belong to different people."),
  ),
  "xii-mvp": lesson(
    "One belief, small enough to fail",
    "An MVP is the smallest thing that can prove or kill the riskiest belief. If the belief is that students will check a screen before they walk to the canteen, a paper list on the door can test it. Extra screens do not strengthen that test. They delay the day you find out the belief was false.",
    "ایم وی پی سب سے چھوٹی چیز ہے جو خطرناک مفروضے کو جھٹلا سکے۔ اضافی اسکرینیں جواب دیر سے دیتی ہیں۔",
    [
      B(30, 70, 160, 56, "one belief", "gold"),
      B(250, 40, 110, 40, "screen 2"),
      B(250, 90, 110, 40, "screen 3"),
      B(250, 140, 110, 40, "screen 4"),
      L(246, 36, 370, 184, "gold"),
    ],
    "The strike is the work that does not test the belief.",
    "Define an MVP as a test of one belief.",
    ask("An MVP should be small so that…", ["It cannot fail", "A false belief is found quickly", "Investors see every feature", "Testing can be skipped"], 1, "The point of small is a fast, honest failure."),
  ),
};

export function applyDepth(lectures) {
  for (const lecture of lectures) {
    const extra = DEPTH[lecture.id];
    if (!extra) continue;
    lecture.beats.push(extra.beat);
    if (Array.isArray(lecture.outcomes)) lecture.outcomes.push(extra.outcome);
    if (Array.isArray(lecture.quiz) && lecture.quiz.length >= 3) lecture.quiz[2] = extra.quiz;
  }
}

export const depthIds = Object.keys(DEPTH);
