/** Worked example, exam trap, recap sheet, and a drill for every lecture. */

export const ROLE_LABEL = {
  idea: "Idea",
  depth: "Deeper rule",
  example: "Worked example",
  trap: "Watch the trap",
  recap: "Exam sheet",
};

export const ROLE_ORDER = ["idea", "depth", "example", "trap", "recap"];

function beat(title, say, sayUr, scene, role) {
  return { title, say, sayUr, scene, role };
}

function pack({
  exampleTitle, exampleSay, exampleSayUr, problem, steps, exampleNote,
  trapTitle, trapSay, trapSayUr, wrong, right, fix,
  recapTitle, recapSay, recapSayUr, lines, formula, sayThis,
  drillQ, drillReveal, quizTraps,
}) {
  return {
    worked: beat(exampleTitle, exampleSay, exampleSayUr, {
      type: "steps", title: exampleTitle, problem, steps, note: exampleNote,
    }, "example"),
    trap: beat(trapTitle, trapSay, trapSayUr, {
      type: "trap", title: trapTitle, wrong, right, note: fix,
    }, "trap"),
    recap: beat(recapTitle, recapSay, recapSayUr, {
      type: "sheet", title: recapTitle, lines, formula, sayThis,
    }, "recap"),
    sheet: { lines, formula, sayThis },
    drill: { q: drillQ, reveal: drillReveal },
    quizTraps,
  };
}

const MASTERY = {
  "xi-digital": pack({
    exampleTitle: "Label three measurements",
    exampleSay: "A register stores absences, a thermometer reading, and a saved temperature of 36. Absences are discrete: 0, 1, 2. The live thermometer is continuous. The saved 36 is already a digital sample. The computer never kept the ramp. It kept a step.",
    exampleSayUr: "غیر حاضری گنی جاتی ہے۔ تھرمامیٹر مسلسل ہے۔ فائل میں 36 ایک نمونہ ہے، ریمپ نہیں۔",
    problem: "Absences = 3. Live water = $36.41^{\\circ}\\mathrm{C}$. File stores $36$.",
    steps: [
      { do: "Absences are discrete.", why: "You can count them one by one." },
      { do: "The live reading is continuous.", why: "It can sit anywhere in a range." },
      { do: "The stored $36$ is a sample.", why: "The file holds an allowed level, not the ramp." },
    ],
    exampleNote: "Name the quantity first. Then say whether a machine stored it.",
    trapTitle: "Smooth is not continuous",
    trapSay: "A 16-bit song can sound smooth and still be discrete. Digital never means the value is better. It means the value was forced onto allowed steps. Extra bits shrink the gap. They do not bring the ramp back.",
    trapSayUr: "ہموار آواز بھی بٹس ہو سکتی ہے۔ ڈیجیٹل کا مطلب بہتر نہیں، سطحوں پر مجبور ہونا ہے۔",
    wrong: "If it sounds smooth, the file must be continuous.",
    right: "Smooth to the ear can still be a staircase of bits.",
    fix: "Ask what the machine is allowed to store, not how it feels.",
    recapTitle: "Discrete, continuous, bit",
    recapSay: "Write four lines. Discrete quantities can be counted. Continuous quantities can sit anywhere in a range. A bit is 0 or 1. A digital file stores samples, not the original ramp.",
    recapSayUr: "متفرق گنی جاتی ہے۔ مسلسل حد میں کوئی بھی قیمت۔ بٹ صفر یا ایک۔ فائل نمونہ رکھتی ہے۔",
    lines: [
      "Discrete: countable steps, such as students.",
      "Continuous: any value in a range, such as temperature.",
      "A bit is one binary digit, $0$ or $1$.",
      "Extra bits make finer steps. They do not restore a ramp.",
    ],
    formula: "$b \\in \\{0, 1\\}$",
    sayThis: "The world can flow. The file is steps.",
    drillQ: "Is the number of unread emails discrete or continuous?",
    drillReveal: "Discrete. You can count them. An unread count of 4.7 is not a real mailbox.",
    quizTraps: [
      "Temperature and speed feel like numbers, so they look countable. They are not stairs.",
      "A bit is not a language or a cable. It is one 0 or one 1.",
      "Extra bits do not undo rounding. They only pack the stairs closer.",
    ],
  }),
  "xi-signals": pack({
    exampleTitle: "Three voltages, one bit",
    exampleSay: "A receiver uses threshold 0.25. It sees 0.41, then 0.44, then 0.39. All three sit above the line, so all three are read as 1. The analog heights are thrown away. Only the side of the line is kept.",
    exampleSayUr: "حد 0.25 ہے۔ تین وولٹیج سب اوپر ہیں، اس لیے تینوں ایک پڑھے جاتے ہیں۔",
    problem: "Threshold $= 0.25$. Samples: $0.41$, $0.44$, $0.39$.",
    steps: [
      { do: "Draw the threshold.", why: "That line is the only question." },
      { do: "Place each sample.", why: "All three sit above $0.25$." },
      { do: "Write the bits $1,1,1$.", why: "Exact height is discarded." },
    ],
    exampleNote: "The bit flips only if a sample crosses the line.",
    trapTitle: "Digital still changes",
    trapSay: "Digital does not mean the signal is frozen. It still moves through time. It jumps between allowed levels instead of gliding. Analog is not automatically more accurate for storage, because noise becomes part of the stored height.",
    trapSayUr: "ڈیجیٹل رکتی نہیں، چھلانگ لگاتی ہے۔ اینالاگ ذخیرہ شور کو قیمت بنا دیتا ہے۔",
    wrong: "Digital means the voltage never changes.",
    right: "Digital jumps between levels as time passes.",
    fix: "Change in time is not the same as a continuous height.",
    recapTitle: "Analog versus digital",
    recapSay: "Analog is a smooth curve. Digital is allowed levels, HIGH for 1 and LOW for 0. Small noise is ignored when it stays on one side of the threshold.",
    recapSayUr: "اینالاگ ہموار۔ ڈیجیٹل سطحیں۔ حد کے ایک طرف شور نظر انداز۔",
    lines: [
      "Analog: any height, a smooth wave.",
      "Digital: HIGH $= 1$, LOW $= 0$.",
      "Noise on analog becomes the value.",
      "Noise on digital is ignored until it crosses the threshold.",
    ],
    formula: "bit $= 1$ if $v > T$, else $0$",
    sayThis: "The receiver asks which side of the line, not how tall.",
    drillQ: "A sample sits just below the threshold. What bit is stored?",
    drillReveal: "0. Below the line is LOW, even if the voltage looks 'almost HIGH'.",
    quizTraps: [
      "Digital jumps, so it feels discontinuous. The smooth one is analog.",
      "HIGH is the 1 level, not 0.",
      "Ignoring noise is not 'the voltage never moves'. It is 'the wiggle stayed on one side'.",
    ],
  }),
  "xi-boolean": pack({
    exampleTitle: "Evaluate one expression",
    exampleSay: "Work Y equals A AND B, then OR with NOT A, when A is 0 and B is 1. AND needs both 1, so that part is 0. NOT of 0 is 1. Then 0 OR 1 is 1. Write the inner results before the last operation.",
    exampleSayUr: "اے صفر، بی ایک۔ این ڈی صفر، ناٹ اے ایک، او آر ایک۔",
    problem: "$Y = (A \\cdot B) + \\overline{A}$, with $A=0$, $B=1$.",
    steps: [
      { do: "$A \\cdot B = 0 \\cdot 1 = 0$.", why: "AND is 1 only when both inputs are 1." },
      { do: "$\\overline{A} = \\overline{0} = 1$.", why: "NOT flips the bit." },
      { do: "$Y = 0 + 1 = 1$.", why: "OR is 1 if any part is 1." },
    ],
    exampleNote: "Parentheses first, then NOT, then AND, then OR.",
    trapTitle: "AND is not OR",
    trapSay: "The classic exam slip is treating AND as 'any 1 is enough'. That rule belongs to OR. AND is strict: every input must be 1. If a door has two locks, one open lock still leaves the door shut.",
    trapSayUr: "این ڈی کا مطلب ہر ان پٹ ایک۔ کوئی ایک کافی ہو تو وہ او آر ہے۔",
    wrong: "AND outputs 1 when any input is 1.",
    right: "AND outputs 1 only when every input is 1.",
    fix: "Say 'all' for AND and 'any' for OR, out loud, before you tick.",
    recapTitle: "AND, OR, NOT, table",
    recapSay: "AND is all ones. OR is any one. NOT flips. Two inputs make four truth-table rows because 2 to the power 2 is 4. De Morgan: NOT of AND is OR of the NOTs.",
    recapSayUr: "این ڈی سب۔ او آر کوئی ایک۔ ناٹ الٹ۔ دو ان پٹ، چار قطاریں۔",
    lines: [
      "AND: 1 only if every input is 1.",
      "OR: 1 if any input is 1.",
      "NOT flips one bit.",
      "Rows $= 2^n$. De Morgan: $\\overline{A \\cdot B} = \\overline{A} + \\overline{B}$.",
    ],
    formula: "$Y = (A \\cdot B) + \\overline{A}$",
    sayThis: "All for AND, any for OR, flip for NOT.",
    drillQ: "What is OR of 0 and 0?",
    drillReveal: "0. OR needs at least one 1.",
    quizTraps: [
      "'Any input is 1' is the OR rule. AND waits for all of them.",
      "NOT 1 is 0, not 1.",
      "People copy NOT onto AND and keep AND. The operator itself changes to OR.",
    ],
  }),
  "xi-gates": pack({
    exampleTitle: "Two gates in a row",
    exampleSay: "A is 1 and B is 0. First XOR, then NAND that result with 1. XOR of different bits is 1. NAND of 1 and 1 is 0. The lamp is dark. Trace left to right. Do not jump to the last gate.",
    exampleSayUr: "ایکس او آر مختلف پر ایک۔ پھر نینڈ ایک اور ایک پر صفر۔",
    problem: "$A=1$, $B=0$. Compute $\\mathrm{NAND}(\\mathrm{XOR}(A,B), 1)$.",
    steps: [
      { do: "$\\mathrm{XOR}(1,0)=1$.", why: "Different inputs." },
      { do: "Second input is $1$.", why: "The wire is tied HIGH." },
      { do: "$\\mathrm{NAND}(1,1)=0$.", why: "NAND is 0 only when every input is 1." },
    ],
    exampleNote: "Write each gate's output before feeding the next.",
    trapTitle: "NAND is not a friendly AND",
    trapSay: "NAND is AND followed by NOT. It is 0 only on the row where AND would have been 1. Calling NAND 'almost AND' loses the inversion, and that is exactly the row the exam asks for.",
    trapSayUr: "نینڈ این ڈی کے بعد ناٹ ہے۔ این ڈی والا صف صفر ہو جاتا ہے۔",
    wrong: "NAND is AND, just drawn with a bubble that you can ignore.",
    right: "The bubble is the whole point: invert the AND result.",
    fix: "On the all-1 row, NAND is 0. If you wrote 1, you dropped the NOT.",
    recapTitle: "Seven gates",
    recapSay: "NAND is 0 only when all inputs are 1. NOR is 1 only when all inputs are 0. XOR lights when they differ. XNOR lights when they match. NAND and NOR are universal: either one can build the rest.",
    recapSayUr: "نینڈ سب ایک پر صفر۔ نار سب صفر پر ایک۔ ایکس او آر مختلف۔ یونیورسل نینڈ اور نار۔",
    lines: [
      "NAND: 0 only if all inputs are 1.",
      "NOR: 1 only if all inputs are 0.",
      "XOR: 1 when inputs differ. XNOR: 1 when they match.",
      "Universal: NAND alone, or NOR alone, can build every gate.",
    ],
    formula: "$Y_{\\mathrm{NAND}} = \\overline{A \\cdot B}$",
    sayThis: "Universal means wiring copies of one gate, not fetching a new chip.",
    drillQ: "XOR of 1 and 1?",
    drillReveal: "0. The inputs match, so exclusive OR is off.",
    quizTraps: [
      "AND and OR are basic, not universal. Universal is NAND and NOR.",
      "Matching inputs make XOR 0. People remember 'OR' and write 1.",
      "NAND's 0-row is the AND 1-row. That is all inputs 1, not 'any 0'.",
    ],
  }),
  "xi-kmap": pack({
    exampleTitle: "Group a two-variable map",
    exampleSay: "Cells are 0, 1, 1, 1. Circle the pair that keeps B, then the pair that keeps A. The expression is A OR B. You never circle the single 0. Groups must have 1, 2, 4, or 8 cells.",
    exampleSayUr: "تین ایک کو جوڑ کر اے او آر بی بنتا ہے۔ صفر کو حلقہ نہ لگائیں۔",
    problem: "Map values $[0,1,1,1]$. Find a simplest sum.",
    steps: [
      { do: "Mark the three 1s.", why: "Only 1s, and optional X, may be grouped." },
      { do: "Take the $B$ pair and the $A$ pair.", why: "Each pair is two cells, a legal size." },
      { do: "Write $Y = A + B$.", why: "Each group drops the variable that changes." },
    ],
    exampleNote: "Larger legal groups give fewer terms.",
    trapTitle: "Three is not a group",
    trapSay: "A ring around three 1s looks tidy and is illegal. Group sizes are powers of two so that each ring drops whole variables. If a cell is 0, it cannot join the ring, even if it sits in the middle.",
    trapSayUr: "تین خانوں کا حلقہ غلط ہے۔ سائز دو کی طاقت ہو۔ صفر شامل نہ ہو۔",
    wrong: "Circle every 1 in sight, even if that makes a group of 3.",
    right: "Legal sizes are 1, 2, 4, 8. A 0 never enters a group.",
    fix: "If the ring is not a power of two, split it.",
    recapTitle: "Expressions and K-maps",
    recapSay: "Order is parentheses, NOT, AND, OR. A K-map is Gray code: neighbors differ by one variable. Groups wrap around the edges. Don't-care X may join a group if that makes a larger legal ring.",
    recapSayUr: "ترتیب ناٹ، این ڈی، او آر۔ پڑوسی ایک متغیر۔ ایکس اختیاری ہے۔",
    lines: [
      "Precedence: $(~)$, NOT, AND, OR.",
      "Groups of $1,2,4,8$ ones. Never a 0.",
      "Neighbors, including wrapped edges, differ by one variable.",
      "X is optional. Use it only to grow a legal group.",
    ],
    formula: "$Y = A + B$",
    sayThis: "A legal group is a power of two that covers 1s, and maybe X.",
    drillQ: "Can you group a cell that holds 0 if it helps a rectangle look nice?",
    drillReveal: "No. A 0 is forbidden in every group.",
    quizTraps: [
      "People start with OR because they write left to right. NOT is first.",
      "Any count looks visual. The algebra needs powers of two.",
      "X is not a required 1. Skip it when it does not help.",
    ],
  }),
  "xi-sdlc": pack({
    exampleTitle: "Pick a model",
    exampleSay: "A school app still does not know whether parents or students will log in. Requirements will move. Choose Agile, and still test every sprint. A payroll tax table is law. Requirements are stable. Waterfall can walk the phases once.",
    exampleSayUr: "بدلتی ضرورت پر ایجائل۔ مستحکم قانون پر واٹر فال۔ دونوں میں ٹیسٹ رہتا ہے۔",
    problem: "Project A: login audience unknown. Project B: tax rules fixed in a gazette.",
    steps: [
      { do: "Ask whether the need will move.", why: "That is the fork, not 'modern versus old'." },
      { do: "Project A: Agile sprints.", why: "You will learn who the user is." },
      { do: "Project B: Waterfall is honest.", why: "The rule is already written." },
    ],
    exampleNote: "Testing is a phase in both models.",
    trapTitle: "Agile is not a skipped test",
    trapSay: "Agile repeats a short cycle. It does not delete design or testing. A sprint that ships with no test is just a tiny waterfall missing a phase. Speed without a check is not a method. It is a hole.",
    trapSayUr: "ایجائل ٹیسٹ ہٹاتا نہیں، دہراتا ہے۔ بغیر ٹیسٹ سپرنٹ ادھورا واٹر فال ہے۔",
    wrong: "Agile means skip documents and skip tests so you can ship.",
    right: "Agile repeats the same jobs in a short loop, including tests.",
    fix: "If testing vanished, you are not doing Agile. You are skipping.",
    recapTitle: "Life cycle",
    recapSay: "Name the phases: requirements, design, implementation, testing, then maintain. Waterfall finishes one before the next. Agile slices the same jobs into sprints. Choose Waterfall when the need is stable. Choose Agile when it will move.",
    recapSayUr: "ضرورت، ڈیزائن، بنانا، ٹیسٹ، دیکھ بھال۔ واٹر فال سیدھا۔ ایجائل دہراؤ۔",
    lines: [
      "Phases: need, design, build, test, maintain.",
      "Waterfall: finish one phase before the next.",
      "Agile: the same jobs, in short sprints.",
      "A sprint with no test is a missing phase, not a method.",
    ],
    sayThis: "The model changes the loop. It does not delete testing.",
    drillQ: "Requirements are frozen in a contract. Which model fits more cleanly?",
    drillReveal: "Waterfall. The need is stable, so a single pass through the phases is honest.",
    quizTraps: [
      "People name tools instead of phases. The exam wants the job of each phase.",
      "Changing needs are the Agile signal, not 'we hate paper'.",
      "Agile is repeated phases. Missing test is not the definition.",
    ],
  }),
  "xi-osi": pack({
    exampleTitle: "Wrap the word Hi",
    exampleSay: "The application writes Hi. Each lower layer wraps a header around it. The cable carries the whole bundle. The receiver peels the outer header first, the last one the sender added. Encapsulation is putting on coats. Decapsulation is taking them off in reverse.",
    exampleSayUr: "ہیلو کو تہہ در تہہ لپیٹا جاتا ہے۔ وصول کنندہ سب سے بیرونی تہہ پہلے اتارتا ہے۔",
    problem: "Message = Hi. Sender adds HTTP, then TCP, then IP.",
    steps: [
      { do: "Start with Hi at the application.", why: "That is the payload." },
      { do: "Wrap headers going down.", why: "Each layer adds its own coat." },
      { do: "Receiver peels IP first.", why: "Last on is first off." },
    ],
    exampleNote: "Layer 1 is the wire, not the app.",
    trapTitle: "Layer 1 is not the app",
    trapSay: "Layer 1 is physical bits on a medium. The application is layer 7. Students reverse the stack because 'first' sounds like the user. Numbering starts at the cable and climbs to the person.",
    trapSayUr: "پہلی تہہ تار ہے۔ ساتویں تہہ ایپ ہے۔ گنتی کیبل سے اوپر جاتی ہے۔",
    wrong: "Layer 1 is the app, because the user starts there.",
    right: "Layer 1 is physical. Layer 7 is the application.",
    fix: "Write Physical at the bottom of your answer booklet before you number anything.",
    recapTitle: "OSI and TCP/IP",
    recapSay: "Seven OSI layers. Encapsulation wraps going down. The receiver peels the outer header first. TCP/IP is the stack that networks actually run. OSI is the teaching map.",
    recapSayUr: "سات تہہ۔ نیچے جاتے لپیٹیں۔ اوپر آتے اتاریں۔ اصل اسٹیک ٹی سی پی آئی پی۔",
    lines: [
      "OSI has 7 layers. Layer 1 is physical.",
      "Going down: add a header. That is encapsulation.",
      "Coming up: peel the outer header first.",
      "TCP/IP is the deployed stack. OSI is the map.",
    ],
    sayThis: "Last header on is the first header off.",
    drillQ: "Which OSI layer is a copper cable?",
    drillReveal: "Layer 1, physical. It carries bits, not application words.",
    quizTraps: [
      "People describe a company, not a layer job.",
      "TCP/IP collapsing layers does not delete the physical wire.",
      "The receiver does not replay the sender's order. It peels the outside first.",
    ],
  }),
  "xi-ct": pack({
    exampleTitle: "Attendance in three moves",
    exampleSay: "Taking attendance: decompose into collect names, mark present, total absences. The pattern is the same every period. Abstraction is a trusted step named mark(name). You do not rewrite the loop in every sentence. You name the piece and hide its insides.",
    exampleSayUr: "حاضری: توڑو، دہراؤ پہچانو، مارک نام رکھ دو۔ اندر چھپا رہے۔",
    problem: "Task: mark who is in the lab.",
    steps: [
      { do: "Decompose.", why: "Names, mark, total." },
      { do: "Spot the pattern.", why: "Every period repeats those steps." },
      { do: "Abstract $\\mathrm{mark}(name)$.", why: "Callers need the result, not the loop." },
    ],
    exampleNote: "An algorithm is the steps. Pseudocode is those steps in words.",
    trapTitle: "Abstract is not vague",
    trapSay: "Abstraction is not woolly writing. It is hiding a solved piece behind a name. If you still describe every loop, you have not abstracted. If you skip testing because 'it is abstract', you have only skipped.",
    trapSayUr: "تجرید دھند نہیں۔ حل شدہ ٹکڑے کا نام ہے۔ لوپ چھپتا ہے، ٹیسٹ نہیں۔",
    wrong: "Abstraction means stay vague so the examiner cannot catch you.",
    right: "Abstraction means name a trusted piece and hide its insides.",
    fix: "If you cannot point to the hidden piece, you only shortened the sentence.",
    recapTitle: "Computational thinking",
    recapSay: "Decompose the job. Reuse the pattern. Abstract by naming a piece. An algorithm is a finite list of steps. Pseudocode writes those steps without a compiler.",
    recapSayUr: "توڑو، پیٹرن دیکھو، نام رکھو۔ الگورتھم قدم ہیں۔ سیوڈو کوڈ الفاظ میں وہ قدم۔",
    lines: [
      "Decomposition: split the job.",
      "Pattern: reuse the shape that repeats.",
      "Abstraction: name a trusted piece and hide its insides.",
      "Algorithm: finite steps. Pseudocode: those steps in words.",
    ],
    sayThis: "Split, reuse, then name the piece you no longer open.",
    drillQ: "Is 'sort the list somehow' an algorithm?",
    drillReveal: "No. An algorithm must be a finite, definite sequence of steps, not a wish.",
    quizTraps: [
      "People list programming languages instead of the thinking moves.",
      "Pseudocode is not Python. It is steps in words.",
      "Abstraction hides insides. It does not mean 'write every loop'.",
    ],
  }),
  "xi-sort": pack({
    exampleTitle: "One bubble pass",
    exampleSay: "List 3, 1, 2. Compare 3 and 1, swap. Now 1, 3, 2. Compare 3 and 2, swap. Now 1, 2, 3. One pass only guarantees the largest value reached the end. A second pass would be needed if the front were still unsorted.",
    exampleSayUr: "ایک پاس سب سے بڑا آخر میں بھیجتا ہے۔ پوری فہرست تب تک نہیں سنورتی۔",
    problem: "One bubble pass on $[3,1,2]$.",
    steps: [
      { do: "Compare $3$ and $1$, swap.", why: "Out of order." },
      { do: "Compare $3$ and $2$, swap.", why: "Out of order." },
      { do: "End of pass: $[1,2,3]$.", why: "The largest has arrived at the end. Here the rest is already tidy." },
    ],
    exampleNote: "Do not claim 'sorted' after pass one unless you checked the rest.",
    trapTitle: "One pass is not sorted",
    trapSay: "Bubble sort's first pass parks the largest at the end. The front can still be messy. Selection sort parks the smallest at the front, one slot per pass. Both cost about n squared comparisons on a large list.",
    trapSayUr: "پہلا پاس فہرست مکمل نہیں کرتا۔ لاگت تقریبا این مربع۔",
    wrong: "After one bubble pass the whole list is sorted.",
    right: "One pass only places one extreme. The rest may still be unsorted.",
    fix: "Ask which position is guaranteed, not whether you feel done.",
    recapTitle: "Bubble and selection",
    recapSay: "Bubble swaps neighbors. Selection finds the minimum and puts it in the next slot. Both are quadratic. A stable sort keeps equal keys in the order they arrived.",
    recapSayUr: "ببل پڑوسی بدلتا ہے۔ سلیکشن کم سے کم ڈھونڈتا ہے۔ دونوں این مربع۔",
    lines: [
      "Bubble: swap adjacent if out of order.",
      "Selection: find min, place it, repeat.",
      "Cost on large $n$: about $n^2$ comparisons.",
      "Stable: equal keys keep their arrival order.",
    ],
    formula: "comparisons $\\approx n^2$",
    sayThis: "One pass parks one value. The algorithm is the repeated passes.",
    drillQ: "After pass one of selection sort on [4, 1, 3], what sits at index 0?",
    drillReveal: "1. Selection puts the current minimum into the first unsorted slot.",
    quizTraps: [
      "People describe merge sort. This lecture is bubble and selection.",
      "Selection does not swap neighbors down the list. It searches for the min.",
      "Stability is arrival order of equals, not 'the list is already sorted'.",
    ],
  }),
  "xi-search": pack({
    exampleTitle: "Find 7",
    exampleSay: "Sorted list 1, 3, 7, 9. Linear search would check 1, then 3, then 7. Binary search checks the middle 3, then throws away the left half, then lands on 7. Binary search is legal only because the list is sorted. The invariant is that the target, if present, stays between low and high.",
    exampleSayUr: "لکیری ایک ایک کر کے۔ بائنری درمیان سے کاٹتی ہے، بشرطیکہ ترتیب ہو۔",
    problem: "Find $7$ in $[1,3,7,9]$.",
    steps: [
      { do: "Mid is $3$.", why: "Low $0$, high $3$, mid index $1$." },
      { do: "$7 > 3$, drop the left.", why: "The target cannot sit in the discarded half." },
      { do: "New mid is $7$. Found.", why: "low and high still bracket the target." },
    ],
    exampleNote: "If the list is unsorted, binary search can walk away from the target.",
    trapTitle: "Unsorted binary search",
    trapSay: "Binary search on a jumble is not a faster linear search. It is a wrong algorithm. The midpoint only tells you which half to keep when order is trustworthy. Linear search is the honest choice on unsorted data.",
    trapSayUr: "بغیر ترتیب بائنری غلط ہے۔ اُس وقت لکیری ایماندار ہے۔",
    wrong: "Binary search is always faster, so always use it.",
    right: "Binary search needs sorted data. Otherwise use linear search.",
    fix: "Write the precondition 'sorted' before you write 'mid'.",
    recapTitle: "Linear and binary",
    recapSay: "Linear checks items one by one and works on any list. Binary halves a sorted list. After a correct step the target, if it exists, is still between low and high.",
    recapSayUr: "لکیری ہر فہرست۔ بائنری صرف ترتیب شدہ۔ ہدف لو اور ہائی کے بیچ رہے۔",
    lines: [
      "Linear: check one by one. Any order.",
      "Binary: check the middle of a sorted list.",
      "Precondition for binary: the data is sorted.",
      "Invariant: the target stays between low and high.",
    ],
    formula: "mid $= \\lfloor (low + high) / 2 \\rfloor$",
    sayThis: "Halving only works when order tells you which half to throw away.",
    drillQ: "Can binary search find 4 in [4, 1, 9, 2]?",
    drillReveal: "You must not trust it. The list is unsorted, so the midpoint can discard the 4.",
    quizTraps: [
      "Linear works on unsorted data. That is its job, not a weakness only.",
      "Mid is an index computed from low and high, not 'the value 2'.",
      "A correct step never throws away the half that still might hold the target.",
    ],
  }),
  "xi-eval": pack({
    exampleTitle: "Ten names or ten thousand",
    exampleSay: "Finding a name in ten rows: a linear scan is clear and cheap. Finding a name in ten thousand: pay to sort once, then binary search, or pay memory for a lookup table. Correctness comes first. Then you spend time, memory, or clarity. You cannot maximise all three.",
    exampleSayUr: "دس ناموں پر سیدھی تلاش۔ دس ہزار پر ترتیب یا جدول کا خرچ۔",
    problem: "Lookup in $n=10$ versus $n=10\\,000$.",
    steps: [
      { do: "For $n=10$, scan.", why: "The simple loop is already fast enough." },
      { do: "For $n=10\\,000$, consider binary search.", why: "You must sort, or keep the list sorted." },
      { do: "A table is faster still, and costs memory.", why: "You spend one resource to save another." },
    ],
    exampleNote: "A fast algorithm that needs sorted data is wrong if you do not have it.",
    trapTitle: "Fastest is not always right",
    trapSay: "The exam loves a trick: the quadratic method is the one you can run, because the fancy method needs extra memory or sorted input you do not have. Efficiency without correctness is a wrong program. Clarity matters when a classmate must maintain it.",
    trapSayUr: "تیز الگورتھم غلط ہے اگر ڈیٹا اس کے شرط پر پورا نہ اترے۔",
    wrong: "Always pick the asymptotically fastest algorithm.",
    right: "Pick the algorithm that is correct for your data, then weigh time, memory, and clarity.",
    fix: "Name the data you actually have before you name Big O.",
    recapTitle: "Choosing an algorithm",
    recapSay: "Judge correctness first, then time, memory, and clarity. Constant-time lookup usually costs extra memory. Quadratic is still fine on tiny n. Reject a fast method whose preconditions you cannot meet.",
    recapSayUr: "پہلے درستی۔ پھر وقت، یاد، صفائی۔ شرط پوری نہ ہو تو تیز طریقہ رد۔",
    lines: [
      "Correct first. Then time, memory, clarity.",
      "You spend one of those to save another.",
      "Fast methods often need sorted data or extra tables.",
      "Tiny $n$ can make a simple loop the right loop.",
    ],
    sayThis: "The best algorithm is the one your data and your people can actually run.",
    drillQ: "You have 8 unsorted marks. Should you binary-search for 9?",
    drillReveal: "No. Sort first, or just scan. Eight comparisons are cheaper than a wrong midpoint.",
    quizTraps: [
      "Clarity is a real criterion, not decoration.",
      "The questions start with the data you have.",
      "Constant-time lookup is paid for with a table in memory, not with magic.",
    ],
  }),
  "xi-python": pack({
    exampleTitle: "Rebind versus alias",
    exampleSay: "x is 2. y is x. Then y is 5. x is still 2, because the name y now points at a new integer. Now a is a list. b is a. Append through b, and a changes too. Assignment copies the name. For a list, both names stick to one object.",
    exampleSayUr: "عدد نیا نام نئی چیز۔ فہرست کا نام بدلنا اصل چیز شیئر کرتا ہے۔",
    problem: "$x=2$; $y=x$; $y=5$. Then $a=[1]$; $b=a$; $b.append(9)$.",
    steps: [
      { do: "After $y=5$, $x$ is still $2$.", why: "Integers were rebound, not edited." },
      { do: "$b=a$ labels the same list.", why: "No copy of the items." },
      { do: "$a$ becomes $[1, 9]$.", why: "Append went through the shared object." },
    ],
    exampleNote: "Ask: new object, or the same object under two names?",
    trapTitle: "Equals always copies",
    trapSay: "Beginners think equals duplicates every value. For a list it aliases. Later they debug 'how did a change?' and never look at b. If you need a second list, slice it: a colon inside brackets copies the items.",
    trapSayUr: "برابر ہمیشہ کاپی نہیں۔ فہرست پر دو نام ایک چیز۔ کاپی کے لیے سلائس۔",
    wrong: "$b = a$ always makes an independent copy.",
    right: "For a list, $b = a$ is two names on one list.",
    fix: "If you mutate through one name, check every other name that was set equal.",
    recapTitle: "Names, types, input",
    recapSay: "A variable is a name. Types such as int and str decide what the object can do. input reads text. print writes. Integer assignment rebinds. List assignment shares. Operators compare, compute, and combine.",
    recapSayUr: "متغیر نام ہے۔ ان پٹ متن۔ فہرست شیئر۔ عدد نیا بندھن۔",
    lines: [
      "A variable is a name bound to an object.",
      "int assignment rebinds. List assignment aliases.",
      "input() returns text. Cast if you need a number.",
      "Need a second list? Copy with a slice, not with $=$ alone.",
    ],
    formula: "$b = a$  (same list)",
    sayThis: "Ask whether you rebound a name or mutated a shared object.",
    drillQ: "After a = [2]; b = a; b[0] = 8; what is a[0]?",
    drillReveal: "8. Both names point at one list.",
    quizTraps: [
      "A program is not an IDE. The IDE is the workshop around it.",
      "input returns a string until you convert it.",
      "Appending through b changes a when they name one list.",
    ],
  }),
  "xi-control": pack({
    exampleTitle: "range stops early",
    exampleSay: "for i in range(1, 4) binds i to 1, then 2, then 3. It never binds 4. The stop value is the first number you do not want. A while loop keeps going while the condition is true. An if elif else chain runs one branch.",
    exampleSayUr: "رینج کا آخری ہندسہ شامل نہیں۔ ون برانچ چلتی ہے۔",
    problem: "What does $\\texttt{range}(1, 4)$ produce?",
    steps: [
      { do: "Start at $1$.", why: "The first argument is included." },
      { do: "Next is $2$, then $3$.", why: "Step $+1$ by default." },
      { do: "Stop before $4$.", why: "The stop is excluded." },
    ],
    exampleNote: "range(4) is 0, 1, 2, 3. Still no 4.",
    trapTitle: "The included 4",
    trapSay: "Students write range(1, 4) and expect 1 through 4. That off-by-one is the most common loop bug in the paper. Nested loops multiply work: an inner loop over n inside an outer loop over n is n squared visits.",
    trapSayUr: "رینج کا وقفہ شامل نہیں۔ اندر والا لوپ ضرب لگاتا ہے۔",
    wrong: "range(1, 4) yields 1, 2, 3, 4.",
    right: "range(1, 4) yields 1, 2, 3.",
    fix: "Read the stop as 'until, not through'.",
    recapTitle: "Branch and loop",
    recapSay: "if, elif, else pick one path. for walks a known sequence. while walks until a condition fails. Nested means a loop inside a loop. range excludes its stop.",
    recapSayUr: "ایک راہ۔ فار معلوم گنتی۔ وائل شرط۔ رینج رُک کر۔",
    lines: [
      "if / elif / else: one branch runs.",
      "for: known sequence. while: unknown count, a condition.",
      "Nested loop: inner work times outer work.",
      "$\\texttt{range}(a, b)$ is $a \\ldots b-1$.",
    ],
    formula: "$\\texttt{range}(1, 4) = 1, 2, 3$",
    sayThis: "The stop in range is the first value you do not get.",
    drillQ: "How many times does for i in range(0, 5) run?",
    drillReveal: "Five times: 0, 1, 2, 3, 4.",
    quizTraps: [
      "elif is not a second if that always runs. It is the next try in one chain.",
      "while needs a condition that can become false, or it never stops.",
      "People include the stop because the comma looks like a closed interval.",
    ],
  }),
  "xi-debug": pack({
    exampleTitle: "Read from the bottom",
    exampleSay: "The last line says TypeError, then a file and a line number. That is where you start. The frames above it are the calls that led there. A syntax error never runs. A runtime error blows up while running. A logic error runs and gives the wrong answer.",
    exampleSayUr: "ٹریس بیک نیچے سے پڑھو۔ قسم، لائن، پھر اوپر کی کال۔",
    problem: "Traceback ends: TypeError: ... file lab.py, line 4.",
    steps: [
      { do: "Read the last line first.", why: "It names the exception." },
      { do: "Note $\\texttt{lab.py}$ line $4$.", why: "That is the location in your code." },
      { do: "Then read the callers above.", why: "They explain how you got there." },
    ],
    exampleNote: "Library frames can sit in the middle. Your file is the one you can edit.",
    trapTitle: "Starting at the top",
    trapSay: "The top of a traceback is often import machinery. Starting there wastes the attempt. Logic errors are worse than crashes because nothing explodes. Tests and print of actual versus expected catch those.",
    trapSayUr: "اوپر سے شروع نہ کرو۔ لاجک ایرر چلتا ہے اور غلط جواب دیتا ہے۔",
    wrong: "Begin at the first line of the traceback and rewrite imports.",
    right: "Begin at the last line: the exception and its location.",
    fix: "Bottom first, always. Then climb only as far as you need.",
    recapTitle: "Errors and tracebacks",
    recapSay: "Syntax: the program never starts. Runtime: it starts and then crashes. Logic: it finishes with the wrong answer. Tracebacks are read from the bottom. Built-in tools come with Python. Third-party tools are installed.",
    recapSayUr: "سنٹیکس، رن ٹائم، لاجک۔ ٹریس بیک نیچے سے۔",
    lines: [
      "Syntax: never runs. Runtime: crashes. Logic: wrong answer.",
      "Traceback: last line first.",
      "That line is the error type and the location.",
      "Built-in versus installed libraries are different sources.",
    ],
    sayThis: "Crash at the bottom. Wrong answer is a logic error that did not crash.",
    drillQ: "The program prints 8 when the spec says 9, and it does not crash. Which error?",
    drillReveal: "Logic error. It ran. The answer is wrong.",
    quizTraps: [
      "A library is not an error type.",
      "Runtime is a crash during the run, not a spelling error in the source.",
      "The first import line is rarely the exception. The last line is.",
    ],
  }),
  "xi-db": pack({
    exampleTitle: "Join on 17",
    exampleSay: "Student 17 is Ali. A marks row stores student_id 17 and score 90. You do not write Ali on every marks row. Names duplicate and misspell. The foreign key is a promise that 17 exists in Student. Join on that id when you need the name.",
    exampleSayUr: "نمبر سترہ علی ہے۔ نمبرز کی قطار میں نام نہیں، کلید ہے۔",
    problem: "Student$(17, \\text{Ali})$. Marks$(17, 90)$. Show who scored 90.",
    steps: [
      { do: "Keep the id in Marks.", why: "The name is not unique." },
      { do: "Join $\\text{Marks.student\\_id} = \\text{Student.id}$.", why: "That is the foreign key." },
      { do: "Read Ali, 90.", why: "The name comes from Student at query time." },
    ],
    exampleNote: "A primary key uniquely names a row. A foreign key points at one.",
    trapTitle: "Store the name everywhere",
    trapSay: "Copying Ali into every related table looks simple and breaks as soon as Ali is spelled two ways. The database cannot promise that 'Aly' is the same person. Store the id. Display the name by joining.",
    trapSayUr: "نام دہرانے سے تعلق ٹوٹتا ہے۔ آئی ڈی کا وعدہ رہتا ہے۔",
    wrong: "Put the student's name on every marks row so you never join.",
    right: "Store the primary key as a foreign key, then join when you need the name.",
    fix: "If a value can be spelled two ways, it is a terrible key.",
    recapTitle: "Tables and keys",
    recapSay: "Data is raw. A database is organised data plus a DBMS. A table has records and fields. A primary key uniquely identifies a row. A foreign key is a promise pointing at that key.",
    recapSayUr: "ڈیٹا خام۔ ڈیٹابیس منظم۔ پرائمری کلید منفرد۔ فارن کلید وعدہ۔",
    lines: [
      "Data versus a database versus a DBMS.",
      "Table: records (rows) and fields (columns).",
      "Primary key: unique, stable, never 'the name' if names collide.",
      "Foreign key: stores that id, and the DBMS can refuse orphans.",
    ],
    formula: "Marks.student_id $\\to$ Student.id",
    sayThis: "The id is the promise. The name is a field you look up.",
    drillQ: "Two students are named Sara. What should a Marks row store?",
    drillReveal: "Each Sara's primary key, not the letters S-a-r-a.",
    quizTraps: [
      "A database is not one field. It is organised related data.",
      "A DBMS is software that manages the database.",
      "A loan row should not store a name that can collide. It stores the key.",
    ],
  }),
  "xi-er": pack({
    exampleTitle: "Students and courses",
    exampleSay: "A student takes many courses. A course has many students. That many-to-many does not live in Student or in Course. It lives in a bridge, Enrollment, with two foreign keys. Each Enrollment row is one pair. Referential integrity refuses a row that points at a missing student.",
    exampleSayUr: "بہت سے سے بہت سے جوڑے کی جدول مانگتے ہیں۔",
    problem: "Student $\\leftrightarrow$ Course.",
    steps: [
      { do: "Name the pair Enrollment.", why: "Each side has many." },
      { do: "Two foreign keys.", why: "student_id and course_id." },
      { do: "Integrity: both ids must exist.", why: "No orphan pairs." },
    ],
    exampleNote: "One-to-many: the foreign key sits on the many side.",
    trapTitle: "A line with no table",
    trapSay: "Drawing a many-to-many as a single line looks clean and has nowhere to store a grade or a year. The pair needs its own rows. Without the bridge you start repeating student rows or course rows, and keys stop meaning one thing.",
    trapSayUr: "بغیر پل جدول کے جوڑا نہیں سماتا۔ قطاریں دہراؤ سے بگڑتی ہیں۔",
    wrong: "Many-to-many is just a line between two boxes.",
    right: "Many-to-many needs a bridge table for the pairs.",
    fix: "If you need to store a fact about the pair, you already need the extra table.",
    recapTitle: "Entities and relationships",
    recapSay: "An entity is a noun you store. A relationship is a verb. Cardinality is one-to-one, one-to-many, or many-to-many. Many-to-many needs a bridge. Referential integrity keeps pointers honest.",
    recapSayUr: "وجود اسم۔ تعلق فعل۔ کثرت۔ پل جدول۔ سالمیت۔",
    lines: [
      "Entity: a noun. Relationship: a verb.",
      "1-1, 1-M, M-M. Foreign key sits on the many side.",
      "M-M: a bridge table holds the pairs.",
      "Referential integrity: a pointer must match a real key.",
    ],
    sayThis: "The pair is a fact. Facts that need fields need a table.",
    drillQ: "Author and Book, if a book can have several authors?",
    drillReveal: "Many-to-many. Add a WrittenBy (or similar) bridge with two ids.",
    quizTraps: [
      "An attribute is a property, not a second copy of the entity.",
      "One-to-many puts the key on the many side, not 'a line in the middle'.",
      "Without a Loan-like table, you are forced to repeat rows.",
    ],
  }),
  "xi-queries": pack({
    exampleTitle: "Filter, then average",
    exampleSay: "You want the average mark in section B. Keep section B rows first, then average. If you average every section and then glance at B, you answered a different question. Charts fail the same way: a pretty pie of twenty tiny slices does not compare sections. A bar does.",
    exampleSayUr: "پہلے بی سیکشن رکھو، پھر اوسط۔ ترتیب سوال بدل دیتی ہے۔",
    problem: "Average mark for section B only.",
    steps: [
      { do: "Filter section $= B$.", why: "Those are the only rows in the question." },
      { do: "Then average the mark.", why: "The filter already chose the population." },
      { do: "A bar chart can compare sections.", why: "Each bar is one group." },
    ],
    exampleNote: "Group, then total, is a different sentence from filter, then total.",
    trapTitle: "Pretty chart, wrong question",
    trapSay: "Choosing a chart because it looks busy is how marks vanish. Pie is for a few parts of one whole. Line is change over time. Histogram is distribution. Scatter is relationship. Bar is comparison. If the question is 'which section is higher', draw bars.",
    trapSayUr: "چارٹ سوال کے لیے ہو، خوبصورتی کے لیے نہیں۔",
    wrong: "Any chart is fine if the numbers are on it somewhere.",
    right: "The chart type is part of the answer. It must match the question.",
    fix: "Say the question in one clause, then pick the picture that asks it.",
    recapTitle: "Queries and charts",
    recapSay: "A query asks. A filter keeps rows. A group total summarises. Filter before you average a subset. Match the chart to the question, not to decoration.",
    recapSayUr: "استفسار پوچھتا ہے۔ فلٹر قطار رکھتا ہے۔ گروپ خلاصہ۔ چارٹ سوال سے۔",
    lines: [
      "Query: a question to the tables.",
      "Filter, then aggregate, when the subset matters.",
      "Bar: compare. Line: over time. Pie: few parts of a whole.",
      "Histogram: distribution. Scatter: relationship.",
    ],
    sayThis: "Change the order of filter and group, and you change the question.",
    drillQ: "You need the total of A grades in one city. Filter city first, or group all cities first?",
    drillReveal: "Filter the city, then count A grades. Otherwise other cities enter the total.",
    quizTraps: [
      "A form is for entering. A report is for presenting. A query is for asking.",
      "Group totals without a filter answer a wider question.",
      "Average-then-delete is not the same as keep-then-average.",
    ],
  }),
  "xi-impacts": pack({
    exampleTitle: "Ice cream and drowning",
    exampleSay: "Ice cream sales and drowning both rise in summer. The chart correlates. Heat is a hidden cause. AI that sees the two lines can still be wrong about policy. Assistive technology is a different claim: a screen reader helps a person finish a task. Accuracy is not the same as fairness.",
    exampleSayUr: "دو لکیریں ساتھ اٹھیں تو سبب نہیں۔ گرمی چھپی وجہ ہو سکتی ہے۔",
    problem: "Two rising lines: ice cream, drowning.",
    steps: [
      { do: "Name the correlation.", why: "Both go up together." },
      { do: "Refuse cause.", why: "A third factor can drive both." },
      { do: "Ask what you would change.", why: "Banning ice cream would not save swimmers." },
    ],
    exampleNote: "IoT is things on a network. Analytics is asking the pile of readings.",
    trapTitle: "The model was accurate",
    trapSay: "Training accuracy is not a moral certificate. A system can score well and still shut a group out. Correlation is a pattern. Cause needs a mechanism and a test. Do not let a confident dashboard replace that.",
    trapSayUr: "درستگی انصاف نہیں۔ تعلق سبب نہیں۔",
    wrong: "If two lines rise together, the first caused the second.",
    right: "Rising together is correlation. Cause needs more evidence.",
    fix: "Write 'pattern' until you can name the mechanism.",
    recapTitle: "AI, IoT, and impacts",
    recapSay: "AI finds patterns from examples. IoT connects objects. Analytics asks questions of data. Assistive tools widen access. Correlation is not cause. A source can be primary or secondary, and biased either way.",
    recapSayUr: "اے آئی پیٹرن۔ آئی او ٹی چیزیں۔ تعلق سبب نہیں۔",
    lines: [
      "AI: learn patterns from examples.",
      "IoT: objects on a network. Analytics: questions to the readings.",
      "Correlation $\\neq$ cause.",
      "Assistive technology is judged by whether a person can finish the task.",
    ],
    sayThis: "A pattern is a clue. A cause is a story you can test.",
    drillQ: "Shoe size and reading score both rise with age. Does a bigger shoe cause reading?",
    drillReveal: "No. Age drives both. That is the ice-cream lesson in another coat.",
    quizTraps: [
      "AI is not 'a robot with feelings'. At syllabus level it is pattern-finding.",
      "IoT is connected things, not a sorting algorithm.",
      "Two rising lines are a correlation until proven otherwise.",
    ],
  }),
  "xi-literacy": pack({
    exampleTitle: "Friends are not 'all students'",
    exampleSay: "You ask twenty WhatsApp friends whether the canteen is fair, then title the chart 'Sindh students'. That is a sample, not the population. Friends share your school and your circle. The people you never asked can lean the other way. A larger friends-only sample is still biased.",
    exampleSayUr: "دوست نمونہ ہیں، آبادی نہیں۔ بڑا جانبدار نمونہ پھر بھی جانبدار ہے۔",
    problem: "Claim: 'all students agree'. Method: twenty friends.",
    steps: [
      { do: "Name the population you claimed.", why: "All students." },
      { do: "Name who you actually asked.", why: "Friends on one chat." },
      { do: "Refuse the leap.", why: "The unasked group can disagree." },
    ],
    exampleNote: "Primary data you collect. Secondary data someone already collected.",
    trapTitle: "Bigger fixes bias",
    trapSay: "A thousand similar friends are still not the population. Quantity does not cancel a sampling hole. Qualitative data is words and meanings. Quantitative is numbers. Mix them on purpose, not by accident.",
    trapSayUr: "سوراخ بڑی تعداد سے بند نہیں ہوتا۔",
    wrong: "Ask more of the same people and the sample becomes the population.",
    right: "Bias stays if the missing groups never enter the sample.",
    fix: "Write who never got asked. That sentence is the limitation.",
    recapTitle: "Inquiry literacy",
    recapSay: "Qualitative versus quantitative. Primary versus secondary. Sample versus population. A method is a plan for collection. Who never got asked is part of the answer, not an afterthought.",
    recapSayUr: "نوعیت، ذریعہ، نمونہ، آبادی۔ جو نہیں پوچھے گئے وہ حد ہیں۔",
    lines: [
      "Qualitative: meanings. Quantitative: numbers.",
      "Primary: you collect it. Secondary: it already exists.",
      "Sample: who you asked. Population: who you claimed.",
      "A larger biased sample is still biased.",
    ],
    sayThis: "The claim can be no wider than the people you actually reached.",
    drillQ: "Interviewing only lab-period students about 'the whole school' — sample or population?",
    drillReveal: "Sample, and a narrow one. Evening-shift students never spoke.",
    quizTraps: [
      "Qualitative is not 'worse numbers'. It is a different kind of data.",
      "A collection method is a plan, not the chart type.",
      "Friends answering 'honestly' does not make them the population.",
    ],
  }),
  "xii-hci": pack({
    exampleTitle: "Same bank, two channels",
    exampleSay: "An ATM keypad is traditional interaction: a learned device. A spoken 'what is my balance' is natural interaction: a human signal. On a noisy bus the keypad can win. Natural is not automatically better. The test is whether the person finishes the real task under real pressure.",
    exampleSayUr: "کی پیڈ روایتی۔ آواز قدرتی۔ شور میں روایتی جیت سکتا ہے۔",
    problem: "Check a balance at a bank.",
    steps: [
      { do: "Keypad: traditional.", why: "A learned control." },
      { do: "Speech: natural.", why: "A human signal." },
      { do: "Pick by context.", why: "Noise, privacy, and motor skill decide." },
    ],
    exampleNote: "HCI is also called CHI or MMI.",
    trapTitle: "Natural always wins",
    trapSay: "Face unlock fails in gloves and dark glass. Speech fails in a ward. Calling natural 'more advanced' skips the user. A saved form that does not change on screen fails the gulf of evaluation: the person cannot tell that the action worked.",
    trapSayUr: "قدرتی ہمیشہ بہتر نہیں۔ خاموش کامیابی ناکامی لگتی ہے۔",
    wrong: "Natural interaction is always the better design.",
    right: "The better channel is the one that finishes the task in that place.",
    fix: "Name the context: noise, hands, privacy, time.",
    recapTitle: "HCI in one page",
    recapSay: "HCI designs for people. Channels: sight, touch, hearing, voice, spatial. Traditional uses devices. Natural uses human signals. A silent success still fails if the person cannot see the result.",
    recapSayUr: "ایچ سی آئی انسان کے لیے۔ روایتی آلہ۔ قدرتی اشارہ۔ نتیجہ دکھائی دے۔",
    lines: [
      "HCI / CHI / MMI: people and machines meeting.",
      "Channels: sight, touch, hearing, voice, space.",
      "Traditional: keypad, mouse. Natural: speech, face, gesture.",
      "Gulf of evaluation: can I see that it worked?",
    ],
    sayThis: "The channel is a tool. The finished task is the grade.",
    drillQ: "A TV remote: traditional or natural?",
    drillReveal: "Traditional. You learned a device. Pointing your face at the TV would be natural.",
    quizTraps: [
      "MMI is man-machine interaction, not a network index.",
      "Face unlock is a human signal, so natural, not a keypad.",
      "A form that does not change fails evaluation, not 'a primary key'.",
    ],
  }),
  "xii-design": pack({
    exampleTitle: "Error is not only red",
    exampleSay: "A field turns red on a bad date. Add the word Error and an icon. Color is no longer the only channel, so more people can perceive it. That is accessibility in one control. UI is the red and the icon. UX is whether the person can fix the date and trust the save.",
    exampleSayUr: "صرف سرخ کافی نہیں۔ لفظ اور آئیکن دوسرا راستہ ہیں۔",
    problem: "Invalid date. Current design: red border only.",
    steps: [
      { do: "Keep the color.", why: "It still helps many people." },
      { do: "Add text and an icon.", why: "A second channel." },
      { do: "Show that Save worked.", why: "Feedback closes the gulf of evaluation." },
    ],
    exampleNote: "Fitts: large and close is faster than tiny and far.",
    trapTitle: "Pretty UI, failed UX",
    trapSay: "A beautiful button that charges the wrong person is a UI success and a UX failure. Usability testing watches people try the task. A/B compares two versions. Automated tests catch what a script can judge. None of those is 'I liked the colour'.",
    trapSayUr: "خوبصورت بٹن غلط رقم کاٹے تو یو ایکس فیل۔",
    wrong: "If the screen looks modern, UX is done.",
    right: "UX is whether the real task succeeds for real people.",
    fix: "Watch one person try the task before you polish gradients.",
    recapTitle: "Access, UI, UX, tests",
    recapSay: "Accessibility: text, captions, keyboard, contrast, not color alone. UI is the surface. UX is the whole task. Usability watches people. A/B compares versions. Wireframes plan structure before color.",
    recapSayUr: "رسائی، سطح، تجربہ، حقیقی صارف کی آزمائش۔",
    lines: [
      "Accessibility: text, captions, keyboard, contrast.",
      "Do not load meaning onto color alone.",
      "UI: surface. UX: whether the task succeeds.",
      "Usability watches people. A/B compares. Automation repeats checkable rules.",
    ],
    sayThis: "If meaning lives in color only, some people never get the message.",
    drillQ: "Save sometimes says Submit. Which HCI problem is that?",
    drillReveal: "Inconsistency. The same action wears two names, so people hesitate.",
    quizTraps: [
      "UI is layout and controls, not the whole feeling of the task.",
      "A usability test is not a CPU benchmark.",
      "Small and far is slower. Fitts says large and close.",
    ],
  }),
  "xii-correct": pack({
    exampleTitle: "Trace sum 1 to n",
    exampleSay: "n is 3. Total starts at 0. i is 1, total 1. i is 2, total 3. i is 3, total 6. The trace table has a row per change. 3n additions and n additions are both linear. The constant 3 is dropped when you name the Big O class.",
    exampleSayUr: "ٹریس ٹیبل ہر قدم۔ تین این اور این دونوں لکیری۔",
    problem: "Sum $1..n$ for $n=3$. Growth of a $3n$ loop.",
    steps: [
      { do: "Write columns $i$ and total.", why: "A trace is a table, not a paragraph." },
      { do: "Rows: $(1,1), (2,3), (3,6)$.", why: "Each line is one assignment." },
      { do: "$3n$ is still $O(n)$.", why: "Drop the constant." },
    ],
    exampleNote: "Logarithmic halves. Quadratic is nested n by n.",
    trapTitle: "The constant you kept",
    trapSay: "Students treat 3n as a different class from n because 3 looks important. In Big O the class is linear for both. Quadratic is n squared, a different family. Constant time does not grow with n. Be ready to rank them, not to worship the coefficient.",
    trapSayUr: "تین این الگ خاندان نہیں۔ خاندان لکیری ہے۔",
    wrong: "3n is a different Big O class from n.",
    right: "Both are linear. The 3 is a constant you drop.",
    fix: "Ask which family: constant, log, linear, quadratic. Then drop coefficients.",
    recapTitle: "Trace and growth",
    recapSay: "A trace table records each interesting variable. Clarity and modularity are part of quality. Rank $O(1)$, $O(\\log n)$, $O(n)$, $O(n^2)$. Drop constants and smaller terms.",
    recapSayUr: "ٹریس ٹیبل۔ بگ او خاندان۔ مستقل چھوڑ دو۔",
    lines: [
      "Trace table: one row per interesting change.",
      "$O(1)$ constant, $O(\\log n)$ halving, $O(n)$ linear, $O(n^2)$ quadratic.",
      "Drop constants and slower terms.",
      "Correct and clear beat a clever mess.",
    ],
    formula: "$3n \\in O(n)$",
    sayThis: "Name the family, not the coefficient.",
    drillQ: "Is n² + n quadratic or linear?",
    drillReveal: "Quadratic. The n² term dominates. The extra n is dropped.",
    quizTraps: [
      "A trace is not Big O. It is the table of values.",
      "Modularity is splitting into pieces, not 'write one long main'.",
      "3n looks bigger, but the class is still linear.",
    ],
  }),
  "xii-linear": pack({
    exampleTitle: "Same three letters",
    exampleSay: "Push A, then B, then pop a stack: B comes out. Enqueue A, then B, then dequeue a queue: A comes out. Undo is a stack. A ticket line is a queue. An array sits in one block. A linked list walks pointers. A doubling array is cheap on average even if one push copies.",
    exampleSayUr: "سٹیک آخری پہلے نکلتی۔ قطار پہلی پہلے۔",
    problem: "Operations: in A, in B, out once.",
    steps: [
      { do: "Stack out: $B$.", why: "Last in, first out." },
      { do: "Queue out: $A$.", why: "First in, first out." },
      { do: "Name a use for each.", why: "Undo versus a waiting line." },
    ],
    exampleNote: "Amortized constant time averages a rare expensive copy with many cheap pushes.",
    trapTitle: "Stack for the first customer",
    trapSay: "Using a stack at a counter serves the last arrival first. That is rude and the wrong structure. The rare expensive push of a doubling array does not make every push expensive. Amortized cost is the average across many operations.",
    trapSayUr: "پہلا گاہک قطار ہے۔ مہنگی کاپی اوسط میں سستی رہتی ہے۔",
    wrong: "A stack is fine for 'first come, first served'.",
    right: "First come, first served is a queue. A stack is last in, first out.",
    fix: "Say LIFO or FIFO out loud before you pick the structure.",
    recapTitle: "Arrays, stacks, queues",
    recapSay: "Array: indexed block. Linked list: nodes and pointers. Stack: LIFO, undo. Queue: FIFO, a line. A doubling array is cheap on average even when one push copies everything.",
    recapSayUr: "آرے بلاک۔ لنکڈ لسٹ پوائنٹر۔ سٹیک لیفو۔ قطار فیفو۔",
    lines: [
      "Array: index in a block. List: nodes linked by pointers.",
      "Stack: last in, first out. Use: undo.",
      "Queue: first in, first out. Use: a line.",
      "Amortized $O(1)$: a rare copy averaged over many cheap pushes.",
    ],
    formula: "stack: LIFO \\quad queue: FIFO",
    sayThis: "Who leaves first? That one question picks the structure.",
    drillQ: "Browser Back button: stack or queue?",
    drillReveal: "Stack. The last page you opened is the first one Back should reopen.",
    quizTraps: [
      "A linked list is not faster at random index. That is the array.",
      "Pop is stack. Dequeue is queue. Mixing the verbs loses the mark.",
      "Amortized does not mean every single push costs the same.",
    ],
  }),
  "xii-nonlinear": pack({
    exampleTitle: "Course tree, city graph",
    exampleSay: "A course has lectures and a lab. That is a tree: one parent, no cycles. Cities with many roads are a graph: a vertex can have several edges, and you can loop. Inserting already sorted keys into an unbalanced tree can produce a stick of height n. Search then walks every node.",
    exampleSayUr: "درخت ایک والدین۔ گراف کئی راہیں۔ ترتیب شدہ داخلہ ڈنڈا بنا سکتا ہے۔",
    problem: "Model a course outline, then a road map.",
    steps: [
      { do: "Course outline: tree.", why: "One parent each, a hierarchy." },
      { do: "Roads: graph.", why: "Many links, cycles allowed." },
      { do: "Sorted inserts can skew a tree.", why: "Height becomes $n$, like a list." },
    ],
    exampleNote: "Root has no parent. Leaves have no children.",
    trapTitle: "Tree equals graph",
    trapSay: "Every tree is a special graph, but not every graph is a tree. If you can walk in a circle, you left tree-land. If the diagram is one-sided after sorted inserts, binary search is no longer logarithmic. Say that sentence in the exam.",
    trapSayUr: "ہر درخت گراف ہے، ہر گراف درخت نہیں۔ دائرہ درخت توڑتا ہے۔",
    wrong: "Trees and graphs are two words for the same picture.",
    right: "A tree is a connected graph with no cycles and one parent per child.",
    fix: "Ask: can I walk in a loop? If yes, it is not a tree.",
    recapTitle: "Trees and graphs",
    recapSay: "Tree: root, parent, children, no cycles. Graph: vertices and edges, cycles allowed. Match the problem: hierarchy versus many-to-many links. Unbalanced sorted inserts can make height n.",
    recapSayUr: "درخت جڑ۔ گراف کنارے۔ ترچھا درخت فہرست بن جاتا ہے۔",
    lines: [
      "Tree: one parent, no cycles, a root.",
      "Graph: vertices and edges. Cycles are allowed.",
      "Hierarchy → tree. Many roads → graph.",
      "Sorted inserts into an unbalanced tree can make height $n$.",
    ],
    formula: "height $= n$  (skewed)",
    sayThis: "If you can loop, it is a graph. If one parent, it may be a tree.",
    drillQ: "The web of pages pointing at pages: tree or graph?",
    drillReveal: "Graph. Pages point in cycles and a page can have many incoming links.",
    quizTraps: [
      "Root is not 'the last node'. It is the node with no parent.",
      "An edge is a link, not a primary key.",
      "Unbalanced sorted inserts do not keep search logarithmic.",
    ],
  }),
  "xii-structs": pack({
    exampleTitle: "Four structures, one fact",
    exampleSay: "List 2, 4. Slot 0 becomes 9: now 9, 4. A tuple 2, 4 cannot assign. A set drops duplicates. A dictionary scores Ali 7, then scores Ali 9: the 7 is gone. Index and slice a list. Tuples are frozen. Sets test membership. Dicts look up by key.",
    exampleSayUr: "لسٹ بدلتی۔ ٹیپل جمے۔ سیٹ یکتا۔ ڈکشنری کلید بدل دیتی ہے۔",
    problem: "list $[2,4]$; tuple $(2,4)$; dict Ali $\\to 7$ then $9$.",
    steps: [
      { do: "list$[0]=9$ works.", why: "Lists are mutable." },
      { do: "tuple$[0]=9$ fails.", why: "Tuples are immutable." },
      { do: "Ali now maps to $9$.", why: "One key holds one value." },
    ],
    exampleNote: "A set is not ordered like a list. Do not index it as if it were.",
    trapTitle: "Second write keeps both",
    trapSay: "A dictionary is not a list of pairs that pile up. The second write to the same key replaces. People also try to append to a tuple. Immutability means you build a new tuple if you need a change.",
    trapSayUr: "ایک کلید ایک قیمت۔ دوسری لکھائی بدل دیتی ہے۔ ٹیپل میں اپینڈ نہیں۔",
    wrong: "scores['Ali'] = 9 keeps 7 and 9 together.",
    right: "The new assignment replaces 7. One key, one value.",
    fix: "If you need history, store a list under the key. Do not hope the dict will remember.",
    recapTitle: "List, tuple, set, dict",
    recapSay: "List: index and slice, mutable. Tuple: frozen. Set: unique membership. Dictionary: key to value, and a second write replaces. Pick by the job, not by which word you remember.",
    recapSayUr: "لسٹ، ٹیپل، سیٹ، ڈکشنری۔ کام سے چنو۔",
    lines: [
      "List: indexed, mutable, slices.",
      "Tuple: immutable sequence.",
      "Set: uniqueness, no duplicate members.",
      "Dict: key $\\to$ value. A second write replaces.",
    ],
    formula: "$\\texttt{d[k] = v}$  replaces",
    sayThis: "Mutable versus frozen, and key versus position, pick the type.",
    drillQ: "Need student ids with no duplicates, order does not matter. Which type?",
    drillReveal: "A set. Uniqueness is the job.",
    quizTraps: [
      "Slicing a list copies a range. It is not a dictionary lookup.",
      "A tuple cannot grow in place.",
      "Assignment to an existing key overwrites, it does not append a second score.",
    ],
  }),
  "xii-files": pack({
    exampleTitle: "Return, then open",
    exampleSay: "A function add(a, b) returns a plus b. x equals add(2, 3) is 5. Names created inside the function are local. To read a file: open, read, close, or a with block. If the file is missing, catch the error. In a CSV, quote Khan comma Jr so the comma stays inside the field.",
    exampleSayUr: "فنکشن واپس دے۔ فائل کھولو پڑھو بند کرو۔ کوما والا نام اوقاف میں۔",
    problem: "add(2,3) and the CSV field Khan, Jr.",
    steps: [
      { do: "$\\texttt{return}$ gives $5$ to $x$.", why: "Callers need the value, not a print." },
      { do: "Open, read, close.", why: "Or $\\texttt{with}$, which closes for you." },
      { do: "Quote $\\texttt{\"Khan, Jr\"}$.", why: "The comma is data, not a separator." },
    ],
    exampleNote: "print is for people. return is for the next line of code.",
    trapTitle: "Comma splits a name",
    trapSay: "CSV splits on commas. An unquoted Khan, Jr becomes two columns and every later field slides. Quotes tell the reader that this comma belongs to the name. Catching FileNotFoundError is not optional decoration. It is how a missing path fails kindly.",
    trapSayUr: "بغیر اوقاف کوما کالم توڑ دیتا ہے۔ غائب فائل کو پکڑو۔",
    wrong: "A comma inside a field is fine; the reader will guess.",
    right: "Quote the field so the comma stays inside the name.",
    fix: "If a field can contain the separator, it must be quoted.",
    recapTitle: "Functions and files",
    recapSay: "Functions return values. Local names live inside the call. Global names live outside. Files: open, read or write, close. Catch a missing file. CSV: commas separate, quotes protect commas inside fields.",
    recapSayUr: "واپسی، دائرہ کار، فائل، کوما سے بچاؤ۔",
    lines: [
      "return hands a value to the caller. print talks to a human.",
      "Local versus global scope.",
      "Open, use, close. Catch a missing path.",
      "CSV: quote fields that contain commas.",
    ],
    formula: "$\\texttt{\"Khan, Jr\"}$",
    sayThis: "Return to code, print to people, quote the comma that is not a split.",
    drillQ: "A function prints 7 but has no return. What does x = f() store?",
    drillReveal: "None. The 7 went to the screen, not to x.",
    quizTraps: [
      "A function without return is not 'returning print'.",
      "A local name is not visible after the call.",
      "Splitting Khan, Jr into two columns is the bug, not the requirement.",
    ],
  }),
  "xii-pandas": pack({
    exampleTitle: "Label 0 is gone",
    exampleSay: "Rows labelled 0, 1, 2. You filter and only 1 and 2 remain. loc of 0 looks for label 0 and misses. iloc of 0 is the first remaining row, which still wears label 1. After a filter, position and label are different stories. Missing values: drop or fill, with a reason.",
    exampleSayUr: "فلٹر کے بعد لوک لیبل ڈھونڈتا ہے۔ آئیلوک پوزیشن۔",
    problem: "After filter, leftover labels $[1,2]$. Fetch the first leftover row.",
    steps: [
      { do: "iloc$[0]$ is label $1$.", why: "Position 0 among what remains." },
      { do: "loc$[0]$ fails or misses.", why: "Label 0 was filtered out." },
      { do: "Say which you meant.", why: "Label versus position." },
    ],
    exampleNote: "A DataFrame is a labelled table. SQLite is queried from Python in steps: connect, execute, fetch, close.",
    trapTitle: "fillna equals dropna",
    trapSay: "Filling missing marks with 0 pretends people scored 0. Dropping those rows pretends they were never in the class. Both can be honest if you declare the choice. They are not interchangeable repairs.",
    trapSayUr: "صفر بھرنا اور قطار گرانا ایک نہیں۔ وجہ لکھو۔",
    wrong: "fillna and dropna are two buttons for the same cleanup.",
    right: "Fill invents a value. Drop removes the row. They answer different questions.",
    fix: "Write the reason next to the call, even in a comment.",
    recapTitle: "SQL and frames",
    recapSay: "SQLite from Python: connect, execute, fetch, close. A DataFrame is a table with labels. loc uses labels. iloc uses positions. After a filter those two diverge. Missing data: fill or drop, with a reason.",
    recapSayUr: "کنیکٹ، چلاؤ، لو، بند۔ لوک لیبل، آئیلوک پوزیشن۔",
    lines: [
      "SQLite: connect, execute, fetch, close.",
      "DataFrame: labelled rows and columns.",
      "loc: labels. iloc: positions. They differ after a filter.",
      "Missing values: fill or drop, and say why.",
    ],
    formula: "$\\texttt{iloc[0]} \\neq \\texttt{loc[0]}$  after a filter",
    sayThis: "After a filter, ask whether you want a label or a place in line.",
    drillQ: "Rows 3, 7, 9 remain. What does loc[3] return?",
    drillReveal: "The row whose label is 3, which here is the first remaining row. iloc[3] would be out of range.",
    quizTraps: [
      "A DataFrame is not a raw CSV string.",
      "Dropping missing values is a choice, not the only cleanup.",
      "iloc[0] is the first remaining row, not 'the row that used to be 0'.",
    ],
  }),
  "xii-stats": pack({
    exampleTitle: "2, 3, 3, 4, 100",
    exampleSay: "Median is 3, the middle seat. Mode is 3, the most common. Mean is 22.4, because 100 drags it. Range is 98. A box plot would show that outlier as a far whisker or a point. The mean moved. The median stayed a middle person.",
    exampleSayUr: "میڈین درمیان۔ اوسط سو سے کھنچتی ہے۔",
    problem: "Marks: $2,3,3,4,100$.",
    steps: [
      { do: "Median $= 3$.", why: "Middle position in the ordered list." },
      { do: "Mean uses every value.", why: "$100$ pulls it to $22.4$." },
      { do: "Report both.", why: "One number would hide the story." },
    ],
    exampleNote: "Pie charts collapse when there are many tiny categories. Use a bar.",
    trapTitle: "One number is the story",
    trapSay: "A mean without a look at outliers is how a class looks brilliant because of one contest. Standard deviation is spread around the mean. Range is max minus min and is itself outlier-sensitive. Choose the chart that matches the question.",
    trapSayUr: "ایک اوسط کہانی چھپا سکتی ہے۔ چارٹ سوال سے چنو۔",
    wrong: "The mean is the fair summary even when one value is wild.",
    right: "An outlier pulls the mean. The median stays the middle seat.",
    fix: "When one value looks absurd, compute median beside the mean.",
    recapTitle: "Charts and summaries",
    recapSay: "Bar compares. Line tracks time. Pie is a few parts of a whole. Histogram is distribution. Scatter is relationship. Box is spread. Mean uses values. Median uses rank. Mode is the most common. Range and standard deviation measure spread.",
    recapSayUr: "چارٹ سوال سے۔ اوسط قیمت۔ میڈین رتبہ۔ موڈ سب سے عام۔",
    lines: [
      "Bar / line / pie / hist / scatter / box: match the question.",
      "Mean: uses values, so outliers pull it.",
      "Median: middle rank. Mode: most common.",
      "Range $= \\max - \\min$. SD: spread around the mean.",
    ],
    formula: "$\\bar{x} = (\\sum x)/n$",
    sayThis: "If one point can bully the mean, show the median too.",
    drillQ: "Which chart compares five sections' average marks?",
    drillReveal: "A bar chart. Each section is a category to compare.",
    quizTraps: [
      "A pie is not the comparison tool for many categories.",
      "Mode is the most common, not the middle.",
      "A high outlier moves the mean farther than the median.",
    ],
  }),
  "xii-ml": pack({
    exampleTitle: "100 percent, then 50",
    exampleSay: "The practice rows score 100 percent. New rows score 50. The model memorised the practice set. Deep learning is neural nets with many layers. More layers are not automatically wiser if they only restate the training names. Hold out a test set you never trained on.",
    exampleSayUr: "مشق پر سو، نئی قطاروں پر پچاس: یاد کرنا۔ ٹیسٹ الگ رکھو۔",
    problem: "Train accuracy $100\\%$. Fresh accuracy $50\\%$.",
    steps: [
      { do: "Name the gap.", why: "Train and test disagree." },
      { do: "Call it memorising.", why: "Overfit to practice rows." },
      { do: "Hold out a test set next time.", why: "That is how you notice." },
    ],
    exampleNote: "A neural net has input, hidden, and output layers. Do not claim certainty.",
    trapTitle: "More layers, more truth",
    trapSay: "Depth can help, and it can memorise noise. Shipping on training accuracy is how a classroom demo lies. Labels on people need humility: a model can rank, and still be wrong for a person. Equity asks who the errors fall on.",
    trapSayUr: "زیادہ تہہ زیادہ سچ نہیں۔ مشق کی درستگی جھوٹ بول سکتی ہے۔",
    wrong: "If training accuracy is perfect, the model is ready.",
    right: "Perfect on practice plus weak on new rows means it memorised.",
    fix: "Never quote training accuracy as if it were the test.",
    recapTitle: "Learning and layers",
    recapSay: "Machine learning fits examples. A neural network has layers. Deep learning is that idea with many layers. Hold out a test set. High train and low test is memorising. Do not over-claim certainty.",
    recapSayUr: "مشین لرننگ مثال سے۔ نیٹ تہہ۔ ٹیسٹ الگ۔ یقین نہ پھیلانا۔",
    lines: [
      "ML: learn from examples, not only from handwritten rules.",
      "NN: input, hidden, output. DL: many hidden layers.",
      "Hold out a test set you never trained on.",
      "Train high, test low: memorising. Do not claim certainty.",
    ],
    sayThis: "The test is rows the model has not seen. Training scores can flatter.",
    drillQ: "Why not train on every row you have?",
    drillReveal: "Then you have no honest test. You cannot tell memorising from learning.",
    quizTraps: [
      "Deep learning sits inside neural nets inside machine learning, not the other way around.",
      "A layer is not a database table.",
      "Ready-to-ship on training accuracy is the memorising trap.",
    ],
  }),
  "xii-security": pack({
    exampleTitle: "Three jobs, three tools",
    exampleSay: "A stolen USB is a confidentiality problem: encrypt. A changed file is an integrity problem: hash it and compare. A crashed disk is an availability problem: backup. Phishing is a fake request for secrets. The mitigation is check the sender, do not follow the panic link. Hashing is not reversible encryption.",
    exampleSayUr: "خفیہ کاری راز۔ ہیش تبدیلی۔ بیک اپ دستیابی۔",
    problem: "USB theft, silent edit, disk crash.",
    steps: [
      { do: "Encrypt the USB.", why: "Confidentiality." },
      { do: "Hash the file.", why: "Integrity: a change shows." },
      { do: "Keep a backup.", why: "Availability after a crash." },
    ],
    exampleNote: "Equity: who can still log in if you only support one kind of phone?",
    trapTitle: "Hash means secret",
    trapSay: "A hash does not hide a file from strangers. It fingerprints it. Encryption hides. Backup brings the file back. Using one word for all three CIA jobs loses the question. Phishing is not malware already on the disk. It is a lie that invites you to hand the keys over.",
    trapSayUr: "ہیش چھپاتا نہیں، پہچان دیتا ہے۔ فشنگ جھوٹ ہے۔",
    wrong: "Hashing is encryption you can reverse if you know a password.",
    right: "A hash checks that the file did not change. Encryption is the secrecy tool.",
    fix: "Name the CIA job first, then the tool.",
    recapTitle: "Threats and CIA",
    recapSay: "Phishing, malware, theft. Match a mitigation to each. Confidentiality: encrypt. Integrity: hash. Availability: backup. Equity asks who is shut out by the design.",
    recapSayUr: "دھمکیاں۔ سی آئی اے تین کام۔ انصاف پوچھتا ہے کون باہر رہا۔",
    lines: [
      "Phishing: a lie for secrets. Malware: hostile software. Theft: data taken.",
      "Confidentiality: encrypt. Integrity: hash. Availability: backup.",
      "A hash is not reversible secrecy.",
      "Equity: who cannot use the tool as designed?",
    ],
    formula: "C: encrypt \\quad I: hash \\quad A: backup",
    sayThis: "Three jobs. Three tools. Do not lend one word to all three.",
    drillQ: "You want to know if a downloaded installer was altered. Encrypt, hash, or backup?",
    drillReveal: "Hash. Compare the published fingerprint to the file you have.",
    quizTraps: [
      "Phishing is social deceit, not a sorting bug.",
      "A backup does not encrypt. It restores availability.",
      "A hash of a file is integrity, not confidentiality.",
    ],
  }),
  "xii-venture": pack({
    exampleTitle: "The canteen line",
    exampleSay: "You watch a long line. The user is a student who will be late. The job is skip the wait. The idea is pre-order, not 'an app'. The buyer may be the school, not the student. Observation, then a person, then a job, then a small idea. That order keeps you from decorating a guess.",
    exampleSayUr: "قطار دیکھو۔ صارف طالب علم۔ کام انتظار کاٹنا۔ خیال چھوٹا ہو۔",
    problem: "Twenty students miss class waiting for food.",
    steps: [
      { do: "User: the late student.", why: "A person, not 'youth'." },
      { do: "Job: get food without the queue.", why: "The outcome they want." },
      { do: "Idea: pre-order at the door.", why: "Small enough to try this week." },
    ],
    exampleNote: "Entrepreneurship is acting on that chain, not a personality type.",
    trapTitle: "User pays",
    trapSay: "In a school the student uses the thing and someone else may pay. Mixing those two people is how a pitch targets the wrong fear. Also: a huge idea is not braver. It is slower to learn you were wrong.",
    trapSayUr: "صارف اور خریدار الگ ہو سکتے ہیں۔ بڑا خیال سیکھنے میں دیر کرتا ہے۔",
    wrong: "The user is automatically the customer who pays.",
    right: "Use and payment can belong to different people.",
    fix: "Write two names: who uses, who pays.",
    recapTitle: "From observation to idea",
    recapSay: "An entrepreneur acts on a problem. Walk observation to a specific user to a job to an idea. Keep the first idea small enough to test. The user may not be the buyer.",
    recapSayUr: "دیکھو، صارف، کام، خیال۔ پہلا خیال قابل آزمائش۔",
    lines: [
      "Entrepreneur: acts on a problem, not only a slogan.",
      "Observe → specific user → job → idea.",
      "The user may not be the buyer.",
      "Small first idea: you can test it this week.",
    ],
    sayThis: "Name a person and a job before you name a product.",
    drillQ: "A parent pays for a homework app the child uses. Who is the user?",
    drillReveal: "The child. The parent is (likely) the customer. Write both.",
    quizTraps: [
      "Entrepreneurship is the action, not a job title on a slide.",
      "A vague 'everyone' is not a user.",
      "The student in a school app is often the user, not automatically the payer.",
    ],
  }),
  "xii-mvp": pack({
    exampleTitle: "A paper list on the door",
    exampleSay: "The riskiest belief: students will check a list before they walk to the canteen. A paper list on the door can kill or prove that belief today. Four extra screens cannot. An MVP is the smallest test of that belief. A prototype can be ugly. It is still not the whole product in miniature.",
    exampleSayUr: "خطرناک یقین کو کاغذ کی فہرست آج ہی توڑ سکتی ہے۔",
    problem: "Belief: students check before they walk.",
    steps: [
      { do: "Write the belief in one sentence.", why: "If it is two beliefs, split them." },
      { do: "Find a test that can fail this week.", why: "A paper list on the door." },
      { do: "Do not build the spare screens.", why: "They delay the honest failure." },
    ],
    exampleNote: "A beachhead is the first tiny market, not the whole country.",
    trapTitle: "MVP means ugly full product",
    trapSay: "An ugly version of every feature is still every feature. The M in MVP is smallest test, not cheapest paint. Prototype fidelity is how finished it looks. High fidelity is for later, when the belief already survived a cheap test.",
    trapSayUr: "ایم وی پی ہر فیچر کی سستی شکل نہیں، سب سے چھوٹا امتحان ہے۔",
    wrong: "An MVP is the whole product, just with rougher pixels.",
    right: "An MVP is the smallest thing that can prove or kill one belief.",
    fix: "If the extra screen does not test the belief, it is not part of the MVP.",
    recapTitle: "Prototype, MVP, beachhead",
    recapSay: "A prototype tries the shape. An MVP tests one belief. Beachhead is the first tiny market. The riskiest assumption is the one that, if false, sinks the rest. Fail that one first.",
    recapSayUr: "پروٹو ٹائپ شکل۔ ایم وی پی یقین۔ پہلی چھوٹی منڈی۔ خطرناک مفروضہ پہلے۔",
    lines: [
      "Prototype: try the shape, even on paper.",
      "MVP: smallest test of one belief.",
      "Beachhead: the first tiny market.",
      "Riskiest assumption first. Extra screens delay the answer.",
    ],
    sayThis: "If it cannot fail this week, it is not yet an MVP.",
    drillQ: "Belief: teachers will pin a late-bus notice. MVP: a full routing app, or a paper on the staff board?",
    drillReveal: "The paper. It can fail tomorrow. The routing app tests ten other beliefs at once.",
    quizTraps: [
      "High fidelity is not the first prototype by default.",
      "A prototype is not automatically an MVP.",
      "An MVP that cannot fail is a brochure, not a test.",
    ],
  }),
};

export function applyMastery(lectures) {
  for (const lecture of lectures) {
    const extra = MASTERY[lecture.id];
    if (!extra) continue;
    lecture.beats.forEach((item) => {
      if (!item.role) item.role = item.scene?.type === "whiteboard" ? "depth" : "idea";
    });
    lecture.beats.push(extra.worked, extra.trap, extra.recap);
    lecture.sheet = extra.sheet;
    lecture.drill = extra.drill;
    extra.quizTraps.forEach((text, index) => {
      if (lecture.quiz[index]) lecture.quiz[index].trap = text;
    });
    if (Array.isArray(lecture.outcomes)) {
      lecture.outcomes.push("Work a short example and name the exam trap.");
    }
  }
}

export const masteryIds = Object.keys(MASTERY);
