function b(title, say, sayUr, scene) {
  return { title, say, sayUr, scene };
}

export const xiLectures = [
  {
    id: "xi-digital",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "Discrete, continuous, and digital",
    golden: false,
    covers: ["1.1.1", "1.1.2"],
    summary: "What can be counted, what flows, and why machines keep only 0 and 1.",
    outcomes: ["Tell a discrete quantity from a continuous one.", "Explain why a digital system uses bits.", "Name four reasons digital machines are useful."],
    beats: [
      b("Two kinds of quantity", "Some quantities are discrete. You can count them one by one, like students in a room or cars in a lot. Each value is a separate step.", "کچھ مقداریں متفرق ہوتی ہیں۔ انہیں ایک ایک کر کے گنا جا سکتا ہے، جیسے کمرے میں طلبہ۔", { type: "split", title: "Stairs and a ramp", left: { eyebrow: "Discrete", title: "Stairs", lines: ["Separate steps", "Students in a class", "Cars in a parking lot"] }, right: { eyebrow: "Continuous", title: "Ramp", lines: ["Any point along the slope", "Temperature of water", "Speed of a moving car"] }, note: "Stairs are fixed steps. A ramp has every height in between." }),
      b("Continuous flow", "A continuous quantity can take any value inside a range. Temperature and speed do not jump from one allowed number to the next. They flow.", "مسلسل مقدار ایک حد کے اندر کوئی بھی قیمت لے سکتی ہے، جیسے پانی کا درجہ حرارت۔", { type: "wave", mode: "analog", title: "Continuous change", note: "A smooth curve has no forced gaps." }),
      b("Only two symbols", "A digital system is an electronic system that uses only two values, 0 and 1. Those two values are called binary digits, or bits.", "ڈیجیٹل نظام صرف صفر اور ایک استعمال کرتا ہے۔ ان دو قیمتوں کو بٹس کہتے ہیں۔", { type: "bits", title: "A bit is a binary digit", rows: [{ bit: "0", meanings: ["OFF", "LOW", "FALSE"] }, { bit: "1", meanings: ["ON", "HIGH", "TRUE"] }] }),
      b("Why digital", "Digital systems are reliable because noise rarely flips a clear 0 into a clear 1. Copies stay accurate. Design is simpler with only two states, and software can change what the machine does.", "ڈیجیٹل نظام شور سے کم متاثر ہوتے ہیں، نقل درست رہتی ہے، اور سافٹ ویئر انہیں کنٹرول کر سکتا ہے۔", { type: "cards", title: "Why build with bits", items: [{ tag: "Reliable", title: "Noise resistant", body: "A signal must move a long way to flip from 0 to 1." }, { tag: "Accurate", title: "Clean copies", body: "Copying bits does not fade the way a sketch fades." }, { tag: "Simple", title: "Two states", body: "Circuits only have to tell LOW from HIGH." }, { tag: "Flexible", title: "Programmable", body: "Software can retarget the same hardware." }] }),
      b("Around you", "A computer processes bits. A phone stores photos and music as bits. A digital camera turns light into binary code. The world you touch is continuous. The file is discrete.", "کمپیوٹر، فون، اور ڈیجیٹل کیمرہ سب معلومات کو صفر اور ایک کی شکل میں رکھتے ہیں۔", { type: "callout", eyebrow: "Hold this", title: "Continuous world, discrete file", body: "The measurement may be continuous. The computer stores a digital sample made of bits." }),
    ],
    quiz: [
      { q: "Which example is discrete?", choices: ["The temperature of tea", "The speed of a bus", "The number of students in a lab", "The loudness of a voice"], answer: 2, why: "Students can be counted one by one. Temperature, speed, and loudness can fall anywhere in a range." },
      { q: "A bit is…", choices: ["A programming language", "One binary digit, 0 or 1", "A type of network cable", "A continuous voltage"], answer: 1, why: "Bit is short for binary digit. It holds one of two values." },
      { q: "Why are digital copies accurate?", choices: ["They use more electricity", "Quality is not lost when bits are copied", "They avoid all software", "They store temperature directly"], answer: 1, why: "Copying a pattern of 0s and 1s does not fade the information." },
    ],
  },
  {
    id: "xi-signals",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "Analog and digital signals",
    golden: true,
    covers: ["1.1.3"],
    summary: "Smooth waves versus square waves, and why bits survive noise.",
    outcomes: ["Describe an analog signal and a digital signal.", "Match examples to each kind.", "Explain which kind resists noise better."],
    beats: [
      b("Golden idea", "Signals carry information through time. An analog signal changes smoothly. A digital signal jumps between allowed levels. This difference sits under every phone call and every file.", "سگنل وقت کے ساتھ معلومات لے جاتا ہے۔ اینالاگ ہموار بدلتا ہے اور ڈیجیٹل چھلانگ لگاتا ہے۔", { type: "board", kicker: "Golden topic · 1.1.3", title: "Two ways to carry a value", points: ["Analog: a smooth curve", "Digital: allowed levels only", "Noise hurts the smooth curve first"] }),
      b("Analog", "An analog signal is continuous. It can be any height at any moment, like a sine wave. A human voice and an old thermometer are analog.", "اینالاگ سگنل مسلسل ہوتا ہے، جیسے انسانی آواز یا پرانا تھرمامیٹر۔", { type: "wave", mode: "analog", title: "Analog signal", note: "The curve may sit at any height. Small noise changes the value." }),
      b("Digital", "A digital signal uses levels such as HIGH and LOW. HIGH stands for 1 and LOW stands for 0. The picture is a square wave because the signal jumps instead of gliding.", "ڈیجیٹل سگنل کی دو سطحیں ہوتی ہیں: ہائی یعنی ایک، اور لو یعنی صفر۔", { type: "wave", mode: "digital", title: "Digital signal", note: "Between samples the signal is either HIGH or LOW." }),
      b("Side by side", "Put the waves together. The analog wave is a hill. The digital wave is a staircase with two heights. Computer data is the staircase. A microphone hears the hill.", "اینالاگ لہر پہاڑی جیسی ہے اور ڈیجیٹل لہر دو اونچائیوں والی سیڑھی جیسی۔", { type: "diagram", diagram: "sample", title: "Same moment, two encodings", note: "Dots on the curve are samples. The lower steps are the bits a file can store." }),
      b("Noise", "Noise adds small random changes. On an analog signal those changes become part of the value. On a digital signal the receiver only asks a rough question: is this closer to HIGH or LOW? Small noise is ignored.", "شور اینالاگ قیمت کو بدل دیتا ہے۔ ڈیجیٹل وصول کنندہ صرف یہ دیکھتا ہے کہ سگنل ہائی کے قریب ہے یا لو کے۔", { type: "compare", title: "Analog data and digital data", headers: ["", "Analog", "Digital"], rows: [["Nature", "Continuous flow", "Separate bits"], ["Shape", "Smooth wave", "Square wave"], ["Noise", "Easily damaged", "Rejected if small"], ["Examples", "Voice, mercury thermometer", "Files, computer data"]], note: "Digital is the more reliable storage form." }),
    ],
    quiz: [
      { q: "Which signal changes smoothly through every intermediate value?", choices: ["Digital", "Analog", "Binary gate", "K-map"], answer: 1, why: "Analog signals are continuous. Digital signals jump between levels." },
      { q: "In a digital square wave, HIGH usually means…", choices: ["0", "1", "Unknown", "Analog"], answer: 1, why: "HIGH is the 1 level and LOW is the 0 level." },
      { q: "Why does a digital signal resist small noise?", choices: ["It never travels on a wire", "The receiver only chooses the nearest allowed level", "It is always faster than light", "It stores temperature"], answer: 1, why: "A small bump still looks like HIGH or still looks like LOW." },
    ],
  },
  {
    id: "xi-boolean",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "Boolean algebra and truth tables",
    golden: true,
    covers: ["1.1.4", "1.1.5", "1.1.6"],
    summary: "True and false, AND, OR, NOT, and the table that lists every case.",
    outcomes: ["Evaluate AND, OR, and NOT.", "Build a truth table for two inputs.", "Connect a Boolean expression to a real rule."],
    beats: [
      b("Boole's two values", "George Boole built an algebra with only two values: true and false, written 1 and 0. Variables such as A and B hold one of those values. This is the math inside digital circuits.", "جارج بول نے ایسا الجبرا بنایا جس میں صرف درست اور غلط ہوتے ہیں، یعنی ایک اور صفر۔", { type: "board", kicker: "1.1.4", title: "Boolean algebra", formula: "$$A, B \\in \\{0, 1\\}$$", points: ["Values are only $0$ and $1$", "Letters stand for those values", "Operations combine them into an output $Y$"] }),
      b("AND", "AND outputs 1 only when every input is 1. Think of a door with two locks. The door opens only when both locks are open. If either lock stays shut, the door stays shut.", "اے این ڈی تبھی ایک دیتا ہے جب تمام ان پٹ ایک ہوں، جیسے دو تالے والا دروازہ۔", { type: "gate", gate: "AND", title: "AND · both must be 1", steps: [{ a: 0, b: 0, y: 0, note: "Both locked. The door stays shut." }, { a: 1, b: 0, y: 0, note: "One lock is still shut." }, { a: 0, b: 1, y: 0, note: "The other lock is still shut." }, { a: 1, b: 1, y: 1, note: "Both open. AND outputs 1." }] }),
      b("OR", "OR outputs 1 when at least one input is 1. A hallway light with two switches can be the picture: either switch is enough to call for light in a simple OR rule.", "او آر تب ایک دیتا ہے جب کم از کم ایک ان پٹ ایک ہو۔", { type: "gate", gate: "OR", title: "OR · either input is enough", steps: [{ a: 0, b: 0, y: 0, note: "Nothing is on." }, { a: 1, b: 0, y: 1, note: "A alone is enough." }, { a: 0, b: 1, y: 1, note: "B alone is enough." }, { a: 1, b: 1, y: 1, note: "Both on is still 1." }] }),
      b("NOT", "NOT flips the single input. 1 becomes 0, and 0 becomes 1. It is also called an inverter. In symbols, NOT A is often written A prime.", "ناٹ ان پٹ کو الٹ دیتا ہے۔ ایک صفر بن جاتا ہے اور صفر ایک۔", { type: "gate", gate: "NOT", title: "NOT · the inverter", steps: [{ a: 0, b: 0, y: 1, note: "Input 0 comes out as 1." }, { a: 1, b: 0, y: 0, note: "Input 1 comes out as 0." }] }),
      b("Truth table", "A truth table lists every input combination and the output. Two inputs give four rows because 2 to the power 2 is 4. Three inputs would give eight rows.", "ٹروتھ ٹیبل ہر ممکن ان پٹ اور اس کا آؤٹ پٹ دکھاتی ہے۔ دو ان پٹ پر چار قطاریں ہوتی ہیں۔", { type: "table", title: "AND and OR for two inputs", headers: ["$A$", "$B$", "$A \\cdot B$", "$A + B$"], rows: [["$0$", "$0$", "$0$", "$0$"], ["$0$", "$1$", "$0$", "$1$"], ["$1$", "$0$", "$0$", "$1$"], ["$1$", "$1$", "$1$", "$1$"]], note: "Two inputs give $2^2 = 4$ rows. Read a row across." }),
    ],
    quiz: [
      { q: "When does AND output 1?", choices: ["When any input is 1", "When all inputs are 1", "When all inputs are 0", "When the inputs differ"], answer: 1, why: "AND is strict. Every input must be 1." },
      { q: "NOT 1 equals…", choices: ["1", "0", "2", "Undefined"], answer: 1, why: "NOT flips the bit." },
      { q: "How many rows does a truth table with 3 inputs have?", choices: ["3", "6", "8", "9"], answer: 2, why: "Each input doubles the rows. 2 to the power 3 is 8." },
    ],
  },
  {
    id: "xi-gates",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "Logic gates, including universal gates",
    golden: true,
    covers: ["1.1.7"],
    summary: "NAND, NOR, XOR, and XNOR, and why two of them can build the rest.",
    outcomes: ["Predict NAND, NOR, XOR, and XNOR.", "Explain what makes a gate universal.", "Describe how a simulator such as Logisim is used."],
    beats: [
      b("Gates are circuits", "A logic gate is a small electronic circuit that performs one Boolean operation. Chips contain huge networks of these gates. You can also place them on screen in a tool such as Logisim Evolution.", "لاجک گیٹ وہ سرکٹ ہے جو ایک بولین عمل کرتا ہے۔ Logisim میں انہیں جوڑ کر دیکھا جا سکتا ہے۔", { type: "cards", title: "From algebra to hardware", items: [{ tag: "Basic", title: "AND, OR, NOT", body: "The three operations you already timed." }, { tag: "Universal", title: "NAND and NOR", body: "Each one can build every other gate." }, { tag: "Compare", title: "XOR and XNOR", body: "They care whether the inputs match." }, { tag: "Tool", title: "Logisim", body: "Place gates, set inputs, watch the output." }] }),
      b("NAND", "NAND means NOT AND. It outputs 0 only when every input is 1. In every other row it outputs 1. NAND is called universal because AND, OR, and NOT can all be made from NAND gates alone.", "نینڈ یعنی ناٹ اے این ڈی صرف تب صفر دیتا ہے جب سب ان پٹ ایک ہوں۔ یہ یونیورسل گیٹ ہے۔", { type: "gate", gate: "NAND", title: "NAND", steps: [{ a: 0, b: 0, y: 1, note: "AND would be 0, so NAND is 1." }, { a: 1, b: 0, y: 1, note: "Still not both 1." }, { a: 0, b: 1, y: 1, note: "Still not both 1." }, { a: 1, b: 1, y: 0, note: "Both inputs are 1, so NAND is 0." }] }),
      b("NOR", "NOR means NOT OR. It outputs 1 only when every input is 0. NOR is the other universal gate. A designer can build a whole computer from copies of just this gate.", "نار یعنی ناٹ او آر صرف تب ایک دیتا ہے جب تمام ان پٹ صفر ہوں۔", { type: "gate", gate: "NOR", title: "NOR", steps: [{ a: 0, b: 0, y: 1, note: "OR would be 0, so NOR is 1." }, { a: 1, b: 0, y: 0, note: "OR is already 1, so NOR is 0." }, { a: 0, b: 1, y: 0, note: "Same idea." }, { a: 1, b: 1, y: 0, note: "Any 1 forces NOR to 0." }] }),
      b("XOR", "XOR outputs 1 when the inputs are different. 0 and 1, or 1 and 0, light the lamp. Matching inputs leave it dark. The name is exclusive OR: one or the other, but not both.", "ایکس او آر تب ایک دیتا ہے جب ان پٹ مختلف ہوں۔", { type: "gate", gate: "XOR", title: "XOR · different inputs", steps: [{ a: 0, b: 0, y: 0, note: "Same inputs. Output 0." }, { a: 1, b: 0, y: 1, note: "Different. Output 1." }, { a: 0, b: 1, y: 1, note: "Different. Output 1." }, { a: 1, b: 1, y: 0, note: "Same again. Output 0." }] }),
      b("XNOR", "XNOR is the opposite of XOR. It outputs 1 when the inputs match. It is useful when a circuit must check equality.", "ایکس نار تب ایک دیتا ہے جب دونوں ان پٹ ایک جیسے ہوں۔", { type: "gate", gate: "XNOR", title: "XNOR · matching inputs", steps: [{ a: 0, b: 0, y: 1, note: "Match." }, { a: 1, b: 0, y: 0, note: "Differ." }, { a: 0, b: 1, y: 0, note: "Differ." }, { a: 1, b: 1, y: 1, note: "Match." }] }),
    ],
    quiz: [
      { q: "Which pair are the universal gates?", choices: ["AND and OR", "XOR and XNOR", "NAND and NOR", "NOT and XOR"], answer: 2, why: "Either NAND alone or NOR alone can be wired to make any Boolean function." },
      { q: "XOR of 1 and 1 is…", choices: ["1", "0", "2", "Undefined"], answer: 1, why: "The inputs match, so exclusive OR is 0." },
      { q: "NAND outputs 0 when…", choices: ["Any input is 0", "All inputs are 1", "All inputs are 0", "The inputs differ"], answer: 1, why: "NAND is AND followed by NOT, so the single 1 from AND becomes 0." },
    ],
  },
  {
    id: "xi-kmap",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "Expressions, diagrams, and K-maps",
    golden: true,
    covers: ["1.1.8", "1.1.10", "1.1.11", "1.1.13"],
    summary: "Order of operations, logic diagrams, and grouping cells to simplify.",
    outcomes: ["Apply Boolean precedence.", "Read a logic diagram as gates wired together.", "Group K-map cells in powers of two."],
    beats: [
      b("Precedence", "Boolean expressions follow an order. Parentheses come first, then NOT, then AND, then OR. Y equals A OR B, then NOT around the whole thing, is not the same as NOT A, then OR B.", "پہلے بریکٹ، پھر ناٹ، پھر اے این ڈی، پھر او آر۔ ترتیب جواب بدل دیتی ہے۔", { type: "code", title: "Same letters, different meaning", lines: ["Y = (A OR B) then NOT", "Z = (NOT A) OR B"], active: [0], note: "$(A + B)'$ is not the same expression as $A' + B$." }),
      b("Minterms", "A minterm is one AND combination where the function is 1. For two variables, A AND NOT B is one minterm. A truth table row of 1 0 with output 1 is that minterm. The full function is the OR of its minterms.", "منٹرم وہ اے این ڈی جملہ ہے جہاں فنکشن ایک ہو۔ پورا فنکشن ان منٹرمز کا او آر ہے۔", { type: "table", title: "Minterms of $Y$", headers: ["$A$", "$B$", "$Y$", "Minterm"], rows: [["0", "0", "0", "—"], ["0", "1", "1", "$\\overline{A} \\cdot B$"], ["1", "0", "1", "$A \\cdot \\overline{B}$"], ["1", "1", "1", "$A \\cdot B$"]], note: "$Y$ is 1 on three rows, so it has three minterms. The sum is $Y = \\overline{A}B + A\\overline{B} + AB$." }),
      b("Logic diagram", "A logic diagram draws the gates and the wires. Inputs enter from the left. Each gate does one job. The wire on the right is the output. Building Y equals A AND B in Logisim is one gate, two input pins, and one output pin.", "لاجک ڈایاگرام گیٹس اور تاروں کی تصویر ہے۔ ان پٹ بائیں سے آتے ہیں اور آؤٹ پٹ دائیں نکلتا ہے۔", { type: "diagram", diagram: "circuit", title: "Diagram for $Y = A \\cdot \\overline{B}$", note: "The triangle with a bubble is NOT. The D shape is AND. Inputs enter from the left." }),
      b("K-map", "A Karnaugh map is a grid that simplifies a Boolean expression. Neighboring cells differ by only one variable. That layout is Gray code. You circle groups of 1, 2, 4, or 8 cells.", "کارنو نقشہ بولین جملے کو سادہ بناتا ہے۔ پڑوسی خانے صرف ایک متغیر میں مختلف ہوتے ہیں۔", { type: "kmap", title: "Two-variable map", vars: ["A", "B"], cells: [0, 1, 1, 1], groups: [{ cells: [1, 3] }, { cells: [2, 3] }], expr: "$Y = A + B$", note: "The vertical pair keeps $B$. The horizontal pair keeps $A$." }),
      b("Three variables", "Three variables need eight cells, because 2 to the power 3 is 8. Columns use Gray code: 00, 01, 11, 10. Groups may wrap around the edges. Larger legal groups give simpler expressions. Never group a cell that holds 0.", "تین متغیرات کے لیے آٹھ خانے چاہییں۔ کالم گرے کوڈ میں ہوتے ہیں: 00، 01، 11، 10۔", { type: "kmap", title: "Three-variable shape", vars: ["A", "B", "C"], cells: [1, 1, 0, 1, 1, 1, 0, 1], expr: "$2^3 = 8$ cells", note: "Legal groups have $1, 2, 4,$ or $8$ cells. Columns use Gray code, so the outside edges are neighbors." }),
    ],
    quiz: [
      { q: "Which operation is applied first if there are no parentheses?", choices: ["OR", "AND", "NOT", "XOR"], answer: 2, why: "The usual order is NOT, then AND, then OR." },
      { q: "A legal K-map group can contain how many cells?", choices: ["Any count", "Only 3", "1, 2, 4, 8, …", "Only prime numbers"], answer: 2, why: "Groups must be powers of two so each group drops whole variables." },
      { q: "Neighboring K-map cells differ by…", choices: ["Every variable", "Exactly one variable", "No variables", "The output only"], answer: 1, why: "Gray code makes adjacent cells, including wrapped edges, one bit apart." },
    ],
  },
  {
    id: "xi-sdlc",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "SDLC, Waterfall, and Agile",
    golden: true,
    covers: ["1.2.1", "1.2.2", "1.2.3", "1.2.4", "1.2.5", "1.2.6", "1.2.7"],
    summary: "The life of a software project, from need to maintenance, in two rhythms.",
    outcomes: ["Name the main SDLC phases and their deliverables.", "Contrast Waterfall with Agile.", "Pick a model for a stable or a changing project."],
    beats: [
      b("A life cycle", "The software development life cycle is a structured path from a need to a working system that is kept healthy. Skipping a phase usually means paying for it later as bugs or rework.", "ایس ڈی ایل سی ضرورت سے لے کر دیکھ بھال تک سافٹ ویئر بنانے کا منظم راستہ ہے۔", { type: "board", kicker: "Golden topic · 1.2", title: "Six phases", points: ["Requirements", "Design", "Implementation", "Testing", "Deployment", "Maintenance"] }),
      b("First half", "Requirements ask what the users need and write it down. Design chooses structure, screens, and data. Implementation turns the design into code. Each phase should leave something a teammate can read.", "ضروریات بتاتی ہیں کہ صارف کو کیا چاہیے۔ ڈیزائن نقشہ بناتا ہے۔ عمل درآمد کوڈ لکھتا ہے۔", { type: "pipeline", title: "Opening phases", loop: false, steps: [{ name: "Requirements", detail: "User needs", note: "Deliverable: a requirements list." }, { name: "Design", detail: "Structure and screens", note: "Deliverable: diagrams and a plan." }, { name: "Implementation", detail: "Write the program", note: "Deliverable: source code." }] }),
      b("Second half", "Testing looks for failures against the requirements. Deployment puts the system where people can use it. Maintenance fixes defects and adapts the software as the world changes. Most of a system's life is maintenance.", "جانچ خامی تلاش کرتی ہے۔ تعیناتی نظام لوگوں تک پہنچاتی ہے۔ دیکھ بھال سب سے لمبا مرحلہ ہے۔", { type: "pipeline", title: "Closing phases", loop: false, steps: [{ name: "Testing", detail: "Find failures", note: "Deliverable: a test report." }, { name: "Deployment", detail: "Release to users", note: "Deliverable: a running system." }, { name: "Maintenance", detail: "Fix and adapt", note: "Deliverable: updates over years." }] }),
      b("Waterfall", "Waterfall is linear. A phase finishes before the next one starts. It fits when the requirements are stable and well understood, such as a rules-heavy school result system with a fixed format. Change is expensive because you walk back upstream.", "واٹر فال میں ہر مرحلہ اگلے سے پہلے مکمل ہوتا ہے۔ جب ضروریات مستحکم ہوں تو یہ موزوں ہے۔", { type: "pipeline", title: "Waterfall", loop: false, steps: [{ name: "Need", detail: "Freeze it", note: "The team treats the written need as fixed." }, { name: "Build", detail: "Follow the plan", note: "Design and code follow that frozen need." }, { name: "Ship", detail: "Test at the end", note: "Users often see the product late." }] }),
      b("Agile", "Agile builds in short cycles called sprints. Each sprint delivers a small working slice and asks users what to change. It fits a school app whose features are still being discovered. The plan is allowed to move.", "ایجائل چھوٹے اسپرت میں کام کرتا ہے۔ ہر اسپرت کے بعد صارف رائے دیتا ہے۔", { type: "cycle", title: "One sprint, then another", steps: [{ name: "Plan a slice", detail: "Choose a few stories" }, { name: "Build", detail: "Make it work" }, { name: "Review", detail: "Show it to users" }, { name: "Adjust", detail: "Change the next slice" }] }),
      b("Choose", "Waterfall values a complete plan and is brittle when the goal moves. Agile values working software and feedback, and it spends more time coordinating. Pick from the shape of the risk, not from fashion.", "اگر مقصد واضح اور مستحکم ہو تو واٹر فال، اگر سیکھتے ہوئے بدلنا ہو تو ایجائل۔", { type: "compare", title: "Waterfall or Agile", headers: ["", "Waterfall", "Agile"], rows: [["Rhythm", "One long sequence", "Repeated sprints"], ["Change", "Costly", "Expected"], ["User feedback", "Mostly at the end", "Every sprint"], ["Best fit", "Stable rules", "Uncertain needs"]], note: "A case study should name which risk is bigger: late discovery, or a moving target." }),
    ],
    quiz: [
      { q: "Which phase writes the code?", choices: ["Requirements", "Design", "Implementation", "Maintenance"], answer: 2, why: "Implementation turns the design into a program. Maintenance comes after release." },
      { q: "Waterfall is a poor fit when…", choices: ["Requirements are stable", "The main risk is that needs will change", "The output format is fixed by law", "The team wants a signed specification first"], answer: 1, why: "Waterfall finishes each phase before the next, so late changes travel back through the plan." },
      { q: "A sprint is…", choices: ["The final test report", "A short cycle that produces a working slice", "A type of logic gate", "Deployment only"], answer: 1, why: "Agile repeats plan, build, and review in sprints." },
    ],
  },
  {
    id: "xi-osi",
    track: "xi",
    level: "XI",
    chapter: "Computer Systems",
    title: "OSI and TCP/IP",
    golden: true,
    covers: ["1.3.1", "1.3.2", "1.3.3", "1.3.4", "1.3.5", "1.3.6"],
    summary: "How a message climbs a stack of jobs on its way to another device.",
    outcomes: ["Give the job of each OSI layer.", "Compare OSI with TCP/IP.", "Trace a message from app to cable and back."],
    beats: [
      b("Why a model", "A communication model splits networking into layers so each layer has one job. The sender walks down the stack. The receiver walks up. You can replace how one layer works without rewriting the others.", "مواصلاتی ماڈل کام کو تہوں میں بانٹتا ہے تاکہ ہر تہہ کا ایک کام ہو۔", { type: "board", kicker: "Golden topic · 1.3", title: "Layers cooperate", points: ["Sender encapsulates downward", "Receiver unwraps upward", "Each layer talks to its partner"] }),
      b("Seven layers", "From the user down to the wire: Application, Presentation, Session, Transport, Network, Data Link, and Physical. A memory line is All People Seem To Need Data Processing.", "اوپر سے نیچے: ایپلیکیشن، پریزنٹیشن، سیشن، ٹرانسپورٹ، نیٹ ورک، ڈیٹا لنک، فزیکل۔", { type: "layers", title: "OSI, top to bottom", layers: [{ name: "7 Application", job: "Services for the user", tag: "HTTP" }, { name: "6 Presentation", job: "Format, compress, encrypt", tag: "JPEG" }, { name: "5 Session", job: "Open and close dialogues", tag: "Session" }, { name: "4 Transport", job: "End-to-end delivery", tag: "TCP UDP" }, { name: "3 Network", job: "Address and route", tag: "IP" }, { name: "2 Data Link", job: "Frames on one link", tag: "MAC" }, { name: "1 Physical", job: "Bits on the medium", tag: "Cable" }], note: "The packet highlight walks from the cable upward, the way a receiver reads." }),
      b("Jobs worth marks", "Application is what people touch, such as the web. Transport numbers ports and can resend lost segments. Network moves packets across networks using IP addresses. Data Link delivers frames on the local link. Physical moves raw bits.", "ایپلیکیشن صارف کی خدمت ہے۔ ٹرانسپورٹ پورٹس سنبھالتا ہے۔ نیٹ ورک راستہ چنتا ہے۔", { type: "cards", title: "Five layers students mix up", items: [{ tag: "7", title: "Application", body: "Browser, mail, file transfer." }, { tag: "4", title: "Transport", body: "TCP is careful. UDP is quick." }, { tag: "3", title: "Network", body: "IP addresses and routing." }, { tag: "2 and 1", title: "Link and physical", body: "Local frames, then voltages or light." }] }),
      b("TCP/IP", "TCP/IP is the model the internet actually runs. It folds OSI's top three layers into one Application layer, keeps Transport, calls the routing layer Internet, and folds the bottom two into Network Access.", "ٹی سی پی آئی پی میں چار تہیں ہیں: ایپلیکیشن، ٹرانسپورٹ، انٹرنیٹ، اور نیٹ ورک ایکسس۔", { type: "layers", title: "TCP/IP", layers: [{ name: "Application", job: "OSI 5 + 6 + 7", tag: "HTTP DNS" }, { name: "Transport", job: "TCP or UDP", tag: "Ports" }, { name: "Internet", job: "IP routing", tag: "IP" }, { name: "Network Access", job: "OSI 1 + 2", tag: "Wi-Fi" }] }),
      b("Compare", "OSI is a careful teaching and design model with seven layers. TCP/IP is a four-layer working model. They are not enemies. Use OSI to name a job. Use TCP/IP to name what the internet deploys.", "او ایس آئی سات تہوں کا تعلیمی ماڈل ہے۔ ٹی سی پی آئی پی انٹرنیٹ کا عملی ماڈل ہے۔", { type: "compare", title: "OSI beside TCP/IP", headers: ["OSI", "TCP/IP"], rows: [["Application, Presentation, Session", "Application"], ["Transport", "Transport"], ["Network", "Internet"], ["Data Link, Physical", "Network Access"]], note: "If a question says 'which model has seven layers', the answer is OSI." }),
    ],
    quiz: [
      { q: "Which OSI layer chooses a route using IP addresses?", choices: ["Physical", "Data Link", "Network", "Session"], answer: 2, why: "Routing between networks is the Network layer's job." },
      { q: "TCP and UDP belong to which layer?", choices: ["Physical", "Transport", "Presentation", "Session"], answer: 1, why: "They provide end-to-end transport, with ports." },
      { q: "TCP/IP's Application layer corresponds to which OSI layers?", choices: ["1 and 2", "3 only", "5, 6, and 7", "4 only"], answer: 2, why: "TCP/IP merges Application, Presentation, and Session." },
    ],
  },
  {
    id: "xi-ct",
    track: "xi",
    level: "XI",
    chapter: "Computational Thinking",
    title: "Computational thinking and algorithms",
    golden: true,
    covers: ["2.1", "2.2", "2.2.2", "2.3.1", "2.3.2", "2.3.3"],
    summary: "Break a problem down, spot a pattern, hide extra detail, then write steps.",
    outcomes: ["Use decomposition, patterns, and abstraction.", "Separate an algorithm from pseudocode.", "Write a short pseudocode for a familiar task."],
    beats: [
      b("Four moves", "Computational thinking is a way of attacking problems. You break them up, notice what repeats, ignore what does not matter, and then write steps a computer could follow.", "کمپیوٹیشنل تھنکنگ مسئلے کو توڑنے، نمونہ پہچاننے، غیر ضروری ہٹانے، اور مراحل لکھنے کا طریقہ ہے۔", { type: "cards", title: "Four habits", items: [{ tag: "2.3.1", title: "Decomposition", body: "Split a big problem into smaller problems." }, { tag: "2.3.2", title: "Patterns", body: "Find what repeats so you solve it once." }, { tag: "2.3.3", title: "Abstraction", body: "Keep only the details the solution needs." }, { tag: "2.2", title: "Algorithms", body: "Write finite, ordered, clear steps." }] }),
      b("Decomposition", "A school timetable looks huge until you split it. Rooms are one subproblem. Teachers are another. Clashes are a third. Each piece can be solved and tested on its own, then joined.", "بڑے مسئلے کو چھوٹے حصوں میں بانٹیں، جیسے ٹائم ٹیبل میں کمرے، اساتذہ، اور ٹکراؤ الگ مسئلے ہیں۔", { type: "pipeline", title: "Timetable, decomposed", loop: false, steps: [{ name: "Rooms", detail: "What is free?", note: "One subproblem." }, { name: "Teachers", detail: "Who is free?", note: "A second subproblem." }, { name: "Clashes", detail: "Who collides?", note: "A third, then you join them." }] }),
      b("Pattern and abstraction", "Pattern recognition sees that every student record needs a name and a roll number. Abstraction then drops the student's favorite color if the task is only attendance. Less detail means a smaller algorithm.", "نمونہ بتاتا ہے کہ ہر ریکارڈ میں نام اور رول نمبر ہے۔ تجرید غیر ضروری رنگ پسند ہٹا دیتی ہے۔", { type: "split", title: "Keep or drop", left: { eyebrow: "Pattern", title: "What repeats", lines: ["Every record has a name", "Every record has a roll number", "The check is the same each time"] }, right: { eyebrow: "Abstraction", title: "What we ignore", lines: ["Shoe size", "Favorite color", "Anything the question did not ask"] } }),
      b("Algorithm versus pseudocode", "An algorithm is the procedure: ordered steps that finish and produce a result. Pseudocode is one way to write it, in structured plain language, not in a specific programming language. Flowcharts are another way.", "الگورتھم مراحل کا طریقہ ہے۔ سوڈو کوڈ اسے سادہ زبان میں لکھنے کا ایک انداز ہے۔", { type: "compare", title: "Do not mix the names", headers: ["", "Algorithm", "Pseudocode"], rows: [["What it is", "The procedure itself", "A way of writing it"], ["Must it run as-is?", "It must be precise", "It is for humans"], ["Also written as", "Flowchart or code", "Indented plain steps"]], note: "A vague wish is neither an algorithm nor pseudocode." }),
      b("Find the max", "Here is pseudocode for the largest number in a list. Start with the first value as the best. Visit each remaining value. If it is larger, it becomes the best. When the list ends, report the best.", "فہرست کی سب سے بڑی عدد کے لیے پہلے نمبر کو بہترین مانیں، پھر ہر عدد سے موازنہ کریں۔", { type: "code", title: "Pseudocode · maximum", lines: ["best ← first value", "for each other value x", "    if x > best then best ← x", "report best"], active: [2], note: "The steps are finite, ordered, and unambiguous." }),
    ],
    quiz: [
      { q: "Ignoring details that the problem does not need is called…", choices: ["Decomposition", "Abstraction", "Deployment", "Encryption"], answer: 1, why: "Abstraction hides unnecessary features and keeps the essential ones." },
      { q: "Pseudocode is…", choices: ["Machine code", "A human-readable draft of an algorithm", "A logic gate", "A network layer"], answer: 1, why: "Pseudocode writes the algorithm in structured plain language." },
      { q: "Splitting a timetable into rooms, teachers, and clashes is…", choices: ["Pattern recognition", "Decomposition", "Waterfall", "A truth table"], answer: 1, why: "Decomposition breaks one problem into smaller problems." },
    ],
  },
  {
    id: "xi-sort",
    track: "xi",
    level: "XI",
    chapter: "Computational Thinking",
    title: "Bubble sort and selection sort",
    golden: true,
    covers: ["2.4", "2.4.1"],
    summary: "Two simple sorts you can trace by hand on a short list.",
    outcomes: ["Trace one pass of bubble sort.", "Trace selection sort's search for the minimum.", "Say what both algorithms cost on large lists."],
    beats: [
      b("Why sort", "Sorting puts a list into order. Searching is faster on sorted data, and reports are easier to read. Bubble sort and selection sort are simple teaching algorithms. Both are slow on long lists.", "ترتیب فہرست کو ترتیب دیتی ہے۔ یہ دونوں طریقے سمجھنے میں آسان ہیں مگر لمبی فہرست پر سست ہیں۔", { type: "board", kicker: "2.4", title: "Start with 8, 4, 1, 9, 3", points: ["Bubble sort swaps neighbors", "Selection sort picks the minimum", "Both end with 1, 3, 4, 8, 9"] }),
      b("Bubble sort", "Bubble sort compares neighbors and swaps them if they are out of order. Large values bubble toward the end. After the first pass on this list, 9 is in its final place. Later passes fix the rest.", "ببل سارٹ پڑوسیوں کا موازنہ کر کے انہیں بدل دیتا ہے۔ بڑی قیمت آخر کی طرف بڑھتی ہے۔", { type: "bars", title: "Bubble sort · first pass", ms: 900, frames: [{ values: [8, 4, 1, 9, 3], hi: [0, 1], note: "8 and 4 are out of order." }, { values: [4, 8, 1, 9, 3], hi: [1, 2], note: "Swap. Now compare 8 and 1." }, { values: [4, 1, 8, 9, 3], hi: [2, 3], note: "Swap. 8 and 9 are already in order." }, { values: [4, 1, 8, 3, 9], hi: [3, 4], placed: [4], note: "9 and 3 swap. 9 has bubbled to the end." }] }),
      b("Selection sort", "Selection sort scans the unsorted part, finds the smallest value, and swaps it into the next open position. It does at most one swap per pass. On this list the first scan finds 1 and parks it at the front.", "سیلیکشن سارٹ ہر چکر میں سب سے چھوٹی قیمت ڈھونڈ کر اس کی جگہ پر رکھتا ہے۔", { type: "bars", title: "Selection sort", ms: 1000, frames: [{ values: [8, 4, 1, 9, 3], hi: [2], note: "The smallest of all is 1." }, { values: [1, 4, 8, 9, 3], hi: [4], placed: [0], note: "1 is placed. The smallest of the rest is 3." }, { values: [1, 3, 8, 9, 4], hi: [4], placed: [0, 1], note: "3 is placed. Next smallest is 4." }, { values: [1, 3, 4, 9, 8], hi: [3, 4], placed: [0, 1, 2], note: "Swap 9 and 8." }, { values: [1, 3, 4, 8, 9], placed: [0, 1, 2, 3, 4], note: "The list is sorted." }] }),
      b("Compare them", "Both algorithms use nested loops, so the work grows like n squared. Bubble sort swaps many times. Selection sort swaps once per pass but still looks at every remaining pair of positions. For large data, better sorts exist. For a short exam trace, these two are the ones to practice.", "دونوں کا وقت تقریباً این اسکوائر بڑھتا ہے۔ ببل زیادہ بار بدلتا ہے، سیلیکشن ہر چکر میں ایک بار۔", { type: "compare", title: "Bubble and selection", headers: ["", "Bubble", "Selection"], rows: [["Move", "Swap neighbors", "Swap the minimum into place"], ["Swaps", "Many", "One per pass"], ["After pass 1", "Largest is at the end", "Smallest is at the front"], ["Growth", "About n squared", "About n squared"]] }),
    ],
    quiz: [
      { q: "After one bubble-sort pass that pushes the largest value right, where is that value?", choices: ["At the front", "In the middle", "In its final position at the end", "Deleted"], answer: 2, why: "Each pass bubbles the next largest unsorted value to the end." },
      { q: "Selection sort's main work each pass is…", choices: ["Finding the minimum of the unsorted part", "Reversing the list", "Building a truth table", "Opening a file"], answer: 0, why: "It selects the smallest remaining value and places it next." },
      { q: "Why are both sorts called slow for large n?", choices: ["They need sorted input", "Nested loops make the work grow like n squared", "They only sort letters", "They use the network layer"], answer: 1, why: "Each pass looks through the list, and there are many passes." },
    ],
  },
  {
    id: "xi-search",
    track: "xi",
    level: "XI",
    chapter: "Computational Thinking",
    title: "Linear search and binary search",
    golden: true,
    covers: ["2.4.2"],
    summary: "Check every item, or cut a sorted list in half again and again.",
    outcomes: ["Trace a linear search.", "Trace a binary search, including the midpoint.", "State the sorted-data requirement."],
    beats: [
      b("Two searches", "Linear search walks from the start until it finds the target or finishes the list. It works on unsorted data. Binary search jumps to the middle and throws away half the list, but only if the list is sorted.", "لینیئر سرچ ایک ایک کر کے دیکھتی ہے۔ بائنری سرچ درمیان سے آدھی فہرست ہٹا دیتی ہے، مگر فہرست مرتب ہونی چاہیے۔", { type: "board", kicker: "Golden topic · 2.4.2", title: "Find 7, or find 3", points: ["Linear: visit every cell if you must", "Binary: only on sorted data", "Binary asks less as the list grows"] }),
      b("Linear", "The list is 8, 3, 6, 1, 7, 2, 4, 5. Searching for 7, we reject 8, 3, 6, and 1. The fifth cell matches. If the target were missing, we would scan every cell and then report failure.", "فہرست میں سات پانچویں جگہ ہے۔ اس سے پہلے چار عدد مسترد ہوتے ہیں۔", { type: "cells", title: "Linear search for 7", values: [8, 3, 6, 1, 7, 2, 4, 5], frames: [{ focus: [0], note: "8 is not 7." }, { focus: [1], note: "3 is not 7." }, { focus: [2], note: "6 is not 7." }, { focus: [3], note: "1 is not 7." }, { focus: [4], found: 4, note: "7 matches. Stop." }] }),
      b("Binary setup", "Binary search keeps a low index and a high index. The middle is the average, rounded down. If the middle value is too small, low moves to just after the middle. If it is too large, high moves to just before the middle.", "لو اور ہائی انڈیکس رکھیں۔ درمیان کی قیمت چھوٹی ہو تو لو آگے بڑھائیں، بڑی ہو تو ہائی پیچھے لائیں۔", { type: "cards", title: "The three indexes", items: [{ tag: "low", title: "Left edge", body: "First index that might still hold the target." }, { tag: "high", title: "Right edge", body: "Last index that might still hold it." }, { tag: "mid", title: "Middle", body: "Compare this cell, then drop a half." }] }),
      b("Binary trace", "Sorted list: 1 through 8. Target: 3. Middle of the whole list is 4. That is too big, so the right half dies. The new middle is 2, still too big. The next middle is 3. Found.", "مرتب فہرست میں تین ڈھونڈتے ہوئے پہلے چار بڑا نکلتا ہے، پھر دائیں حصہ چھوڑ دیا جاتا ہے۔", { type: "cells", title: "Binary search for 3", values: [1, 2, 3, 4, 5, 6, 7, 8], ms: 1300, frames: [{ low: 0, high: 7, mid: 3, note: "Middle value 4 is too big. high becomes 2." }, { low: 0, high: 2, mid: 1, note: "Middle value 2 is too small. low becomes 2." }, { low: 2, high: 2, mid: 2, found: 2, note: "Middle value 3 matches." }] }),
      b("Choose", "If the data is unsorted and the list is short, linear search is honest and simple. If you will search a long sorted list many times, binary search pays for the sorting. Never run binary search on unsorted data. It will throw away the half that actually holds the answer.", "غیر مرتب ڈیٹا پر بائنری سرچ استعمال نہ کریں۔ وہ صحیح آدھا حصہ بھی پھینک سکتی ہے۔", { type: "compare", title: "Which search", headers: ["", "Linear", "Binary"], rows: [["Data", "Any order", "Must be sorted"], ["Method", "One by one", "Halve the range"], ["Growth", "Proportional to n", "Proportional to log n"], ["Miss", "Scan all", "Range becomes empty"]] }),
    ],
    quiz: [
      { q: "Binary search requires…", choices: ["Unsorted data", "Sorted data", "Exactly three items", "A truth table"], answer: 1, why: "Throwing away a half is only valid when order tells you which half cannot contain the target." },
      { q: "Linear search on an unsorted list of n items may inspect…", choices: ["Only the middle", "Every item, if the target is last or missing", "Only two items", "No items"], answer: 1, why: "There is no reason to stop early if you have not seen the target." },
      { q: "The middle value is greater than the target. What changes?", choices: ["low moves above the middle", "high moves below the middle", "The list is reversed", "The search always restarts"], answer: 1, why: "The target cannot sit at the middle or to its right, so high moves just left of mid." },
    ],
  },
  {
    id: "xi-eval",
    track: "xi",
    level: "XI",
    chapter: "Computational Thinking",
    title: "Evaluating and choosing an algorithm",
    golden: false,
    covers: ["2.5", "2.5.1", "2.6"],
    summary: "Correct, clear, and cheap enough for the data you actually have.",
    outcomes: ["Judge correctness, clarity, and efficiency.", "Ask the questions that pick an algorithm.", "Reject a fast algorithm that needs data you do not have."],
    beats: [
      b("Three questions", "An algorithm is correct if the output matches the expected result, including awkward cases such as an empty list. It is clear if another person can read and change it. It is efficient enough if it finishes with the time and memory you have.", "صحیح الگورتھم متوقع جواب دیتا ہے۔ واضح الگورتھم پڑھا جا سکتا ہے۔ موثر الگورتھم وقت اور میموری میں سمٹتا ہے۔", { type: "cards", title: "Evaluation", items: [{ tag: "2.5.1", title: "Correctness", body: "Right answers, including edge cases." }, { tag: "Clarity", title: "Readable steps", body: "Names and structure a classmate can follow." }, { tag: "Efficiency", title: "Time and memory", body: "Good enough for the size of the input." }] }),
      b("Edge cases", "Correctness is not one happy example. Ask what happens if the list is empty, if it has one item, if the target is missing, and if every value is identical. An algorithm that fails those tests is not correct yet.", "خالی فہرست، ایک عنصر، اور غائب ہدف بھی جانچیں۔ صرف خوشگوار مثال کافی نہیں۔", { type: "table", title: "Tests for 'find the maximum'", headers: ["Case", "Expected"], rows: [["Empty list", "A clear failure, not a crash"], ["One value", "That value"], ["All equal", "That shared value"], ["Negatives", "The least negative, or the greatest"]] }),
      b("How to choose", "Before you pick, ask four practical questions. How large is the input? Is it sorted already? Do you need the absolute fastest, or the easiest to get right? Will you search once, or thousands of times?", "پہلے پوچھیں: ڈیٹا کتنا بڑا ہے، مرتب ہے یا نہیں، اور تلاش ایک بار ہو گی یا بار بار؟", { type: "pipeline", title: "Decision pass", loop: false, steps: [{ name: "Size", detail: "Tens, or millions?", note: "A tiny list can use a simple algorithm." }, { name: "Order", detail: "Sorted yet?", note: "Binary search is illegal until it is." }, { name: "Repeats", detail: "One use or many?", note: "Sorting once can pay for many searches." }, { name: "Clarity", detail: "Who maintains it?", note: "A clear n-squared sort can beat a clever bug." }] }),
      b("A choice", "For eight classroom marks, linear search is fine. For a sorted national exam file searched all day, binary search is the point of keeping the file sorted. Speed that depends on a lie about the data is not speed.", "چھوٹی فہرست پر سادہ تلاش ٹھیک ہے۔ بڑی مرتب فہرست پر بائنری سرچ۔", { type: "callout", eyebrow: "Rule of thumb", title: "Match the algorithm to the data you really have", body: "Ask about size, order, and how often the task repeats before you argue about cleverness." }),
    ],
    quiz: [
      { q: "An algorithm can be fast and still be a bad choice if it is…", choices: ["Correct on edge cases", "Impossible to understand or wrong on empty input", "Written in pseudocode", "Finite"], answer: 1, why: "Correctness and clarity are part of the evaluation, not optional extras." },
      { q: "Which fact most strongly allows binary search?", choices: ["The list is short", "The list contains only positive numbers", "The list is sorted", "The list is stored in a phone"], answer: 2, why: "Order is the requirement. Size only changes whether it is worth it." },
      { q: "Why test an empty list?", choices: ["Empty lists are the fastest networks", "Edge cases reveal missing rules", "Truth tables require them", "Agile forbids them"], answer: 1, why: "A procedure that only works on a friendly example is not yet correct." },
    ],
  },
  {
    id: "xi-python",
    track: "xi",
    level: "XI",
    chapter: "Programming Fundamentals",
    title: "Python values, variables, and operators",
    golden: true,
    covers: ["3.1", "3.2", "3.3", "3.4", "3.4.1", "3.4.2", "3.4.3"],
    summary: "What a program is, where names store data, and how operators combine it.",
    outcomes: ["Describe a program and an IDE.", "Use variables, types, input, and print.", "Choose arithmetic, comparison, and logical operators."],
    beats: [
      b("Programs", "A computer does not invent the task. A program is a set of instructions. Python is a high-level language: closer to English than to the processor, and the same source can run on many machines. An IDE such as VS Code is the workshop where you edit, run, and debug.", "پروگرام ہدایات کا مجموعہ ہے۔ Python ایک ہائی لیول زبان ہے، اور IDE وہ جگہ ہے جہاں کوڈ لکھا اور چلایا جاتا ہے۔", { type: "cards", title: "Languages sit at different heights", items: [{ tag: "High-level", title: "Python", body: "Readable, with a huge set of libraries." }, { tag: "High-level", title: "C++", body: "Powerful and closer to the machine." }, { tag: "Workshop", title: "IDE", body: "Editor, runner, and error messages together." }] }),
      b("Variables", "A variable is a name for a place in memory. Write count equals 30 and Python stores the integer 30 under that name. You may later assign a new value. Names should say what they hold: total, not t.", "ویری ایبل میموری میں نام کی جگہ ہے۔ نام سے مطلب واضح ہونا چاہیے۔", { type: "code", title: "Names and values", lines: ["students = 30", "average = 72.5", "section = \"XI\"", "passed = True"], active: [0], note: "The type comes from the value you store." }),
      b("Types and input", "Integers, floats, strings, and Booleans are everyday types. input always returns text. If you need a number, convert it. print displays a value. Forgetting the conversion is a classic bug: \"10\" plus \"2\" becomes \"102\", while 10 plus 2 is 12.", "input ہمیشہ متن دیتا ہے۔ عدد چاہیے تو اسے تبدیل کریں، ورنہ 10 اور 2 جوڑ کر 102 بن جائیں گے۔", { type: "code", title: "Read a number", lines: ["name = input(\"Name: \")", "marks = int(input(\"Marks: \"))", "print(name, marks)"], active: [1], note: "int converts the text into an integer." }),
      b("Operators", "An operand is a value. An operator is the symbol that acts on it. Arithmetic operators compute. Comparison operators ask a yes-or-no question and return True or False. Logical operators and, or, and not combine those answers.", "آپریٹر وہ نشان ہے جو قیمتوں پر عمل کرتا ہے۔ موازنہ درست یا غلط لوٹاتا ہے۔", { type: "table", title: "Operators you will trace", headers: ["Kind", "Symbols", "Example"], rows: [["Arithmetic", "+  -  *  /  //  %", "7 // 2 is 3"], ["Comparison", "==  !=  >  <", "marks >= 40"], ["Logical", "and  or  not", "age > 16 and passed"]] }),
      b("Bitwise preview", "Bitwise operators look at the bits inside an integer. AND, OR, XOR, and shifts are the same ideas as logic gates, applied to every bit. You do not need them for a bill calculator, but they connect this chapter to digital circuits.", "بٹ وائز آپریٹر عدد کے بٹس پر لاجک گیٹس کی طرح عمل کرتے ہیں۔", { type: "bits", title: "5 is 101, 3 is 011", rows: [{ bit: "101", meanings: ["5"] }, { bit: "011", meanings: ["3"] }, { bit: "001", meanings: ["5 AND 3 = 1"] }], note: "A bitwise AND keeps a bit only where both numbers have 1." }),
    ],
    quiz: [
      { q: "What does input() return?", choices: ["Always an integer", "Always text", "Always a Boolean", "A logic gate"], answer: 1, why: "Convert with int or float when you need a number." },
      { q: "Which expression is a comparison?", choices: ["total + 5", "marks >= 40", "int(\"7\")", "print(name)"], answer: 1, why: "Comparison operators return True or False." },
      { q: "A variable is…", choices: ["A named place that stores a value", "A network cable", "An OSI layer", "Only a string"], answer: 0, why: "The name lets the program read and replace the stored value." },
    ],
  },
  {
    id: "xi-control",
    track: "xi",
    level: "XI",
    chapter: "Programming Fundamentals",
    title: "Sequence, selection, and loops",
    golden: true,
    covers: ["3.5", "3.5.2", "3.5.3"],
    summary: "Programs run in order, choose with conditions, and repeat with loops.",
    outcomes: ["Trace if, elif, and else.", "Choose for or while.", "Explain a nested loop."],
    beats: [
      b("Sequence", "By default Python runs top to bottom, one statement after another. That order is sequence. If you swap two lines, you can easily use a value before it exists.", "عام طور پر Python اوپر سے نیچے چلتا ہے۔ اس ترتیب کو سیکوئنس کہتے ہیں۔", { type: "flow", title: "Sequence", nodes: [{ id: "a", text: "Read price", kind: "start" }, { id: "b", text: "Read quantity", kind: "step" }, { id: "c", text: "Compute total", kind: "end" }], order: ["a", "b", "c"] }),
      b("Selection", "Selection chooses a path from a condition. if runs its block only when the condition is true. else runs when it is false. elif adds more conditions and stops at the first true one. Indentation is the block, not braces.", "if شرط سچ ہو تو چلتا ہے۔ elif اگلی شرط دیکھتا ہے۔ else تب چلتا ہے جب کوئی شرط سچ نہ ہو۔", { type: "flow", title: "Grade band", nodes: [{ id: "q", text: "marks >= 80?", kind: "decision" }, { id: "a", text: "Distinction", kind: "step" }, { id: "b", text: "marks >= 40?", kind: "decision" }, { id: "c", text: "Pass or fail", kind: "end" }], order: ["q", "a", "b", "c"] }),
      b("for loop", "A for loop repeats once for each item in a collection, or for each number in a range. Use it when you know what you are walking through: every price in a cart, or the numbers 1 to 10.", "for تب موزوں ہے جب معلوم ہو کہ کن چیزوں پر چلنا ہے، جیسے ٹوکری کی ہر قیمت۔", { type: "code", title: "Add a cart", lines: ["total = 0", "for price in cart:", "    total = total + price", "print(total)"], active: [1], note: "The indented line is the body. It runs once per price." }),
      b("while loop", "A while loop repeats as long as its condition stays true. Use it when you do not know the count in advance, such as 'keep reading until the user types stop'. Something inside the loop must eventually make the condition false, or it never ends.", "while تب تک چلتا ہے جب تک شرط سچ رہے۔ اندر کوئی چیز شرط کو جھوٹ ضرور کرے۔", { type: "code", title: "Until the user says stop", lines: ["word = input()", "while word != \"stop\":", "    print(word)", "    word = input()"], active: [1], note: "Forgetting the second input leaves word unchanged forever." }),
      b("Nested and a bill", "A nested loop is a loop inside a loop. The inner loop finishes completely for each step of the outer loop. A shopping bill uses all three structures: sequence to read data, selection to apply a discount, and a loop to visit every item.", "اندر والا حلقہ باہر والے کے ہر قدم پر مکمل چلتا ہے۔ بل میں ترتیب، انتخاب، اور تکرار تینوں ملتے ہیں۔", { type: "code", title: "Discount if the total is high", lines: ["total = 0", "for price in cart:", "    total = total + price", "if total > 5000:", "    total = total * 0.9", "print(total)"], active: [3], note: "The if is not inside the loop. It runs once, after the sum exists." }),
    ],
    quiz: [
      { q: "Which statement adds another condition after if?", choices: ["for", "elif", "import", "while"], answer: 1, why: "elif is checked only if earlier conditions were false." },
      { q: "A while loop never ends when…", choices: ["The condition becomes false", "Nothing ever makes the condition false", "It contains print", "It is indented"], answer: 1, why: "The condition must change. Otherwise the body repeats forever." },
      { q: "In Python, a block of statements is grouped by…", choices: ["Curly braces only", "Indentation", "The word begin", "Line color"], answer: 1, why: "The indented lines under if or for belong to that statement." },
    ],
  },
  {
    id: "xi-debug",
    track: "xi",
    level: "XI",
    chapter: "Programming Fundamentals",
    title: "Libraries, errors, and tracebacks",
    golden: false,
    covers: ["3.6", "3.6.1", "3.6.2"],
    summary: "Reuse trusted code, then read the error instead of guessing.",
    outcomes: ["Tell a built-in library from a third-party one.", "Classify syntax, runtime, and logic errors.", "Read a traceback from the bottom up."],
    beats: [
      b("Libraries", "A library is code someone else already tested. Built-in libraries ship with Python. You import math and call math.sqrt. Third-party libraries are installed, often with pip, because they are not included. Use a library when it solves your problem. Do not import a mystery package you do not need.", "لائبریری پہلے سے لکھا ہوا کوڈ ہے۔ کچھ Python کے ساتھ آتی ہیں اور کچھ pip سے نصب ہوتی ہیں۔", { type: "split", title: "Where the code comes from", left: { eyebrow: "Built in", title: "Already installed", lines: ["math, random, statistics", "import math", "No extra install"] }, right: { eyebrow: "Third party", title: "Install first", lines: ["Made by the community", "pip install package", "Then import it"] } }),
      b("Three bugs", "A syntax error breaks the grammar, so the program does not start. A missing colon or a bad indent is syntax. A runtime error starts, then fails, such as dividing by zero or converting 'ten' with int. A logic error runs and gives the wrong answer, such as using plus when you meant minus.", "نحو کی غلطی پروگرام شروع نہیں ہونے دیتی۔ رن ٹائم غلطی چلتے ہوئے آتی ہے۔ منطق کی غلطی غلط جواب دیتی ہے۔", { type: "cards", title: "Name the bug before you fix it", items: [{ tag: "Syntax", title: "Grammar", body: "The file will not run. Look at the caret." }, { tag: "Runtime", title: "Illegal action", body: "Division by zero, missing file, bad int()." }, { tag: "Logic", title: "Wrong idea", body: "It runs. The answer is still wrong." }] }),
      b("Traceback", "When Python crashes it prints a traceback. Read the last line first: that is the error type and message. Above it, the file name and line number show where it failed. Then look at your code on that line, and one line earlier.", "ٹریس بیک کی آخری سطر غلطی کا نام بتاتی ہے۔ اوپر لائن نمبر بتاتا ہے کہ کہاں رکے۔", { type: "code", title: "A traceback points here", lines: ["marks = int(input())", "ZeroDivisionError: division by zero", "average = total / count"], active: [2], note: "The crash is on the division. The cause may be that count is still 0." }),
      b("A repair habit", "Reproduce the bug with the smallest input. Read the message. Change one thing. Run again. A logic error needs a trace: write down the variables after each line, the same way you trace an algorithm.", "پہلے غلطی دہرائیں، پیغام پڑھیں، ایک چیز بدلیں، پھر دوبارہ چلائیں۔", { type: "cycle", title: "Debug loop", steps: [{ name: "Reproduce", detail: "Smallest failing input" }, { name: "Read", detail: "Last traceback line" }, { name: "Change one thing", detail: "Do not rewrite everything" }, { name: "Retest", detail: "Including the edge case" }] }),
    ],
    quiz: [
      { q: "A missing colon on an if line is usually…", choices: ["A logic error", "A syntax error", "A network error", "A correct program"], answer: 1, why: "The program violates Python grammar, so it does not start." },
      { q: "int('ten') fails as…", choices: ["A syntax error before running", "A runtime error", "A successful float", "An import"], answer: 1, why: "The text is legal Python. The conversion fails while running." },
      { q: "math is available after…", choices: ["pip install math, always", "import math, because it is built in", "Opening Logisim", "A truth table"], answer: 1, why: "Built-in libraries ship with Python. You still import them." },
    ],
  },
  {
    id: "xi-db",
    track: "xi",
    level: "XI",
    chapter: "Data and Analysis",
    title: "Databases, tables, and keys",
    golden: true,
    covers: ["4.1.1", "4.1.2", "4.2", "4.3.1"],
    summary: "From raw facts to a managed table, and the keys that keep rows unique.",
    outcomes: ["Separate data, information, and a database.", "Name tables, records, and fields.", "Choose a primary key and spot a foreign key."],
    beats: [
      b("Data and information", "Data is raw facts: 42, Ali, 17. Information is data arranged so it means something: Ali scored 42 in the test. A database is an organized collection of related data, stored so many people can use it without tripping over each other's copies.", "ڈیٹا خام حقائق ہیں۔ انفارمیشن وہی ڈیٹا ہے جب اس کا مطلب بن جائے۔ ڈیٹابیس متعلقہ ڈیٹا کا منظم ذخیرہ ہے۔", { type: "split", title: "Facts and meaning", left: { eyebrow: "Data", title: "Raw", lines: ["42", "Ali", "17"] }, right: { eyebrow: "Information", title: "Arranged", lines: ["Ali scored 42", "He is in section XI-B", "The fact answers a question"] } }),
      b("DBMS and tables", "A database management system, such as MS Access, stores the data, checks rules, and lets you ask questions. Inside it, a table holds one kind of thing. A row is a record. A column is a field.", "ڈی بی ایم ایس ڈیٹا سنبھالتا ہے۔ جدول میں قطار ریکارڈ ہے اور کالم فیلڈ۔", { type: "table", title: "Table: Student", headers: ["roll_no", "name", "section"], rows: [["XI-014", "Ali", "B"], ["XI-015", "Hina", "B"], ["XI-022", "Omar", "A"]], note: "Three records. Three fields. One table." }),
      b("Primary key", "A primary key uniquely identifies each row and must not be empty. Roll number can be a primary key. Student name cannot, because two students can share a name. A candidate key is any field that could have been the primary key. The ones you did not pick are alternate keys.", "پرائمری کی ہر قطار کو منفرد بناتی ہے اور خالی نہیں ہو سکتی۔ نام پرائمری کی نہیں بن سکتا۔", { type: "cards", title: "Keys", items: [{ tag: "Primary", title: "The chosen id", body: "Unique and required. One per table in the simple model." }, { tag: "Candidate", title: "Could have been chosen", body: "Any unique identifier, including the primary key." }, { tag: "Alternate", title: "The ones left over", body: "Candidate keys you did not select." }, { tag: "Foreign", title: "A reference", body: "A field that points at another table's primary key." }] }),
      b("Foreign key", "If a Marks table stores roll_no, that field is a foreign key when it must match a real student. The DBMS can refuse an orphan mark for a student who does not exist. That rule is integrity, and the next lecture stays with it.", "فارن کی دوسری جدول کی پرائمری کی کی طرف اشارہ کرتی ہے، تاکہ یتیم ریکارڈ نہ بنے۔", { type: "er", title: "A mark belongs to a student", entities: [{ name: "Student", attrs: [{ name: "roll_no", key: true }, { name: "name" }] }, { name: "Mark", attrs: [{ name: "mark_id", key: true }, { name: "roll_no", key: true }, { name: "score" }] }], links: ["Mark.roll_no references Student.roll_no"], note: "The key highlight marks identifying fields." }),
    ],
    quiz: [
      { q: "A row in a table is a…", choices: ["Field", "Record", "Primary key always", "Query"], answer: 1, why: "A record is one row. A field is a column." },
      { q: "Which field is the safest primary key?", choices: ["Student name", "City", "A unique roll number", "Favorite color"], answer: 2, why: "Names and cities repeat. A primary key must identify one row." },
      { q: "Information differs from data because it…", choices: ["Is always numeric", "Is processed so it has meaning", "Cannot be stored", "Has no structure"], answer: 1, why: "Data is raw. Information answers a question." },
    ],
  },
  {
    id: "xi-er",
    track: "xi",
    level: "XI",
    chapter: "Data and Analysis",
    title: "ER models and referential integrity",
    golden: true,
    covers: ["4.4", "4.5", "4.6", "4.7"],
    summary: "Entities, relationships, and the rule that keeps references honest.",
    outcomes: ["Draw entities, attributes, and relationships.", "Classify one-to-one, one-to-many, and many-to-many.", "Explain referential integrity and a bridge table."],
    beats: [
      b("ER model", "An entity-relationship model is a plan you draw before you build the database. An entity is a thing, such as Student or Book. An attribute is a fact about it. A relationship is how entities act on each other, such as borrows.", "ای آر ماڈل ڈیٹابیس سے پہلے کا نقشہ ہے۔ اینٹیٹی چیز ہے، ایٹریبیوٹ اس کی خصوصیت، اور ریلیشن شپ ان کا تعلق۔", { type: "er", title: "College library", entities: [{ name: "Student", attrs: [{ name: "student_id", key: true }, { name: "name" }] }, { name: "Book", attrs: [{ name: "book_id", key: true }, { name: "title" }] }], links: ["Student borrows Book"] }),
      b("Three relationships", "One-to-one: a student has one current library card. One-to-many: one author writes many books. Many-to-many: one student borrows many books over time, and one book is borrowed by many students. Relational tables do not store a many-to-many link directly.", "ون ٹو ون، ون ٹو مینی، اور مینی ٹو مینی۔ آخری تعلق براہ راست جدول میں نہیں رکھا جاتا۔", { type: "cards", title: "Relationship types", items: [{ tag: "1 : 1", title: "One card", body: "Each student has one current card, and that card has one student." }, { tag: "1 : N", title: "One author", body: "One author, many books. The book stores the author's key." }, { tag: "M : N", title: "Borrowing", body: "Needs a new table in the middle." }] }),
      b("Bridge table", "To store borrowing, add an entity Loan. Each loan points at one student and one book, and it can store the due date. Many loans per student and many loans per book turn one many-to-many relationship into two one-to-many relationships.", "لون کی جدول درمیان میں آتی ہے۔ ہر قرض ایک طالب علم اور ایک کتاب کی طرف اشارہ کرتا ہے۔", { type: "er", title: "Many-to-many becomes Loan", entities: [{ name: "Student", attrs: [{ name: "student_id", key: true }] }, { name: "Loan", attrs: [{ name: "loan_id", key: true }, { name: "due" }] }, { name: "Book", attrs: [{ name: "book_id", key: true }] }], links: ["Student 1—N Loan", "Book 1—N Loan"], note: "The schema is the written form of this picture." }),
      b("Referential integrity", "Referential integrity says a foreign key must match an existing primary key, or be empty if the rule allows it. You should not record a loan for student 999 if that student is not in the Student table. The DBMS can block the bad insert, or cascade a delete so loans do not become orphans.", "ریفرنشل انٹیگریٹی کہتی ہے کہ فارن کی موجود پرائمری کی سے ملے، ورنہ اندراج رد ہو۔", { type: "compare", title: "When a student row is deleted", headers: ["Action", "What the DBMS can do"], rows: [["Restrict", "Refuse the delete while loans exist"], ["Cascade", "Delete the student's loans too"], ["Set null", "Keep the loan but clear the student id, if allowed"]], note: "The point is consistency without hand-editing every table." }),
    ],
    quiz: [
      { q: "A student borrows many books, and each book is borrowed by many students. That relationship is…", choices: ["One-to-one", "One-to-many", "Many-to-many", "Not allowed to be discussed"], answer: 2, why: "Both sides have many. It needs a bridge table such as Loan." },
      { q: "Referential integrity is broken when…", choices: ["A foreign key points at a missing primary key", "A table has three columns", "A query uses a chart", "Two students share a city"], answer: 0, why: "The reference must land on a real row." },
      { q: "In an ER model, an attribute is…", choices: ["A relationship", "A fact about an entity", "A programming loop", "A network layer"], answer: 1, why: "Entities have attributes. Relationships connect entities." },
    ],
  },
  {
    id: "xi-queries",
    track: "xi",
    level: "XI",
    chapter: "Data and Analysis",
    title: "Queries, forms, and charts",
    golden: true,
    covers: ["4.8", "4.9", "4.10", "4.11", "4.11.6"],
    summary: "Ask the database a question, enter data safely, and show the pattern.",
    outcomes: ["Say what tables, forms, queries, and reports are for.", "Describe a filter and a grouped total.", "Match a chart to a question."],
    beats: [
      b("Objects", "Tables store the data. Forms are screens for entering and editing one record carefully. Queries ask questions. Reports present the answer for printing or sharing. A database without queries is only a cupboard.", "ٹیبل ڈیٹا رکھتے ہیں۔ فارم اندراج کی اسکرین ہیں۔ کوئری سوال پوچھتی ہے۔ رپورٹ جواب پیش کرتی ہے۔", { type: "cards", title: "Database objects", items: [{ tag: "Store", title: "Table", body: "Fields, records, and keys." }, { tag: "Enter", title: "Form", body: "A kinder screen than a raw grid." }, { tag: "Ask", title: "Query", body: "Filter, join, and summarize." }, { tag: "Show", title: "Report", body: "A laid-out answer." }] }),
      b("Design a table", "In Access Design View you name each field, choose a data type, and mark the primary key before anyone types a row. Text for names, number for marks, date for a due day. Choosing the type early stops '17' and 'seventeen' from living in the same column.", "ڈیزائن ویو میں فیلڈ کا نام، ڈیٹا ٹائپ، اور پرائمری کی پہلے مقرر کریں۔", { type: "table", title: "Design view, before any rows", headers: ["Field", "Type", "Rule"], rows: [["roll_no", "Short text", "Primary key"], ["name", "Short text", "Required"], ["marks", "Number", "0 to 100"], ["joined_on", "Date", "Not in the future"]] }),
      b("Filter and group", "A query can show only the rows you care about, such as section B. Grouping folds matching rows together so you can count students per section or average their marks. The filter decides which rows enter. The group decides how they are combined.", "فلٹر قطاریں چنتا ہے۔ گروپ ملتی قطاریں جوڑ کر گنتی یا اوسط نکالتا ہے۔", { type: "table", title: "Average marks by section", headers: ["section", "students", "average"], rows: [["A", "28", "71"], ["B", "30", "76"], ["C", "27", "69"]], note: "This is a summary, not a list of every student." }),
      b("Charts", "A bar chart compares categories. A pie chart shows parts of a whole, and it gets hard to read with many slices. A line chart is for change over time. Pick the chart from the question, not from the prettiest icon.", "بار زمرے موازنہ کرتا ہے۔ پائی حصہ دکھاتی ہے۔ لائن وقت کے ساتھ بدل دکھاتی ہے۔", { type: "chart", kind: "bar", title: "Average marks by section", labels: ["A", "B", "C"], values: [71, 76, 69], note: "Bars compare sections. A pie would pretend the averages are parts of one whole." }),
    ],
    quiz: [
      { q: "A form is mainly for…", choices: ["Routing IP packets", "Entering and viewing records through a screen", "Drawing logic gates", "Compiling Python"], answer: 1, why: "Forms are the user interface of the database." },
      { q: "Which chart best compares average marks of three sections?", choices: ["Pie with dozens of slices", "Bar chart", "A truth table", "A K-map"], answer: 1, why: "Bars compare categories. Averages are not slices of a single pie." },
      { q: "Grouping in a query is for…", choices: ["Combining rows to compute counts or averages", "Deleting the primary key", "Turning off referential integrity", "Installing Python"], answer: 0, why: "Group by section, then count or average inside each group." },
    ],
  },
  {
    id: "xi-impacts",
    track: "xi",
    level: "XI",
    chapter: "Applications and Impacts",
    title: "AI, IoT, sources, and access",
    golden: true,
    covers: ["5.1.1", "5.1.2", "5.1.3", "5.2", "5.3", "5.4", "5.5"],
    summary: "What computing is doing in the world, and how to judge a source.",
    outcomes: ["Describe AI, IoT, and data analytics at syllabus level.", "Classify information sources.", "Give examples of assistive technology."],
    beats: [
      b("Three forces", "Artificial intelligence lets software perform tasks that usually need human judgment, such as recognizing speech. The Internet of Things connects physical devices so they can sense and send data. Data analytics turns collected data into a decision.", "اے آئی فیصلے میں مدد دیتی ہے۔ آئی او ٹی آلات جوڑتی ہے۔ ڈیٹا اینالیٹکس اعداد سے فیصلہ بناتی ہے۔", { type: "cards", title: "Know which idea you are using", items: [{ tag: "AI", title: "Judgment from examples", body: "Speech, recommendations, image labels." }, { tag: "IoT", title: "Things that report", body: "A sensor, a connection, and something that acts." }, { tag: "Analytics", title: "Data with a question", body: "Collect, clean, study, present." }] }),
      b("IoT pieces", "An IoT device senses something, such as a classroom's temperature. Connectivity carries that reading. A processor or a service decides, and an actuator may respond, such as starting a fan. The same pattern appears in farming, health, homes, and smart classrooms.", "سینسر ناپتا ہے، کنیکشن بھیجتا ہے، اور سسٹم فیصلہ کر کے عمل کر سکتا ہے۔", { type: "pipeline", title: "From sensor to action", loop: true, steps: [{ name: "Sensor", detail: "Measure", note: "Temperature, pulse, or a door." }, { name: "Network", detail: "Send", note: "The reading leaves the device." }, { name: "Decide", detail: "Compare", note: "Software applies a rule or a model." }, { name: "Act", detail: "Respond", note: "A fan, an alert, or a log entry." }] }),
      b("Sources", "A primary source is the original evidence: your own survey, or a research paper's data. A secondary source interprets it: a news article or a textbook chapter. A tertiary source summarizes many sources: an encyclopedia entry. The web contains all three, so the container is not the category.", "پرائمری اصل ثبوت ہے۔ سیکنڈری اس کی تشریح ہے۔ ٹرشری خلاصہ ہے۔", { type: "compare", title: "Where the claim came from", headers: ["Source", "What it is", "Classroom example"], rows: [["Primary", "Original evidence", "Your survey responses"], ["Secondary", "An interpretation", "A magazine article about the survey"], ["Tertiary", "A summary of summaries", "An encyclopedia overview"]] }),
      b("Impacts and access", "Computing speeds up study, health, and business, and it also creates privacy risks and dependence. Assistive technology is the set of tools that let more people use the same systems: a screen reader for a blind student, captions for a deaf student, a magnifier, or a switch instead of a mouse.", "کمپیوٹنگ فائدہ بھی دیتی ہے اور نجی زندگی کا خطرہ بھی۔ اسسٹو ٹیکنالوجی زیادہ لوگوں کو شامل کرتی ہے۔", { type: "cards", title: "Access is part of the design", items: [{ tag: "Vision", title: "Screen reader", body: "Speaks on-screen text." }, { tag: "Hearing", title: "Captions", body: "Text for speech and video." }, { tag: "Motor", title: "Switch access", body: "A single control instead of a precise pointer." }, { tag: "Risk", title: "Privacy", body: "Collected data can be misused. Collect less." }] }),
    ],
    quiz: [
      { q: "A temperature sensor that reports to an app is an example of…", choices: ["A K-map", "The Internet of Things", "Bubble sort", "A primary key"], answer: 1, why: "A physical device, a measurement, and a connection: that is IoT." },
      { q: "Your own class survey results are…", choices: ["A primary source", "Always tertiary", "A logic gate", "An OSI layer"], answer: 0, why: "You collected the original evidence." },
      { q: "A screen reader is…", choices: ["Malware", "Assistive technology", "A sorting algorithm", "A foreign key"], answer: 1, why: "It lets a person who cannot see the screen hear the content." },
    ],
  },
  {
    id: "xi-literacy",
    track: "xi",
    level: "XI",
    chapter: "Digital Literacy",
    title: "Digital inquiry and data",
    golden: true,
    covers: ["6.1", "6.3", "6.4", "6.5", "6.7", "6.8"],
    summary: "Collect the right data, know its source, and present a careful artefact.",
    outcomes: ["Separate qualitative and quantitative data.", "Plan a collection method.", "Distinguish primary from secondary data in a project."],
    beats: [
      b("Digital literacy", "Digital literacy is the ability to use devices and online tools safely and honestly. It includes searching, judging what you found, collecting data, and presenting it so someone else can check your work.", "ڈیجیٹل خواندگی آلات کو محفوظ اور دیانت دار طریقے سے استعمال کرنے کی صلاحیت ہے۔", { type: "board", kicker: "Chapter 6", title: "A careful digital student", points: ["Search with a real question", "Judge the source", "Collect data on purpose", "Show the work so it can be checked"] }),
      b("Kinds of data", "Quantitative data is numbers: hours of screen time, marks, counts. Qualitative data is descriptions: a student's comment that revision videos feel rushed. A good inquiry often needs both. Numbers show the size. Words show the reason.", "مقداری ڈیٹا عدد ہوتا ہے۔ معیاری ڈیٹا بیان ہوتا ہے۔ دونوں مل کر تصویر مکمل کرتے ہیں۔", { type: "split", title: "Two kinds of evidence", left: { eyebrow: "Quantitative", title: "Numbers", lines: ["Hours online", "Test scores", "Counts and averages"] }, right: { eyebrow: "Qualitative", title: "Descriptions", lines: ["Interview comments", "Observed behavior", "A written reason"] } }),
      b("Collecting", "You can survey a class, interview a few people in depth, observe a place, or build a prototype and watch people use it. A survey needs neutral questions. An interview can follow a surprising answer. A prototype tests a design before you build the real thing.", "سروے، انٹرویو، مشاہدہ، یا پروٹوٹائپ۔ سوال جانبدار نہ ہو۔", { type: "cards", title: "Collection strategies", items: [{ tag: "6.4", title: "Survey", body: "Same questions, many people." }, { tag: "6.4", title: "Interview", body: "Fewer people, deeper answers." }, { tag: "6.4", title: "Observation", body: "Watch what people do, not only what they say." }, { tag: "6.4", title: "Prototype", body: "An early model you can test." }] }),
      b("Primary or secondary", "Primary data is collected by you for this question. Secondary data was collected by someone else, for their question. A published article about screen time is secondary. Your class tally is primary. Say which is which in the project, and do not pretend a blog is a census.", "پرائمری ڈیٹا آپ نے اس سوال کے لیے اکٹھا کیا۔ سیکنڈری کسی اور کا جمع کردہ ہے۔", { type: "compare", title: "Name the source in the write-up", headers: ["", "Primary", "Secondary"], rows: [["Who collected it", "You, for this project", "Someone else"], ["Example", "Class questionnaire", "A cited article"], ["Risk", "A biased question", "A source that does not fit your question"]] }),
      b("The artefact", "A digital inquiry ends in an artefact: a report, slides, or an infographic that answers the original question. Show the question, the method, the chart, and the limit of your evidence. A chart of thirty classmates is not a claim about every teenager in Sindh.", "آخری ڈیجیٹل شے سوال کا جواب دے، طریقہ بتائے، اور اپنے ثبوت کی حد بھی لکھے۔", { type: "pipeline", title: "Inquiry steps", loop: false, steps: [{ name: "Question", detail: "One sentence", note: "Narrow the question until data can answer it." }, { name: "Search", detail: "Background", note: "Use secondary sources to learn the field." }, { name: "Collect", detail: "Primary data", note: "Survey or observation with a fair method." }, { name: "Present", detail: "Artefact", note: "Chart plus a sentence about what you cannot claim." }] }),
    ],
    quiz: [
      { q: "Comments from three interviews are…", choices: ["Quantitative data", "Qualitative data", "A primary key", "Machine code"], answer: 1, why: "They are descriptions, not measurements." },
      { q: "A journal article you cite is…", choices: ["Primary data you collected", "Secondary data", "Always wrong", "A logic diagram"], answer: 1, why: "Someone else gathered and interpreted that evidence." },
      { q: "A class chart of 30 students supports a claim about…", choices: ["Every person in the country", "The group you actually measured, with limits", "All future years automatically", "Nothing, so charts are useless"], answer: 1, why: "The artefact should match the size of the evidence." },
    ],
  },
];
