function b(title, say, sayUr, scene) {
  return { title, say, sayUr, scene };
}

export const xiiLectures = [
  {
    id: "xii-hci",
    track: "xii",
    level: "XII",
    chapter: "Human Computer Interaction",
    title: "HCI, senses, and domains",
    golden: true,
    covers: ["1.1", "1.1.1", "1.1.2", "1.2", "1.3"],
    summary: "How people and machines meet, through ordinary devices and natural ones.",
    outcomes: ["Define HCI and its other names.", "Contrast traditional and natural interaction.", "Place HCI in health, banking, education, and communication."],
    beats: [
      b("What HCI is", "Human-computer interaction designs technology so people can use it. The same field is called CHI, computer-human interaction, or MMI, man-machine interaction. A good system is learnable, efficient, and responsive.", "ایچ سی آئی ٹیکنالوجی کو انسان کے قابل استعمال بناتی ہے۔ اسے سی ایچ آئی یا ایم ایم آئی بھی کہتے ہیں۔", { type: "board", kicker: "Class XII · 1.1", title: "People first", points: ["Learnable without a manual for every click", "Efficient for the frequent task", "Responsive, with visible feedback"] }),
      b("Senses", "People and computers meet through channels. Sight uses screens. Touch uses taps and haptics. Hearing uses sound. Voice sends speech commands. Spatial interaction tracks a body in a room, as in virtual reality.", "نظر، چھونا، سننا، آواز، اور جسم کی جگہ: یہ پانچ رابطے کے راستے ہیں۔", { type: "cards", title: "Channels", items: [{ tag: "Sight", title: "Screens", body: "Text, color, and layout." }, { tag: "Touch", title: "Haptics", body: "Taps, swipes, and vibration." }, { tag: "Hearing", title: "Audio", body: "Alerts and spoken feedback." }, { tag: "Voice", title: "Speech", body: "A command such as play the lesson." }, { tag: "Spatial", title: "Movement", body: "The system tracks where you are." }] }),
      b("Traditional and natural", "Traditional interaction uses a mouse, a keyboard, a remote, or an ATM keypad. Natural interaction drops those and uses speech, face, or gesture. Face unlock and a spoken assistant are natural. A TV remote is traditional. Both can be good design.", "روایتی رابطہ ماؤس اور کی بورڈ ہے۔ قدرتی رابطہ آواز، چہرہ، یا اشارہ استعمال کرتا ہے۔", { type: "split", title: "How the input arrives", left: { eyebrow: "Traditional", title: "Learned controls", lines: ["Mouse and keyboard", "ATM keypad", "TV remote"] }, right: { eyebrow: "Natural", title: "Human signals", lines: ["Spoken commands", "Face unlock", "Hand tracking in VR"] } }),
      b("Where it matters", "HCI is not only a phone skin. Patient portals, bank apps, exam systems, and video calls all succeed or fail on interaction. The user benefit is the test: can a person finish the real task under real pressure?", "صحت، بینک، تعلیم، اور رابطے کی ایپس اسی لیے کامیاب یا ناکام ہوتی ہیں کہ کام پورا ہوتا ہے یا نہیں۔", { type: "cards", title: "Domains", items: [{ tag: "Health", title: "Portals", body: "Reach a service without a confusing form." }, { tag: "Banking", title: "Careful screens", body: "Fast transfers that are hard to mis-tap." }, { tag: "Education", title: "Learning systems", body: "A student can find the task and submit it." }, { tag: "Communication", title: "Calls and chat", body: "People can join, speak, and share." }] }),
    ],
    quiz: [
      { q: "MMI stands for…", choices: ["Many-Many Interface", "Man-Machine Interaction", "Main Memory Index", "Mapped Mobile Internet"], answer: 1, why: "HCI is also called CHI or MMI." },
      { q: "Face unlock is best classed as…", choices: ["Traditional interaction", "Natural interaction", "A sorting algorithm", "A primary key"], answer: 1, why: "It uses a human signal instead of a typed password on a keypad." },
      { q: "Which channel is haptic feedback using?", choices: ["Sight only", "Touch", "Smell", "Network routing"], answer: 1, why: "Vibration and physical click are touch feedback." },
    ],
  },
  {
    id: "xii-design",
    track: "xii",
    level: "XII",
    chapter: "Human Computer Interaction",
    title: "Accessibility, UI, UX, and testing",
    golden: true,
    covers: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.11"],
    summary: "Find the need, draw a wireframe, and test the interface with people.",
    outcomes: ["List practical accessibility checks.", "Separate UI from UX.", "Describe usability, A/B, and automated tests."],
    beats: [
      b("Why HCI matters", "HCI turns a capable machine into one people can approach. Importance shows up as fewer errors, faster tasks, and access for more bodies and senses. Need analysis comes before drawing: who is the user, what are they trying to finish, and where does the current screen fail?", "پہلے ضرورت سمجھیں: صارف کون ہے، کون سا کام ادھورا رہتا ہے، اور موجودہ اسکرین کہاں ناکام ہے۔", { type: "pipeline", title: "Need analysis before pixels", loop: false, steps: [{ name: "Users", detail: "Who, really?", note: "A student, a clerk, a patient." }, { name: "Goal", detail: "Which task?", note: "Submit, pay, or find a result." }, { name: "Gap", detail: "What fails now?", note: "The difference between today and the goal." }] }),
      b("Accessibility", "Accessibility means the interface still works with different bodies and senses. Offer text for images, captions for audio, keyboard use without a mouse, and contrast that can be read in daylight. Feedback must not be color alone, because some people do not see that color.", "متن، کیپشن، کی بورڈ، اور واضح کنٹراسٹ۔ صرف رنگ پر انحصار نہ کریں۔", { type: "cards", title: "Checks you can apply", items: [{ tag: "See", title: "Text alternatives", body: "Images and icons have words." }, { tag: "Hear", title: "Captions", body: "Video is not the only channel." }, { tag: "Operate", title: "Keyboard", body: "Every control can be reached without a pointer." }, { tag: "Perceive", title: "Contrast", body: "Text stands off the background." }] }),
      b("Problems", "Common HCI failures are clutter, inconsistent words, missing feedback, and ignoring context. If Save sometimes says Submit, people hesitate. If a tap does nothing visible, they tap again and pay twice. Contextual neglect is a system that behaves the same in a quiet office and on a shaky bus.", "بے ترتیبی، بدلتے الفاظ، اور غائب فیڈ بیک عام مسئلے ہیں۔ خاموش بٹن دوبارہ دبانے پر مجبور کرتا ہے۔", { type: "cards", title: "Problems to name in an answer", items: [{ tag: "1.7", title: "Clutter", body: "Too many actions of equal weight." }, { tag: "1.7", title: "Inconsistency", body: "The same command wears two names." }, { tag: "1.7", title: "No feedback", body: "The system ate the click silently." }, { tag: "1.7", title: "Context", body: "The design ignores where it is used." }] }),
      b("UI and UX", "UI is the surface: buttons, type, color, layout. UX is the whole experience, including whether the task felt obvious and trustworthy. A beautiful button that charges the wrong person is a UI success and a UX failure. Wireframes plan structure before color. A prototype can be clicked, even if it is only paper.", "یو آئی سطح ہے، یو ایکس پورے کام کا احساس۔ وائر فریم رنگ سے پہلے ڈھانچہ ہے۔", { type: "split", title: "Surface and experience", left: { eyebrow: "UI", title: "What you see", lines: ["Layout", "Labels", "Color and type"] }, right: { eyebrow: "UX", title: "What it feels like to finish", lines: ["Can I find the task?", "Do I trust the result?", "Would I return?"] } }),
      b("Testing", "Testing asks whether the system behaves. Evaluation asks whether people can use it. A usability test watches real users attempt a task. A/B testing compares two versions. Automated tests repeat checks a script can judge, such as a broken link. Figma is one tool for sharing the design before code.", "یوزیبلٹی ٹیسٹ صارف کو کام کرتے دیکھتا ہے۔ اے بی دو نسخوں کا موازنہ ہے۔ آٹومیشن وہی جانچ دہراتی ہے جو اسکرپٹ کر سکے۔", { type: "compare", title: "Three methods", headers: ["Method", "Question it answers"], rows: [["Usability test", "Can a person complete the task?"], ["A/B test", "Which of two versions works better?"], ["Automated test", "Did a checkable rule break?"]] }),
    ],
    quiz: [
      { q: "UI differs from UX because UI focuses on…", choices: ["The whole feeling of the task", "The visual controls and layout", "Database keys", "Sorting speed"], answer: 1, why: "UI is the surface. UX includes whether the task succeeds for the person." },
      { q: "A usability test mainly…", choices: ["Watches people try a real task", "Only measures CPU time", "Replaces the need for any users", "Draws a K-map"], answer: 0, why: "You learn from observed attempts, including hesitation and errors." },
      { q: "Relying on red versus green alone fails…", choices: ["Referential integrity", "Accessibility, for people who cannot see that difference", "Bubble sort", "TCP"], answer: 1, why: "Meaning needs a second channel: text, icon, or position." },
    ],
  },
  {
    id: "xii-correct",
    track: "xii",
    level: "XII",
    chapter: "Algorithms and Data Structures",
    title: "Correctness, clarity, and Big O",
    golden: true,
    covers: ["2.1", "2.1.1", "2.1.2", "2.2", "2.3", "2.4"],
    summary: "Trace tables, readable steps, and how runtime grows.",
    outcomes: ["Build a short trace table.", "Explain clarity and modularity.", "Rank constant, logarithmic, linear, and quadratic growth."],
    beats: [
      b("Correctness", "An algorithm is correct when the output matches the expected result for the inputs you claim to handle. You show that by a trace table, a manual dry run, or by stepwise reasoning that checks the state after each logical section.", "الگورتھم تب درست ہے جب بیان کردہ ان پٹ پر متوقع آؤٹ پٹ آئے۔ ٹریس ٹیبل یہ دکھاتی ہے۔", { type: "board", kicker: "Golden topic", title: "Show your work", points: ["Trace table: values after each step", "Stepwise reasoning: why a section is valid", "Clarity still matters when the answer is right"] }),
      b("Trace table", "Suppose a rule accepts a cadet only if height is at least 160. Start with count at 0. Each row of the table is one person. Write the height, the decision, and the new count. The last count is the output you defend.", "ہر قطار میں قد، فیصلہ، اور نئی گنتی لکھیں۔ آخری گنتی آپ کا جواب ہے۔", { type: "table", title: "Who meets 160 cm?", headers: ["Person", "Height", "Accept?", "Count"], rows: [["1", "158", "No", "0"], ["2", "171", "Yes", "1"], ["3", "160", "Yes", "2"], ["4", "149", "No", "2"]], note: "160 qualifies if the rule is at least 160. Write the rule before you trace." }),
      b("Clarity", "A clear algorithm can be read, tested, and changed. Modularity splits it into named parts, such as a function that averages an array, instead of one block that reads, sums, divides, and prints. Readability uses honest names and a straight path.", "واضح الگورتھم نام والے حصوں میں بٹا ہوتا ہے تاکہ اسے پڑھا اور بدلا جا سکے۔", { type: "split", title: "One block or a named part", left: { eyebrow: "Poor clarity", title: "Everything tangled", lines: ["Read, sum, divide, print", "No name for the average", "Hard to reuse the math"] }, right: { eyebrow: "Modular", title: "A function", lines: ["average(values)", "The caller prints", "The math can be tested alone"] } }),
      b("Big O", "Big O describes how work grows as the input size n grows. It ignores constants and keeps the dominant term. Constant time barely changes. Logarithmic time grows very slowly, like binary search. Linear time walks the input once. Quadratic time, from nested loops, hurts sooner.", "بگ او بتاتا ہے کہ کام این کے ساتھ کیسے بڑھتا ہے۔ غالب حصہ رکھا جاتا ہے، مستقل نظر انداز۔", { type: "chart", kind: "line", title: "Growth, sketched", labels: ["n=1", "n=2", "n=4", "n=8"], values: [3, 4, 5, 6], note: "This curve is the slow climb of log n. A nested loop would bend up much faster." }),
      b("Loops dominate", "The repetitions decide the class. One loop over n items is linear. A loop inside a loop over the same list is quadratic. Binary search halves, so it is logarithmic. Refinement removes repeated work, such as stopping bubble sort early when a pass makes no swaps.", "ایک حلقہ لکیری ہے، حلقہ اندر حلقہ مربع، اور آدھا کرتے جانا لاگارتھمک۔", { type: "compare", title: "Name the class", headers: ["Pattern", "Big O", "Example"], rows: [["No loop over n", "Constant", "Read one array slot"], ["Halve each time", "Log n", "Binary search"], ["One pass", "Linear", "Linear search"], ["Pass inside a pass", "n squared", "Bubble sort"]] }),
    ],
    quiz: [
      { q: "A trace table is used to…", choices: ["Draw a user interface", "Record variable values step by step", "Install a library", "Encrypt a disk"], answer: 1, why: "It is a dry run that shows the state after each step." },
      { q: "Binary search's growth is…", choices: ["Quadratic", "Logarithmic", "Always constant, even if unsorted", "Exponential by definition"], answer: 1, why: "Each comparison removes half of the remaining sorted range." },
      { q: "Nested loops over the same n items usually mean…", choices: ["Constant time", "Quadratic time", "No repetition", "A primary key"], answer: 1, why: "Work grows like n times n." },
    ],
  },
  {
    id: "xii-linear",
    track: "xii",
    level: "XII",
    chapter: "Algorithms and Data Structures",
    title: "Arrays, lists, stacks, and queues",
    golden: true,
    covers: ["2.5", "2.5.1", "2.7"],
    summary: "Linear structures: neighbors in a line, a pile, or a waiting line.",
    outcomes: ["Contrast an array with a linked list.", "Operate a stack and a queue.", "Pick one for undo or for a waiting line."],
    beats: [
      b("Array", "An array stores items of one type in contiguous memory. The index finds an item quickly. Inserting in the middle is costly because neighbors must shift. Use an array when you mostly read by position.", "ارے میں ایک قسم کے عناصر لگاتار میموری میں ہوتے ہیں۔ انڈیکس سے رسائی تیز ہے، بیچ میں داخلہ مہنگا۔", { type: "cells", title: "Index finds the cell", values: ["XI", "B", "Ali", "72"], frames: [{ focus: [2], note: "Index 2 is Ali. No walking required." }] }),
      b("Linked list", "A linked list stores each value in a node with a pointer to the next node. Nodes need not sit together in memory. Inserting at the front is cheap. Finding the tenth item means walking nine links. There is no formula that jumps straight there.", "لنکڈ لسٹ کے ہر نوڈ میں قیمت اور اگلے نوڈ کا پتہ ہوتا ہے۔ دسویں تک پہنچنے کے لیے چلنا پڑتا ہے۔", { type: "flow", title: "Walk the links", nodes: [{ id: "a", text: "Ali →", kind: "step" }, { id: "b", text: "Hina →", kind: "step" }, { id: "c", text: "Omar", kind: "end" }], order: ["a", "b", "c"] }),
      b("Stack", "A stack is last in, first out. Push adds to the top. Pop removes the top. The undo button of an editor is a stack: the latest action is the one you undo first. You do not pull an item from the middle.", "سٹیک آخر میں آیا پہلے نکلتا ہے۔ پش اوپر رکھتا ہے، پاپ اوپر سے ہٹاتا ہے۔", { type: "stack", title: "Undo is a stack", frames: [{ items: ["type A"], note: "Push the first action." }, { items: ["type A", "type B"], note: "Push B. B is on top." }, { items: ["type A"], note: "Pop undoes B first, not A." }] }),
      b("Queue", "A queue is first in, first out. Enqueue joins the rear. Dequeue leaves from the front. A print line and a help desk work this way. The person who arrived first is served first. A stack would serve the latest arrival instead, which is the wrong fairness.", "قطار میں جو پہلے آیا پہلے نکلتا ہے۔ داخلہ پیچھے سے، خروج آگے سے۔", { type: "queue", title: "A help desk", frames: [{ items: ["Ayesha"], note: "Ayesha arrives and is at the front." }, { items: ["Ayesha", "Bilal"], note: "Bilal enqueues at the rear." }, { items: ["Bilal"], note: "Dequeue serves Ayesha first." }] }),
      b("Retrieval", "Tracing retrieval means saying which item comes out and what remains. An array retrieves by index. A linked list retrieves by walking. A queue retrieves only at the front. If a question says 'the second item pushed is removed before the first', it is describing a stack, not a queue.", "ارے انڈیکس سے دیتا ہے، لسٹ چل کر، اور قطار صرف آگے سے۔", { type: "compare", title: "Linear structures", headers: ["Structure", "Retrieval", "Classic use"], rows: [["Array", "By index", "A fixed table of marks"], ["Linked list", "Walk from the head", "Frequent inserts at the front"], ["Stack", "Top only", "Undo, back button"], ["Queue", "Front only", "Printer, waiting list"]] }),
    ],
    quiz: [
      { q: "Pop removes which item?", choices: ["The first one ever pushed", "The current top", "A random item", "The rear of a queue"], answer: 1, why: "A stack is last in, first out." },
      { q: "A printer spool that serves the earliest file first is a…", choices: ["Stack", "Queue", "Tree", "Graph"], answer: 1, why: "First in, first out is a queue." },
      { q: "Why is the middle of a linked list slower to reach than an array index?", choices: ["Nodes must be visited in order", "Lists cannot store numbers", "Arrays are always unsorted", "Queues forbid indexes"], answer: 0, why: "You follow pointers. An array computes the address from the index." },
    ],
  },
  {
    id: "xii-nonlinear",
    track: "xii",
    level: "XII",
    chapter: "Algorithms and Data Structures",
    title: "Trees, graphs, and choosing",
    golden: true,
    covers: ["2.5.2", "2.6"],
    summary: "Hierarchies and free-form connections, and how to pick a structure.",
    outcomes: ["Describe a tree's root, parent, and children.", "Describe a graph's vertices and edges.", "Match a problem to a structure."],
    beats: [
      b("Tree", "A tree organizes data in a hierarchy from a single root. Each node except the root has one parent. A college chart is a tree: the college at the root, departments under it, classes under those. You do not draw a cycle back to the root.", "ٹری کی جڑ ایک ہوتی ہے۔ ہر دوسرے نوڈ کا ایک والدین ہوتا ہے۔ چکر نہیں ہوتا۔", { type: "tree", title: "A college chart", levels: [["College"], ["CS", "Science"], ["XI", "XII", "Lab"]], note: "CS and Science are children of College. XI and XII can sit under CS." }),
      b("Graph", "A graph is vertices connected by edges, with no rule that there is a single root. A road map is a graph: towns are vertices, roads are edges, and you can travel in cycles. Use a graph when relationships are many-to-many and not a strict hierarchy.", "گراف میں نوڈس اور کنکشن ہوتے ہیں۔ جڑ لازمی نہیں اور چکر ہو سکتا ہے، جیسے سڑکوں کا نقشہ۔", { type: "graph", title: "Routes between towns", nodes: [{ id: "h", label: "Hyderabad", x: 20, y: 30 }, { id: "k", label: "Karachi", x: 75, y: 25 }, { id: "s", label: "Sukkur", x: 50, y: 70 }], edges: [["h", "k"], ["h", "s"], ["k", "s"]], note: "Any town can connect to any other. That freedom is the point." }),
      b("Choose", "If items have a clear before and after, think array, list, stack, or queue. If they form a hierarchy with one parent each, think tree. If anything can connect to anything, think graph. The scenario decides. Do not store a family tree in a queue just because a queue was the last lesson.", "ترتیب ہو تو لکیری ڈھانچہ، درجہ بندی ہو تو ٹری، آزاد کنکشن ہوں تو گراف۔", { type: "table", title: "Scenario to structure", headers: ["Situation", "Structure"], rows: [["Undo the latest edit", "Stack"], ["Serve the earliest customer", "Queue"], ["College departments", "Tree"], ["Bus routes between cities", "Graph"], ["Marks looked up by position", "Array"]] }),
    ],
    quiz: [
      { q: "A tree has…", choices: ["No root and required cycles", "A root and a hierarchy", "Only two nodes, ever", "FIFO retrieval"], answer: 1, why: "Everything branches from the root, and each other node has one parent." },
      { q: "Bus routes with possible cycles fit a…", choices: ["Stack", "Queue", "Graph", "Single integer"], answer: 2, why: "Places and arbitrary connections, including cycles, are a graph." },
      { q: "The latest action should be undone first. Use a…", choices: ["Queue", "Stack", "Pie chart", "Foreign key"], answer: 1, why: "That is last in, first out." },
    ],
  },
  {
    id: "xii-structs",
    track: "xii",
    level: "XII",
    chapter: "Programming",
    title: "Lists, tuples, sets, and dictionaries",
    golden: true,
    covers: ["3.1", "3.1.1", "3.1.2", "3.1.3", "3.1.4", "3.1.5"],
    summary: "Python's four everyday collections and the job each one is built for.",
    outcomes: ["Index and slice a list.", "Explain why a tuple is immutable.", "Use a set for uniqueness and a dictionary for lookup."],
    beats: [
      b("Lists", "A list is ordered and mutable. Indexes start at 0. Negative indexes count from the end, so minus 1 is the last item. A slice copies a section with start, stop, and an optional step. The stop index is not included.", "لسٹ ترتیب رکھتی ہے اور بدل سکتی ہے۔ انڈیکس صفر سے شروع ہوتا ہے۔ مائنس ایک آخری عنصر ہے۔", { type: "code", title: "Indexes and a slice", lines: ["marks = [61, 70, 88, 54]", "marks[0]      # 61", "marks[-1]     # 54", "marks[1:3]    # [70, 88]"], active: [3], note: "Slicing stops before index 3, so 54 is not included." }),
      b("Tuples", "A tuple is ordered and immutable. Once you create it, you do not replace an item. That makes it a safe record, such as a point or a fixed RGB color. Methods like count and index still work, because they do not change the tuple.", "ٹیوپل ترتیب رکھتا ہے مگر بدل نہیں سکتا۔ یہ مستقل ریکارڈ کے لیے موزوں ہے۔", { type: "code", title: "A fixed record", lines: ["point = (3, 4)", "point[0]", "# point[0] = 9  would fail"], active: [2], note: "The assignment is a comment because it would raise an error." }),
      b("Sets", "A set stores unique items and does not promise order or indexes. It is the right tool for 'who showed up', because a second add of the same name changes nothing. Union, intersection, and difference answer questions about two groups.", "سیٹ میں دہرائی نہیں ہوتی اور ترتیب کا وعدہ نہیں۔ یونین، انٹرسیکشن، اور ڈفرنس گروہوں کے سوال ہیں۔", { type: "cards", title: "Two clubs", items: [{ tag: "Union", title: "Either club", body: "Names that appear in at least one set." }, { tag: "Intersection", title: "Both clubs", body: "Names that appear in each set." }, { tag: "Difference", title: "Only the first", body: "Names you lose if you leave the second club." }] }),
      b("Dictionaries", "A dictionary maps a unique key to a value. A roll number maps to a name. Bracket access fails if the key is missing. The get method can return a default instead. Adding a key is an assignment. Keys should be immutable values such as strings or numbers.", "ڈکشنری چابی کو قیمت سے جوڑتی ہے۔ get گمشدہ چابی پر پروگرام نہیں گراتا۔", { type: "code", title: "Lookup that survives a missing key", lines: ["roll = {\"014\": \"Ali\"}", "roll[\"014\"]", "roll.get(\"999\", \"absent\")", "roll[\"015\"] = \"Hina\""], active: [2], note: "get returns absent instead of crashing." }),
      b("Choose a collection", "Use a list when order matters and items may change. Use a tuple for a fixed record. Use a set to remove duplicates or compare groups. Use a dictionary when the question is 'what value belongs to this key?' Built-ins such as len, max, and sum work across several of these.", "ترتیب اور تبدیلی کے لیے لسٹ، مستقل ریکارڈ کے لیے ٹیوپل، انفرادیت کے لیے سیٹ، تلاش کے لیے ڈکشنری۔", { type: "compare", title: "Pick by the question", headers: ["Need", "Collection"], rows: [["Ordered marks that change", "List"], ["A fixed pair", "Tuple"], ["Unique visitors", "Set"], ["Roll number to name", "Dictionary"]] }),
    ],
    quiz: [
      { q: "marks[-1] on a non-empty list is…", choices: ["Always 0", "The last item", "A syntax error", "The length"], answer: 1, why: "Negative indexes count backward from the end." },
      { q: "Which collection refuses duplicate items and has no index?", choices: ["List", "Tuple", "Set", "String always"], answer: 2, why: "A set is unique and unordered." },
      { q: "Why prefer dict.get when the key might be missing?", choices: ["It sorts the dictionary", "It can return a default instead of raising", "It converts text to int", "It closes a file"], answer: 1, why: "Direct brackets raise KeyError if the key is absent." },
    ],
  },
  {
    id: "xii-files",
    track: "xii",
    level: "XII",
    chapter: "Programming",
    title: "Functions, scope, and files",
    golden: true,
    covers: ["3.2", "3.2.2", "3.2.4", "3.3", "3.6", "3.8", "3.9"],
    summary: "Named tasks, local names, and data that survives after the program ends.",
    outcomes: ["Write a function that returns a value.", "Separate local and global scope.", "Read and write a file, and catch a missing file."],
    beats: [
      b("Functions", "A function packages steps you would otherwise copy. def names it. Parameters receive inputs. return sends a value back. A function that only prints is harder to reuse than one that returns, because the caller can test the number.", "فنکشن مراحل کو نام دیتا ہے۔ return قیمت واپس بھیجتا ہے تاکہ کال کرنے والا اسے استعمال کر سکے۔", { type: "code", title: "Return the average", lines: ["def average(values):", "    return sum(values) / len(values)", "", "print(average([10, 20, 30]))"], active: [1], note: "The print stays outside, so average remains a pure calculation." }),
      b("Scope", "A variable created inside a function is local. It disappears when the function returns, and the outside cannot read it. A variable created at the top of the file is global. Prefer parameters and return values over globals, so each function's inputs are visible.", "فنکشن کے اندر بنا متغیر لوکل ہے۔ باہر والا گلوبل ہے۔ پیرامیٹر گلوبل سے زیادہ واضح ہیں۔", { type: "split", title: "Where a name lives", left: { eyebrow: "Local", title: "Inside the function", lines: ["Created on assignment", "Hidden from other functions", "Gone after return"] }, right: { eyebrow: "Global", title: "Whole file", lines: ["Created outside functions", "Easy to change by accident", "Harder to test"] } }),
      b("Files", "Variables vanish when the program ends. A file keeps data. open uses a mode: r to read, w to write from scratch, a to append. read and write are methods on the file object. write mode erases an existing file, so choose it on purpose.", "فائل پروگرام کے بعد بھی ڈیٹا رکھتی ہے۔ r پڑھتا ہے، w نیا لکھ کر پرانا مٹا سکتا ہے، a جوڑتا ہے۔", { type: "code", title: "Modes", lines: ["f = open(\"marks.txt\", \"w\")", "f.write(\"Ali 72\\n\")", "f.close()"], active: [0], note: "w creates or empties the file. a would keep old lines." }),
      b("with and exceptions", "The with statement closes the file even if something fails. try and except catch errors you can recover from, such as a missing file. Bare except that hides every error makes debugging worse. Name the error you expect.", "with فائل خود بند کرتا ہے۔ try اور except متوقع غلطی سنبھالتے ہیں، ہر غلطی کو چھپائیں نہیں۔", { type: "code", title: "Read, or explain the failure", lines: ["try:", "    with open(\"marks.txt\") as f:", "        text = f.read()", "except FileNotFoundError:", "    text = \"\""], active: [3], note: "The with block still closes the file if read fails halfway." }),
      b("Grade tracker", "A small grade tracker ties the chapter together. Append one line per student, read the lines back, split each line into a name and a mark, and return the average. The file is the memory. The function is the calculation. The exception is the plan for the first run, when the file does not exist yet.", "گریڈ ٹریکر فائل میں نام اور نمبر جوڑتا ہے، پھر اوسط نکالتا ہے۔ پہلی بار فائل نہ ہو تو استثنا کام آتا ہے۔", { type: "pipeline", title: "Tracker flow", loop: false, steps: [{ name: "Append", detail: "Mode a", note: "Add one result without deleting history." }, { name: "Read", detail: "Mode r", note: "Pull every line back." }, { name: "Split", detail: "Name and mark", note: "Turn text into numbers." }, { name: "Average", detail: "return", note: "Let the caller print it." }] }),
    ],
    quiz: [
      { q: "A value created inside a function is by default…", choices: ["Global", "Local", "A foreign key", "Immutable always"], answer: 1, why: "Local names belong to that call." },
      { q: "Opening with mode w …", choices: ["Always appends", "Starts writing from scratch and can erase existing text", "Only reads", "Sorts the file"], answer: 1, why: "Use a to keep the old contents." },
      { q: "Why use with open(...)?", choices: ["It writes faster than light", "It closes the file even if an error occurs", "It removes the need for a function", "It disables exceptions"], answer: 1, why: "The file is closed when the block ends, including on failure." },
    ],
  },
  {
    id: "xii-pandas",
    track: "xii",
    level: "XII",
    chapter: "Data Analysis",
    title: "SQLite, DataFrames, and missing data",
    golden: true,
    covers: ["4.1", "4.1.1", "4.2", "4.3", "4.3.1", "4.3.2", "4.3.3"],
    summary: "Connect Python to a database, then clean a table of rows and columns.",
    outcomes: ["List the steps to query SQLite from Python.", "Describe a DataFrame.", "Choose fill or drop for missing values."],
    beats: [
      b("Why connect", "Data analysis turns raw facts into a decision. The facts often live in a database or a file, not in your source code. Python becomes useful when it can connect, query, and then analyze. If any step in that chain fails, you are guessing.", "تجزیے کے لیے Python کو ڈیٹا سے جڑنا پڑتا ہے: کنکشن، سوال، پھر مطالعہ۔", { type: "board", kicker: "4.1", title: "From stored facts to a claim", points: ["Connect", "Query", "Clean", "Summarize"] }),
      b("SQLite steps", "SQLite is a lightweight database in a single file. The standard path is: import sqlite3, connect to a file, create a cursor, execute SQL, commit a change, then close. A select needs a fetch. An insert needs a commit or the new row disappears.", "sqlite3 درآمد کریں، فائل سے جڑیں، کرسر بنائیں، ایس کیو ایل چلائیں، کمیٹ کریں، بند کریں۔", { type: "code", title: "Insert, then keep it", lines: ["import sqlite3", "con = sqlite3.connect(\"school.db\")", "cur = con.cursor()", "cur.execute(\"CREATE TABLE IF NOT EXISTS student(name TEXT)\")", "cur.execute(\"INSERT INTO student VALUES (?)\", (\"Ali\",))", "con.commit()"], active: [5], note: "The question mark is a placeholder. Do not glue user text into the SQL." }),
      b("DataFrame", "Pandas stores a table as a DataFrame: columns have names, rows have an index. You can build one from a dictionary or load a CSV. A column can be calculated from other columns, such as total equals theory plus practical.", "ڈیٹا فریم جدول ہے: نام والے کالم اور قطاریں۔ سی ایس وی سے بھی بن سکتا ہے۔", { type: "table", title: "A three-row DataFrame", headers: ["name", "theory", "practical", "total"], rows: [["Ali", "40", "30", "70"], ["Hina", "35", "32", "67"], ["Omar", "28", "20", "48"]], note: "total is a new column, derived, not retyped." }),
      b("Missing values", "Missing data is a blank, not a zero, unless you decide otherwise. Pandas marks it as NA. Filling replaces the blank, for example with the column median. Dropping removes the row or column. Filling hides the gap. Dropping shrinks the evidence. Say which one you did.", "خالی خانہ صفر نہیں ہوتا۔ fill اسے بھرتا ہے، drop قطار ہٹا دیتا ہے۔ جو کیا ہو لکھیں۔", { type: "compare", title: "Fill or drop", headers: ["Choice", "When it is honest"], rows: [["Fill with median", "A few blanks in a numeric column, and the middle is meaningful"], ["Drop the row", "The row is too empty to trust"], ["Leave it", "The fact of being missing is itself information"]] }),
    ],
    quiz: [
      { q: "After INSERT, which call makes the new row durable?", choices: ["print", "commit", "import", "slice"], answer: 1, why: "commit writes the transaction. Closing without it can lose the insert." },
      { q: "A DataFrame is closest to…", choices: ["A single integer", "A named table of rows and columns", "A logic gate", "A network cable"], answer: 1, why: "Columns have names. Rows are the records you analyze." },
      { q: "A blank mark should not automatically become 0 because…", choices: ["0 means a scored zero, which may be false", "Pandas cannot store numbers", "SQL forbids blanks", "Charts require blanks"], answer: 0, why: "Missing and zero are different facts. Choose fill or drop deliberately." },
    ],
  },
  {
    id: "xii-stats",
    track: "xii",
    level: "XII",
    chapter: "Data Analysis",
    title: "Charts and descriptive statistics",
    golden: true,
    covers: ["4.4", "4.5", "4.5.2", "4.5.3", "4.5.4", "4.5.5", "4.5.6", "4.6", "4.6.2"],
    summary: "Pick a picture for the question, then summarize center and spread.",
    outcomes: ["Match bar, line, pie, histogram, scatter, and box plots to questions.", "Compute the idea of mean, median, and mode.", "Explain range and standard deviation."],
    beats: [
      b("Bars and lines", "A bar chart compares categories, such as sections. A line chart connects values in time order, such as attendance each month. Do not use a line if the horizontal axis is not an order. Months are an order. Section names are not.", "بار زمرے دکھاتا ہے۔ لائن وقت کا رجحان۔ بغیر ترتیب کے لائن نہ جوڑیں۔", { type: "chart", kind: "line", title: "Attendance across months", labels: ["Jan", "Feb", "Mar", "Apr"], values: [80, 84, 79, 90], note: "The line is honest because the months are in order." }),
      b("Pie and histogram", "A pie chart shows parts of one whole, with few slices. A histogram groups a numeric variable into bins and shows how many values fell in each bin. It is not a bar chart of unrelated categories. Bins touch because the axis is continuous.", "پائی ایک کل کے حصے دکھاتی ہے۔ ہسٹوگرام عددی ڈیٹا کو بنوں میں گنتا ہے۔", { type: "chart", kind: "hist", title: "How many students in each mark band", labels: ["0-49", "50-64", "65-79", "80-100"], values: [6, 14, 18, 9], note: "Touching bins: this is a distribution, not four unrelated clubs." }),
      b("Scatter and box", "A scatter plot places one dot per pair of numbers, such as hours studied and marks. It suggests a relationship, not a proof. A box plot summarizes a distribution with the minimum, first quartile, median, third quartile, and maximum. The box is the middle half of the data.", "سکیٹر دو عددی متغیرات کا جوڑا دکھاتا ہے۔ باکس پلاٹ پانچ عددی خلاصہ دیتا ہے۔", { type: "chart", kind: "box", title: "Marks in one section", min: 42, q1: 61, median: 74, q3: 86, max: 98, note: "Half of the students sit between 61 and 86. The median is 74." }),
      b("Center", "The mean is the arithmetic average, and outliers pull it. The median is the middle value after sorting, and it resists a single extreme mark. The mode is the most frequent value. For salaries or a class with one perfect score and many ordinary ones, report the median beside the mean.", "اوسط کو انتہا کھینچتی ہے۔ میڈین درمیانی قیمت ہے اور زیادہ مضبوط ہے۔ موڈ سب سے زیادہ دہرائی جانے والی قیمت ہے۔", { type: "cards", title: "Center", items: [{ tag: "Mean", title: "Add and divide", body: "Sensitive to a very high or low value." }, { tag: "Median", title: "Middle after sorting", body: "Half the data is on each side." }, { tag: "Mode", title: "Most common", body: "Useful for categories too, such as a favorite lab day." }] }),
      b("Spread", "Center is not the whole story. The range is maximum minus minimum. Variance averages the squared distance from the mean. Standard deviation is the square root of variance, so it is in the same units as the data. A small standard deviation means the class clustered. A large one means the marks were scattered.", "رینج زیادہ اور کم کا فرق ہے۔ معیاری انحراف بتاتا ہے کہ قیمتیں اوسط سے کتنی بکھری ہیں۔", { type: "callout", eyebrow: "Pair them", title: "A mean without a spread can hide two different classes", body: "Both classes can average 70. One sits tightly around 70. The other mixes 40s and 100s. Standard deviation tells those stories apart." }),
    ],
    quiz: [
      { q: "Monthly attendance is best shown with…", choices: ["A line chart", "A K-map", "XOR", "A stack"], answer: 0, why: "The horizontal axis is time, and a line shows the trend." },
      { q: "One extremely high mark affects which measure most?", choices: ["The median", "The mean", "Neither, they are identical by definition", "The primary key"], answer: 1, why: "The mean uses every value. The median uses position." },
      { q: "A histogram's bins represent…", choices: ["Unrelated categories such as city names", "Ranges of a numeric variable", "Foreign keys", "OSI layers"], answer: 1, why: "Bins partition a number line. Bars for cities are a bar chart." },
    ],
  },
  {
    id: "xii-ml",
    track: "xii",
    level: "XII",
    chapter: "AI, Security, and Equity",
    title: "Machine learning, networks, and deep learning",
    golden: true,
    covers: ["5.1", "5.1.1", "5.1.2", "5.1.3", "5.1.4", "5.1.5", "5.2"],
    summary: "Models that learn patterns, and the layered networks inside modern ones.",
    outcomes: ["Place deep learning inside neural networks and machine learning.", "Name the layers of a simple network.", "Give an application without exaggerating certainty."],
    beats: [
      b("Three nested ideas", "Machine learning builds a model that improves from examples instead of a hand-written rule for every case. A neural network is one kind of model, loosely inspired by connected neurons. Deep learning uses neural networks with many hidden layers to learn more complex patterns.", "مشین لرننگ مثالوں سے سیکھتی ہے۔ نیورل نیٹ ورک اس کی ایک قسم ہے۔ ڈیپ لرننگ میں چھپی تہیں زیادہ ہوتی ہیں۔", { type: "tree", title: "Which idea contains which", levels: [["Machine learning"], ["Neural networks", "Other models"], ["Deep learning"]], note: "Deep learning sits inside neural networks, which sit inside machine learning." }),
      b("A small network", "Inputs form the first layer, such as pixels or marks. Hidden layers transform those numbers. The output layer produces a prediction, such as 'cat' or 'not cat'. Training adjusts the connections so the prediction moves closer to known examples. It does not memorize a sentence of Python if-statements for every photo.", "ان پٹ تہہ، چھپی تہیں، اور آؤٹ پٹ تہہ۔ تربیت کنکشنز کو مثالوں کے قریب کرتی ہے۔", { type: "network", title: "A tiny network", layers: [["x1", "x2", "x3"], ["h1", "h2"], ["y"]], note: "Each hidden neuron combines the inputs. The output is a prediction, not a guarantee." }),
      b("What deep adds", "Depth means more hidden layers, which can build features from other features. That power needs more data and more computation, and it can fail quietly when the new photo does not look like the training photos. A model is not a witness. It is a pattern matcher with an error rate.", "زیادہ تہیں زیادہ طاقت دیتی ہیں، مگر نئے ڈیٹا پر خاموشی سے غلط بھی ہو سکتی ہیں۔", { type: "cards", title: "Use the words precisely", items: [{ tag: "Learn", title: "From examples", body: "Labeled photos, past marks, recorded speech." }, { tag: "Predict", title: "On new input", body: "Useful when the new case resembles training." }, { tag: "Limit", title: "Error rate", body: "Report uncertainty. Do not claim magic." }] }),
      b("Applications", "Networks and deep learning show up in speech transcription, translation, photo organization, and medical image support. In each case a professional remains responsible. The system proposes. A person checks high-stakes results. That is the honest syllabus version of 'AI in society'.", "تقریر، ترجمہ، تصاویر، اور طبی تصاویر میں یہ مدد دیتے ہیں۔ اہم فیصلے میں انسان ذمہ دار رہتا ہے۔", { type: "cards", title: "Applications, with a human still accountable", items: [{ tag: "Speech", title: "Transcription", body: "Audio in, text out, then a person edits names." }, { tag: "Vision", title: "Photo tools", body: "Grouping shots is low stakes." }, { tag: "Health", title: "Image support", body: "A clinician confirms. The model does not diagnose alone." }] }),
    ],
    quiz: [
      { q: "Deep learning is best described as…", choices: ["A replacement for all algorithms", "Machine learning that uses multi-layer neural networks", "A sorting method", "A file mode"], answer: 1, why: "Depth refers to multiple hidden layers inside a neural network." },
      { q: "The output layer produces…", choices: ["The training photographs", "A prediction", "A primary key", "An IP route"], answer: 1, why: "The network turns inputs into an output such as a class or a number." },
      { q: "A high-stakes medical result from a model should be…", choices: ["Trusted with no review", "Checked by a qualified person", "Stored as a logic gate", "Used as a primary key"], answer: 1, why: "The model proposes from patterns. A person remains accountable." },
    ],
  },
  {
    id: "xii-security",
    track: "xii",
    level: "XII",
    chapter: "AI, Security, and Equity",
    title: "Threats, mitigation, and fair access",
    golden: true,
    covers: ["5.3", "5.4", "5.4.2", "5.4.3", "5.5", "5.5.2"],
    summary: "Protect shared work, recognize attacks, and keep collaboration from excluding people.",
    outcomes: ["Identify phishing, malware, and data theft.", "Name mitigations that match those threats.", "Apply equity to a class collaboration tool."],
    beats: [
      b("Shared work", "Collaboration tools let a class edit, meet, and share files. Security here means the right people can act, and others cannot. Accountability means an edit is tied to a real account so you can see who changed a shared report. Convenience without identity is how a document gets vandalized.", "مشترکہ کام میں صحیح لوگوں کو رسائی ہو، اور تبدیلی کسی اکاؤنٹ سے جڑی ہو۔", { type: "cards", title: "Protect the collaboration", items: [{ tag: "Identity", title: "Real accounts", body: "Guests do not get edit rights by default." }, { tag: "Least access", title: "Only what is needed", body: "View, comment, or edit are different." }, { tag: "Tracking", title: "History", body: "You can see who changed a paragraph." }] }),
      b("Threats", "A threat is anything that can harm the system or the data. Phishing is a fake message that steals a password. Malware is software that runs against the owner's interest. Data theft copies information without permission. Identity theft uses that data while pretending to be the person.", "فشنگ پاس ورڈ چراتی ہے۔ مالویئر نقصان دہ سافٹ ویئر ہے۔ ڈیٹا چوری نقل بناتی ہے۔", { type: "cards", title: "Name the threat", items: [{ tag: "Phishing", title: "Fake urgency", body: "A message that imitates a bank or a school." }, { tag: "Malware", title: "Hostile software", body: "Arrives as a download, attachment, or fake update." }, { tag: "Theft", title: "Copied data", body: "Files leave without permission." }, { tag: "Identity", title: "Pretending", body: "Someone uses your account as you." }] }),
      b("Signs and mitigation", "Signs include unexpected password resets, a new login place, or files you did not share. Mitigation reduces the harm: updates, unique passwords, multi-factor sign-in, backups, and refusing surprise links. No single control is the whole defense. Backups matter because prevention sometimes fails.", "غیر متوقع لاگ اِن خطرے کی علامت ہے۔ اپ ڈیٹ، مضبوط داخلہ، بیک اپ، اور مشکوک لنک سے پرہیز دفاع ہے۔", { type: "cycle", title: "A basic defense loop", steps: [{ name: "Update", detail: "Close known holes" }, { name: "Authenticate", detail: "Long password plus a second factor" }, { name: "Verify", detail: "Check the real sender before clicking" }, { name: "Back up", detail: "A copy the attacker cannot edit" }] }),
      b("Equity", "A collaboration tool fails the class if only some students can use it. Equity means considering language, a shared family phone, a cheap data plan, captions, and low bandwidth. Offering only a live video call at one hour excludes students who share a device. A recording, a text option, and a small file size are part of computer science, not an optional kindness.", "برابری کا مطلب ہے کہ زبان، آلہ، انٹرنیٹ، اور کیپشن کسی طالب علم کو باہر نہ چھوڑیں۔", { type: "cards", title: "Design for the whole class", items: [{ tag: "Device", title: "Shared phones", body: "The task can be finished in short sessions." }, { tag: "Network", title: "Small files", body: "Text first, video optional." }, { tag: "Language", title: "Plain wording", body: "Instructions in the language of the class." }, { tag: "Senses", title: "Captions", body: "The call is not audio-only." }] }),
    ],
    quiz: [
      { q: "A message that imitates the school and asks for your password is…", choices: ["Phishing", "A histogram", "Abstraction", "A queue"], answer: 0, why: "Phishing steals secrets by pretending to be someone you trust." },
      { q: "Which mitigation still helps after an attack succeeds?", choices: ["A backup the attacker cannot change", "Sending the password to a friend", "Disabling all updates forever", "Posting the database publicly"], answer: 0, why: "Backups restore work. The other choices increase harm." },
      { q: "Equity in a class tool includes…", choices: ["Assuming everyone has a private laptop and unlimited data", "Considering shared devices, data cost, language, and captions", "Removing accounts", "Disabling feedback"], answer: 1, why: "Access is part of whether the collaboration actually works." },
    ],
  },
  {
    id: "xii-venture",
    track: "xii",
    level: "XII",
    chapter: "Digital Entrepreneurship",
    title: "From a local problem to an idea",
    golden: true,
    covers: ["6.1", "6.2", "6.3"],
    summary: "Entrepreneurs start from a real problem and use digital tools to test a solution.",
    outcomes: ["Define entrepreneur and entrepreneurship.", "Walk from observation to a specific user and idea.", "Keep the first idea small enough to test."],
    beats: [
      b("Entrepreneur", "An entrepreneur notices a problem, proposes a solution, and tries to make that solution a product or service people actually use. Entrepreneurship is that process, including the chance that the first idea is wrong. It is not a slogan and it is not only opening a shop.", "کاروباری شخص مسئلہ دیکھتا ہے، حل بناتا ہے، اور اسے ایسی خدمت بناتا ہے جسے لوگ استعمال کریں۔", { type: "board", kicker: "6.1", title: "Problem, attempt, evidence", points: ["A person with a problem", "A solution you can show", "A test that can prove you wrong"] }),
      b("Digital age", "Digital entrepreneurship uses online tools to start, test, and reach people: a form, a chat group, a simple page, a payment link. The business can begin in a college or a neighborhood. The digital part reduces the cost of the first version. It does not remove the need for a real user.", "ڈیجیٹل اوزار پہلے نسخے کی لاگت گھٹاتے ہیں۔ اصل صارف پھر بھی ضروری ہے۔", { type: "cards", title: "Ordinary problems, digital first step", items: [{ tag: "College", title: "Canteen queue", body: "A shared sheet of what is still available." }, { tag: "Neighborhood", title: "Tuition matching", body: "A form that pairs a subject with a tutor." }, { tag: "Market", title: "Price list", body: "A page that replaces rumor with today's price." }] }),
      b("Problem to idea", "Start by watching. Who is stuck, how often, and what do they do today? Write the user in one sentence. Then write the idea as a change in their day, not as a list of features. 'Students see which snacks remain before they queue' is an idea. 'An AI super-app' is a costume.", "دیکھیں کون پھنسا ہے، صارف کو ایک جملے میں لکھیں، اور خیال کو ان کے دن کی تبدیلی بنائیں۔", { type: "pipeline", title: "Narrow the idea", loop: false, steps: [{ name: "Observe", detail: "A repeated annoyance", note: "Queue, missed deadline, missing price." }, { name: "Name the user", detail: "One group", note: "Class XII at this college, not everyone." }, { name: "Today", detail: "Current workaround", note: "They ask a friend or walk and hope." }, { name: "Change", detail: "One difference", note: "They know before they stand in line." }] }),
      b("Stay local", "The strongest student projects are local enough to test this week. You can talk to five classmates. You cannot honestly claim a national market from a bedroom sketch. Specific is a sign of seriousness.", "اس ہفتے پانچ ہم جماعتوں سے جانچ ممکن ہو تو منصوبہ سنجیدہ ہے۔ سارے ملک کا دعویٰ ابھی جلد ہے۔", { type: "callout", eyebrow: "Constraint", title: "If you cannot find five users, the idea is still a guess", body: "Digital tools help you reach them. They do not invent them." }),
    ],
    quiz: [
      { q: "Entrepreneurship in this chapter starts with…", choices: ["A logo", "A problem someone has", "Buying advertisements first", "A neural network"], answer: 1, why: "The solution exists to change someone's day." },
      { q: "A strong first idea names…", choices: ["Every possible user on earth", "A specific user and a specific change", "Only the programming language", "The office furniture"], answer: 1, why: "Specific users can be found and tested." },
      { q: "Digital tools mainly help the first version by…", choices: ["Removing the need for users", "Lowering the cost of showing and testing an idea", "Guaranteeing profit", "Replacing observation"], answer: 1, why: "A form or a page is cheaper than a shop. The user is still required." },
    ],
  },
  {
    id: "xii-mvp",
    track: "xii",
    level: "XII",
    chapter: "Digital Entrepreneurship",
    title: "Prototypes, MVPs, and a beachhead",
    golden: true,
    covers: ["6.4", "6.5", "6.6", "6.8", "6.9", "6.10", "6.13", "6.14"],
    summary: "Show the idea, test the riskiest belief, then serve a small first group.",
    outcomes: ["Compare prototype fidelity levels.", "Separate a prototype from an MVP.", "Define a beachhead market and a riskiest assumption."],
    beats: [
      b("Prototype", "A prototype is an early model of a product, site, or service. Its job is to show the idea and learn, not to impress with polish. Low fidelity is paper. Medium fidelity is a linked wireframe. High fidelity looks real and is easy to fall in love with before you have evidence.", "پروٹوٹائپ سیکھنے کے لیے ابتدائی نمونہ ہے۔ کاغذ کافی ہو سکتا ہے۔ خوبصورت نسخہ ثبوت سے پہلے خطرناک ہے۔", { type: "cards", title: "Fidelity", items: [{ tag: "Low", title: "Paper", body: "Fast, cheap, honest. Start here." }, { tag: "Medium", title: "Clickable wireframe", body: "Tests navigation without final art." }, { tag: "High", title: "Looks finished", body: "Useful later. Misleading if it is step one." }] }),
      b("The cycle", "You build a small prototype, give it to a few users, watch them, and change the prototype. A class can do this with paper screens for a homework reminder: five classmates try to find tomorrow's task, and the team notes where fingers hesitate.", "بنائیں، چند صارفوں کو دیں، دیکھیں، بدلیں۔ ہچکچاہٹ بھی نتیجہ ہے۔", { type: "cycle", title: "Prototype cycle", steps: [{ name: "Build", detail: "The smallest showable version" }, { name: "Test", detail: "Five real users" }, { name: "Watch", detail: "Where they hesitate" }, { name: "Revise", detail: "Change the prototype, not the user" }] }),
      b("MVP", "A minimum viable product is the smallest working version that real people can use in their real routine. A prototype mainly tests the design. An MVP tests whether people return and get value. A paper screen is not an MVP. A shared sheet that the canteen actually updates at lunch can be one.", "ایم وی پی سب سے چھوٹا کام کرتا نسخہ ہے جسے لوگ اپنے اصل دن میں استعمال کریں۔", { type: "split", title: "Prototype versus MVP", left: { eyebrow: "Prototype", title: "Learn about the design", lines: ["Can be paper", "Answers 'do they understand?'", "Not the real service"] }, right: { eyebrow: "MVP", title: "Learn about use", lines: ["Must actually work", "Answers 'do they come back?'", "Tiny feature list"] } }),
      b("Riskiest assumption", "Every idea hides beliefs. The riskiest assumption is the belief that, if false, kills the idea. For a canteen app it might be 'students will check a screen before they walk' or 'the canteen will update the list'. Test that belief first. Extra features do not repair a false assumption.", "سب سے خطرناک مفروضہ وہ ہے جو غلط ہو تو خیال مر جائے۔ پہلے اسے جانچیں۔", { type: "callout", eyebrow: "Test this first", title: "Will the canteen update the list at all?", body: "If the staff will not maintain it, a prettier app does not matter. The MVP should answer that question and little else." }),
      b("Beachhead", "A beachhead market is the small first group you can serve well. Not all of Sindh. Perhaps one college canteen at lunch. You learn the real objections there, then you earn the right to widen. A beachhead is a strategy, not a lack of ambition.", "بیچ ہیڈ وہ پہلا چھوٹا گروہ ہے جس کی خدمت آپ اچھی طرح کر سکیں۔ وہیں سے سیکھا جاتا ہے۔", { type: "pipeline", title: "Start narrower than your ambition", loop: false, steps: [{ name: "Beachhead", detail: "One canteen, one lunch", note: "You can visit it." }, { name: "MVP", detail: "Today's snacks, updated", note: "One job, done for real." }, { name: "Evidence", detail: "Did anyone look?", note: "Count views and ask why not." }, { name: "Widen", detail: "Only after it works", note: "A second canteen is a new test." }] }),
    ],
    quiz: [
      { q: "A paper screen used to watch classmates hunt for a button is…", choices: ["An MVP in production", "A low-fidelity prototype", "A neural network", "A foreign key"], answer: 1, why: "It tests understanding. It is not yet a working service." },
      { q: "An MVP must…", choices: ["Include every imagined feature", "Be a working version people can use for real", "Be drawn only in pencil", "Avoid users"], answer: 1, why: "The point is real use, with the smallest feature set that can deliver value." },
      { q: "A beachhead market is…", choices: ["Everyone you might someday serve", "A small first group you can serve well", "A security threat", "A type of chart"], answer: 1, why: "You learn from a focused group before widening." },
    ],
  },
];
