# (id, num, drawable, diff, en_name, ur_name, en_sum, ur_sum)
MOVE_META = [
    ("ultimate_cat", 1, "pic_missionary", "INTERMEDIATE", "Coital Alignment (CAT)", "ہم آہنگ داخلہ",
     "Missionary variation for clitoral stimulation during intercourse.", "داخلہ کے دوران کلائیٹورل محرک والی مشنری۔"),
    ("ultimate_zen", 2, "pic_spooning", "BEGINNER", "Zen Hero", "زین ہیرو",
     "Calming rhythmic intimacy to help her unwind.", "سکون دینے والی تال والی قربت۔"),
    ("ultimate_backyard", 3, "pic_standing", "ADVANCED", "Backyard Adventure", "صحن میں مہم",
     "Playful outdoor intimacy with gentle bounce.", "بیرون کھیلتی ہوئی قربت۔"),
    ("ultimate_alchemist", 4, "pic_standing", "ADVANCED", "The Alchemist", "الکیمسٹ",
     "Transform tension into passion through playful surrender.", "تناؤ کو جذبے میں بدلیں۔"),
    ("ultimate_glider", 5, "pic_side_by_side", "BEGINNER", "Easy Glider", "آسان گلائیڈر",
     "Full-body oiled glide for mutual massage pleasure.", "تیل والا پورے جسم کا رابطہ۔"),
    ("ultimate_bronco", 6, "pic_cowgirl", "INTERMEDIATE", "Bucking Bronco", "بکنگ برونکو",
     "Guide her cowgirl rhythm with strong arms.", "کاؤگرل تال رہنمائی کریں۔"),
    ("ultimate_wild", 7, "pic_doggy", "INTERMEDIATE", "Call of the Wild", "جنگلی پکار",
     "Rear-entry with playful wild energy.", "پیچھے سے جارحانہ توانائی۔"),
    ("ultimate_bedtime", 8, "pic_lazy_dog", "INTERMEDIATE", "Bedtime Stories", "سونے کی کہانیاں",
     "Read erotica while in intimate position.", "قریبی پوزیشن میں ادب پڑھیں۔"),
    ("ultimate_garden", 9, "pic_standing", "ADVANCED", "Garden Splash", "باغ میں پانی",
     "Outdoor water play for spontaneous fun.", "بیرون پانی سے کھیل۔"),
    ("ultimate_office", 10, "pic_edge_bed", "INTERMEDIATE", "The Office", "دفتر",
     "Office chair leverage for deep angles.", "دفتر کی کرسی سے زاویے۔"),
    ("ultimate_hug", 11, "pic_lotus", "BEGINNER", "The Naked Hug", "ننگا گلے لگنا",
     "Face-to-face seated embrace for deep connection.", "آمنے سامنے گلے لگ کر جڑیں۔"),
    ("ultimate_ball", 12, "pic_cowgirl", "INTERMEDIATE", "Bounce Ball", "گیند پر اچھال",
     "Exercise ball adds bounce to woman-on-top.", "گیند سے اچھال والی اوپر پوزیشن۔"),
    ("ultimate_ball_rider", 13, "pic_reverse_cowgirl", "INTERMEDIATE", "Ball Rider", "گیند پر سواری",
     "Reverse position on exercise ball.", "گیند پر الٹا بیٹھنا۔"),
    ("ultimate_jiggy", 14, "pic_standing", "INTERMEDIATE", "Getting Jiggy With It", "رقص کے ساتھ",
     "Dance-floor intimacy in a dark corner.", "اندھیرے میں رقص قربت۔"),
    ("ultimate_fashion", 15, "pic_standing", "BEGINNER", "Fashion Show", "فیشن شو",
     "Lingerie fashion show with loving commentary.", "لنگری فیشن شو۔"),
    ("ultimate_taichi", 16, "pic_lotus", "BEGINNER", "Sexy Tai Chi", "سیکسی ٹائی چی",
     "Slow energy movement and dual meditation.", "آہستہ توانائی اور مراقبہ۔"),
    ("ultimate_campers", 17, "pic_spooning", "BEGINNER", "Real Campers Sideways", "کیمپر سائیڈ",
     "Side-lying in a sleeping bag outdoors.", "کیمپنگ بیگ میں سائیڈ لین۔"),
    ("ultimate_party", 18, "pic_side_by_side", "ADVANCED", "Pleasure Party", "لطف کی محفل",
     "Multi-stimulation pleasure combination.", "کثیر محرک لطف۔"),
    ("ultimate_shaga", 19, "pic_butterfly", "INTERMEDIATE", "Shagalicious", "شگلشس",
     "Oral pleasure with satin and candlelight.", "موم بتی اور زبان سے لطف۔"),
    ("ultimate_kiss_date", 20, "pic_edge_bed", "BEGINNER", "The Kiss of Date", "بوسے کی ڈیٹ",
     "Kissing journey from lips downward.", "ہونٹوں سے نیچے بوسوں کا سفر۔"),
    ("ultimate_goddess", 21, "pic_butterfly", "BEGINNER", "Oh My Goddess", "اے میری دیوی",
     "Worship her with devoted oral attention.", "عبادت جیسی زبانی توجہ۔"),
    ("ultimate_sex101", 22, "pic_missionary", "INTERMEDIATE", "Sex 101", "سیکس 101",
     "Film yourselves to learn what she loves.", "سیکھنے کے لیے خود فلم بنائیں۔"),
    ("ultimate_splash", 23, "pic_scissors", "ADVANCED", "Splash", "چھینٹے",
     "G-spot stimulation for female ejaculation.", "جی سپاٹ محرک۔"),
    ("ultimate_concert", 24, "pic_scissors", "INTERMEDIATE", "Summer Concert", "گرمیوں کا کنسرٹ",
     "Discreet manual pleasure under a blanket.", "کمبل کے نیچے خفیہ لطف۔"),
    ("ultimate_blue", 25, "pic_missionary", "INTERMEDIATE", "Blue Arousal", "نیلی جوش",
     "Extended foreplay building intense arousal.", "لمبی پیش بازی سے جوش۔"),
    ("ultimate_sandy", 26, "pic_standing", "ADVANCED", "Sandy Shenanigans", "ریت پر شرارت",
     "Beach intimacy without sand discomfort.", "ساحل پر آرام دہ قربت۔"),
    ("ultimate_medicine", 27, "pic_butterfly", "BEGINNER", "The Medicine Man", "دوا والا",
     "Doctor roleplay with healing oral pleasure.", "ڈاکٹر کردار زبانی لطف۔"),
    ("ultimate_mileage", 28, "pic_reverse_cowgirl", "ADVANCED", "Xtra Mileage", "اضافی فاصلہ",
     "Positions and techniques to last longer.", "زیادہ دیر تک رہنے کی تکنیک۔"),
    ("ultimate_improv", 29, "pic_standing", "INTERMEDIATE", "Day at the Improv", "امپروو کا دن",
     "Costume roleplay with seven-minute scenes.", "سات منٹ کے کردار۔"),
    ("ultimate_finale", 30, "pic_lotus", "INTERMEDIATE", "The Grand Finale", "شاندار اختتام",
     "Extended 24-hour intimacy retreat.", "چوبیس گھنٹے قربت۔"),
]

# Per-move educational content keyed by id
CONTENT = {
    "ultimate_cat": {
        "en_desc": "The Coital Alignment Technique shifts your pelvis during missionary so the base of the penis and pubic bone contact her clitoris with each rocking motion. Women report significantly more orgasms using this method.",
        "ur_desc": "CAT میں مشنری کے دوران کولہے بدل کر عضو کی جڑ اور عانہ کی ہڈی ہر حرکت پر کلائیٹورس سے رابطہ کرتی ہے۔",
        "en_steps": ["Begin in missionary.", "Shift body slightly higher.", "Rock pelvis slowly instead of thrusting.", "Keep pubic bone contact steady.", "Ask about pressure and rhythm.", "Try small circular hip motions."],
        "ur_steps": ["مشنری میں شروع کریں۔", "جسم تھوڑا اوپر کریں۔", "جھٹکوں کی بجائے کولہے جھولیں۔", "عانہ کا رابطہ برقرار رکھیں۔", "دباؤ اور تال پوچھیں۔", "چھوٹے گول حرکات آزمائیں۔"],
        "en_tips": ["Pillow under her hips helps angle.", "Slow rocking beats fast thrusting.", "Add manual clitoral touch if wanted."],
        "ur_tips": ["کولہوں کے نیچے تکیہ مدد کرتا ہے۔", "آہستہ جھولنا بہتر ہے۔", "ضرورت ہو تو ہاتھ سے محرک دیں۔"],
        "en_man": ("On top, body shifted higher.", ["Rock don't thrust", "Steady pubic contact", "Check in often"]),
        "ur_man": ("اوپر، جسم تھوڑا اوپر۔", ["جھولیں نہ کہ جھٹکیں", "عانہ کا رابطہ", "بار بار پوچھیں"]),
        "en_woman": ("On back receiving rocking motion.", ["Guide his hips if needed", "Breathe and relax", "Say what rhythm works"]),
        "ur_woman": ("پیٹ کے بل جھولنے والی حرکت۔", ["کولہے رہنمائی کریں", "سانس لیں آرام کریں", "تال بتائیں"]),
    },
    "ultimate_zen": {
        "en_desc": "Slow rhythmic rocking combined with shared breathing helps her release daily stress. You become a calming, grounding presence while pleasure builds naturally.",
        "ur_desc": "آہستہ تال والی حرکت اور مشترکہ سانسیں تناؤ اتارتی ہیں۔ آپ پرسکون سہارا بنیں۔",
        "en_steps": ["Warm bath or comfortable setting.", "She faces you or leans on your chest.", "Enter slowly with gentle rocking.", "Breathe together in sync.", "Keep movements small and steady.", "Whisper reassurance."],
        "ur_steps": ["گرم پانی یا آرام دہ جگہ۔", "آپ کی طرف منہ یا سینے پر ٹیک۔", "آہستہ داخل ہوں۔", "سانسیں ہم آہنگ کریں۔", "حرکات چھوٹی رکھیں۔", "تسلی دیں۔"],
        "en_tips": ["Presence over performance.", "Dim lights, silence phones.", "Let her set the pace."],
        "ur_tips": ["موجودگی اہم ہے۔", "روشنی مدھم، فون بند۔", "رفتار اس کے ہاتھ میں۔"],
        "en_man": ("Behind or beneath, rocking steadily.", ["Breathe slowly", "Ocean-wave rhythm", "No rushing"]),
        "ur_man": ("پیچھے، مستقل جھولنا۔", ["آہستہ سانس", "لہر جیسی تال", "جلدی نہ کریں"]),
        "en_woman": ("Relaxed and supported.", ["Melt into rhythm", "Release stress", "Speak up if needed"]),
        "ur_woman": ("آرام سے سہارے میں۔", ["تال میں ڈوبیں", "تناؤ چھوڑیں", "ضرورت ہو تو بولیں"]),
    },
    "ultimate_backyard": {
        "en_desc": "Outdoor playfulness adds freedom and laughter. A trampoline or soft mat creates unique bouncing rhythms. Privacy and safety always come first.",
        "ur_desc": "بیرون کھیل پن آزادی دیتا ہے۔ نرم سطح منفرد تال بناتی ہے۔ رازداری اور حفاظت پہلے۔",
        "en_steps": ["Ensure complete privacy.", "Use trampoline or soft mat.", "Start playful while clothed.", "Position carefully on surface.", "Use bounce gently.", "Pause if balance is uncertain."],
        "ur_steps": ["رازداری یقینی بنائیں۔", "نرم سطح استعمال کریں۔", "کپڑوں میں کھیل سے شروع۔", "احتیاط سے پوزیشن۔", "ہلکی اچھال۔", "توازن مشکوک ہو تو رکیں۔"],
        "en_tips": ["Towels and water nearby.", "Avoid hard surfaces.", "Respect local privacy laws."],
        "ur_tips": ["تولیے اور پانی رکھیں۔", "سخت سطح سے بچیں۔", "قوانین کا احترام کریں۔"],
        "en_man": ("On top using gentle bounce.", ["Hold hips for stability", "Start very slow", "Watch for discomfort"]),
        "ur_man": ("اوپر ہلکی اچھال۔", ["کولہے تھامیں", "بہت آہستہ", "بے آرامی دیکھیں"]),
        "en_woman": ("On bouncing surface.", ["Use arms for balance", "Enjoy playfulness", "Stop anytime"]),
        "ur_woman": ("اچھال والی سطح پر۔", ["توازن کے لیے بازو", "کھیل سے لطف", "کبھی بھی رکیں"]),
    },
}

# Default template for moves without full custom content
def default_content(en_name, move_num):
    return {
        "en_desc": f"Move {move_num}: {en_name} — a technique from the Ultimate Edition guide to deepen her pleasure through communication, creativity, and confident loving touch.",
        "ur_desc": f"الٹیمیٹ ایڈیشن کی تکنیک {move_num}: {en_name} — بات چیت، تخلیق اور اعتماد سے اس کے لطف کو گہرا کریں۔",
        "en_steps": [
            "Discuss boundaries and desires beforehand.",
            "Set the scene with mood lighting and comfort.",
            "Begin slowly and read her body language.",
            "Adjust pace, depth, and angle based on feedback.",
            "Maintain eye contact and verbal check-ins.",
            "Afterward, cuddle and talk about what felt best.",
        ],
        "ur_steps": [
            "پہلے حدود اور خواہشات پر بات کریں۔",
            "روشنی اور آرام سے ماحول بنائیں۔",
            "آہستہ شروع کریں اور جسمانی اشارے پڑھیں۔",
            "ردعمل کے مطابق رفتار اور زاویہ بدلیں۔",
            "آنکھوں کا رابطہ اور زبانی پوچھ گچھ رکھیں۔",
            "بعد میں گلے ملیں اور بہترین احساس پر بات کریں۔",
        ],
        "en_tips": ["Consent is ongoing — pause anytime.", "Lubricant improves comfort.", "Focus on her pleasure, not performance."],
        "ur_tips": ["رضامندی مسلسل ہے — کبھی رک سکتے ہیں۔", "لوبریکنٹ آرام بڑھاتا ہے۔", "کارکردگی نہیں، اس کا لطف اہم ہے۔"],
        "en_man": ("Active partner guiding the experience.", ["Lead with patience", "Watch her responses", "Communicate throughout"]),
        "ur_man": ("فعال ساتھی تجربے کی رہنمائی۔", ["صبر سے قیادت", "ردعمل دیکھیں", "بات جاری رکھیں"]),
        "en_woman": ("Receiving partner expressing preferences.", ["Guide with words and touch", "Relax and breathe", "Say what feels good"]),
        "ur_woman": ("وصول کرنے والی ترجیحات ظاہر کریں۔", ["الفاظ اور چھونے سے رہنمائی", "آرام کریں سانس لیں", "اچھا لگنے والا بتائیں"]),
    }

# Custom overrides for key moves
CUSTOM = {
    "ultimate_alchemist": {
        "en_desc": "Channel emotional tension into passionate connection through playful dominance, light restraint, and loving presence. Consent and safewords are essential.",
        "ur_desc": "جذباتی تناؤ کو کھیلتی ہوئی قیادت اور نرم بندھن سے جذبے میں بدلیں۔ رضامندی اور محفوظ لفظ ضروری ہیں۔",
        "en_steps": ["Agree on boundaries and safeword.", "Acknowledge her mood with warmth.", "Lift arms gently as gesture of surrender.", "Kiss deeply with confident eye contact.", "Use soft ties only if pre-agreed.", "Debrief afterward with cuddles."],
        "ur_steps": ["حدود اور محفوظ لفظ طے کریں۔", "گرمجوشی سے موڈ تسلیم کریں۔", "بازو نرمی سے اٹھائیں۔", "گہرا بوسہ اعتماد سے۔", "نرم پٹی صرف رضامندی سے۔", "بعد میں گلے لگ کر بات کریں۔"],
    },
    "ultimate_glider": {
        "en_desc": "Full-body contact with oil or lotion creates a slip-and-glide massage for both partners. Perfect when you both want to give and receive touch simultaneously.",
        "ur_desc": "تیل یا لوشن سے پورے جسم کا رابطہ دونوں کے لیے مساج جیسا لطف دیتا ہے۔",
    },
    "ultimate_bronco": {
        "en_desc": "Woman on top while you guide her hips with strong arms. Coach her rhythm with encouragement — she will appreciate your active involvement.",
        "ur_desc": "عورت اوپر، آپ مضبوط بازوؤں سے کولہے رہنمائی کریں۔ حوصلہ افزائی سے تال سکھائیں۔",
    },
    "ultimate_wild": {
        "en_desc": "Rear-entry variations with playful animal energy. Many women fantasize about being passionately claimed — communicate and follow her lead on intensity.",
        "ur_desc": "پیچھے سے مختلف زاویے کھیلتی ہوئی توانائی سے۔ شدت پر اس کی رہنمائی لیں۔",
    },
    "ultimate_bedtime": {
        "en_desc": "Fold her knees to chest while you read erotic literature aloud. Words combined with physical closeness ignite her mind and body together.",
        "ur_desc": "گھٹنے سینے تک موڑیں اور شہوانی ادب بلند آواز پڑھیں۔ الفاظ اور قربت دماغ اور جسم دونوں جلاتے ہیں۔",
    },
    "ultimate_goddess": {
        "en_desc": "Kneel and worship her with your tongue. Being adored is a common female fantasy — leave ego at the door and focus entirely on her pleasure.",
        "ur_desc": "گھٹنوں کے بل بیٹھ کر زبان سے عبادت کریں۔ پوجے جانے کی خواہش عام ہے — مکمل توجہ اس کے لطف پر۔",
    },
    "ultimate_splash": {
        "en_desc": "Learn to stimulate the G-spot and Skene glands for female ejaculation. Use a come-hither finger motion on the upper vaginal wall. Talk through the experience together.",
        "ur_desc": "جی سپاٹ اور سکین غدود کی محرک سے سیکھیں۔ اوپری دیوار پر انگلی کی حرکت۔ ساتھ بات کریں۔",
    },
    "ultimate_finale": {
        "en_desc": "The Grand Finale — dedicate extended time to lovemaking, rest, nourishment, and connection. Twenty-four hours of focused intimacy can rejuvenate your relationship.",
        "ur_desc": "شاندار اختتام — لمبا وقت قربت، آرام، کھانا اور تعلق کے لیے۔ چوبیس گھنٹے تعلق تازہ کر سکتے ہیں۔",
    },
}

for mid, meta in zip([m[0] for m in MOVE_META], MOVE_META):
    if mid not in CONTENT and mid not in CUSTOM:
        pass  # will use default
